### PR TITLE
Fix OperatorContext race condition

### PR DESCRIPTION
**Pull request by pnowojski**
Addressing issue https://github.com/prestodb/presto/issues/5735.

First commit fixes this issue, second is a proposal for the refactor.

### CODE REVIEW

**Comment by martint** [comment]
@dain, can you review?

**Comment by dain** [comment]
The second commit `Use synchronized methods in OperatorContext` is how the entire statistics gathering system designed (a.k.a debugging information).  There is no guarantees that the information is accurate or consistent since the information is polled from multiple sources on multiple machines.

The first commit should be reviewed by @cberner

**Comment by cberner** [comment]
@pnowojski `OperatorContext` isn't designed to be safe for concurrent access, beyond calling `getOperatorStats()` concurrently with other methods. If it needs to be, then we need to figure out what implications that has for other classes, in particular `DriverContext`. A driver is processed by a single thread at a time, at the moment.

**Comment by pnowojski** [comment]
If it wasn't supposed to be thread safe, then this annotation is really misleading :)

@dain I didn't intend to fix stats consistency. The second commit is just refactor, to avoid errors as fixed in first commit.

@cberner I know and `DriverContext` seems to be free of this bug, since it doesn't have methods like `setMemoryReservation` which requires two separate access to `AtomicLong` values. However it also might be a good idea to switch in `DriverContext` to using `synchronized` methods instead of `AtomicLongs`. 

I was thinking about other ways to unblock drivers/operators after revoking memory and updating operator's memory usage from spiller's thread seems like a best solution. If you don't want to treat it as a bug this code could be made part of the https://github.com/prestodb/presto/pull/5843 (which partially already is)

**Comment by cberner** [comment]
Yep, I agree it's misleading. @dain is that just there to indicate that the stats can be collected concurrently? Instead of fixing this as a bug perhaps we should just document that in a comment?

**Comment by dain** [comment]
The `@ThreadSafe` annotation is wrong and should be removed.  Other than that change, I think we should drop the second commit.

**Comment by pnowojski** [comment]
I have dropped this annotation. Synchronization issue can be resolved in https://github.com/prestodb/presto/pull/5843 PR

**Comment by cberner** [comment]
Merged. Thanks!

**Pull request closed without merging**
