### PR TITLE
[native] Fix type signature parser to allow numeric struct names

### LINKED ISSUE #20639: [native] Failed to parse type [row("123" varchar,"456" varchar)]:
```
assertQuery("SELECT cast(row(orderkey, comment) as row(\"123\" varchar, \"456\" varchar)) FROM orders");

Caused by: VeloxUserError:  Failed to parse type [row("123" varchar,"456" varchar)]: 
```

CC: @pratyakshsharma @aditi-pandit @amitkdutta @zacw7 

Unit test to repro:

```
TEST_F(TestTypeSignature, xxx) {
  assertRowSignature(
      "row(\"12\" bigint,b bigint,c bigint)",
      rowSignature(
          namedParameter("12", false, signature("bigint")),
          namedParameter("b", false, signature("bigint")),
          namedParameter("c", false, signature("bigint"))));
}
```

### PR DESCRIPTION
**Pull request by mbasmanova**
Allow parsing of types like row("12" bigint, b bigint, c bigint).

Fixes #20639

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by mbasmanova** [comment]
@majetideepak Presto supports row("12" bigint, b bigint, c bigint), hence, we need same support in Prestissimo.

**Comment by mbasmanova** [comment]
@majetideepak 

```
presto:di> SELECT cast(row(orderkey, comment) as row("123" varchar, "456" varchar)) FROM tpch.tiny.orders LIMIT 5;
                                         _col0
----------------------------------------------------------------------------------------
 {123=1, 456=nstructions sleep furiously among }
 {123=2, 456= foxes. pending accounts at the pending, silent asymptot}
 {123=3, 456=sly final accounts boost. carefully regular ideas cajole carefully. depos}
 {123=4, 456=sits. slyly regular warthogs cajole. regular, regular theodolites acro}
 {123=5, 456=quickly. bold deposits sleep slyly. packages use slyly}
(5 rows)
```

**Review by majetideepak — APPROVED** [review]

**Review by majetideepak — CHANGES_REQUESTED** [review]
@mbasmanova Do we need the antlr4 submodule?

**Comment by mbasmanova** [comment]
> @mbasmanova Do we need the antlr4 submodule?

No, sorry, removed.

**Review by majetideepak — APPROVED** [review]

**Review by kgpai — APPROVED** [review]

**Pull request merged**
