### PR TITLE
Fix Travis Maven repository

### PR DESCRIPTION
**Pull request by electrum**

### CODE REVIEW

**Comment by dain** [comment]
@electrum  does mean we don't need https://github.com/prestodb/presto/pull/6670?

**Comment by maciejgrzybek** [comment]
@dain I believe @electrum is trying to debug our build to understand why https://github.com/prestodb/presto/pull/6670 solved a problem for us.

**Comment by petroav** [comment]
Also according to the ticket (https://issues.sonatype.org/browse/MVNCENTRAL-1369) everything should be fixed now.

**Comment by ebd2** [comment]
Maven central has marked the issue resolved: https://issues.sonatype.org/browse/MVNCENTRAL-1369

**Comment by electrum** [comment]
Sorry yes, I forgot to mention this is for debugging and you can ignore it

**Comment by electrum** [comment]
I was trying to figure out why it sometimes uses HTTP and other times HTTPS. I assumed it was a Travis issue and not Central being broken :)

**Pull request closed without merging**
