### PR TITLE
Add ORM and Ecosystem for presto-docs

### PR DESCRIPTION
**Pull request by TommyLemon**
## Description

Add ORM and Ecosystem for presto-docs

## Motivation and Context

Add links for ecosystem projects, to help users easily find what they need, and help the projects gain more impact.

## Impact

No feature impact, impact performance impact

## Test Plan

View the web page of the docs

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [x] CI passed.

## Release Notes
* Added 2 folders(orm, ecosystem) and 2 files in sphinx
* Added 2 lines in sphinx/index.rst

```
== RELEASE NOTES ==

General Changes
* Added 2 folders(orm, ecosystem) and 2 files in sphinx
* Added 2 lines in sphinx/index.rst
```

### CODE REVIEW

**Review by steveburnett — APPROVED** [review]
LGTM!

**Comment by TommyLemon** [comment]
@steveburnett  there remains dozens of tests to be completed, it seems that the tests were paused 
image

**Comment by tdcmeehan** [comment]
Please rebase one more time.  There was a bug in our reporting of tests for docs-only changes.  Thanks!

**Comment by steveburnett** [comment]
@TommyLemon, as @tdcmeehan suggested please rebase again - the docs-only tests had a bug and rebasing should rerun the tests with the improved test process. Thanks!

**Comment by TommyLemon** [comment]
@steveburnett @tdcmeehan new pr for the same purpose:
https://github.com/prestodb/presto/pull/21600

**Pull request closed without merging**
