### PR TITLE
[native] Advance Velox

### PR DESCRIPTION
**Pull request by aditi-pandit**
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by aditi-pandit** [comment]
@majetideepak

**Review by majetideepak — APPROVED** [review]

**Comment by aditi-pandit** [comment]
@pramodsatya : The linux-presto-e2e-tests is failing with the following error. Shouldn't it be fixed by https://github.com/prestodb/presto/pull/21825 ? Can you take a look ?

```
[ERROR] java.lang.OutOfMemoryError: Compressed class space
[ERROR] Terminating due to java.lang.OutOfMemoryError: Compressed class space
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 59, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[WARNING] Corrupted channel by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /root/project/presto-native-execution/target/surefire-reports/2024-02-12T16-33-39_340-jvmRun1.dumpstream
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:57 min (Wall Clock)
[INFO] Finished at: 2024-02-12T16:42:32-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project presto-native-execution: 
[ERROR] 
[ERROR] Please refer to /root/project/presto-native-execution/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd '/root/project/presto-native-execution' && '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.362.b08-3.el8.x86_64/jre/bin/java' '-Dfile.encoding=UTF-8' '-Xmx4g' '-Xms4g' '-XX:+ExitOnOutOfMemoryError' '-XX:+HeapDumpOnOutOfMemoryError' '-XX:-OmitStackTraceInFastThrow' '-jar' '/root/project/presto-native-execution/target/surefire/surefirebooter-20240212163340700_39.jar' '/root/project/presto-native-execution/target/surefire' '2024-02-12T16-33-39_340-jvmRun1' 'surefire-20240212163340700_37tmp' 'surefire_2-20240212163340700_38tmp'
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 3
[ERROR] Crashed tests:
[ERROR] com.facebook.presto.nativeworker.TestPrestoNativeWindowQueries
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd '/root/project/presto-native-execution' && '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.362.b08-3.el8.x86_64/jre/bin/java' '-Dfile.encoding=UTF-8' '-Xmx4g' '-Xms4g' '-XX:+ExitOnOutOfMemoryError' '-XX:+HeapDumpOnOutOfMemoryError' '-XX:-OmitStackTraceInFastThrow' '-jar' '/root/project/presto-native-execution/target/surefire/surefirebooter-20240212163340700_39.jar' '/root/project/presto-native-execution/target/surefire' '2024-02-12T16-33-39_340-jvmRun1' 'surefire-20240212163340700_37tmp' 'surefire_2-20240212163340700_38tmp'
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 3
[ERROR] Crashed tests:
[ERROR] com.facebook.presto.nativeworker.TestPrestoNativeWindowQueries
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:513)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkPerTestSet(ForkStarter.java:460)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:327)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:269)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1334)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1167)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:931)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
[ERROR]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[ERROR]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[ERROR]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[ERROR]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[ERROR]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[ERROR]         at java.lang.Thread.run(Thread.java:750)
[ERROR] Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd '/root/project/presto-native-execution' && '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.362.b08-3.el8.x86_64/jre/bin/java' '-Dfile.encoding=UTF-8' '-Xmx4g' '-Xms4g' '-XX:+ExitOnOutOfMemoryError' '-XX:+HeapDumpOnOutOfMemoryError' '-XX:-OmitStackTraceInFastThrow' '-jar' '/root/project/presto-native-execution/target/surefire/surefirebooter-20240212163340700_39.jar' '/root/project/presto-native-execution/target/surefire' '2024-02-12T16-33-39_340-jvmRun1' 'surefire-20240212163340700_37tmp' 'surefire_2-20240212163340700_38tmp'
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 3
[ERROR] Crashed tests:
[ERROR] com.facebook.presto.nativeworker.TestPrestoNativeWindowQueries
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:714)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.lambda$runSuitesForkPerTestSet$7(ForkStarter.java:449)
[ERROR]         ... 4 more
[ERROR] -> [Help 1]
[ERROR] 
```

**Comment by pramodsatya** [comment]
> @pramodsatya : The linux-presto-e2e-tests is failing with the following error. Shouldn't it be fixed by #21825 ? Can you take a look ?
> 
> ```
> [ERROR] java.lang.OutOfMemoryError: Compressed class space
> [ERROR] Terminating due to java.lang.OutOfMemoryError: Compressed class space
> [INFO] 
> [INFO] Results:
> [INFO] 
> [INFO] Tests run: 59, Failures: 0, Errors: 0, Skipped: 0
> [INFO] 
> [WARNING] Corrupted channel by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /root/project/presto-native-execution/target/surefire-reports/2024-02-12T16-33-39_340-jvmRun1.dumpstream
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 08:57 min (Wall Clock)
> [INFO] Finished at: 2024-02-12T16:42:32-06:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project presto-native-execution: 
> [ERROR] 
> [ERROR] Please refer to /root/project/presto-native-execution/target/surefire-reports for the individual test results.
> [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
> [ERROR] ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
> [ERROR] Command was /bin/sh -c cd '/root/project/presto-native-execution' && '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.362.b08-3.el8.x86_64/jre/bin/java' '-Dfile.encoding=UTF-8' '-Xmx4g' '-Xms4g' '-XX:+ExitOnOutOfMemoryError' '-XX:+HeapDumpOnOutOfMemoryError' '-XX:-OmitStackTraceInFastThrow' '-jar' '/root/project/presto-native-execution/target/surefire/surefirebooter-20240212163340700_39.jar' '/root/project/presto-native-execution/target/surefire' '2024-02-12T16-33-39_340-jvmRun1' 'surefire-20240212163340700_37tmp' 'surefire_2-20240212163340700_38tmp'
> [ERROR] Error occurred in starting fork, check output in log
> [ERROR] Process Exit Code: 3
> [ERROR] Crashed tests:
> [ERROR] com.facebook.presto.nativeworker.TestPrestoNativeWindowQueries
> [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
> [ERROR] Command was /bin/sh -c cd '/root/project/presto-native-execution' && '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.362.b08-3.el8.x86_64/jre/bin/java' '-Dfile.encoding=UTF-8' '-Xmx4g' '-Xms4g' '-XX:+ExitOnOutOfMemoryError' '-XX:+HeapDumpOnOutOfMemoryError' '-XX:-OmitStackTraceInFastThrow' '-jar' '/root/project/presto-native-execution/target/surefire/surefirebooter-20240212163340700_39.jar' '/root/project/presto-native-execution/target/surefire' '2024-02-12T16-33-39_340-jvmRun1' 'surefire-20240212163340700_37tmp' 'surefire_2-20240212163340700_38tmp'
> [ERROR] Error occurred in starting fork, check output in log
> [ERROR] Process Exit Code: 3
> [ERROR] Crashed tests:
> [ERROR] com.facebook.presto.nativeworker.TestPrestoNativeWindowQueries
> [ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:513)
> [ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkPerTestSet(ForkStarter.java:460)
> [ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:327)
> [ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:269)
> [ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1334)
> [ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1167)
> [ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:931)
> [ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
> [ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
> [ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
> [ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
> [ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
> [ERROR]         at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
> [ERROR]         at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
> [ERROR]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [ERROR]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [ERROR]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [ERROR]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [ERROR]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [ERROR]         at java.lang.Thread.run(Thread.java:750)
> [ERROR] Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
> [ERROR] Command was /bin/sh -c cd '/root/project/presto-native-execution' && '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.362.b08-3.el8.x86_64/jre/bin/java' '-Dfile.encoding=UTF-8' '-Xmx4g' '-Xms4g' '-XX:+ExitOnOutOfMemoryError' '-XX:+HeapDumpOnOutOfMemoryError' '-XX:-OmitStackTraceInFastThrow' '-jar' '/root/project/presto-native-execution/target/surefire/surefirebooter-20240212163340700_39.jar' '/root/project/presto-native-execution/target/surefire' '2024-02-12T16-33-39_340-jvmRun1' 'surefire-20240212163340700_37tmp' 'surefire_2-20240212163340700_38tmp'
> [ERROR] Error occurred in starting fork, check output in log
> [ERROR] Process Exit Code: 3
> [ERROR] Crashed tests:
> [ERROR] com.facebook.presto.nativeworker.TestPrestoNativeWindowQueries
> [ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:714)
> [ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.lambda$runSuitesForkPerTestSet$7(ForkStarter.java:449)
> [ERROR]         ... 4 more
> [ERROR] -> [Help 1]
> [ERROR] 
> ```

@aditi-pandit, yes it was supposed to be fixed with this PR

> @pramodsatya : The linux-presto-e2e-tests is failing with the following error. Shouldn't it be fixed by #21825 ? Can you take a look ?
> 
> ```
> [ERROR] java.lang.OutOfMemoryError: Compressed class space
> [ERROR] Terminating due to java.lang.OutOfMemoryError: Compressed class space
> [INFO] 
> [INFO] Results:
> [INFO] 
> [INFO] Tests run: 59, Failures: 0, Errors: 0, Skipped: 0
> [INFO] 
> [WARNING] Corrupted channel by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /root/project/presto-native-execution/target/surefire-reports/2024-02-12T16-33-39_340-jvmRun1.dumpstream
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 08:57 min (Wall Clock)
> [INFO] Finished at: 2024-02-12T16:42:32-06:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project presto-native-execution: 
> [ERROR] 
> [ERROR] Please refer to /root/project/presto-native-execution/target/surefire-reports for the individual test results.
> [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
> [ERROR] ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
> [ERROR] Command was /bin/sh -c cd '/root/project/presto-native-execution' && '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.362.b08-3.el8.x86_64/jre/bin/java' '-Dfile.encoding=UTF-8' '-Xmx4g' '-Xms4g' '-XX:+ExitOnOutOfMemoryError' '-XX:+HeapDumpOnOutOfMemoryError' '-XX:-OmitStackTraceInFastThrow' '-jar' '/root/project/presto-native-execution/target/surefire/surefirebooter-20240212163340700_39.jar' '/root/project/presto-native-execution/target/surefire' '2024-02-12T16-33-39_340-jvmRun1' 'surefire-20240212163340700_37tmp' 'surefire_2-20240212163340700_38tmp'
> [ERROR] Error occurred in starting fork, check output in log
> [ERROR] Process Exit Code: 3
> [ERROR] Crashed tests:
> [ERROR] com.facebook.presto.nativeworker.TestPrestoNativeWindowQueries
> [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
> [ERROR] Command was /bin/sh -c cd '/root/project/presto-native-execution' && '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.362.b08-3.el8.x86_64/jre/bin/java' '-Dfile.encoding=UTF-8' '-Xmx4g' '-Xms4g' '-XX:+ExitOnOutOfMemoryError' '-XX:+HeapDumpOnOutOfMemoryError' '-XX:-OmitStackTraceInFastThrow' '-jar' '/root/project/presto-native-execution/target/surefire/surefirebooter-20240212163340700_39.jar' '/root/project/presto-native-execution/target/surefire' '2024-02-12T16-33-39_340-jvmRun1' 'surefire-20240212163340700_37tmp' 'surefire_2-20240212163340700_38tmp'
> [ERROR] Error occurred in starting fork, check output in log
> [ERROR] Process Exit Code: 3
> [ERROR] Crashed tests:
> [ERROR] com.facebook.presto.nativeworker.TestPrestoNativeWindowQueries
> [ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:513)
> [ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkPerTestSet(ForkStarter.java:460)
> [ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:327)
> [ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:269)
> [ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1334)
> [ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1167)
> [ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:931)
> [ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
> [ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
> [ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
> [ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
> [ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
> [ERROR]         at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
> [ERROR]         at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
> [ERROR]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [ERROR]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [ERROR]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [ERROR]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [ERROR]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [ERROR]         at java.lang.Thread.run(Thread.java:750)
> [ERROR] Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
> [ERROR] Command was /bin/sh -c cd '/root/project/presto-native-execution' && '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.362.b08-3.el8.x86_64/jre/bin/java' '-Dfile.encoding=UTF-8' '-Xmx4g' '-Xms4g' '-XX:+ExitOnOutOfMemoryError' '-XX:+HeapDumpOnOutOfMemoryError' '-XX:-OmitStackTraceInFastThrow' '-jar' '/root/project/presto-native-execution/target/surefire/surefirebooter-20240212163340700_39.jar' '/root/project/presto-native-execution/target/surefire' '2024-02-12T16-33-39_340-jvmRun1' 'surefire-20240212163340700_37tmp' 'surefire_2-20240212163340700_38tmp'
> [ERROR] Error occurred in starting fork, check output in log
> [ERROR] Process Exit Code: 3
> [ERROR] Crashed tests:
> [ERROR] com.facebook.presto.nativeworker.TestPrestoNativeWindowQueries
> [ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:714)
> [ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.lambda$runSuitesForkPerTestSet$7(ForkStarter.java:449)
> [ERROR]         ... 4 more
> [ERROR] -> [Help 1]
> [ERROR] 
> ```

Thanks for sharing @aditi-pandit, it looks like the jvm option `-XX:CompressedClassSpaceSize=3g` is not set in the command that runs on the forked VM. Could you please try updating the maven surefire plugin config in `presto-native-execution/pom.xml` with:
```
                 <configuration>
                     <forkCount>1</forkCount>
                     <reuseForks>false</reuseForks>
+                    <argLine>-Xms4g -Xmx4g -XX:CompressedClassSpaceSize=3g</argLine>
                     <excludedGroups>remote-function,textfile_reader</excludedGroups>
                     <systemPropertyVariables>
                         <PRESTO_SERVER>/root/project/build/debug/presto_cpp/main/presto_server</PRESTO_SERVER>
```

**Comment by majetideepak** [comment]
@aditi-pandit the critical bug fix in the description should be in here https://github.com/prestodb/presto/commit/0bc6f916327086aad5c2c977dcdcafcba0f58fa7
Can you update the description?

**Comment by aditi-pandit** [comment]
@majetideepak : TaskManager.cpp needed a code change for the change in the API introduced by https://github.com/facebookincubator/velox/commit/9c79ef96fc552d07e83b08d05c8019076c482d31

Please can you review again.

**Review by majetideepak — APPROVED** [review]
Thanks, Aditi!
I see that the following API change on the Velox side requires a change here.
```
using DataAvailableCallback = std::function<void(
    std::vector<std::unique_ptr<folly::IOBuf>> pages,
    int64_t sequence,
    std::vector<int64_t> remainingBytes)>;
```

**Comment by majetideepak** [comment]
The CI test failed due to some timeout. I restarted it.

**Pull request merged**
