### PR TITLE
Update DROP Table example in Delta document

### PR DESCRIPTION
**Pull request by agrawalreetika**
Ref: #17457 

Test plan - (Please fill in how you tested your changes)

Please make sure your submission complies with our [Development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [Formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), and [Commit Message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests) guidelines. Don't forget to follow our [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution) for any code copied from other projects.

Fill in the release notes towards the bottom of the PR description.
See [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) for details.

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by yzhang1991** [comment]
@agrawalreetika Can you ask Naveen to take a first pass and also re-run the failed tests? I assume those test failures are not relevant but we need to have a green test to merge.
Also we probably need to have a clearer commit message than just "Delta document update"?

**Comment by nmahadevuni** [comment]
LGTM. Please change the title as @yzhang1991 mentioned.

**Comment by agrawalreetika** [comment]
> LGTM. Please change the title as @yzhang1991 mentioned.

Done

**Review by nmahadevuni — APPROVED** [review]

**Comment by yzhang1991** [comment]
@prestodb/committers Can we merge this? It's a doc update. Thanks!

**Review by rschlussel — APPROVED** [review]

**Pull request merged**
