### PR TITLE
[WIP] Use smallest possible type for LongLiterals

### PR DESCRIPTION
**Pull request by kokosing**

### CODE REVIEW

**Comment by sopel39** [comment]
Some tests fail, probably need to change result types

**Comment by kokosing** [comment]
This an old story... I knew that there is something related to it, but I forgot what. When a function accepts `integer`, but when it gets `tinyint` then it fails with: `type of symbol 'expr_7' is expected to be integer, but the actual type is tinyint`

Besides that, this is very invasive change!

**Comment by kokosing** [comment]
FYI: @findepi

**Comment by findepi** [comment]
You surely need to update `LiteralInterpreter.toExpression` too.

**Comment by kokosing** [comment]
As far I recall it came out of https://github.com/prestodb/presto/pull/9984#issuecomment-370182878.

Closing.

**Pull request closed without merging**
