### PR TITLE
Revert "Add support for Filelist caching for symlink tables"

### PR DESCRIPTION
**Pull request by elharo**
Reverts prestodb/presto#19145 due to flakiness. This PR depends on the PR that introduced the flakiness so roll this one back first.

### CODE REVIEW

**Comment by tdcmeehan** [comment]
Why not just disable the product test?

**Comment by tdcmeehan** [comment]
@elharo based on the stack trace in #22425, it seems to be failing during the setup portion of the test case.  To me it seems like a testing issue, and it would be quicker and more straightforward to just disable the test.  Even if you're correct, the procedure that was added is opt-in, and no one will be using this until 0.287 is released, and that release hasn't even been cut yet, so there's actually only a risk if someone is using recent unstable releases (which are not widely used).

**Comment by agrawalreetika** [comment]
Hi @elharo @tdcmeehan,
I have been traveling, but I doubt if the feature is actually affected. I can take out some time and verify the feature if that works and we can disable the tests for now. As I checked the last some recent changes caused this failing and affecting JMX metrics in here.
LMK what do you guys think?

**Comment by elharo** [comment]
I'm not comfortable with an in-between state where we leave the feature in untested. The safe options are fix or revert. If you can find and revert some recent change that caused this to start failing, that would be great. Otherwise, let's revert now and fix it at our leisure later.

**Comment by agrawalreetika** [comment]
@elharo Could you please confirm if we are seeing test failure for https://github.com/prestodb/presto/blob/master/presto-product-tests/src/main/java/com/facebook/presto/tests/hive/TestSymlinkTableListCaching.java as well? I didn't find any CI example with failure on this.

**Comment by elharo** [comment]
No, I don't think TestSymlinkTableListCaching is flaky but it depends on the PR that is. 

Are you proposing to block the release until this is fixed? That feels risky. It seems much safer to simply roll everything back, and then fix at our leisure. If the fix is done before the release, great. If not, nothing else needs to wait for it.

**Comment by agrawalreetika** [comment]
@elharo Sure thanks for confirmation. These changes shouldn't be flaky.

Also for other one, I have found the RCA for flakiness for TestDirectoryListCacheInvalidation and proposed the test modification  https://github.com/prestodb/presto/pull/22455

**Comment by tdcmeehan** [comment]
Superseded by #22455

**Pull request closed without merging**
