### PR TITLE
Add configuration for dfs.client.retry.max.attempts

### PR DESCRIPTION
**Pull request by zhenxiao**
Need to play with configuration: dfs.client.retry.max.attempts (default 10)
to let Presto:
1. retry more in case of NameNode failover
2. retry less in case of NameNode super busy

### CODE REVIEW

**Comment by nezihyigitbasi** [comment]
Please update the hive connector docs with the new parameter.

**Comment by zhenxiao** [comment]
thank you @nezihyigitbasi get it addressed

**Comment by nezihyigitbasi** [comment]
Btw just curious, why can't you just put these configs in your hdfs-site.xml and add that to `hive.config.resources` in your Presto config, then we won't need these changes? Does sth prevent that from working?

**Comment by zhenxiao** [comment]
yep, I think Presto loads default HDFS configuration, and have to add new configs inside Presto to play with it. Please fix me if my understanding is incorrect

**Comment by nezihyigitbasi** [comment]
Presto copies first the configuration set by the `hive.config.resources` and then adds some more to it, please see [HdfsConfigurationUpdater::updateConfiguration()](https://github.com/prestodb/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/HdfsConfigurationUpdater.java#L138). So if you put your config in hdfs-site.xml and put that in `hive.config.resources` Presto should pick it up, please give it a try.

**Comment by zhenxiao** [comment]
@nezihyigitbasi you are correct, it is working fine

**Pull request closed without merging**
