### PR TITLE
Remove /v1/execute resource

### PR DESCRIPTION
**Pull request by electrum**

### CODE REVIEW

**Comment by lattwood** [comment]
What was the rationale for removing this @electrum? We are (were) looking at sticking prestodb behind a load balancer and using traditional HTTP connection draining for replacing prestodb coordinators, but without being able to do 1 HTTP request in flight = 1 running query, we can't.

**Comment by dain** [comment]
The execute resource only worked for very small short queries because the entire query must be run in a the timescale of a singe HTTP request.  We were unaware of any using the due to the limitations and would like to maintain fewer interfaces to Presto.

**Comment by lattwood** [comment]
Yeah, we were expecting blocking behaviour for this

**Comment by lattwood** [comment]
On that basis, is there a case to be made for adding synchronous query functionality back? Otherwise we're looking at writing a PrestoDB load balancer that has to keep track of asynchronous query execution.

**Comment by lattwood** [comment]
Opened #8063

**Pull request closed without merging**
