### PR TITLE
Fix serialized name for retriable QueryError property

### PR DESCRIPTION
**Pull request by MasterOdin**
Test plan - Added unit test in `presto-client/src/test/java/com/facebook/presto/client/TestQueryError.java`

```
== RELEASE NOTES ==

General Changes
* Fix serialized name for retriable QueryError property
```

### CODE REVIEW

**Review by jaystarshot — APPROVED** [review]

**Review by tdcmeehan — APPROVED** [review]
Thanks for fixing this!

**Comment by tdcmeehan** [comment]
Please rebase to kick off latest tests. I'll merge when finished.

**Comment by MasterOdin** [comment]
@tdcmeehan Done!

**Comment by MasterOdin** [comment]
@tdcmeehan I've rebased again. Looking at the test failures, I'm not sure why they would fail, as they appear to be unrelated to my change.

**Comment by tdcmeehan** [comment]
Rebased again, should fix the errors.  Will merge once tests pass.

**Review by ajaygeorge — APPROVED** [review]
LGTM

**Comment by tdcmeehan** [comment]
Thanks once again @MasterOdin

**Pull request merged**
