### PR TITLE
Parquet partition schema evolution on non-primitive columns

### PR DESCRIPTION
**Pull request by Yaliang**
Combined with the flexible parquet struct converter(#4714), this PR added a lazy equal on HiveType in order to allow a partition schema evolution over non-primitive fields(especially Struct).

### CODE REVIEW

**Comment by billonahill** [comment]
A general question I have is whether this functionality should be required to be enabled with a config setting, or if backward-compatible schema evolution should just be natively supported? I would think we'd want the latter, which is how I thought parquet schema evolution patches like #4714 were being handled.

**Comment by Yaliang** [comment]
Right, as I comment [here](https://github.com/prestodb/presto/pull/7305/commits/6251bea0004b9767144efd103301af307d70c4e5#diff-5b2f67483a7afa9203204186749ecf84R149). I am not sure if other formats have similar functionalities to handle the name-based mapping for non-primitive fields. We may able to combine with other information to decided either `equals` or `lazyEquals` should be used. But for prototyping, I would just pass this setting from the configuration.

**Comment by Yaliang** [comment]
For case of parquet format, we should use `lazyEquals` once the `isUseParquetColumnNames()` returns `true`.

**Comment by geraint0923** [comment]
I think Presto already has some support for primitive type evolution. If you want to support evolution for non-primitive types, it would be better to do it in `HiveCoercionPolicy` and then handle the coercions in `HiveCoercionRecordCursor`.

**Comment by Yaliang** [comment]
@geraint0923 Correct, that is an alternative approach and looks more structured.

**Comment by Yaliang** [comment]
It looks like #4714 has a dependency on presto-main beyond the test scope, which is bad. Will work on alternative approach without #4714. I guess I may have to repack the object in ``HiveCoercionRecordCursor``.

**Comment by Yaliang** [comment]
#4714 Rebased without dependency of presto-main. Will update when it passed CI.

**Comment by Yaliang** [comment]
Restructured commits.
Parquet cursor will get the column handler in the form of table schema and do the flexible conversion in itself. And for other formats, they will run into Not-Supported Exception.

**Comment by Yaliang** [comment]
@geraint0923 Ready for review

**Comment by Yaliang** [comment]
Closing this PR and implementing the coercion in HiveCoercionRecordCursor and HivePageSource #9131

**Pull request closed without merging**
