### PR TITLE
Remove toggle allowing to disable the Iterative Optimizer

### PR DESCRIPTION
**Pull request by findepi**
Although the toggle was called
`experimental.iterative-optimizer-enabled`, today, running with
iterative optimizer disabled should be considered experimental.

### CODE REVIEW

**Comment by kokosing** [comment]
The only concern I have is about future migration of remaining legacy rules. Maybe instead of this we should remove legacy rules that were migrated long time ago?

**Comment by findepi** [comment]
I think that if a rule is to be configurable, it should have a toggle.

**Comment by martint** [comment]
The idea with this toggle was to be able to fall back to the old visitor-based optimizers (for those that have one defined) if we found any issues. Once a `Rule`-based optimizer has been proven to work reliably, the corresponding legacy optimizer is supposed to be deleted, which "locks in" the new implementation for that point on.

**Comment by findepi** [comment]
@martint but this is kind of dead code -- i've found only one such fallback optimizer (`TransformCorrelatedSingleRowSubqueryToProject`); i will post a PR removing that optimizer as a separate PR.

do we want to retain this flag for any future use?

**Comment by findepi** [comment]
@martint if the toggle stays, it should not be called `experimental.iterative-optimizer-enabled`. It does not disable/enable Iterative Optimizer anymore.

**Comment by martint** [comment]
Agreed. We should come up with a better name for it.

**Pull request closed without merging**
