### PR TITLE
Use Scopes to resolve lambda argument references in ExpressionAnalyzer

### LINKED ISSUE #9023: Analysis error for table alias in lambda
```
presto:default> select transform(array[1], x -> x + t.a) from (values 1, 2, 3) t(a);
Query 20170921_015629_01585_tme2n failed: line 1:37: Column 't' cannot be resolved
com.facebook.presto.sql.analyzer.SemanticException: line 1:37: Column 't' cannot be resolved
	at com.facebook.presto.sql.analyzer.SemanticExceptions.missingAttributeException(SemanticExceptions.java:30)
	at com.facebook.presto.sql.analyzer.Scope.lambda$resolveField$0(Scope.java:104)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.facebook.presto.sql.analyzer.Scope.resolveField(Scope.java:104)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitIdentifier(ExpressionAnalyzer.java:371)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitIdentifier(ExpressionAnalyzer.java:282)
	at com.facebook.presto.sql.tree.Identifier.accept(Identifier.java:70)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:301)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitDereferenceExpression(ExpressionAnalyzer.java:404)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitDereferenceExpression(ExpressionAnalyzer.java:282)
	at com.facebook.presto.sql.tree.DereferenceExpression.accept(DereferenceExpression.java:54)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:301)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.getOperator(ExpressionAnalyzer.java:1145)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitArithmeticBinary(ExpressionAnalyzer.java:575)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitArithmeticBinary(ExpressionAnalyzer.java:282)
	at com.facebook.presto.sql.tree.ArithmeticBinaryExpression.accept(ArithmeticBinaryExpression.java:85)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:301)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitLambdaExpression(ExpressionAnalyzer.java:1080)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitLambdaExpression(ExpressionAnalyzer.java:282)
	at com.facebook.presto.sql.tree.LambdaExpression.accept(LambdaExpression.java:60)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:301)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:264)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.access$1900(ExpressionAnalyzer.java:160)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.lambda$visitFunctionCall$1(ExpressionAnalyzer.java:799)
	at com.facebook.presto.sql.analyzer.TypeSignatureProvider.getTypeSignature(TypeSignatureProvider.java:60)
	at com.facebook.presto.metadata.SignatureBinder$FunctionSolver.update(SignatureBinder.java:725)
	at com.facebook.presto.metadata.SignatureBinder.iterativeSolve(SignatureBinder.java:399)
	at com.facebook.presto.metadata.SignatureBinder.bindVariables(SignatureBinder.java:114)
	at com.facebook.presto.metadata.SignatureBinder.bind(SignatureBinder.java:91)
	at com.facebook.presto.metadata.FunctionRegistry.identifyApplicableFunctions(FunctionRegistry.java:734)
	at com.facebook.presto.metadata.FunctionRegistry.matchFunction(FunctionRegistry.java:703)
	at com.facebook.presto.metadata.FunctionRegistry.matchFunctionExact(FunctionRegistry.java:693)
	at com.facebook.presto.metadata.FunctionRegistry.resolveFunction(FunctionRegistry.java:648)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.resolveFunction(ExpressionAnalyzer.java:1321)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:808)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:282)
	at com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:111)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:301)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:258)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:1472)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.analyzeExpression(StatementAnalyzer.java:1901)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.analyzeSelect(StatementAnalyzer.java:1713)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.legacyVisitQuerySpecification(StatementAnalyzer.java:968)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:913)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:245)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:127)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:257)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:267)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:648)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:245)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:94)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:257)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:231)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:72)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:64)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:351)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:337)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
select transform(array[1], x -> x + t.a) from (values 1, 2, 3) t(a)

### LINKED ISSUE #9025: Wrong query results when lambda scope shadows column name
It's not possible to use dereference expressions in lambda context (#9023) except when dereferencing lambda argument's field (https://github.com/prestodb/presto/commit/789e4772527037efaed9e3bfbccfdee42697fa4b). 

However, even in the "supported" case, result is different when lambda arguement shadows a column reference:
```
SELECT transform(array[CAST(ROW(10) AS ROW(x INTEGER))], r -> r.x) FROM (VALUES 1) u(x);
 _col0 
-------
 [10]  
(1 row)

SELECT transform(array[CAST(ROW(10) AS ROW(x INTEGER))], r -> r.x) FROM (VALUES 1) r(x);
 _col0 
-------
 [1]   
(1 row)
```

IMO both queries should produce `10`, as column is being shadowed by lambda's formal argument.

### PR DESCRIPTION
**Pull request by findepi**
Use `Scope` to resolve lambda arguments in `ExpressionAnalyzer`.

Fixes #9023, #7784

For #7790 following things are still needed:
* `AggregationAnalyzer` needs similar update
* This doesn't fix #9025 (`QueryPlanner`?)

### CODE REVIEW

**Comment by sopel39** [comment]
Duplicate of https://github.com/prestodb/presto/issues/7790?

**Comment by findepi** [comment]
This is related to #7790 -- a step towards that direction.

I agree there is risk of inconsistency. However, there already is some inconsistency (#9025) even though scopes were used nowhere, so I think this still is a good step in a good direction.

**Comment by findepi** [comment]
@martint , did you have time to look into this?

**Comment by martint** [comment]
I did. The code looks good, but I need to think about the comment @sopel39 made above regarding inconsistencies. It'd be great if we can find concrete examples where it wouldn't work as expected (beyond the once you listed in #9025)

**Comment by findepi** [comment]
@sopel39 , did you have anything specific in mind?

**Comment by sopel39** [comment]
Resolution works differently than in `TranslationMap` (although it might be consistent. However this is a tricky code with edge cases). Why can't you simply make `ExpressionAnalyzer.Visitor#visitIdentifier` to behave like `TranslationMap#translateNamesToSymbols`. This way we wouldn't introduce second (possibly inconsistent) resolution method for lambda arguments.

**Comment by findepi** [comment]
`TranslationMap#translateNamesToSymbols` already does it differently than `ExpressionAnalyzer`, see my today comments in #9025.

Can we have an example of a query that will work incorrectly after this change and used to work correctly or at least fail before?

**Comment by sopel39** [comment]
> Can we have an example of a query that will work incorrectly after this change and used to work correctly or at least fail before?

I am not sure (I haven't deeply though about it), but this doesn't mean that there won't be any new regression. It seems that it would be easier to make that both `TranslationMap` and `ExpressionAnalyzer` to behave consistently for now (using current mechanism) than using yet another resolution method in `ExpressionAnalyzer` .

**Comment by findepi** [comment]
@sopel39 but the problem is in master they both do wrong (differently). After this PR, `ExpressionAnalyzer` will correctly resolve lambda references and captures within lambda and translation map needs to follow (I'm working on it currently) or abstain from any use of scopes (#7398).

I did a quick look into doing #7398, but the code seems both complex and 'there is room for improvement'-ish.

**Comment by sopel39** [comment]
> translation map needs to follow

Yeah, but then you probably should use `Scope` for lambda arguments resolution in `TranslationMap` too (in order to be consistent). I am just not sure it's worth the work since `Scopes` would be removed from actual planning.

**Comment by sopel39** [comment]
> but then you probably should use Scope for lambda arguments resolution in TranslationMap too 

Or maybe couple of `TODOs` would do for now too.

**Comment by findepi** [comment]
@martint , @sopel39 
i created follow-up PR that fixes `TranslationMap` and thus fixes #9025: #9090. This is not much code so it doesn't get us away from  #7398 (it doesn't get us closer either).

**Comment by sopel39** [comment]
> Yeah, but then you probably should use Scope for lambda arguments resolution in TranslationMap too 

This is probably not true. I think in `TranslationMap` you can just check if node is column ref or lambda argument ref.

**Comment by findepi** [comment]
@sopel39 let's move the discussion related to #9090 there. Do you have any other comments relating this PR? Can @martint merge it?

**Comment by sopel39** [comment]
I haven't reviewed it yet (I don't know if I will have time). However, the approach to use `Scope` in `ExpressionAnalzyzer` seems legit. I would avoid using it in `TranslationMap` though. Generally, it appears to be easier to switch to `Scope` for lambda args resolution than I thought.

**Comment by findepi** [comment]
@sopel39 i don't think you need to review this thoroughly, as @martint already did.

**Comment by findepi** [comment]
Superseded by #9099

**Pull request closed without merging**
