### PR TITLE
[native] Remove PRESTO_ENABLE_PARQUET logic from PrestoServer.cpp 

### PR DESCRIPTION
**Pull request by mbasmanova**
This logic is no longer needed.

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by mbasmanova** [comment]
@majetideepak Deepak, would you help review this one-liner?

**Comment by majetideepak** [comment]
@mbasmanova On the Velox side, the code is refactored such that we don't need this change in Prestissimo.
We can remove the check for `#include "velox/dwio/parquet/RegisterParquetReader.h" // @manual` as well.
Can you share the issue you are seeing? Probably we need only the `@manual` bits.

**Comment by mbasmanova** [comment]
@majetideepak Thank you for the comments. I just noticed that reader was include under the #ifdef, but writer was not. The original issue I was looking into is that Prestissimo brings in apache-thrift dependency, which has duplicate symbols with  //thrift/lib/cpp2/protocol:protocol  dependency brought in by Cosco. This results in linker errors for Presto-on-Spark targets.

**Comment by mbasmanova** [comment]
@majetideepak I removed the usage of PRESTO_ENABLE_PARQUET macro. Please, take another look.

**Comment by mbasmanova** [comment]
@majetideepak I wonder if we could refactor some more to make it so that DWRF and PARQUET readers / writers are registered only when Hive connector is registered.

```
  velox::dwrf::registerDwrfReaderFactory();
 
  velox::parquet::registerParquetReaderFactory(
```

**Review by majetideepak — APPROVED** [review]

**Comment by majetideepak** [comment]
> I wonder if we could refactor some more to make it so that DWRF and PARQUET readers / writers are registered only when Hive connector is registered.

@mbasmanova this is definitely an improvement we can implement. Do you want to open an Issue to track this?

**Comment by mbasmanova** [comment]
> @mbasmanova this is definitely an improvement we can implement. Do you want to open an Issue to track this?

Filed #19968

**Pull request merged**
