### PR TITLE
Remove Raptor codebase.

### PR DESCRIPTION
**Pull request by amitkdutta**
Raptor was a meta internal system used for fast analytics. The system is deprecated and shut down with many enhancement made in Presto (e.g. caching).  This PR removes raptor directory.

```
== RELEASE NOTES ==

General Changes
* Remove Raptor module

```

### CODE REVIEW

**Review by jainxrohit — APPROVED** [review]

**Review by pranjalssh — APPROVED** [review]

**Comment by pranjalssh** [comment]
https://www.google.com/url?sa=i&url=https%3A%2F%2Fgfycat.com%2Fgifs%2Fsearch%2Fdeath%2Bnote%2Bdelete&psig=AOvVaw29cDeCooXUJLP_V73fclry&ust=1679715490236000&source=images&cd=vfe&ved=0CA4QjRxqFwoTCMDdifvR8_0CFQAAAAAdAAAAABAD

**Comment by amitkdutta** [comment]
It's waiting for `test (:presto-raptor)` [which is deleted.](https://github.com/prestodb/presto/pull/19236/files#diff-56ede167cf06a6744d823b8c6880cbac5f4fe9c8a5452c34018cb5708d73b1ddL46) @pranjalssh I think we can merge this one and next changes won't run those tests.

**Comment by amitkdutta** [comment]
`test native` is fixed in https://github.com/prestodb/presto/pull/19243

**Comment by pranjalssh** [comment]
@tdcmeehan do you how can we remove presto-raptor as a Required test?

**Comment by amitkdutta** [comment]
@tdcmeehan Tim, will be very helpful if you can disable`test (:presto-raptor)` from workflow. We can delete a large chunk of code, tests which will make things a bit better.

**Comment by amitkdutta** [comment]
Removed protocol import for native worker here https://github.com/prestodb/presto/pull/19259

**Pull request merged**
