### PR TITLE
Change Hive's default storage format to ORC

### PR DESCRIPTION
**Pull request by findepi**
As ORC is the generally recommended storage format, defaults should
reflect that.

### CODE REVIEW

**Comment by electrum** [comment]
I agree with this change, but we shouldn't do it until the optimized ORC writer is enabled by default. When we do that, we also need to decide if validation should be enabled.

@dain and @wenleix thoughts?

**Comment by dain** [comment]
I'm hopeful that during this release cycle we will have the writer fully rolled out at FB, and then we should turn it on by default in Presto.  At the same time we can make ORC the default.  After a few more releases we can delete support for the old ORC code.  As for writer validation, I don't think it should be on by default.

**Comment by findepi** [comment]
> I agree we could enable ORC Optimized Writer

@wenleix will you?

**Comment by haozhun** [comment]
I'm very surprised that we haven't turned on optimized writer by default yet.

When we flip on the optimized writer by default, we should also turn off validation by default.

As @dain recently told me in a discussion, our configuration needs to be user-friendly and benchmark-friendly. Having validation on by default is definitely not.

**Comment by findepi** [comment]
@wenleix updated

@dain @haozhun FYI, as this also enables optimized ORC writer, this also disables validation by default.

**Pull request merged**
