### PR TITLE
allow user and password passthrough from catalog config file when usi…

### PR DESCRIPTION
**Pull request by flobit**
allow user and password passthrough from catalog config file when using sid in jdbc url

Test plan - (Please fill in how you tested your changes)

Please make sure your submission complies with our [Development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [Formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), and [Commit Message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests) guidelines. Don't forget to follow our [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution) for any code copied from other projects.

Fill in the release notes towards the bottom of the PR description.
See [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) for details.

```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by yzhang1991** [comment]
Hi @agrawalreetika , can you review this?

**Comment by rohanpednekar** [comment]
@flobit Could you please sign CLA?

**Comment by agrawalreetika** [comment]
Hi @flobit,
I believe there is already `connection-user` and `connection-password` property exposed for JDBC connectors. could you please let me know why we need this?

**Comment by rohanpednekar** [comment]
@flobit, Hope all is well with you! 

This is just a friendly ping!

**Comment by flobit** [comment]
> @flobit, Hope all is well with you!

thank you ! recently my network meet some trouble,so could not dealing email in time
I have already sign the CLA

**Comment by agrawalreetika** [comment]
@flobit Here in baseJdbc, `connection-user` & `connection-password` is being set in connection properties which we could set in the Oracle catalog - https://prestodb.io/docs/current/connector/oracle.html#configuration
Ref - https://github.com/prestodb/presto/blob/master/presto-base-jdbc/src/main/java/com/facebook/presto/plugin/jdbc/DriverConnectionFactory.java#L47

Please help me understand what different are we doing by setting connection properties again in the PR changes?

**Comment by flobit** [comment]
> different are we doing by setting connection properties again

hello, in old code provided these properties but not pass them to the driver.
now I have changed to use the method in DriverConnectionFactory to build the base connection properties

**Comment by agrawalreetika** [comment]
Hi @flobit, 
Could we talk about this change over slack? I couldn't find you there, could you please ping me over slack?

**Pull request closed without merging**
