### PR TITLE
Disable registering JdkBasedZoneInfoProvider

### LINKED ISSUE #12235: joda-to-java bridge causing excessive CachedDateTimeZone$Info objects
While testing we found that 8ac4b8466a7db96d9941e27cecf7aaf64c85bfaf causes 180gb heaps to fill up with 145-150gb of org.joda.time.tz.CachedDateTimeZone.

It looks like it's due to https://github.com/airlift/joda-to-java-time-bridge/commit/bebbce575864bb4bbc56be6f799cd8acae65c8d9: the JdkBasedZoneInfoProvider creates CachedDateTimeZone for all non fixed zones (in the static block).

@haozhun would you have more context about this?

### PR DESCRIPTION
**Pull request by elonazoulay**
Resolves #12235

### CODE REVIEW

**Comment by elonazoulay** [comment]
Also added a commit to update the year in verifySystemTimeIsReasonable to 2019.

**Comment by electrum** [comment]
The documentation removal is in the wrong commit. I realized we will also need to remove the check in `PluginManager`.

I'm still looking at the other approach of actually fixing it by removing the caching.

**Comment by elonazoulay** [comment]
Updated the commits.

For fixing this would it help to do a test and find out which time zones are causing the most caching of Info objects?

**Comment by elonazoulay** [comment]
Closing since https://github.com/airlift/joda-to-java-time-bridge/pull/5 was merged.

**Comment by findepi** [comment]
Superseded by https://github.com/prestodb/presto/pull/12241

**Comment by elonazoulay** [comment]
Merging, this is to address the issues seen in testing where the heap fills up due to issues/possible bugs in the joda library discussed in #12235 (cache thrashing).

**Pull request merged**
