### PR TITLE
Fix checkArgument message in `DefaultOrcWriterFlushPolicy`

### PR DESCRIPTION
**Pull request by polaris6**

### CODE REVIEW

**Comment by polaris6** [comment]
@mbasmanova @sdruzkin could you please help me review and merge this pr when you have time? thank you very much!

**Comment by steveburnett** [comment]
Could a release note entry be of use here? Perhaps something like 

```
== RELEASE NOTES ==

General Changes
* Fix checkArgument message in DefaultOrcWriterFlushPolicy
```

**Comment by sdruzkin** [comment]
LGTM. Please fill in the PR summary.

**Comment by tdcmeehan** [comment]
IMO this is trivial and doesn't require a release note.

**Review by tdcmeehan — APPROVED** [review]

**Pull request merged**
