### PR TITLE
Add TableWriterOperator memory tracking

### PR DESCRIPTION
**Pull request by jacobgao**
Also, seems no system memory really needs to be tracked for TableScanOperator?

-Jacob

### CODE REVIEW

**Comment by electrum** [comment]
TableScan can be a huge source of memory usage. The ORC readers have large buffers.

**Comment by electrum** [comment]
I see some unit test failures for `TestExchangeClient` in Travis.

**Comment by cberner** [comment]
Can you rebase this and make sure Travis is passing?

**Comment by cberner** [comment]
Can you take this over? You can create a new PR and assign that to me when it's ready for review

**Comment by cberner** [comment]
Going to close this as it's not complete

**Pull request closed without merging**
