### PR TITLE
Ensure that checkstyle is ignoring generated code

### PR DESCRIPTION
**Pull request by chrisunder**

### CODE REVIEW

**Comment by electrum** [comment]
Checkstyle should only run on source directories. Can you give an example of how to reproduce the issue that this solves?

**Comment by chrisunder** [comment]
On every Mac on our team and our CI environment the files in presto-parser/target/generated-sources/antlr4/com/facebook/presto/type kept getting scanned and failed because they are auto generated and don't match the style guides.

This happens on brand new CI nodes with an empty ~/.m2 folder. 

I also asked Jason Vanzyl who has access to our internal environment and we couldn't figure out why this works elsewhere and not here.

**Comment by electrum** [comment]
@jvanzyl any ideas on this?

**Comment by electrum** [comment]
I found that this fails: `mvn -pl presto-parser generate-sources validate`

But running them in separate Maven invocations in that order does not:
```
mvn -pl presto-parser generate-sources
mvn -pl presto-parser validate
```

Could this be related to your issue? What is the exact Maven command that you are running?

**Comment by electrum** [comment]
Running that first command with `-X` shows this:
```
[DEBUG]   (f) sourceDirectories = [/Users/dphillips/src/presto/presto-parser/src/main/java, /Users/dphillips/src/presto/presto-parser/target/generated-sources/antlr4]
```
I suppose that is expected behavior, because the `generate-sources` goal adds the generated directory to the project sources.

**Comment by electrum** [comment]
Can you try adding this to the checkstyle plugin configuration?
```
<sourceDirectories>
    <directory>${project.build.sourceDirectory}</directory>
</sourceDirectories>
<testSourceDirectories>
    <directory>${project.build.testSourceDirectory}</directory>
</testSourceDirectories>

**Comment by electrum** [comment]
If that works for you, please update the pull request to do that it that way.

Though I'd still like to understand what is happening, since there might be other problems like this.

**Comment by chrisunder** [comment]
Maven details:
`[workspace] $ /usr/lib/jvm/java-1.8.0-openjdk.x86_64/bin/java -DskipTests=true -Dmaven.javadoc.skip=true -cp /var/lib/jenkins/plugins/maven-plugin/WEB-INF/lib/maven32-agent-1.6.jar:/usr/share/apache-maven/boot/plexus-classworlds-2.5.2.jar:/usr/share/apache-maven/conf/logging jenkins.maven3.agent.Maven32Main /usr/share/apache-maven /var/cache/jenkins/war/WEB-INF/lib/remoting-2.57.jar /var/lib/jenkins/plugins/maven-plugin/WEB-INF/lib/maven32-interceptor-1.6.jar /var/lib/jenkins/plugins/maven-plugin/WEB-INF/lib/maven3-interceptor-commons-1.6.jar 51780

Executing Maven:  -B -f /var/lib/jenkins/jobs/presto/workspace/pom.xml clean install package`

I also tried upgrading to the latest maven and that didn't help.

**Comment by chrisunder** [comment]
I will also revert my changes and test out the following locally.  May take me till later tonight
```
<sourceDirectories>
    <directory>${project.build.sourceDirectory}</directory>
</sourceDirectories>
<testSourceDirectories>
    <directory>${project.build.testSourceDirectory}</directory>
</testSourceDirectories>
```

**Comment by jvanzyl** [comment]
Are you using the Maven Job type and not a Freestyle Job type in Jenkins?

**Comment by chrisunder** [comment]
I am using the Maven Job Type, but the issue also happens on about every corpate Macbook I could get my hands on and that is just me typing `mvn clean install package`

**Comment by electrum** [comment]
FYI, we used to hit all sorts of weird issues with the Maven job type in Jenkins. Using Freestyle and just running `mvn` was much better. Though you lose nice features like deploying everything at the end of the job instead of as it runs.

**Comment by chrisunder** [comment]
Looks like 
```
<sourceDirectories>
    <directory>${project.build.sourceDirectory}</directory>
</sourceDirectories>
<testSourceDirectories>
    <directory>${project.build.testSourceDirectory}</directory>
</testSourceDirectories>
```

Is working.  I will update the PR today

**Comment by electrum** [comment]
Merged, thanks!

**Comment by chrisunder** [comment]
Thanks for the help!

**Pull request closed without merging**
