### PR TITLE
Adding html_entity_escape function to presto

### PR DESCRIPTION
**Pull request by drudenko**
@martint @electrum , please review

### CODE REVIEW

**Comment by drudenko** [comment]
@martint @cberner please review

**Comment by drudenko** [comment]
ping

**Comment by facebook-github-bot-1** [comment]
Thank you for your pull request.  As you may know, we require contributors to sign our Contributor License Agreement, and we don't seem to have you on file and listed as active anymore.  In order for us to review and merge your code, please email cla@fb.com with your details so we can update your status.

**Comment by facebook-github-bot-7** [comment]
Thank you for your pull request.  As you may know, we require contributors to sign our Contributor License Agreement, and we don't seem to have you on file and listed as active anymore.  In order for us to review and merge your code, please email cla@fb.com with your details so we can update your status.

**Comment by facebook-github-bot-7** [comment]
Thank you for your pull request.  As you may know, we require contributors to sign our Contributor License Agreement, and we don't seem to have you on file and listed as active anymore.  In order for us to review and merge your code, please email cla@fb.com with your details so we can update your status.

**Comment by raghavsethi** [comment]
@electrum Could you take a look at the syntax?

**Pull request closed without merging**
