### PR TITLE
Projection in split source manager

### PR DESCRIPTION
**Pull request by arhimondr**
https://github.com/prestodb/presto/pull/5122#issuecomment-234366563

### CODE REVIEW

**Comment by maciejgrzybek** [comment]
Looks good. Please squash commits though.

**Comment by arhimondr** [comment]
Second commit is mostly the Intellij automatic refactor. I thought it would be better to keep them in separate to be able to easily check the actual changes.

**Comment by martint** [comment]
What's the purpose of this change? Something we've been considering is to be able to push down column (and sub-column) projections to connectors so that, for instance, formats like Parquet can avoid even reading the bytes for sub-columns that are not going to be used by the engine (e.g., https://github.com/prestodb/presto/pull/5547). 

To do that, we'd need to modify the getTableLayout call in connector metadata to take some descriptor of what's needed. That's completely different approach than the one proposed in this PR.

**Comment by arhimondr** [comment]
In one of our internal connectors we need to initiate query only once, when the Presto query begins. And we need to fetch only columns that are needed. There was a long discussion in #5122. [ @maciejgrzybek, @electrum ]

**Comment by electrum** [comment]
I agree, this should be in the layout, since a layout might only have a subset of columns and thus needs to know about the desired columns anyway.

**Comment by maciejgrzybek** [comment]
@martint: the problem is `getTableLayout` is called before optimizer finishes work, so the projection list may change AFTER calling `getTableLayout`. E.g. `MetadataQueryOptimizer` or `BeginTableWrite` call `getTableLayout`. If there's an optimizer after `MetadataQueryOptimizer` pruning projection list, then `TableLayout` is inaccurate.

If you want to pass that information in `TableLayout` (in oppose to what @electrum suggested here: https://github.com/prestodb/presto/pull/5122#issuecomment-234366563) it means `getTableLayout` / `getTableLayouts` should be fired after all rewrites, which is quite against what's the purpose of this method now IMO.

**Comment by electrum** [comment]
@martint can decide if this is the correct API, then I can review

**Comment by martint** [comment]
I see. Yeah, that will require some thinking, and it might not be doable until we have a more sophisticated planner. Let's go with this approach, then.

BTW, if you're going to add the columns to the SplitManager call, we should consider removing it from PageSourceProvider (since, presumably, the information will already be in the splits). In particular, it would be confusing if getSplits() gets called with one set of columns and createPageSource() with a different set (or in a different order).

**Comment by arhimondr** [comment]
Do you want me to do so as part of this PR?

**Comment by electrum** [comment]
Yes

**Comment by arhimondr** [comment]
This change is not longer needed for the team it was initially made for. @martint, @electrum let me know if it is something you would like to have anyway, so i can re-open it.

**Pull request closed without merging**
