### PR TITLE
Hover tooltip in Live Plan for tablescan and filter nodes

### PR DESCRIPTION
**Pull request by rebeccajfriedman**
Addresses: https://github.com/prestodb/presto/issues/9602

Exposes a tooltip for `tablescan` nodes to display the table name. Also exposes a tooltip for `filter` nodes to show the predicate.

Test query [tested with Hive and MySQL]:
```sql
select * 
from system.runtime.tasks a 
inner join system.runtime.tasks b 
    on a.task_id = b.task_id 
where a.state <> 'FINISHED';
```

screen shot 2018-06-15 at 2 02 27 pm

screen shot 2018-06-15 at 2 10 48 pm

### CODE REVIEW

**Comment by findepi** [comment]
@rebeccajfriedman great thanks for putting up this PR!
This is definitely a good improvement. However, did you consider putting table name directly on the page, without a tooltip?
At least on your screenshots, it looks as if the table name could be fitted directly on the screen. This might help navigating over bigger plans.

cc @raghavsethi

**Comment by martint** [comment]
@findepi, my plan since I built the first version has been to eventually expand it to show more info in the boxes, including live stats for every operator, so that would be my preference, too.

**Comment by rebeccajfriedman** [comment]
@findepi @martint This is what I did:
1. Add the table name directly under tableScan
2. Pull table name functionality out of extraInfo functionality, because there are other things that we may want to expose via a tooltip

What do you think?

screen shot 2018-06-20 at 11 52 34 am

**Comment by findepi** [comment]
I like this. Can you somehow include catalog in the table name as well ("system" in this example)?

Just thinking -- what if we removed "tablescan" from the table scan node, leaving just the table name?

@martint ?

**Comment by findepi** [comment]
@batareyka you're more than welcome! 

> Can Presto query tables from multiple catalogues within the same query? 

Yes! This is one of the key features -- Presto is _not_ a "frontend" to databases or a "catalog". It's an execution engine that can pull data from many sources and yes, it can pull form different sources within the same query.

> I personally like having tablescan in the node, ...

Please correct me if I didn't understand -- you mean to retain information about table being scanned? Or the exact word "tablescan"?
If you find the word "tablescan" helpful -- I am OK. I don't have strong opinion here.

**Comment by raghavsethi** [comment]
@rebeccajfriedman @findepi I'll take this and add into my next batch of Web UI fixes (sometime this month for sure).

**Comment by batareyka** [comment]
Thank you!! I am super excited for these changes :)

**Comment by raghavsethi** [comment]
Rebecca,

I started looking into this to put in as part of #11158, but while looking over your code I realized how brittle and sensitive it is to specifics of the plan node fields (which are certainly not APIs, and do change frequently). Perhaps a better solution is for each plan node to produce a textual representation that we can use in the UIs (perhaps `toString`s could be used as-is, modified slightly, or we could add another method like it). This would decouple the UI from the plan nodes a lot better, and would make it easy to refactor or make changes without breaking things. It is challenging to integration-test the UI with the Java source code in it's current form.

If you would like to explore that route, please let me know. If not, we can close this PR out and add an issue to track the work item.

**Comment by raghavsethi** [comment]
Ran across this scrolling through email and realized I didn't link PRs properly. Just for completeness, this functionality was merged in with commit  55a4f8683f407156fabddae2a019d27424e61c04.

**Pull request closed without merging**
