### PR TITLE
Iceberg: Extend Parquet reader system to add an optional row-index column.

### PR DESCRIPTION
**Pull request by shidayang**
Cherry-pick of  [trinodb/trino#7523](https://github.com/trinodb/trino/pull/7523).

Co-authored-by: Jacob Ilias Komissar

Test plan - Not needed

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by shidayang** [comment]
cc @ChunxuTang

**Comment by ChunxuTang** [comment]
@shidayang Thanks for your nice contribution! 
Would you mind fixing the maven compilation error from the tests?

**Comment by shidayang** [comment]
@ChunxuTang Thanks for your reply. I have some doubts whether I caused the  compilation error. I have compiled and validated the code successfully in local.  I had not changed the module druid, but the message is _Failed to execute goal com.hubspot.maven.plugins:dependency-scope-maven-plugin:0.8:check (default) on project presto-druid: Error resolving descriptor for artifact org.hyperic:sigar:1.6.5.132: Failed to read artifact descriptor for org.hyperic:sigar:jar:1.6.5.132_

**Comment by ChunxuTang** [comment]
> @ChunxuTang Thanks for your reply. I have some doubts whether I caused the compilation error. I have compiled and validated the code successfully in local. I had not changed the module druid, but the message is _Failed to execute goal com.hubspot.maven.plugins:dependency-scope-maven-plugin:0.8:check (default) on project presto-druid: Error resolving descriptor for artifact org.hyperic:sigar:1.6.5.132: Failed to read artifact descriptor for org.hyperic:sigar:jar:1.6.5.132_

I see. Could you try `git rebase (or merge)` the current Presto master branch and then force push your changes to rerun the tests?

**Comment by shidayang** [comment]
@ChunxuTang OK, I am going to have a try.

**Comment by shidayang** [comment]
@ChunxuTang The last error is "maven checks",  but now the error is "ci / product-tests-specific-environment2"

**Comment by shidayang** [comment]
@ChunxuTang Aha, All checks have passed

**Comment by shidayang** [comment]
@ChunxuTang Thank you for your guidance.

**Comment by ChunxuTang** [comment]
@shidayang Thanks for your work!

Hi @zhenxiao and @beinan, would you like to have another review of this change and see whether it looks good to you?

**Review by zhenxiao — APPROVED** [review]
thank you @shidayang looks good to me. 
what do you think @beinan

**Review by beinan — APPROVED** [review]
lgtm, many thanks for the contribution!

**Pull request merged**
