### PR TITLE
Remove `using namespace` from header files

### PR DESCRIPTION
**Pull request by r-barnes**
Removes `using namespace` from header files to align with Velox C++ codestyle guidelines ([link](https://github.com/facebookincubator/velox/blob/main/CODING_STYLE.md#namespaces)).

### CODE REVIEW

**Comment by rschlussel** [comment]
I think -Wheader-hygiene is an internal concept?

Can you change the PR title/description and commit message title/description to be clearer about what this is doing and why.  It sounds like what this is doing is removing "using namespace xxx" from header files, as is aligned with our c++ codestyle guidelines, which follows the velox style guide https://github.com/facebookincubator/velox/blob/main/CODING_STYLE.md#namespaces.

**Comment by rschlussel** [comment]
Can you update the commit message as well (same description/title as the pr description)?

**Review by rschlussel — APPROVED** [review]
thanks! I need someone from team-velox to approve @amitkdutta

**Comment by rschlussel** [comment]
@r-barnes I think you need to split the presto part of this change out from the other part for your diff.

**Review by aditi-pandit — APPROVED** [review]
Thanks @r-barnes.

**Pull request merged**
