### PR TITLE
Revert dictionary block optimization for unnest

### PR DESCRIPTION
**Pull request by wenleix**
Regression that causes query to fail is observed in production workload.

This reverts the following commits:
- "Add benchmark for UnnestOperator": 8e45a9616a2d4385284ff64069b396e8f4f6910f.
- "Adjust getOffset output in Columnar classes for trimmed element blocks": df67792817187bbc0e2e907d83ee3c02dcbce9b7.
- "Implement Unnest Operator with Dictionary Blocks": 9232496259862c10dfad051050db451767bc77ee.
- "Move classes for Unnest Operator to a separate package": 1906c165d90aea8a4a14e67a79c53248110bfcb7.

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by wenleix** [comment]
This reverts https://github.com/prestodb/presto/pull/13319, which backports prestosql/presto#901

**Comment by rongrong** [comment]
Please fix checkstyle error first

**Comment by jessesleeping** [comment]
Also there is compile failure which depends on this change:

**Comment by wenleix** [comment]
Still investigate the root cause.

**Pull request closed without merging**
