### PR TITLE
Upgrade Iceberg to 0.12.0 and upgrade Parquet to 1.12.0

### PR DESCRIPTION
**Pull request by beinan**
Upgrade Iceberg to 0.12.0 and upgrade Parquet to 1.12.0

```
== RELEASE NOTES ==

Hive Changes
* Upgrade Parquet to 1.12.0

Iceberg Changes
* Upgrade Iceberg to 0.12.0
```

### CODE REVIEW

**Review by zhenxiao — APPROVED** [review]
looks good
let's re-run. the test, making sure all tests passed

**Comment by beinan** [comment]
thank you @zhenxiao!  all test passed

**Review by zhenxiao — APPROVED** [review]

**Comment by arunthirupathi** [comment]
One of the parquet test is failing with this error.

Error:  Failures: 
Error:    TestFullParquetReader>AbstractTestParquetReader.testDecimalBackedByFixedLenByteArray:938 » IllegalArgument

```
java.lang.IllegalArgumentException: maxCapacityHint can't be less than initialSlabSize 1024 100
	at org.apache.parquet.Preconditions.checkArgument(Preconditions.java:53)
	at org.apache.parquet.bytes.CapacityByteArrayOutputStream.<init>(CapacityByteArrayOutputStream.java:153)
	at org.apache.parquet.column.values.delta.DeltaBinaryPackingValuesWriter.<init>(DeltaBinaryPackingValuesWriter.java:91)
	at org.apache.parquet.column.values.delta.DeltaBinaryPackingValuesWriterForInteger.<init>(DeltaBinaryPackingValuesWriterForInteger.java:71)
	at org.apache.parquet.column.values.deltastrings.DeltaByteArrayWriter.<init>(DeltaByteArrayWriter.java:45)
	at org.apache.parquet.column.values.factory.DefaultV2ValuesWriterFactory.getFixedLenByteArrayValuesWriter(DefaultV2ValuesWriterFactory.java:82)
	at org.apache.parquet.column.values.factory.DefaultV2ValuesWriterFactory.newValuesWriter(DefaultV2ValuesWriterFactory.java:58)
	at org.apache.parquet.column.values.factory.DefaultValuesWriterFactory.newValuesWriter(DefaultValuesWriterFactory.java:52)
	at org.apache.parquet.column.ParquetProperties.newValuesWriter(ParquetProperties.java:149)
	at org.apache.parquet.column.impl.ColumnWriterBase.<init>(ColumnWriterBase.java:66)
	at org.apache.parquet.column.impl.ColumnWriterV2.<init>(ColumnWriterV2.java:59)
	at org.apache.parquet.column.impl.ColumnWriteStoreV2.createColumnWriter(ColumnWriteStoreV2.java:35)
	at org.apache.parquet.column.impl.ColumnWriteStoreBase.<init>(ColumnWriteStoreBase.java:94)
	at org.apache.parquet.column.impl.ColumnWriteStoreV2.<init>(ColumnWriteStoreV2.java:30)
	at org.apache.parquet.column.ParquetProperties.newColumnWriteStore(ParquetProperties.java:182)
	at org.apache.parquet.hadoop.InternalParquetRecordWriter.initStore(InternalParquetRecordWriter.java:106)
	at org.apache.parquet.hadoop.InternalParquetRecordWriter.<init>(InternalParquetRecordWriter.java:96)
	at org.apache.parquet.hadoop.ParquetRecordWriter.<init>(ParquetRecordWriter.java:153)
	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:487)
	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:416)
	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:411)
	at org.apache.hadoop.hive.ql.io.parquet.write.ParquetRecordWriterWrapper.<init>(ParquetRecordWriterWrapper.java:70)
	at org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat.getParquerRecordWriterWrapper(MapredParquetOutputFormat.java:137)
	at org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat.getHiveRecordWriter(MapredParquetOutputFormat.java:126)
	at com.facebook.presto.hive.parquet.write.TestMapredParquetOutputFormat.getHiveRecordWriter(TestMapredParquetOutputFormat.java:63)
	at com.facebook.presto.hive.parquet.ParquetTester.writeParquetColumn(ParquetTester.java:706)
	at com.facebook.presto.hive.parquet.ParquetTester.assertRoundTrip(ParquetTester.java:369)
	at com.facebook.presto.hive.parquet.ParquetTester.testRoundTripType(ParquetTester.java:333)
	at com.facebook.presto.hive.parquet.ParquetTester.testRoundTrip(ParquetTester.java:229)
	at com.facebook.presto.hive.parquet.AbstractTestParquetReader.testDecimalBackedByFixedLenByteArray(AbstractTestParquetReader.java:938)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

Can you please take a look ?

**Comment by beinan** [comment]
> One of the parquet test is failing with this error.
> 
> Error: Failures: Error: TestFullParquetReader>AbstractTestParquetReader.testDecimalBackedByFixedLenByteArray:938 » IllegalArgument
> 
> ```
> java.lang.IllegalArgumentException: maxCapacityHint can't be less than initialSlabSize 1024 100
> 	at org.apache.parquet.Preconditions.checkArgument(Preconditions.java:53)
> 	at org.apache.parquet.bytes.CapacityByteArrayOutputStream.<init>(CapacityByteArrayOutputStream.java:153)
> 	at org.apache.parquet.column.values.delta.DeltaBinaryPackingValuesWriter.<init>(DeltaBinaryPackingValuesWriter.java:91)
> 	at org.apache.parquet.column.values.delta.DeltaBinaryPackingValuesWriterForInteger.<init>(DeltaBinaryPackingValuesWriterForInteger.java:71)
> 	at org.apache.parquet.column.values.deltastrings.DeltaByteArrayWriter.<init>(DeltaByteArrayWriter.java:45)
> 	at org.apache.parquet.column.values.factory.DefaultV2ValuesWriterFactory.getFixedLenByteArrayValuesWriter(DefaultV2ValuesWriterFactory.java:82)
> 	at org.apache.parquet.column.values.factory.DefaultV2ValuesWriterFactory.newValuesWriter(DefaultV2ValuesWriterFactory.java:58)
> 	at org.apache.parquet.column.values.factory.DefaultValuesWriterFactory.newValuesWriter(DefaultValuesWriterFactory.java:52)
> 	at org.apache.parquet.column.ParquetProperties.newValuesWriter(ParquetProperties.java:149)
> 	at org.apache.parquet.column.impl.ColumnWriterBase.<init>(ColumnWriterBase.java:66)
> 	at org.apache.parquet.column.impl.ColumnWriterV2.<init>(ColumnWriterV2.java:59)
> 	at org.apache.parquet.column.impl.ColumnWriteStoreV2.createColumnWriter(ColumnWriteStoreV2.java:35)
> 	at org.apache.parquet.column.impl.ColumnWriteStoreBase.<init>(ColumnWriteStoreBase.java:94)
> 	at org.apache.parquet.column.impl.ColumnWriteStoreV2.<init>(ColumnWriteStoreV2.java:30)
> 	at org.apache.parquet.column.ParquetProperties.newColumnWriteStore(ParquetProperties.java:182)
> 	at org.apache.parquet.hadoop.InternalParquetRecordWriter.initStore(InternalParquetRecordWriter.java:106)
> 	at org.apache.parquet.hadoop.InternalParquetRecordWriter.<init>(InternalParquetRecordWriter.java:96)
> 	at org.apache.parquet.hadoop.ParquetRecordWriter.<init>(ParquetRecordWriter.java:153)
> 	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:487)
> 	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:416)
> 	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:411)
> 	at org.apache.hadoop.hive.ql.io.parquet.write.ParquetRecordWriterWrapper.<init>(ParquetRecordWriterWrapper.java:70)
> 	at org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat.getParquerRecordWriterWrapper(MapredParquetOutputFormat.java:137)
> 	at org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat.getHiveRecordWriter(MapredParquetOutputFormat.java:126)
> 	at com.facebook.presto.hive.parquet.write.TestMapredParquetOutputFormat.getHiveRecordWriter(TestMapredParquetOutputFormat.java:63)
> 	at com.facebook.presto.hive.parquet.ParquetTester.writeParquetColumn(ParquetTester.java:706)
> 	at com.facebook.presto.hive.parquet.ParquetTester.assertRoundTrip(ParquetTester.java:369)
> 	at com.facebook.presto.hive.parquet.ParquetTester.testRoundTripType(ParquetTester.java:333)
> 	at com.facebook.presto.hive.parquet.ParquetTester.testRoundTrip(ParquetTester.java:229)
> 	at com.facebook.presto.hive.parquet.AbstractTestParquetReader.testDecimalBackedByFixedLenByteArray(AbstractTestParquetReader.java:938)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> ```
> 
> Can you please take a look ?

Sure, I'm on it.  Thank you for the heads up!

**Comment by beinan** [comment]
> One of the parquet test is failing with this error.
> 
> Error: Failures: Error: TestFullParquetReader>AbstractTestParquetReader.testDecimalBackedByFixedLenByteArray:938 » IllegalArgument
> 
> ```
> java.lang.IllegalArgumentException: maxCapacityHint can't be less than initialSlabSize 1024 100
> 	at org.apache.parquet.Preconditions.checkArgument(Preconditions.java:53)
> 	at org.apache.parquet.bytes.CapacityByteArrayOutputStream.<init>(CapacityByteArrayOutputStream.java:153)
> 	at org.apache.parquet.column.values.delta.DeltaBinaryPackingValuesWriter.<init>(DeltaBinaryPackingValuesWriter.java:91)
> 	at org.apache.parquet.column.values.delta.DeltaBinaryPackingValuesWriterForInteger.<init>(DeltaBinaryPackingValuesWriterForInteger.java:71)
> 	at org.apache.parquet.column.values.deltastrings.DeltaByteArrayWriter.<init>(DeltaByteArrayWriter.java:45)
> 	at org.apache.parquet.column.values.factory.DefaultV2ValuesWriterFactory.getFixedLenByteArrayValuesWriter(DefaultV2ValuesWriterFactory.java:82)
> 	at org.apache.parquet.column.values.factory.DefaultV2ValuesWriterFactory.newValuesWriter(DefaultV2ValuesWriterFactory.java:58)
> 	at org.apache.parquet.column.values.factory.DefaultValuesWriterFactory.newValuesWriter(DefaultValuesWriterFactory.java:52)
> 	at org.apache.parquet.column.ParquetProperties.newValuesWriter(ParquetProperties.java:149)
> 	at org.apache.parquet.column.impl.ColumnWriterBase.<init>(ColumnWriterBase.java:66)
> 	at org.apache.parquet.column.impl.ColumnWriterV2.<init>(ColumnWriterV2.java:59)
> 	at org.apache.parquet.column.impl.ColumnWriteStoreV2.createColumnWriter(ColumnWriteStoreV2.java:35)
> 	at org.apache.parquet.column.impl.ColumnWriteStoreBase.<init>(ColumnWriteStoreBase.java:94)
> 	at org.apache.parquet.column.impl.ColumnWriteStoreV2.<init>(ColumnWriteStoreV2.java:30)
> 	at org.apache.parquet.column.ParquetProperties.newColumnWriteStore(ParquetProperties.java:182)
> 	at org.apache.parquet.hadoop.InternalParquetRecordWriter.initStore(InternalParquetRecordWriter.java:106)
> 	at org.apache.parquet.hadoop.InternalParquetRecordWriter.<init>(InternalParquetRecordWriter.java:96)
> 	at org.apache.parquet.hadoop.ParquetRecordWriter.<init>(ParquetRecordWriter.java:153)
> 	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:487)
> 	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:416)
> 	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:411)
> 	at org.apache.hadoop.hive.ql.io.parquet.write.ParquetRecordWriterWrapper.<init>(ParquetRecordWriterWrapper.java:70)
> 	at org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat.getParquerRecordWriterWrapper(MapredParquetOutputFormat.java:137)
> 	at org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat.getHiveRecordWriter(MapredParquetOutputFormat.java:126)
> 	at com.facebook.presto.hive.parquet.write.TestMapredParquetOutputFormat.getHiveRecordWriter(TestMapredParquetOutputFormat.java:63)
> 	at com.facebook.presto.hive.parquet.ParquetTester.writeParquetColumn(ParquetTester.java:706)
> 	at com.facebook.presto.hive.parquet.ParquetTester.assertRoundTrip(ParquetTester.java:369)
> 	at com.facebook.presto.hive.parquet.ParquetTester.testRoundTripType(ParquetTester.java:333)
> 	at com.facebook.presto.hive.parquet.ParquetTester.testRoundTrip(ParquetTester.java:229)
> 	at com.facebook.presto.hive.parquet.AbstractTestParquetReader.testDecimalBackedByFixedLenByteArray(AbstractTestParquetReader.java:938)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> ```
> 
> Can you please take a look ?

Hey @arunthirupathi  Where did you see this failure?  I cannot reproduce it locally.

image

**Comment by arunthirupathi** [comment]
It failed twice for me on my recent PR but on re-run it passed again. 

https://github.com/prestodb/presto/runs/4290404568?check_suite_focus=true

**Comment by arunthirupathi** [comment]
I am not sure whether this change is even related, but there is no change in presto-hive or presto-parquet module and this was the recent change. Apologies, if I incorrectly tagged!

**Comment by arunthirupathi** [comment]
The second failure, https://github.com/prestodb/presto/runs/4283271275?check_suite_focus=true (Though it contains failure related to my change as well, and they are legitimate, My change does not impact the presto-parquet code paths though).

Here is my PR: (This is how the ORC streams are laid out in a file and completely unrelated to the failing tests).
https://github.com/prestodb/presto/pull/17026

**Comment by beinan** [comment]
> I am not sure whether this change is even related, but there is no change in presto-hive or presto-parquet module and this was the recent change. Apologies, if I incorrectly tagged!

sounds like the test is flaky,  I didn't see this failure on my PRs these days.  I will try to investigate the root cause and get back to you later (probably it's related with the parquet version, we did the parquet upgrade from 1.11.0 to 1.11.1 and then 1.12.0 recently)

**Comment by beinan** [comment]
> > I am not sure whether this change is even related, but there is no change in presto-hive or presto-parquet module and this was the recent change. Apologies, if I incorrectly tagged!
> 
> sounds like the test is flaky, I didn't see this failure on my PRs these days. I will try to investigate the root cause and get back to you later (probably it's related with the parquet version, we did the parquet upgrade from 1.11.0 to 1.11.1 and then 1.12.0 recently)

@arunthirupathi are you still seeing the test failure?  sorry, I didn't get chance to really look into this one.

**Comment by arunthirupathi** [comment]
This test is still flaky,
https://github.com/prestodb/presto/runs/4402004972?check_suite_focus=true (Run as of Dec. 2)

**Pull request merged**
