### PR TITLE
Create table for TestPrestoSparkNativeSimpleQueries

### PR DESCRIPTION
**Pull request by singcha**
Fix missing tables while running native tests

Test plan - 
Ran existing failing tests due to missing tables and they succeed now.

### CODE REVIEW

**Comment by miaoever** [comment]
LGTM, thanks @singcha for fixing this issue. BTW, there is a maven checks failures in the CI , could you fix it? Thanks.

**Review by miaoever — APPROVED** [review]

**Comment by singcha** [comment]
> LGTM, thanks @singcha for fixing this issue. BTW, there is a maven checks failures in the CI , could you fix it? Thanks.

Thanks for review. I have pushed the fix for check style.

**Review by gggrace14 — APPROVED** [review]
Thanks for making the change! Approving. If it's not taking much time, it'd be better to add creation of more tables, so that ppl without this context are more flexible to use the tables when adding more unit tests afterwards.

**Comment by singcha** [comment]
> Thanks for making the change! Approving. If it's not taking much time, it'd be better to add creation of more tables, so that ppl without this context are more flexible to use the tables when adding more unit tests afterwards.

Thats a good point. let me add it back!

**Comment by tanjialiang** [comment]
Thanks for the change. Why do we need this many tables in TestPrestoSparkNativeSimpleQueries? I can see from the tests that only orders and lineitem are needed.

**Comment by singcha** [comment]
> Thanks for the change. Why do we need this many tables in TestPrestoSparkNativeSimpleQueries? I can see from the tests that only orders and lineitem are needed.

Yes, we need just two. I added back more tables based on Ge's comment. Here is reasoning behind it:

"Approving. If it's not taking much time, it'd be better to add creation of more tables, so that ppl without this context are more flexible to use the tables when adding more unit tests afterwards."

**Comment by singcha** [comment]
> > Thanks for the change. Why do we need this many tables in TestPrestoSparkNativeSimpleQueries? I can see from the tests that only orders and lineitem are needed.
> 
> Yes, we need just two. I added back more tables based on Ge's comment. Here is reasoning behind it:
> 
> "Approving. If it's not taking much time, it'd be better to add creation of more tables, so that ppl without this context are more flexible to use the tables when adding more unit tests afterwards."

@tanjialiang

**Comment by tanjialiang** [comment]
> > > Thanks for the change. Why do we need this many tables in TestPrestoSparkNativeSimpleQueries? I can see from the tests that only orders and lineitem are needed.
> > 
> > 
> > Yes, we need just two. I added back more tables based on Ge's comment. Here is reasoning behind it:
> > "Approving. If it's not taking much time, it'd be better to add creation of more tables, so that ppl without this context are more flexible to use the tables when adding more unit tests afterwards."
> 
> @tanjialiang

This does not seem to be a proper place to create tables that are not needed in the scope. We should follow the norm of how other classes create tables. Limiting the number of tables created improves efficiency.

**Pull request merged**
