### PR TITLE
Enable count(*) partial aggregation for Alpha file format

### PR DESCRIPTION
**Pull request by sdruzkin**
## Description
Enable count(*) partial aggregation for Alpha file format.

## Motivation and Context
Let's enabled partial aggregation for the landed the Alpha aggregated page source.

## Impact
Up to 120x perf improvement for count(*) queries.

## Test Plan
* Tested manually. 
* Existing aggregation tests in TestPrismIntegrationSmokeTest#testAlphaAggregation

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [x] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by sdruzkin** [comment]
@rschlussel can you please take a look at this PR?

**Review by rschlussel — COMMENTED** [review]
Can you add a test?

**Comment by sdruzkin** [comment]
> Can you add a test?

Alpha is not available in OSS. We have unit and integ tests in the presto-facebook.

**Comment by rschlussel** [comment]
> > Can you add a test?
> 
> Alpha is not available in OSS. We have unit and integ tests in the presto-facebook.

maybe we should move this to presto-facebook then. Create a class PrismPartialAggregationPushdown that extends/calls to this one, but adds handling for alpha file format.

**Comment by sdruzkin** [comment]
> > > Can you add a test?
> > 
> > 
> > Alpha is not available in OSS. We have unit and integ tests in the presto-facebook.
> 
> maybe we should move this to presto-facebook then. Create a class PrismPartialAggregationPushdown that extends/calls to this one, but adds handling for alpha file format.

I can do it, but the current implementation of HivePartialAggregationPushdown is really closed. I'll have to break it into multiple pieces to make it extendable and reusable.

**Pull request closed without merging**
