### PR TITLE
Add userCredential property to presto-jdbc driver

### PR DESCRIPTION
**Pull request by devanshsoni9**
I created an issue for the same https://github.com/prestodb/presto/issues/11845

This is being added to support passing Kerberos impersonation
credential via driver Properties. Also, this code re-uses an already
existing Kerberos login session created by the user instead
of the driver creating a new session each time.

I got ideas from the SQLServer jdbc driver to add the property. Copy-pasted below my last comment on the issue: 

So, for example, the SQL Server driver takes in the impersonated credentials as a [driver property](https://github.com/Microsoft/mssql-jdbc/blob/d01e90af030e63aae0a14faba77b32fc6d368281/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java#L232) . The driver checks if such property was passed by the user [here](https://github.com/Microsoft/mssql-jdbc/blob/d01e90af030e63aae0a14faba77b32fc6d368281/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java#L3552) and initialize it in a separate [constructor](https://github.com/Microsoft/mssql-jdbc/blob/d01e90af030e63aae0a14faba77b32fc6d368281/src/main/java/com/microsoft/sqlserver/jdbc/KerbAuthentication.java#L347) of their KerbAuthentication class.

While authenticating they use the above saved peerCredentials to [create peerContext](https://github.com/Microsoft/mssql-jdbc/blob/d01e90af030e63aae0a14faba77b32fc6d368281/src/main/java/com/microsoft/sqlserver/jdbc/KerbAuthentication.java#L71) and  eventually to invoke [initSecContext](https://github.com/Microsoft/mssql-jdbc/blob/d01e90af030e63aae0a14faba77b32fc6d368281/src/main/java/com/microsoft/sqlserver/jdbc/KerbAuthentication.java#L166) which redirects to Java GSS API. 

I think presto can handle similarly by 
1. Allowing the user to pass impersonation creds using a special property
2. Handling the case when such a property is present by using the passed credential instead of the session credential while creating context [here](https://github.com/prestodb/presto/blob/353eceed9b9b395849d852a2828062514c394fd8/presto-client/src/main/java/com/facebook/presto/client/SpnegoHandler.java#L154)

Testing: 

I was able to connect to a presto db by logging using kerberos and ssl and  was able to impersonate a db User. 

This is how my test code looks like 
https://github.com/devanshsoni9/other/blob/master/SampleKerberosDelegationInPresto

### CODE REVIEW

**Comment by electrum** [comment]
This approach is clever, but I don't think we should put arbitrary objects into `Properties`. From the `Properties` Javadoc:

> Each key and its corresponding value in the property list is a string.
>
> Because `Properties` inherits from `Hashtable`, the `put` and `putAll` methods can be applied to a `Properties` object. Their use is strongly discouraged as they allow the caller to insert entries whose keys or values are not `String`s.

And `DriverManager`:

> info – a list of arbitrary string tag/value pairs as connection arguments

I need to do more research, but the PostgreSQL approach of using the current `AccessControlContext` seems better.

**Comment by devanshsoni9** [comment]
@electrum 
So I took a look at the [postgres driver](https://github.com/pgjdbc/pgjdbc/blob/master/pgjdbc/src/main/java/org/postgresql/gss/MakeGSS.java#L47) and tried to implement it in a similar way as below in SpnegoHandler.java

```
private byte[] generateToken(String servicePrincipal)
    {
        GSSContext context = null;
        GSSCredential clientCreds = null;
        boolean checkSession = true;
        Subject subject;
        subject = Subject.getSubject(AccessController.getContext());
        if (subject != null) {
            Set<GSSCredential> gssCreds = subject.getPrivateCredentials(GSSCredential.class);
            if (!gssCreds.isEmpty()) {
                clientCreds = gssCreds.iterator().next();
                checkSession = false;
            }
        }
        try {
            if (checkSession) {
                Session session = getSession();
                subject = session.getLoginContext().getSubject();
                clientCreds = session.getClientCredential();
            }
            context = getSecurityContext(subject, servicePrincipal, clientCreds);
            byte[] token = context.initSecContext(new byte[0], 0, 0);
            if (token == null) {
                throw new LoginException("No token generated from GSS context");
            }
            return token;
        }
        catch (GSSException | LoginException e) {
            throw new ClientException(format("Kerberos error for [%s]: %s", servicePrincipal, e.getMessage()), e);
        }
        finally {
            try {
                if (context != null) {
                    context.dispose();
                }
            }
            catch (GSSException ignored) {
            }
        }
    }

    private synchronized GSSContext getSecurityContext(Subject subject, String servicePrincipal,
            final GSSCredential clientCredential)
            throws GSSException
    {
        return doAs(subject, () -> {
            GSSContext result = GSS_MANAGER.createContext(
                    GSS_MANAGER.createName(servicePrincipal, NT_HOSTBASED_SERVICE),
                    SPNEGO_OID,
                    clientCredential,
                    INDEFINITE_LIFETIME);

            result.requestMutualAuth(true);
            result.requestConf(true);
            result.requestInteg(true);
            result.requestCredDeleg(false);
            return result;
        });
    }
```

However, the above code is not working.
Debugging it found that  `subject = Subject.getSubject(AccessController.getContext());` is returning a null Subject. Further debugging `public static Subject getSubject(final AccessControlContext acc) ` which is present in **javax.security.auth;**,  I can see that **acc** is not null. So, I don't get why there is no Subject returned.

I am calling the driver connection api in the same way as before

```            
   protected Connection createConnection(final GSSCredential impersonatedUserCredential)
            throws PrivilegedActionException {
        this.serviceSubject.getPrivateCredentials().add(impersonatedUserCredential);
        return Subject.doAs(this.serviceSubject, (PrivilegedExceptionAction<Connection>) () -> {
            Properties driverProperties = new Properties();

            driverProperties.put("user", <DB-USER-NAME>);
            driverProperties.put("SSL","true");
            driverProperties.put("SSLTrustStorePath", "prestoTrustStore");
            driverProperties.put("SSLTrustStorePassword","password");
            driverProperties.put("KerberosRemoteServiceName","presto");
            driverProperties.put("KerberosPrincipal",<MY-SERVICE-PRINCIPAL-NAME>);
            driverProperties.put("KerberosUseCanonicalHostname", "false");
            driverProperties.put("KerberosConfigPath","krb5.conf");
            driverProperties.put("KerberosKeytabPath","keyTabFile.keytab");
            driverProperties.put("userCredential",impersonatedUserCredential);

            return DriverManager.getConnection(PRESTO_CONNECTION_URI, driverProperties);
        });
    }
```

**Comment by rsaw4** [comment]
did u fix @devanshsoni9 ?

**Comment by devanshsoni9** [comment]
@rsaw4 I have not looked into it in a while.

**Pull request closed without merging**
