### PR TITLE
Add support for Glue endpoint URL

### PR DESCRIPTION
**Pull request by v-jizhang**
Cherry pick of https://github.com/trinodb/trino/pull/3239

Co-authored-by: Pawel Palucha <pawel.palucha@starburstdata.com>

```
== RELEASE NOTES ==

General Changes
* Add support for Glue endpoint URL
```

### CODE REVIEW

**Review by agrawalreetika — COMMENTED** [review]
This looks like a clean cherry-pick. 
@v-jizhang Could you please add documentation for the property?
Code and tests look good to me.

**Comment by v-jizhang** [comment]
> This looks like a clean cherry-pick.
> @v-jizhang Could you please add documentation for the property?
> Code and tests look good to me.

Sure, thank you.

**Comment by v-jizhang** [comment]
@agrawalreetika Other properties have been added by #16018.

**Comment by agrawalreetika** [comment]
@v-jizhang I think, it would be good to add documentation with the specific feature PR.

**Comment by v-jizhang** [comment]
> 
> 
> @v-jizhang I think, it would be good to add documentation with the specific feature PR.

Created PR #16058

**Review by aweisberg — APPROVED** [review]

**Pull request merged**
