### PR TITLE
Follow the SQL standard in cast from double or real to varchar

### PR DESCRIPTION
**Pull request by v-jizhang**
Cherry-pick of https://github.com/trinodb/trino/pull/10211/commits/631a95891208308f6fcdea2026aed9e1f0656d84
This change applies to double and real

Co-authored-by: kasiafi <30203062+kasiafi@users.noreply.github.com>

Test plan - Added tests

```
== RELEASE NOTES ==

General Changes
* Follow the SQL standard in cast from double or real to varchar

```

### CODE REVIEW

**Comment by zhenxiao** [comment]
@v-jizhang could you please rebase? I will take a look

**Comment by v-jizhang** [comment]
> 

@zhenxiao Done. Thanks

**Review by zhenxiao — APPROVED** [review]
looks nice @v-jizhang 
one minor thing, could you please merge the style fix commit into previous commits?

**Comment by v-jizhang** [comment]
> 

Squashed. Thanks

**Pull request merged**
