### PR TITLE
[native] Revert remaining filter pushdown from FilterNode

### PR DESCRIPTION
**Pull request by Yuhta**
If there is column renaming happening in-between, this will not work. Handling projection is too complex at worker level, we need to fix this in optimizer.

### CODE REVIEW

**Review by amitkdutta — APPROVED** [review]
@Yuhta Can this PR create correctness issues and is it already running in production environment?

**Comment by Yuhta** [comment]
@amitkdutta In theory it could cause correctness issue, but in practice it is unlikely, because the optimizer generated name always has a underscore number suffix and it is unlikely we happen to have a similar name with same underscore number suffix with same type in the same table.

**Comment by jaystarshot** [comment]
@Yuhta is this a revert of an existing PR? Just checking to determine if release notes are necessary for this PR."

**Comment by Yuhta** [comment]
@jaystarshot Yes it's partial revert of #23755

**Comment by jaystarshot** [comment]
Okay thanks! I am adding this in release notes, please let me know if its inaccurate

`* Reverted merging of FilterNode into TableScanNode done in pr `23755`.`

**Pull request merged**
