### PR TITLE
Parquet: Fix incorrect schema checking when struct type column has extra entries in new partitions

### PR DESCRIPTION
**Pull request by vkorukanti**
Currently we expect the struct type in Parquet to match exactly to the table schema.
This causes problems with data in existing partitions when new entries are added
to struct types in latest partition.

Please make sure your submission complies with our [Development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [Formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), and [Commit Message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests) guidelines.

Fill in the release notes towards the bottom of the PR description.
See [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) for details.

```
== RELEASE NOTES ==
Hive Changes
* Fix incorrect schema checking when struct type column has extra entries in new partitions
```

### CODE REVIEW

**Comment by vkorukanti** [comment]
@zhenxiao please review

**Comment by zhenxiao** [comment]
Hi @vkorukanti nice catch
I think this is related to @beinan's work:
https://github.com/prestodb/presto/pull/14204/files

Maybe we first get that PR in, then work on top of it?

**Comment by vkorukanti** [comment]
Sounds good @zhenxiao

**Comment by zhenxiao** [comment]
hi @vkorukanti 
@beinan 's PR has been merged. Could you please rebase?

**Comment by vkorukanti** [comment]
@zhenxiao the last commit added in PR #14204 fixes this issue. There is however one more issue when the types are upgraded (int32->int64). I will send a PR.

**Pull request closed without merging**
