### PR TITLE
Fix race in task results API

### PR DESCRIPTION
**Pull request by cberner**
A race in Jetty causes the results API to randomly fail with garbage
results (most frequently a 500 status code)

### CODE REVIEW

**Comment by cberner** [comment]
I'll merge this after airlift 0.129 is out (and update to the final artifact)

**Comment by cberner** [comment]
Fixes https://github.com/prestodb/presto/issues/5458

**Comment by dain** [comment]
Looks good

**Comment by electrum** [comment]
Remove it from airbase rather than overriding the version here. We don't use jetty directly in Presto, so we shouldn't set it here.

**Comment by electrum** [comment]
https://github.com/airlift/airbase/pull/88
https://github.com/airlift/airlift/pull/428

**Comment by cberner** [comment]
Depends on https://github.com/prestodb/presto/pull/5519

**Pull request closed without merging**
