### PR TITLE
Fix parquet complex type null handling and enable new reader by default

### PR DESCRIPTION
**Pull request by nezihyigitbasi**
This should fix the test failures in #6305 and also supersedes it.

/cc @zhenxiao

### CODE REVIEW

**Comment by zhenxiao** [comment]
Looks good to me

**Comment by nezihyigitbasi** [comment]
looking at test failures, seems like sth else is failing.

**Comment by dain** [comment]
@nezihyigitbasi can you fix the test failures, and assign back to me when ready for review?

**Comment by electrum** [comment]
Is this PR still relevant?

**Pull request closed without merging**
