### PR TITLE
Update docs theme to sphinx-immaterial

### LINKED ISSUE #22817: Logo is missing in 0.287 Documentation
I see this piece of code in every HTML document under https://prestodb.io/docs/current/ (https://prestodb.io/docs/0.287/):

```html
<a href="#" title="Presto 0.287 Documentation" class="md-nav__button md-logo">
  <img src="_static/" alt=" logo" width="48" height="48">
</a>
```

I looked into presto-docs/src/main/sphinx/ but couldn't figure out how this could happen.

### PR DESCRIPTION
**Pull request by ZacBlanco**
Updates our old docs theme to to sphinx-immaterial theme. Fixes the issue with the logo and makes the site feel a little newer.

image

Fixes #22817

### CODE REVIEW

**Comment by steveburnett** [comment]
Nice! Thanks for including the screenshot of the new style. I've done a local build of your branch and it looks the same as your screenshot, which is not surprising at all but nice nonetheless. 

One question: 
Is it possible for us to keep the "View page source / Edit this page / Create docs issue / Create project issue" links in the existing doc's right sidebar? 
(Screenshot of the existing [Presto Concepts](https://prestodb.io/docs/current/overview/concepts.html) for comparison with your screenshot.)
Screenshot 2024-05-31 at 4 23 21 PM

**Comment by ZacBlanco** [comment]
This should work now. I also added a light/dark mode toggle which is a feature of this new theme:

image

**Review by steveburnett — APPROVED** [review]
LGTM! (docs)

Pull updated branch, new local docs build. 

* The "View page source / Edit this page / Create docs issue / Create project issue" links in the existing doc's right sidebar are back as requested. 
* The light/dark mode toggle is present and it works - thanks for adding it in!  

I have no other concerns. This fixes the original problem of the missing Presto logo, updates us to a currently-maintained Sphinx theme, and adds a light/dark mode feature for our readers. Thanks!

**Comment by ZacBlanco** [comment]
@tdcmeehan would you like to look before I merge this?

**Review by tdcmeehan — APPROVED** [review]
Thanks @ZacBlanco !

**Comment by steveburnett** [comment]
Just noticed this today, not sure when it happened. 

Some of the right border tables of content for individual pages have the headings preceded with a purple "M" character. 

This affects most of the pages in /functions/ and in /rest/, but I didn't find this problem elsewhere in the Presto doc set. 

Example screenshots from a local docs build of https://prestodb.io/docs/current/functions/conversion.html, and https://prestodb.io/docs/current/rest/node.html.

**Comment by ZacBlanco** [comment]
@steveburnett That's part of the theme -- when using the `..function::` directive in the RST the theme inserts `M` (for "Method"). I can see about removing it if you think it's distracting

**Comment by steveburnett** [comment]
@ZacBlanco thanks - I thought they might be a feature of the theme instead of a bug, but I wanted to ask. If you can find an easy way to disable this feature, I'd appreciate it.

**Pull request merged**
