### PR TITLE
[native] Presto Protocol issues fix

### PR DESCRIPTION
**Pull request by Mionsz**
This PR fixes the Presto Protocol issues in presto native execution. It reflects the Presto Java changes.

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by mbasmanova** [comment]
@Mionsz There are test failures? Are these related? 

CC: @amitkdutta

**Comment by Mionsz** [comment]
@majetideepak This one is also rather crucial when using:

https://github.com/prestodb/presto/blob/f6b45656e2deae817a77b37a7ff1036c74574c8f/presto-native-execution/Makefile#L78

The build/test pipeline does not include presto protocol remake but it should I think. Couple of paths have changed in presto java.

**Comment by majetideepak** [comment]
@Mionsz I remember that the Presto protocol files need some manual changes. That is why this is not automated.
Is this not the case anymore? Do we know why the test native is failing?

**Comment by Mionsz** [comment]
@majetideepak  This is not mandatory as I found. There are lots more changes in the protocol but as for now I see this can be omited.

**Pull request closed without merging**
