### PR TITLE
Fix incorrect nullability reporting in Presto JDBC metadata

### PR DESCRIPTION
**Pull request by srameshkanna**
## Description
While inspecting columns to identify which ones support null values and which ones do not . presto unable to distinguish between them due to hardcoded metadata for all column.so added fix for that.

## Motivation and Context
Issue: https://github.com/prestodb/presto/issues/11510

## Impact
Incorrect Hive table column nullability reporting by the Presto JDBC driver led to inconsistent schema handling and query planning .

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Connector Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by ClarenceThreepwood — COMMENTED** [review]
Could you please add a unit test?

**Comment by agrawalreetika** [comment]
@srameshkanna  Thanks for the change.
It looks like there is already an existing test for GetColumns [here](https://github.com/prestodb/presto/blob/master/presto-product-tests/src/main/java/com/facebook/presto/tests/jdbc/JdbcTests.java#L203), where `NULLABLE` is set to 2 (that refers to `columnNullableUnknown`) currently for test data and because of change in your PR product test for this is failing. 

If you set appropriate data for this test it should help, you can refer to the existing tests [here](https://productionresultssa4.blob.core.windows.net/actions-results/73f90c2d-7633-412a-a7d4-6e76fa525b04/workflow-job-run-6e378daa-8c9a-5434-ca2d-2abde4b288b1/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-07-25T20%3A54%3A26Z&sig=8%2FeagxcDggUBvAcAlGmVuYLSnoMo2SWTFez9WYrkv5k%3D&ske=2024-07-26T07%3A49%3A45Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-07-25T19%3A49%3A45Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-05-04&sp=r&spr=https&sr=b&st=2024-07-25T20%3A44%3A21Z&sv=2024-05-04) And search for JdbcTests.shouldGetColumns test in this log.

**Review by agrawalreetika — APPROVED** [review]

**Comment by agrawalreetika** [comment]
@srameshkanna Please plan to squash your commit into one, since product test failure fix is because of the this feature change itself.

**Comment by srameshkanna** [comment]
@ClarenceThreepwood I’ve updated the unit tests for the fix that was previously failing. Could you please review?

**Review by tdcmeehan — APPROVED** [review]

**Pull request merged**
