### PR TITLE
[native] Add e2e tests for beta_cdf function

### PR DESCRIPTION
**Pull request by Ann-Rose**
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by Ann-Rose** [comment]
@aditi-pandit Can you please review?

**Review by aditi-pandit — APPROVED** [review]

**Comment by aditi-pandit** [comment]
@Ann-Rose : Please can you rebase your code and push this PR again. It seems like the build workflow is stuck and needs a git push to re-schedule it.

**Comment by Ann-Rose** [comment]
> @Ann-Rose : Please can you rebase your code and push this PR again. It seems like the build workflow is stuck and needs a git push to re-schedule it.

@aditi-pandit  Rebased the code

**Comment by aditi-pandit** [comment]
@Ann-Rose : There are some build failures and I'm not able to re-run the failed workflows. Please can you rebase and push your code so the workflows are triggered again.

**Comment by Ann-Rose** [comment]
@aditi-pandit Rebased it

**Pull request merged**
