### PR TITLE
Handle array type as any other type in ColumnInfo#getType

### PR DESCRIPTION
**Pull request by kokosing**
Handle array type as any other type in ColumnInfo#getType

### CODE REVIEW

**Comment by electrum** [comment]
The commit message refers to a private utility class inside the JDBC driver. Can you change the commit message to reflect the functional change?

**Comment by electrum** [comment]
@findepi I agree, since until I read your comment I thought this was fixing a bug

**Comment by electrum** [comment]
Merged, thanks!

**Comment by kokosing** [comment]
Thank you!

**Pull request closed without merging**
