### PR TITLE
Update the plan viewer page

### PR DESCRIPTION
**Pull request by yhwang**
## Description
Update the plan viewer page to include the following tabs:
- Overview
- Stage
- Splits

related: #21062 item 11

## Motivation and Context
After adding the plan viewer page, it would be good to also include `Overview`, `Stage Performance`, and `Splits` tabs.

## Impact
Update the plan viewer page to query viewer page which contains 4 tabs.

## Test Plan
Manually verify the page

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [x] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by yhwang** [comment]
here is a clip to show the new page:

https://github.com/prestodb/presto/assets/1147320/3682c74c-b290-4795-a775-b6e265ad1c16

**Comment by yhwang** [comment]
cc @tdcmeehan @aditi-pandit @majetideepak

**Comment by steveburnett** [comment]
This looks great! Suggest adding documentation about the new tabs to https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/clients/presto-console.rst

**Comment by tdcmeehan** [comment]
@alonsovb can your team help provide feedback?  Thank you!

**Comment by yhwang** [comment]
> This looks great! Suggest adding documentation about the new tabs to https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/clients/presto-console.rst either here or in a separate PR

@steveburnett thanks for reminding me of that. The old section is named `Plan Viewer`. I will update it to `Query Viewer` and mention the new tabs. Is that good enough for you? I guess the change would be small, I can add it into this PR.

**Comment by steveburnett** [comment]
> @steveburnett thanks for reminding me of that. The old section is named `Plan Viewer`. I will update it to `Query Viewer` and mention the new tabs. Is that good enough for you? I guess the change would be small, I can add it into this PR.

Yes, that sounds great! Do what you think reasonable. We can always iterate and add more detail later in a later docs PR if we feel the need.

**Review by steveburnett — APPROVED** [review]
LGTM! (docs)

Pull branch, local build, everything looks fine. 

Detail about the new tabs can be added later in a docs-only PR.

**Comment by aaneja** [comment]
Looks great ! Can you confirm that in 'Stage Performance' the task's are clickable (as before) and display a popup with more stats ?

**Comment by yhwang** [comment]
@aaneja yes:
image

**Review by aaneja — APPROVED** [review]

**Review by alonsovb — APPROVED** [review]
Looks pretty good!

I think there might be some improvements that could be done using React's `useMemo` instead of a function + `useEffect`, or using `useCallback` for the functions. But these are not required.

**Comment by yhwang** [comment]
@alonsovb thanks for the review and tips. I would incorporate your suggestions next time when I refactor the code base from class components to function components

**Review by tdcmeehan — APPROVED** [review]

**Pull request merged**
