### PR TITLE
Add @ScalarFunction with Block parameters

### PR DESCRIPTION
**Pull request by dain**

### CODE REVIEW

**Comment by electrum** [comment]
Is the non-block version of a function still required?

**Comment by dain** [comment]
So if we are going to reuse the same annotation for the functions, how do you want handle things like "deterministic", "alias", "hidden" and "description" attributes of ScalarFunctions.  Do all functions need to be annotated the same, and what if there are conflicts?

**Comment by kokosing** [comment]
@dain Is it not covered by https://github.com/facebook/presto/pull/4199? Is not eligible to be closed?

**Comment by dain** [comment]
This change was a hack to allow a function to take `Block` and `int position` instead of a specific value, which lets us write functions that can avoid one object creation.  For example, the `length(VARBINARY)` function we extract a `Slice` from the block and then call `Slice.length()`.  With this code we can call `Block.length(position)`.

**Comment by dain** [comment]
Will reopen if this is needed.

**Pull request closed without merging**
