### PR TITLE
[native] Advance Velox

### PR DESCRIPTION
**Pull request by tanjialiang**

### CODE REVIEW

**Comment by amitkdutta** [comment]
@pedroerp testCorrelatedExistsSubqueries failing with the nested loop join fix.

```
[ERROR]   TestPrestoNativeGeneralQueriesJSON>AbstractTestNativeGeneralQueries.testCorrelatedExistsSubqueries:1647->AbstractTestQueryFramework.assertQuery:174 For query: 
 SELECT EXISTS(SELECT 1 FROM (VALUES 1, 1, 1, 2, 2, 3, 4) i(a) WHERE i.a < o.a AND i.a < 4) FROM (VALUES 0, 3, 3, 5) o(a)
 actual column types:
 [boolean]
expected column types:
[boolean]

not equal
Expected rows (3 of 3 missing rows shown, 4 rows in total):
    [false]
    [true]
    [true]
```

**Comment by tanjialiang** [comment]
> @pedroerp testCorrelatedExistsSubqueries failing with the nested loop join fix.
> 
> ```
> [ERROR]   TestPrestoNativeGeneralQueriesJSON>AbstractTestNativeGeneralQueries.testCorrelatedExistsSubqueries:1647->AbstractTestQueryFramework.assertQuery:174 For query: 
>  SELECT EXISTS(SELECT 1 FROM (VALUES 1, 1, 1, 2, 2, 3, 4) i(a) WHERE i.a < o.a AND i.a < 4) FROM (VALUES 0, 3, 3, 5) o(a)
>  actual column types:
>  [boolean]
> expected column types:
> [boolean]
> 
> not equal
> Expected rows (3 of 3 missing rows shown, 4 rows in total):
>     [false]
>     [true]
>     [true]
> ```

Do we have a fix for this now? Someone working on it?

**Comment by tanjialiang** [comment]
> @pedroerp testCorrelatedExistsSubqueries failing with the nested loop join fix.
> 
> ```
> [ERROR]   TestPrestoNativeGeneralQueriesJSON>AbstractTestNativeGeneralQueries.testCorrelatedExistsSubqueries:1647->AbstractTestQueryFramework.assertQuery:174 For query: 
>  SELECT EXISTS(SELECT 1 FROM (VALUES 1, 1, 1, 2, 2, 3, 4) i(a) WHERE i.a < o.a AND i.a < 4) FROM (VALUES 0, 3, 3, 5) o(a)
>  actual column types:
>  [boolean]
> expected column types:
> [boolean]
> 
> not equal
> Expected rows (3 of 3 missing rows shown, 4 rows in total):
>     [false]
>     [true]
>     [true]
> ```

You mean the mentioned PR broke the build? Should we revert that PR?

**Review by xiaoxmeng — APPROVED** [review]

**Comment by pedroerp** [comment]
> @pedroerp testCorrelatedExistsSubqueries failing with the nested loop join fix.

Thank you guys for quickly reverting it. I'll take a look at it today and submit the PR again

**Pull request merged**
