### PR TITLE
Fix Live Plan UI for index joins

### PR DESCRIPTION
**Pull request by neuzrui**

### CODE REVIEW

**Comment by neuzrui** [comment]
This is the fix for the issue raised in here https://github.com/prestodb/presto/issues/12054
@mbasmanova

**Comment by findepi** [comment]
@neuzrui please check https://github.com/prestodb/presto/blob/master/README.md#building-the-web-ui 
You need to include `../dist/*js` files in your commit as well.

cc @raghavsethi

**Comment by mbasmanova** [comment]
@neuzrui Re-generating dist/*.js should fix Travis error:

https://api.travis-ci.org/v3/job/466824312/log.txt
```
ERROR: Generated dist folder did not match checked-in version
Refer to the root README.md for instructions on generating Web UI
travis_time:end:20fea478:start=1544585386933361137,finish=1544585410732090827,duration=23798729690
```

**Comment by neuzrui** [comment]
hi @mbasmanova, i will update my PR soon with generated dist files, and i will shorten my PR commit message as well. thanks!

**Comment by neuzrui** [comment]
Updated the PR with generated files and shortened commit message @mbasmanova @findepi @raghavsethi

**Comment by mbasmanova** [comment]
@neuzrui 

> The build failed on a test case in TestSqlStageExecution, but I don't think my change would affect that.

I saw this recently. Rebased on top of trunk helped. Would you try that?

**Comment by mbasmanova** [comment]
@neuzrui I restarted Travis build.

**Comment by martint** [comment]
There's a typo in the commit message. It should say "live plan", not "line plan".

**Comment by mbasmanova** [comment]
@neuzrui Ray, no re-approval is needed. Once the build turns green this PR will become ready-to-merge. At the moment the repo is frozen as we are working on a release. We'll merge once the repo re-opens.

**Comment by neuzrui** [comment]
thanks again! @mbasmanova

**Pull request merged**
