### PR TITLE
Add rule to push down table constraints

### PR DESCRIPTION
**Pull request by kokosing**
Add rule to push down table constraints

### CODE REVIEW

**Comment by rschlussel** [comment]
This PR is a prerequisite for some of the statistics work.  We get stats from tables based on table layout.  Though TableLayouts don't get chosen until AddExchanges, we want to push down table constraints separately so that we can take our best guess at the right table layout during earlier phases of planning in order to have more accurate statistics.

**Comment by kokosing** [comment]
How does it interfere or relate with `PickLayout` rule?

03.08.2017 4:48 PM "Rebecca Schlussel" <notifications@github.com>
napisał(a):

**Comment by rschlussel** [comment]
PickLayout is called after AddExchanges runs to pick an arbitrary layout in case a layout hasn't been chosen (I think that only happens if you are running on a single node).  This needs to be called before AddExchanges.  It also has more logic than PickLayout, all of which has been taken from planTableScan() in AddExchanges.  The difference between this and planTableScan() is that if there are multiple possible layouts, this chooses just the first one because it doesn't have the plan properties to choose the best one.  AddExchanges will replace the table layout anyway once we get there. Here we just need a best effort.

**Comment by kokosing** [comment]
So it looks you can remove `PickLayout` with this, am I right? What more this one is doing that `PickLayout` is not?

**Comment by rschlussel** [comment]
This only sets the table layout if there's a filter above the tablescan.  And also doesn't set it if there are no layouts with all output symbols.  Maybe that latter should be a checkstate instead.  So, I think if we could extend this to also handle tablescans without a filter on top, we could get rid of PickLayout.  It's a bit tricky how that matching would work.

**Comment by kokosing** [comment]
So why not to call `PickLayout` in place of this new rule?

**Comment by rschlussel** [comment]
If we add the filter for layoutHasAllNeededOutputs, and also removing nonDeterminsticsConjuncts to `TableLayoutRewriter`, then the rewrite functionality is the same, and we could definitely use that in this rewrite.  
The thing that I'm not sure of, is that `PickLayout` only gets run once (if a layout is already chosen, it doesn't do anything).  But if you're running this in the middle of the plan, more predicates could get pushed down, and then you'd want to run it again.  However, you still want that if you see a filter node and choose a layout based on the predicate, you don't want to replace it when you see the tablescan.

**Comment by rschlussel** [comment]
actually I think it would be totally fine to redo picking the layout for a filter and a tablescan because once the table constraints are pushed down, you'll choose the same layout.  If we can have a flag for the `picklayout` optimizer to pick layouts even if one has already been chosen, then I think we can reuse that rule here.

**Comment by cawallin** [comment]
You'd need to be careful about introducing infinite loops in adding new layouts, but that should work.

**Comment by kokosing** [comment]
@rschlussel @cawallin So what do you think about going this way? IMO it is good to not introduce another very similar rule. Moreover it seems to be easier to just modify existing one

**Comment by rschlussel** [comment]
I agree.  I can work on that.

**Comment by rschlussel** [comment]
superseded by #8735

**Pull request closed without merging**
