### PR TITLE
Migrate array_intersect() to new scalar framework

### PR DESCRIPTION
**Pull request by geraint0923**
Migrate array_intersect() to new scalar framework and do some small optimizations.

### CODE REVIEW

**Comment by geraint0923** [comment]
@erichwang @cberner

**Comment by cberner** [comment]
Can you rebase and then assign this to me?

**Comment by geraint0923** [comment]
Rebased.

**Comment by cberner** [comment]
Can you split this into two commits? One that migrates to the new framework, and one that adds the optimizations. That will make it easier to review, and also we try to make each commit reflect one logical change.

**Comment by geraint0923** [comment]
Address the comment, split into two separated commits.

**Comment by cberner** [comment]
Check why Travis failed. Otherwise looks good

**Comment by geraint0923** [comment]
Thanks! The test failure is due to a non-completed test change. I will restart the tests after that error has been fixed.

**Pull request merged**
