### PR TITLE
Add specialized addInput function to Accumulator - continuation3

### PR DESCRIPTION
**Pull request by maciejgrzybek**
Identical to https://github.com/prestodb/presto/pull/7775 code-wise, just rebased, resolved conflicts (imports only) and squashed fixups.

---

@dain: it's ready for you.

### CODE REVIEW

**Comment by maciejgrzybek** [comment]
presto-checks are here:
https://travis-ci.org/Teradata/presto-checks/builds/220149888
https://travis-ci.org/Teradata/presto-checks/builds/220149847
https://travis-ci.org/Teradata/presto-checks/builds/220149866

 #1988.11 (https://travis-ci.org/Teradata/presto-checks/jobs/220149858) is failed but this is unrelated (type mismatch (varchar(1) vs varchar(255)) for mysql tests). It has to be caused by something on master.
Will investigate what's the problem tomorrow, at work.

**Comment by maciejgrzybek** [comment]
@dain: please wait with merging till I make sure what's going on with Presto Checks.

**Comment by dain** [comment]
@maciejgrzybek This looks good.  Let me know when you want me to merge it.

**Comment by maciejgrzybek** [comment]
@dain: this is independent issue.
We had this problem already before this patch. Master is also affected.
We don't see it on Travis because we don't run Distributed MySQL ATQ.
You can merge it. In a meantime, I will fix master as a separate PR.

**Comment by maciejgrzybek** [comment]
Rebased on master to resolve a tiny conflict in imports in ATQ.

**Comment by dain** [comment]
Merged, thanks!

**Pull request closed without merging**
