### PR TITLE
Unify `FunctionInvoker.invoke` with `ExpressionInterpreter` code

### LINKED ISSUE #8329: Explain (plan printing) fails for a Hive table partitioned by timestmp or date
Explain <select * from table> gives errors for a table partitoned by timestamp. 

```
CREATE EXTERNAL TABLE TEST_TABLE(
  account_id bigint,
  account_type string,
  account_number bigint
)
PARTITIONED BY (
  business_eff_dt timestamp)
STORED AS ORC
  LOCATION
  's3://fimt-fpphistory-dev-content/TABLE_DATA/TEMP_LOAD/TEST_TABLE'
TBLPROPERTIES (
  'orc.compress'='ZLIB');
```
This is the stack i get when i run explain 
```
presto:default> explain select * from TEST_TABLE;
Query 20170622_135942_00034_dwh5v failed: index (1) must be less than size (1)
java.lang.IndexOutOfBoundsException: index (1) must be less than size (1)
        at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1177)
        at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1159)
        at com.google.common.collect.SingletonImmutableList.get(SingletonImmutableList.java:41)
        at com.facebook.presto.sql.FunctionInvoker.invoke(FunctionInvoker.java:67)
        at com.facebook.presto.sql.FunctionInvoker.invoke(FunctionInvoker.java:43)
        at com.facebook.presto.sql.planner.PlanPrinter.castToVarchar(PlanPrinter.java:1376)
        at com.facebook.presto.sql.planner.PlanPrinter.access$700(PlanPrinter.java:146)
        at com.facebook.presto.sql.planner.PlanPrinter$Visitor.lambda$formatDomain$15(PlanPrinter.java:1293)
        at com.facebook.presto.spi.predicate.SortedRangeSet$2.consume(SortedRangeSet.java:220)
        at com.facebook.presto.sql.planner.PlanPrinter$Visitor.formatDomain(PlanPrinter.java:1288)
        at com.facebook.presto.sql.planner.PlanPrinter$Visitor.printConstraint(PlanPrinter.java:1274)
        at com.facebook.presto.sql.planner.PlanPrinter$Visitor.printTableScanInfo(PlanPrinter.java:1036)
        at com.facebook.presto.sql.planner.PlanPrinter$Visitor.visitTableScan(PlanPrinter.java:909)
        at com.facebook.presto.sql.planner.PlanPrinter$Visitor.visitTableScan(PlanPrinter.java:620)
        at com.facebook.presto.sql.planner.plan.TableScanNode.accept(TableScanNode.java:135)
        at com.facebook.presto.sql.planner.PlanPrinter$Visitor.processChildren(PlanPrinter.java:1247)
        at com.facebook.presto.sql.planner.PlanPrinter$Visitor.visitExchange(PlanPrinter.java:1189)
        at com.facebook.presto.sql.planner.PlanPrinter$Visitor.visitExchange(PlanPrinter.java:620)
        at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:195)
        at com.facebook.presto.sql.planner.PlanPrinter$Visitor.processChildren(PlanPrinter.java:1247)
        at com.facebook.presto.sql.planner.PlanPrinter$Visitor.visitOutput(PlanPrinter.java:1077)
        at com.facebook.presto.sql.planner.PlanPrinter$Visitor.visitOutput(PlanPrinter.java:620)
        at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
        at com.facebook.presto.sql.planner.PlanPrinter.<init>(PlanPrinter.java:167)
        at com.facebook.presto.sql.planner.PlanPrinter.<init>(PlanPrinter.java:154)
        at com.facebook.presto.sql.planner.PlanPrinter.textLogicalPlan(PlanPrinter.java:191)
        at com.facebook.presto.sql.analyzer.QueryExplainer.getPlan(QueryExplainer.java:95)
        at com.facebook.presto.sql.rewrite.ExplainRewrite$Visitor.getQueryPlan(ExplainRewrite.java:126)
        at com.facebook.presto.sql.rewrite.ExplainRewrite$Visitor.visitExplain(ExplainRewrite.java:104)
        at com.facebook.presto.sql.rewrite.ExplainRewrite$Visitor.visitExplain(ExplainRewrite.java:60)
        at com.facebook.presto.sql.tree.Explain.accept(Explain.java:80)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at com.facebook.presto.sql.rewrite.ExplainRewrite.rewrite(ExplainRewrite.java:57)
        at com.facebook.presto.sql.rewrite.StatementRewrite.rewrite(StatementRewrite.java:51)
        at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:65)
        at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:60)
        at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:296)
        at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:282)
        at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:238)
        at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:62)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

This looks like its happening for a "timestamp" or "date" partitioned table. I tried on a table without partitioning table and another table with "string" partitioning and both worked fine without issues. Note: The tables are Hive tables, stored as ORC accessed in presto via the hive connector.

### PR DESCRIPTION
**Pull request by maciejgrzybek**
Use `ExpressionInterpreter.invoke` instead of `FunctionInvoker.invoke` which diverged from the execution code.

---

Fixes #8329.

### CODE REVIEW

**Comment by martint** [comment]
I don't think this is the right direction. FunctionInvoker was extracted a while ago to abstract how function calling conventions work for use in interpreter, analyzer, optimizer. The goal was to eventually make ExpressionInterpreter use it, instead.

**Comment by maciejgrzybek** [comment]
But in fact `FunctionInvoker` was out of sync, not handling correctly `ConnectorSession`.
Should I fix `FunctionInvoker` instead and use it in `ExpressionInterpreter` then?

We should not have this code duplicated because it leads to situations like described in #8329. We didn't catch the problem with `FunctionInvoker` because it was used only in two places: `PlanPrinter` (explain) and reporting errors in `MapSubscriptOperator`.
While at the same time, we care about `ExpressionInterpreter` because if it malfunctions, some operators may not execute correctly in queries, which is more visible than not working `explain` (because we test more thoroughly query correctness than explains).

**Comment by martint** [comment]
It's odd it wasn't handling ConnectorSession correctly. What changed? FWIW, we had this exact bug a while ago.

But I agree that we shouldn't have that code duplicated. It'd be better to get rid of the logic in ExpressionInterpreter and use FunctionInvoker there.

**Comment by maciejgrzybek** [comment]
The problem most likely was introduced with 7c92b1e6ed8438d597fae68f8d8c2a94c5c81c4e. Here, specifically: https://github.com/prestodb/presto/commit/7c92b1e6ed8438d597fae68f8d8c2a94c5c81c4e#diff-4a3157539c8a9ebe368ec1854b489110R67.
If `ConnectorSession` is present as a parameter nullFlags() are off by one.

Will fix that and make `ExpressionInterpreter` use `FunctionInvoker` too.

**Comment by maciejgrzybek** [comment]
Superseded by https://github.com/prestodb/presto/pull/8528.

**Pull request closed without merging**
