### PR TITLE
Create aria test driver

### PR DESCRIPTION
**Pull request by elonazoulay**
WIP: creating test driver per aria test driver spec
* To run a single test suite create a json resource file like presto-tests/src/test/resources/test-driver/suite_spec.json and run the following:
  mvn test -Dtest=com.facebook.presto.tests.localtestdriver.TestSuiteGroups#testSingleSuite -DtestSuiteResource=test-driver/suite_spec.json -Dforce=false
* To test all the example suite groups run:
  mvn test -Dtest=com.facebook.presto.tests.localtestdriver.TestSuiteGroups#testExampleSuiteGroup

### CODE REVIEW

**Comment by mbasmanova** [comment]
@elonazoulay Elon, how is this test driver different from presto-product-tests https://github.com/prestodb/presto/tree/master/presto-product-tests ? What's the moticavation for adding yet another test driver given that unit tests, verifier and presto-product-tests exist already?

**Comment by elonazoulay** [comment]
Just quoting from Orri's prestodriver.doc:
* It is intended to be used while developing and testing correctness changes on your laptop
* Reruns the test for every combination of session properties
ex. "aria_hash" = [ true, false ], "aria_scan" = [true, false]
will run 4 tests with all combinations of values
* Optionally saves the control data and checksums to a local directory
* Sorts lists and maps so they can be compared
* Rounds decimals to 9 places

Eventually there will be more features:
* Branch testing: will test if certain branches of code were executed (for example by incrementint a jmx counter)

**Comment by mbasmanova** [comment]
@elonazoulay Elon, creating a whole new test framework is a lot of work. Before doing that, let's look at existing test frameworks (unit tests, verifier, tempto: https://github.com/prestodb/tempto) and find out if any one of these could be extended to include the necessary features.

**Comment by elonazoulay** [comment]
I did initially and will continue look at extending tempto. I wanted to get something out quickly that satisfies the requirements Orri put together in the testdriver doc so that testing on a laptop/devbox can be unblocked for now.

**Comment by rschlussel** [comment]
@elonazoulay I agree with @mbasmanova about augmenting an existing framework instead of creating a new one

it sounds to me like the best fits would be:
1) adding features to the way we run integration tests using the AbstractTestQueryFramework (e.g. in AbstractTestQueries)
2) adding some features to Tempto

Here are my thoughts on how your requirements could work with each of those two options
1) Either can be run on your laptop. The query runner tests are lighter weight, while Tempto creates more of an end to end testing environment by setting up presto instances in small docker containers. It just depends what you need.
2) Either system can probably be extended to run a matrix of session properties.  For ATQ you may need to create a wrapper that creates different test runners for each session property combination since the session gets created when the QueryRunners are built (or look into updating the session in an existing query runner).  For Tempto I would look at adding the matrix via the yaml configuration.  Benchto already has that capability for benchmarking, so look how it's done there. 
3)  I'm sure either could be extended to save the data.
4) I'm not sure about Tempto, though I'm fairly certain that doubles are also handled there, but ATQ tests already do rounding for doubles (see MaterializedRow.java). 
5) The list sorting seems like a simple enough thing to add to either.

**Comment by findepi** [comment]
> Here are the differences, quoting from Orri's prestodriver.doc:

just curious, what's `prestodriver.doc`?

**Comment by rongrong** [comment]
I think the need that currently are not fulfilled by existing test frameworks are in the line of running "product tests" in dev cycles. AbstractTestQueryFramework is not friendly in describing expected results when the result is large. There's great value in adding functionality to easily run a set of complicated test queries over some non-trivial amount of data and verify the results from dev environment. This can be done by either enhance AbstractTestQueryFramework or make the other frameworks more accessible, or introducing another driver. As long as the end product is easy to use as "click a button" or "issue a command", and the test result is easily comprehensible, how this is achieved is less important to the user (like me).

**Comment by elonazoulay** [comment]
> > Here are the differences, quoting from Orri's prestodriver.doc:
> 
> just curious, what's `prestodriver.doc`?

Hi @findepi!
This is a document that one of our team members, Orri Erling created as a spec for a test driver that can be used with the aria project. I will follow up to get this shared.

**Comment by elonazoulay** [comment]
@findepi Here is the prestodriver.doc so you can see the requirements Orri outlined:
[prtestdriver.docx](https://github.com/prestodb/presto/files/2853585/prtestdriver.docx)

**Comment by mbasmanova** [comment]
We are going to take a different approach.

**Pull request closed without merging**
