### PR TITLE
[native] Advance velox.

### PR DESCRIPTION
**Pull request by amitkdutta**

### CODE REVIEW

**Comment by amitkdutta** [comment]
The error is

```
_deps/boost-src/libs/filesystem/include/boost/filesystem/detail/path_traits.hpp:25:10: fatal error: boost/system/error_category.hpp: No such file or directory
   25 | #include <boost/system/error_category.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Can it be related to this PR https://github.com/facebookincubator/velox/pull/9094?

CC: @kgpai @majetideepak

**Comment by majetideepak** [comment]
@amitkdutta yes, seems related to the boost upgrade. The CI run is probably conflicting with the installed system boost version.
Let me work with the release team to create a new image.

**Comment by majetideepak** [comment]
I see that boost 1_72_0 does not have the missing header. The build is likely conflicting with the system version.
https://www.boost.org/doc/libs/1_72_0/boost/system/detail/error_category.hpp

**Comment by majetideepak** [comment]
@amitkdutta can you rebase?

**Comment by czentgr** [comment]
@amitkdutta quick question, is this PR moving forward, or should we make a new one? 
There will be build issues as changes in Velox will make Prestissimo have build errors with the latest commits.  One known issue will require 
```
add_compile_definitions(VELOX_ENABLE_BACKWARD_COMPATIBILITY)
```  to be added to the Prestissimo CMakeLists.txt as `FileFormat::ALPHA` is now behind this macro.

**Comment by amitkdutta** [comment]
@czentgr This is not moving forward. Closing it.

**Pull request closed without merging**
