### PR TITLE
[native] Advance velox.

### PR DESCRIPTION
**Pull request by amitkdutta**

### CODE REVIEW

**Comment by amitkdutta** [comment]
Observing CMake version failure in CI

```
CMake Error at velox/CMakeLists.txt:14 (cmake_minimum_required):
  CMake 3.28 or higher is required.  You are running version 3.26.5
```

This is due to CMake version is updated in vleox https://github.com/facebookincubator/velox/pull/9861

I ran into same problem locally as well. Updated CLion to latest version (CLion 2024.1.1, Build #CL-241.15989.121, built on April 25, 2024) to unblock.

We need to update here as well to unblock builds on latest velox.

CC: @majetideepak @kgpai @mbasmanova

**Comment by majetideepak** [comment]
@amitkdutta We have to build a new CI Image. The Presto release team should be able to help with this.
CC: @tdcmeehan, @wanglinsong

**Comment by wanglinsong** [comment]
> @amitkdutta We have to build a new CI Image. The Presto release team should be able to help with this. CC: @tdcmeehan, @wanglinsong

@majetideepak are you talking about the base build image?

**Comment by majetideepak** [comment]
@wanglinsong this would be the centos dependency image. We need to build it after advancing Velox. I built it this time here
https://github.com/prestodb/presto/pull/22839

**Comment by wanglinsong** [comment]
We need to finish this first https://github.com/prestodb/presto/pull/22806, which has an option to build the centos dependency docker image.

**Pull request closed without merging**
