### PR TITLE
Revert cast formatting regression

### PR DESCRIPTION
**Pull request by asjadsyed**
Context: https://github.com/prestodb/presto/issues/17522

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by varungajjala** [comment]
cc @v-jizhang

**Comment by highker** [comment]
Can we open a ticket and move the context to a ticket?

**Comment by varungajjala** [comment]
Release note is not required for this.

**Review by highker — APPROVED** [review]

**Comment by highker** [comment]
Ticket #17522

**Pull request merged**
