### PR TITLE
Add Connector Session info to SQL String

### PR DESCRIPTION
**Pull request by Naveen007**
Depended by https://github.com/facebookexternal/presto-facebook/pull/1065
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by jainxrohit** [comment]
Why did we close the previous PR?

**Comment by Naveen007** [comment]
> Why did we close the previous PR?

My Environment got messed up and when I did forced sync up with fork it automatically closed the old PR

**Comment by jainxrohit** [comment]
Do you want to add a test to verify is user info and query ID is appended?

**Comment by jainxrohit** [comment]
> ```
> == RELEASE NOTES ==
> 
> General Changes
> Adding Connector Session based info to the SQL query String as comment
> 
> Hive Changes
> * ...
> * ...
> ```
> 
> ```
> == NO RELEASE NOTE ==
> This is to show extra info in the SQL string sent to XDB as a comment for better troubleshooting. There is no immediate release needed
> ```

You have to specify dependent facebook PR here as
depended by {facebook PR link}
An example: https://github.com/prestodb/presto/pull/14499

Also Just leave notes as 
== NO RELEASE NOTE ==

Please also fix the commit message as "Add connector session info to SQL String"

**Comment by jainxrohit** [comment]
> This is to show extra info in the SQL string sent to XDB as a comment for better troubleshooting. There is no immediate release needed

Can you move description on the top, currently its after no release notes.

**Comment by Naveen007** [comment]
> > This is to show extra info in the SQL string sent to XDB as a comment for better troubleshooting. There is no immediate release needed
> 
> Can you move description on the top, currently its after no release notes.

Done

**Comment by jainxrohit** [comment]
No need to mention "There is no immediate release needed" in the PR description.

**Comment by Naveen007** [comment]
> No need to mention "There is no immediate release needed" in the PR description.

Done

**Comment by jainxrohit** [comment]
Also the change is not XDB specific, its done in the JDBC layer, can you fix the PR description?

**Comment by Naveen007** [comment]
> Also the change is not XDB specific, its done in the JDBC layer, can you fix the PR description?

Done

**Pull request merged**
