### PR TITLE
 Remove Optional from tagged memory allocation support API

### PR DESCRIPTION
**Pull request by nezihyigitbasi**
Follow up for https://github.com/prestodb/presto/pull/11011 cleaning the API.

### CODE REVIEW

**Comment by haozhun** [comment]
Why not force-free with a special tag: "force free"? I understand that tags are allowed to be negative. So this should be no problem.

**Comment by haozhun** [comment]
For `Remove Optional from tagged memory allocation support API`, I was mislead by the commit message. I thought this is just turning Optional into nullable. However, it turns out to be completely different after reading the code. It is making the String mandatory. In this case, at the bottom level (in updateTaggedMemoryAllocations maybe), there should be a `requireNonNull`.

**Comment by dain** [comment]
@haozhun In general, I want all allocations and frees to be tagged an aligned (so no negative totals), but there are cases when we are cleaning up or killing stuff that we don't know the tags.  I like this change because it make it clear that there is a normal API for allocating and freeing, and then a special "force" it API for those special cases.

**Comment by haozhun** [comment]
I can see three approaches:

1. No force kill. Just have the caller do use a special tag
2. Force kill is a sugar at the very top level. For all but the immediate user-facing API, the concept of "force kill" doesn't exist.
3. Force kill is propagated all the way through. At the bottom level, forceKill delegates to `updateTaggedMemoryAllocations` using a special tag.
4. Force kill is out side the tracking mechanism.

* I'm against 4 because I imagine force-kill is a valuable tag to track.
* I'm also against 3 because it introduces too much extra complexity to the API.
* I prefer 1. But I can live with 2.

This is my opinion. Then again, I may not be well informed. Therefore, I'm happy to discuss if you disagree.

**Comment by nezihyigitbasi** [comment]
I will discuss with @haozhun offline (and update this thread once we decide on a solution).

> I understand that tags are allowed to be negative
You mean, the value of a tagged allocation can be negative? Yes, it can.

> 1. No force kill. Just have the caller do use a special tag

With tags we track operators, buffers, etc. that own allocations, but force free doesn't fit to that model. Also, these tags are exposed through REST interfaces, and in order not to expose them we need special handling logic. So, I am not really in favor of adding a special tag for force free operation. 

> 2. Force kill is a sugar at the very top level. For all but the immediate user-facing API, the concept of "force kill" doesn't exist.

(I want to understand this one better, so will take it offline.)

I take the memory context classes as user facing API, and those interfaces don't have the force free method. Force free isn't supposed to be user visible, it's an implementation detail in the presto-memory-context module (I had to make it public in the MemoryReservationHandler interface as it's an interface, but in theory it can be package private). This method is called from `AbstractAggregatedMemoryContext::close()` method only. It's also private in `QueryContext` implementations.

I will update the commit message.

**Comment by nezihyigitbasi** [comment]
The final decision is to introduce a force free tag, will update the PR shortly.

**Comment by nezihyigitbasi** [comment]
Updated. This PR depends on https://github.com/prestodb/presto/pull/11182 to simplify the refactoring, I will rebase once the other one is merged.

**Comment by nezihyigitbasi** [comment]
@haozhun Please take a look when you have a chance.

**Pull request merged**
