### PR TITLE
#6812 Fix table creation with external location

### PR DESCRIPTION
**Pull request by xbsd-nikolay**

### CODE REVIEW

**Comment by electrum** [comment]
Why is the additional table property needed? The metastore already has a `tableType` field for `Table`.

**Comment by electrum** [comment]
Looks like Hive sets both and uses them each in different places. What a mess :(

**Comment by xbsd-nikolay** [comment]
The problem in Hive Metastore here: 
https://github.com/apache/hive/blob/release-2.1.0-rc3/metastore/src/java/org/apache/hadoop/hive/metastore/ObjectStore.java#L1416
```java
    String tableType = tbl.getTableType();
    boolean isExternal = "TRUE".equals(tbl.getParameters().get("EXTERNAL"));
    if (TableType.MANAGED_TABLE.toString().equals(tableType)) {
      if (isExternal) {
        tableType = TableType.EXTERNAL_TABLE.toString();
      }
    }
    if (TableType.EXTERNAL_TABLE.toString().equals(tableType)) {
      if (!isExternal) {
        tableType = TableType.MANAGED_TABLE.toString();
      }
    }
```
Basically metastore ignores the table type, if there is no "EXTERNAL" flag in parameters.

**Comment by xbsd-nikolay** [comment]
Agree, hive just a mess!

**Comment by electrum** [comment]
Merged, thanks!

**Comment by xbsd-nikolay** [comment]
@electrum Thanks, it was fast! :)

**Pull request closed without merging**
