### PR TITLE
Fix arrows SortingProperty.toString()

### PR DESCRIPTION
**Pull request by ebd2**

### CODE REVIEW

**Comment by electrum** [comment]
Can you show the character before/after this change?

**Comment by martint** [comment]
> Can you show the character before/after this change?

It's just swapping them around. The characters are "→" and "←", btw.

**Comment by electrum** [comment]
Ah, thanks, I missed it was just swapping them.

**Comment by ebd2** [comment]
Before:

Ordering | Symbols
-----------|-----------
ASC_NULLS_FIRST|↑←
ASC_NULLS_LAST|↑←
DESC_NULLS_FIRST|↓→
DESC_NULLS_LAST|↓→

With this patch:

Ordering | Symbols
-----------|-----------
ASC_NULLS_FIRST|↑←
ASC_NULLS_LAST|↑→
DESC_NULLS_FIRST|↓←
DESC_NULLS_LAST|↓→

**Comment by electrum** [comment]
Merged, thanks!

**Pull request closed without merging**
