### PR TITLE
Adding Elasticsearch connector. Please check and suggest improvements.

### PR DESCRIPTION
**Pull request by sumanth232**
I have written a basic connector using scan and scroll on the basis of Example-http connector.
It reads the schema and the table names from the elasticsearch-metadata.json through http.

The columns of a table are dynamically listed on the fly based on the sources of the table provided in the elasticsearch-metadata.json file. The columns are obtained from the mapping of the index/type provided in the source

### CODE REVIEW

**Comment by chinaworld** [comment]
hi! sumanth232 
Could you write a brief document for elasticsearch connector? I'm now testing the connector. Thank you!

**Comment by albertocsm** [comment]
+1

**Comment by albertocsm** [comment]
having a good look at this one. haven't gone all the way yet but it looks a reasonable starting point.
the schema retrieval  and based on the "elasticsearch-metadata.json" is not clear to me @sumanth232. can u plz clarify which ES enpoint are u refering to?

**Comment by mateilucianstefan** [comment]
Hi all! 
@sumanth232 are you still developing this?
@cberner did you start work on another implementation?

**Comment by albertocsm** [comment]
i've made a few changes and fixes over @sumanth232 work and currently have a working experimental version of the plugin on https://github.com/albertocsm/presto (master)
any input would be appreciated

**Comment by cberner** [comment]
I haven't no. Unfortunately, it doesn't look like I'm going to have time to work on one in the near future

**Comment by mateilucianstefan** [comment]
Thanks guys for the quick replies.
@albertocsm looks like we've taken the same path:) I will take a look at your repo soon and let you know.

**Comment by chinaworld** [comment]
https://github.com/albertocsm/presto/tree/master/presto-elasticsearch

**Comment by cberner** [comment]
@sumanth232 looks like you're not working on this anymore. If you still are please re-open! If someone else has finished an ES connector please open a separate PR.

**Comment by rohanarora0921** [comment]
@albertocsm I was going through your version of this on : https://github.com/albertocsm/presto and was wondering:

1. If you could provide a basic example of DDL to create something in ElasticSearch using this connector through Presto.
2. If you could explain the mapping between Presto Mapping->Java API for ES (QueryBuilder).

Would really appreciate your help!

**Comment by albertocsm** [comment]
What are you trying to accomplish?
What is the current status? Are you having trouble configuring the connector?

It's probably best if you open an issue in my fork.

**Comment by linqer** [comment]
hi  albertocsm:
could you tell me what is the right "metadata-uri" of ES connector?

**Comment by albertocsm** [comment]
Hi.
Check https://github.com/albertocsm/presto/issues/30

**Pull request closed without merging**
