### PR TITLE
Support GROUP BY alias of the expression in the SELECT list.

### PR DESCRIPTION
**Pull request by javainthinking**
Seems that group by alias will fail currently.

presto:default> select count(cname), cid as id from ss_dev.course_rt group by id;
Query 20160705_122534_00018_ej4np failed: line 1:63: Column '"id"' cannot be resolved
select count(cname), cid as id from ss_dev.course_rt group by id

### CODE REVIEW

**Comment by martint** [comment]
That's the expected behavior. In ANSI SQL, that's not a valid query. The expressions in the select clause are "evaluated" after group by, window functions, etc. so their names are not in scope for those operations.

**Comment by javainthinking** [comment]
@martint  yes, we just migrate lots of application from oracle/mysql to presto (currently running to 0.144.1), found that many query failed due to this, so I changed this to fit for those legacy queries.

**Comment by electrum** [comment]
This feature is problematic. Per the SQL standard, the GROUP BY column names must be resolved based on the input relations. The additional resolution against output names would have to happen after input names. The consequence is that adding a column to a table can break existing queries. Consider the following:
```
CREATE TABLE t (a bigint);

SELECT a AS b, count(*)
FROM t
GROUP BY b;

ALTER TABLE t ADD COLUMN b bigint;
```
Re-running the query would now fail with an error: `'"a"' must be an aggregate expression or appear in GROUP BY clause`

I'm having trouble coming up with an example, but there might be other queries that change behavior and thus silently return incorrect answers.

**Comment by electrum** [comment]
Note that there's a standard, portable way to do this (without repeating a complex expression in the GROUP BY clause):
```
SELECT (a + b + c) AS x, count(*)
FROM t
GROUP BY 1;
```
I realize this doesn't help with applications that have existing queries, but might help for the future.

**Comment by electrum** [comment]
PostgreSQL supports this, but resolves names against the input relations first, which illustrates the problem I described above:
```
dphillips=# CREATE TABLE t (a bigint);
CREATE TABLE
dphillips=# SELECT a AS b, count(*) FROM t GROUP BY b;
 b | count 
---+-------
(0 rows)

dphillips=# ALTER TABLE t ADD COLUMN b bigint;
ALTER TABLE
dphillips=# SELECT a AS b, count(*) FROM t GROUP BY b;
ERROR:  column "t.a" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT a AS b, count(*) FROM t GROUP BY b;
               ^

**Comment by martint** [comment]
Actually, `GROUP BY` with column ordinals is not in the spec.

**Comment by javainthinking** [comment]
Yeah, new column definition b with the same name of the alias will surely lead to the SQL failure, which is expected. This could be categorized to the kinds of "syntactic sugar", which oracle/postgre/mysql implemented in the past decades.
Even, alias within HAVING clause are used widely in many legacy SQL, such as
SELECT count(id) as cnt, col1
FROM table1
WHERE col2 = 2
GROUP BY col1
HAVING cnt > 2;
which is not supported currently,
we should change the SQL to:
SELECT count(id) as cnt, col1
FROM table1
WHERE col2 = 2
GROUP BY col1
HAVING count(id) > 2;

**Pull request closed without merging**
