### PR TITLE
Support nested namespaces in Iceberg's REST Catalog

### PR DESCRIPTION
**Pull request by denodo-research-labs**
## Description
Support nested namespaces in Iceberg's REST Catalog. The configuration property `iceberg.rest.nested.namespace.enabled` enables this feature (default: `true`).

## Motivation and Context
- Allow Presto to read Snowflake-managed Iceberg tables through external Polaris catalogs when Snowflake identifiers are in lowercase. Snowflake-managed tables are always available in Polaris under nested namespaces.
- Allow Presto to read Iceberg tables from Unity catalog. Previously an error was thrown:
 `Invalid two-part namespace unity`.

## Impact
Namespaces in Polaris can be nested up to 16 levels. If a large number of recursive namespaces result in lower performance, querying nested namespaces can be disabled: `iceberg.rest.nested.namespace.enabled=false`

## Test Plan
- Added `TestIcebergSmokeRestNestedNamespace` that uses the nested namespace: `"ns1.ns2"` for all operations.
- We would like to add tests against Polaris catalog, but we couldn't find any hosted container image. This feature request in the Polaris project is still open: https://github.com/apache/polaris/issues/152
- Same scenario for the Unity catalog

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

Iceberg Connector Changes
* Add configuration property ``iceberg.rest.nested.namespace.enabled`` to support nested namespaces in Iceberg's REST Catalog. Defaults to ``true``. :pr:`24083`

### CODE REVIEW

**Review by steveburnett — APPROVED** [review]
LGTM! (docs)

Pull branch, local doc build, looks good. Thanks for the doc!

**Comment by steveburnett** [comment]
Suggest revising the release note entry to follow the Order of changes in the Release Notes Guidelines, and formatting. 

```
== RELEASE NOTES ==

Iceberg Connector Changes
* Add configuration property ``iceberg.rest.nested.namespace.enabled`` to support nested namespaces in Iceberg's REST Catalog. Defaults to ``true``. :pr:`24083`
```

**Review by kiersten-stokes — COMMENTED** [review]
Thanks for this - I know it's a desired feature! I have one NIT below. My only other doubt is the subclassing of the ~100 tests in `TestIcebergSmokeRest` as opposed to having a select few tests. I tend to stand on the "more tests the better" side of things but just thinking out loud 🙂

**Comment by denodo-research-labs** [comment]
@kiersten-stokes, we wanted to make sure all features work with nested namespaces, but let us know if you have a better suggestion!

**Review by kiersten-stokes — APPROVED** [review]
LGTM! Agreed about the tests :)

**Comment by tdcmeehan** [comment]
@denodo-research-labs can you create issues for creating native tests against Polaris and Unity catalogs, and note the dependent issues that block this?  I agree we need such tests and it would be great to not lose track of that.

**Review by tdcmeehan — APPROVED** [review]

**Pull request merged**
