### PR TITLE
Upgrade AWS SDK version to 1.12.261

### PR DESCRIPTION
**Pull request by guanlisheng**
Test plan - (Please fill in how you tested your changes)
* UT

```
== RELEASE NOTES ==

General Changes
* Upgrade AWS SDK version to 1.12.261
```

### CODE REVIEW

**Comment by guanlisheng** [comment]
hi @ajaygeorge, would you mind taking a look at the PR? The updated SDK has the capability to tell more fine glacier objects

**Review by ajaygeorge — APPROVED** [review]
LGTM.
Can you please clean up the commit message to something like
`Upgrade AWS SDK version to 1.12.261`

**Comment by guanlisheng** [comment]
thanks @ajaygeorge, I just updated all related messages.

**Comment by ajaygeorge** [comment]
@guanlisheng Can you please push the amended commit as well. I can only see the PR heading change. The commit message is still the old one.

**Comment by ajaygeorge** [comment]
@guanlisheng There is an unrelated test failure for which the fix I believe is in master now.
Can you please rebase with latest master so that all the tests are passing now.

**Comment by ajaygeorge** [comment]
@guanlisheng can you please squash the three commits as well.

**Comment by ajaygeorge** [comment]
@guanlisheng Also please sign the EasyCLA as well.

**Comment by guanlisheng** [comment]
going to close this one, and just sent another PR https://github.com/prestodb/presto/pull/19486

**Pull request closed without merging**
