### PR TITLE
Use @SqlNullable for functions instead of @Nullable

### PR DESCRIPTION
**Pull request by electrum**

### CODE REVIEW

**Comment by dain** [comment]
Looks good

**Comment by RobinUS2** [comment]
I was thinking about this one, I totally agree with the refactor, however it seems that plugins need a rewrite a lot these days. Are there any plans to stabilize the plugin API and abstract out the internal refactors?

**Comment by dain** [comment]
This is part of what @electrum is working on.  We are creating a clean separation between what the Plugins can see from Presto, so when we make changes to the internals they don't effect Plugins as much.

**Comment by electrum** [comment]
The last release had a number of changes to the SPI. It cleaned up `Plugin` by taking advantage of Java 8 default interface methods and replaced injection with explicit method parameters, which made the API easier to use and understand. It also moved functions into the SPI as a first-class supported interface.

This work allowed hardening the plugin class loader. Unfortunately, `@Nullable` is not part of the JDK and there isn't a canonical Maven artifact for it (that doesn't contain a bunch of other junk), or even a finished specification. So the cleanest solution was to replace it with a custom annotation, with the downside of being a backwards incompatible change.

We do think hard about what goes into the SPI and making backwards incompatible changes, but we generally favor improving Presto or the SPI over backwards compatibility.

**Pull request closed without merging**
