### PR TITLE
Fix unable to display stage performance

### PR DESCRIPTION
**Pull request by xyueji**
Fix unable to display stage performance. [issue17546](https://github.com/prestodb/presto/issues/17546)
image

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by xyueji** [comment]
Hi @prithvip, @caithagoras  and @highker , would you mind taking a look at this PR? Thanks.

**Review by NikhilCollooru — COMMENTED** [review]
I understand that  the commit "Fix unable to display stage performance" resolves the issue. 

But what is the "fix check_webui.sh" commit ? Do we need that ?

**Comment by xyueji** [comment]
The comment of the commit is inappropriate. I had deleted the "fix check_webui.sh" commit

**Comment by xyueji** [comment]
> I understand that the commit "Fix unable to display stage performance" resolves the issue.
> 
> But what is the "fix check_webui.sh" commit ? Do we need that ?


The comment of the commit is inappropriate. I had deleted the "fix check_webui.sh" commit.

**Review by NikhilCollooru — APPROVED** [review]
LGTM

**Review by highker — APPROVED** [review]

**Pull request merged**
