### PR TITLE
Add Hive schemas into InputFormat#getSplits

### PR DESCRIPTION
**Pull request by rumeshkrish**
**Changes** - Unable to use the serialization.ddl and table paramerters inside Hive custom input format. This changes bring the SerDe parameters and Table parameters into Input format as way hive query planning.

Test plan - (Please fill in how you tested your changes)

Please make sure your submission complies with our [Development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [Formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), and [Commit Message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests) guidelines. Don't forget to follow our [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution) for any code copied from other projects.

Fill in the release notes towards the bottom of the PR description.
See [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) for details.

```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by rumeshkrish** [comment]
@zhenxiao / @vkorukanti Can you please review this changes and give approval ?

**Comment by zhenxiao** [comment]
hi @rumeshkrish looks good. could you please sign the easyCLA?

**Comment by rumeshkrish** [comment]
> hi @rumeshkrish looks good. could you please sign the easyCLA?

Done.

**Comment by rumeshkrish** [comment]
@zhenxiao Can you please review this changes and merge the pr ?

**Pull request merged**
