### PR TITLE
Iceberg: Add new fields in files system table

### PR DESCRIPTION
**Pull request by v-jizhang**
Cherry-pick of https://github.com/trinodb/trino/pull/8536

Add new fields introduced in Iceberg in files table, to match:
https://github.com/apache/iceberg/blob/0.11.x/api/src/main/java/org/apache/iceberg/DataFile.java#L72-L88

Co-authored-by: Jack Ye <yzhaoqin@amazon.com>

Test plan - Added tests

```
== RELEASE NOTES ==

General Changes
* Add new fields in Iceberg files system table
```

### CODE REVIEW

**Comment by v-jizhang** [comment]
Failed test is related to #16554

**Comment by ChunxuTang** [comment]
Hi @v-jizhang, thanks for your contribution to the Iceberg connector!
Feel free to ping me for review when the tests pass.

**Comment by v-jizhang** [comment]
> Hi @v-jizhang, thanks for your contribution to the Iceberg connector! Feel free to ping me for review when the tests pass.

@ChunxuTang Review please.

**Review by ChunxuTang — APPROVED** [review]
@v-jizhang LGTM! Thanks a lot for the contribution!

**Comment by ChunxuTang** [comment]
Hi @beinan and @zhenxiao, would you like to take another look at this PR? Thanks.

**Review by beinan — APPROVED** [review]
lgtm

**Pull request merged**
