### PR TITLE
Issue #6581 : Categorize IOException as HIVE_BAD_DATA

### LINKED ISSUE #6581: Categorize IOException when reading Hive table
It should be categorized as HIVE_BAD_DATA

```
java.io.IOException: incorrect header check
java.lang.RuntimeException
   com.google.common.base.Throwables.propagate(Throwables.java:160)
   com.facebook.presto.hive.ColumnarBinaryHiveRecordCursor.parseLongColumn(ColumnarBinaryHiveRecordCursor.java:319)
   com.facebook.presto.hive.ColumnarBinaryHiveRecordCursor.parseColumn(ColumnarBinaryHiveRecordCursor.java:688)
   com.facebook.presto.hive.ColumnarBinaryHiveRecordCursor.isNull(ColumnarBinaryHiveRecordCursor.java:676)
   com.facebook.presto.hive.HiveRecordCursor.isNull(HiveRecordCursor.java:237)
   com_facebook_presto_$gen_CursorProcessor_58220.filter(Unknown Source)
   com_facebook_presto_$gen_CursorProcessor_58220.process(Unknown Source)
   com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:223)
   com.facebook.presto.operator.Driver.processInternal(Driver.java:378)
   com.facebook.presto.operator.Driver.processFor(Driver.java:301)
   com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
   com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:534)
   com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:670)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by striderarun**
Resolves #6581

### CODE REVIEW

**Comment by striderarun** [comment]
@martint Can you please take a look and review this when you get time?

**Comment by electrum** [comment]
We don't put the issue number in the commit message. This is a better commit message: "Categorize IOException when reading RCBinary files"

**Comment by electrum** [comment]
Merged, thanks!

**Comment by striderarun** [comment]
Thanks! I will add more appropriate commit messages in the future.

**Pull request closed without merging**
