### PR TITLE
[native] Add e2e tests for to_iee754_64 scalar function

### PR DESCRIPTION
**Pull request by pdabre12**
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by pdabre12** [comment]
@aditi-pandit  Please review this PR.

**Review by aditi-pandit — APPROVED** [review]
Thanks @pdabre12

**Review by aditi-pandit — CHANGES_REQUESTED** [review]
@pdabre12 : maven-checks are failing with a checkstyle warning. Please fix.

Error:  src/test/java/com/facebook/presto/nativeworker/AbstractTestNativeGeneralQueries.java:[817] (regexp) RegexpMultiline: Blank line before closing brace

**Comment by pdabre12** [comment]
@aditi-pandit  Fixed , please review again.

**Review by aditi-pandit — APPROVED** [review]

**Pull request merged**
