### PR TITLE
fix bigQuery bug

### PR DESCRIPTION
**Pull request by fgwang7w**
Test plan - Unit tested by running locally to validate end-to-end functionality between presto's local prestoServer to GCP bigquery.

This PR resolves following issues: #16145, #16178,  #16093

image

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by henneberger** [comment]
Should the listTable code also be adjusted? The Optional logic seems inverted. Thanks https://github.com/prestodb/presto/blob/64d08c4b3b2814a903c3afbd5162dd5c4b9146a1/presto-bigquery/src/main/java/com/facebook/presto/plugin/bigquery/BigQueryMetadata.java#L232

**Review by beinan — COMMENTED** [review]
The bug fix looks good to me,  but I'm just thinking if we could put the dependency upgrade to a separate commit, I don't think the dependency changes are related with the bug fix.

**Comment by fgwang7w** [comment]
> The bug fix looks good to me, but I'm just thinking if we could put the dependency upgrade to a separate commit, I don't think the dependency changes are related with the bug fix.
> Can we also put more details in the commit message? Looks like you're fixing a bug about the missing table in BQ?

@beinan Thank you for reviewing the code changes. I believe splitting the fix into 2 commits makes sense, since in fact this PR proposes to fix 2 problems: 
- one is to fix the missing table from querying the BQ ( #16145, #16178), 
- the other one is to fix `NoClassDefFoundError` during presto launch time (#16093).

**Review by beinan — APPROVED** [review]

**Comment by fgwang7w** [comment]
@zhenxiao Hi could you please help review on this PR? Many thanks

**Comment by fgwang7w** [comment]
@beinan could you please help merge the PR if it's approved ok? I got a few comments that BQ is not working on presto from the community. many thanks

**Pull request merged**
