### PR TITLE
Fix function resolution for varchar(x)

### PR DESCRIPTION
**Pull request by cberner**

### CODE REVIEW

**Comment by cberner** [comment]
This seems like a pretty hacky fix, but as far as I can tell it's the "correct" thing to do now that we have "type only" coercions. @losipiuk can you confirm?

**Comment by losipiuk** [comment]
It does not seem right to me.  The problem we are solving here are the missing implicit casts for type only coercions. 
The code fails because we are folding expressions in `LocalExecutionPlanner` where we are lacking `Cast`s for type only coercions.
Maybe we are basically stripping the type-only-coercions information too soon.
It should be possible to always add `Cast` in `RelationPlanner.addCoercions`; even for type-only coercions.
And the handle them in `LocalExecutionPlanner` so the unnecessary ones are not really executed (to avoid performance penalty). 

If you want to commit your patch as a stop gap fix this is fine. But we should make it high priority to get rid of that.

@arhimondr please also take a look as you did most of the coercions work.

**Comment by losipiuk** [comment]
Or maybe we can get rid of `type-only` flag altogether. And assume (as type-only cast is identity function) that JIT will do good job inlining those calls in final compiled expressions.

**Comment by fiedukow** [comment]
I don't think type only coersion is responsible for that. I've changed TypeRegistry.isTypeOnlyCoercion implementation to simple `return false` and it does not help. I'm investigating that further.

**Comment by fiedukow** [comment]
One thing that suprised my, the `varchar(1)` is taken from `WHERE z='c'` clause. I'm not SQL master but it does not seem to be related.

eg. This query will try to look for `concat(varchar, varchar(9)):varchar` instead:
```
 +        // Complex coercions across joins
 +        assertQuery("SELECT * FROM (" +
 +                "  SELECT t2.x || t2.z cc FROM (" +
 +                "    SELECT *" +
 +                "    FROM (VALUES (CAST('a' as VARCHAR), CAST('c' as VARCHAR))) t(x, z)" +
 +                "  ) t2" +
 +                "  JOIN (" +
 +                "    SELECT *" +
 +                "    FROM (VALUES (CAST('a' as VARCHAR), CAST('c' as VARCHAR))) u(x, z)" +
 +                "    WHERE z='foobarbaz'" +
 +                "  ) u2" +
 +                "  ON t2.z = u2.z" +
 +                ") tt " +
 +                "WHERE cc = 'ac'",
 +                "SELECT 'ac'");
```

**Comment by fiedukow** [comment]
I think this problem is caused by 8c43eb4e

**Comment by cberner** [comment]
Closing as this is not the right fix

**Comment by cberner** [comment]
Re-opening as it looks like this is actually the only way to fix this (short of removing type only coercions or completely changing the way expressions are transported to workers). @losipiuk see https://github.com/prestodb/presto/pull/5638 for why type only coercions aren't necessarily present in the plan

**Comment by martint** [comment]
looks good

**Comment by fiedukow** [comment]
I still insist this solution is invalid and as we've already talked there is an underlaying problem not connected to type only coercion.
Here is an example how to reproduce this with DOUBLE and BIGINT which are not "type only" coercions. This example is of course invalid as commit but shows that the problem still exists right now:
https://github.com/Teradata/presto/commit/f6caac77b29d83f8489b7a0ec5407e2058d8626e
The (complex) test is failing with:
```com.facebook.presto.spi.PrestoException: sin(bigint):double not found```

Basically what you did is you fixed the cases that are currently in presto but did not fixed real problem. Also I don't think that there is any real reason (except of the fact that it accidentally cover all of our cases) why to do checks for
```+                boolean nonTypeOnlyCoercion = false;```
Current solution is merging parts of ```resolveScalarFunction`` into ```getScalarFunction``` which seems to be a bad idea.

There was an idea to fix optimizers which are most probably responsible for erratic behavior (PredicatePushDown + UnaliasSymbolReferences combo). What happend to this idea?

**Comment by fiedukow** [comment]
My suggestion would be at least to change the hack to something that will not suggest that "type only" coercions are the problem. Maybe we can just call resolveScalarFunction if function is not found?

**Comment by cberner** [comment]
So there are two problems with the code in 0.151:
1) EQUAL is allowed to be defined as EQUAL(T,U). This shouldn't have been allowed and it should be constrained to EQUAL(T,T). The reason for this is that two values which are equal should be interchangable, and also that if you consider what a theoretical type class "equatable" would look like, it would define a EQUAL(T,T), not EQUAL(T,U). I filed an issue for this, as there's also discuss about it in the `char(x)` PR: https://github.com/prestodb/presto/issues/5800
2) Type only coercions mixed with (1) cause function signatures which do not exist to be requested, as casts were not inserted. This is the part my PR fixes.

**Pull request merged**
