### PR TITLE
Upgrade airlift to 0.193 and discovery-server to 1.32

### PR DESCRIPTION
**Pull request by Zeoh**

### CODE REVIEW

**Comment by mayankgarg1990** [comment]
Don't we need to have the refactor as a part of this PR so that we don't have duplicate classes and also so that the authentication framework plugs in properly?

**Comment by arhimondr** [comment]
@mayankgarg1990 We need to update the Airlift version to unblock @sujay-jain . But it feels like the https://github.com/prestodb/presto/pull/14851 is ready to get merged. So It might make sense to simply update the airlift version in there and get it merged. @Zeoh what do you think?

**Comment by mayankgarg1990** [comment]
@arhimondr - I don't think just updating the version is a good idea given the changes that should be brought in. In addition to that given that the next release cut is slated for next week, any specific reason for rushing this ? Also, as you said, @Zeoh 's PR to take care of the changes in the authenticator is already there - so lets get that merged by tomorrow morning at the latest (I want to ensure a clean build and hence tomorrow morning)

**Comment by Zeoh** [comment]
It would be great if I can fully tested the new version airlift with presto before merge this PR.

**Pull request merged**
