### PR TITLE
[native pos] Fix presto protocol generation by correcting java file path

### PR DESCRIPTION
**Pull request by singcha**
Fix presto protocol generation by updating java file path to reflect current package structure
Add newly introduced partial field in sample json to fix failing test after protocol update
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by mbasmanova — APPROVED** [review]
Thanks.

**Review by vermapratyush — APPROVED** [review]
Thanks for the fix @singcha

**Comment by singcha** [comment]
Thanks @vermapratyush @mbasmanova !
I see that protocol generation is generating struct out of order too. checking on possible fix

**Comment by singcha** [comment]
> Thanks @vermapratyush @mbasmanova ! I see that protocol generation is generating struct out of order too. checking on possible fix

Regenerating worked!

**Pull request merged**
