### PR TITLE
Allow for different implementations of StatementClient

### PR DESCRIPTION
**Pull request by AlekseiS**

### CODE REVIEW

**Comment by martint** [comment]
Why do we need multiple implementations?

**Comment by AlekseiS** [comment]
For v2 version of client protocol.

**Comment by martint** [comment]
Yes, but why? The server will probably have to continue to support the old version for a while, but we don't need the client to do the same.

**Comment by electrum** [comment]
We generally avoid making the client incompatible with old servers as that makes it hard to upgrade — you can’t update the client until every server everywhere is guaranteed to be on the new version.

And that can leave you in a position where you can’t update the client for a long time because you have a few old servers.

**Comment by martint** [comment]
I don't think that's been an explicit goal so far. We control all deployments, so we can choose when we upgrade. 

In fact, just one or two versions ago we broke this kind of compatibility with the change to how USE works.

You can always run an older version of the client to talk to an old server. With this change, what would be the mechanism for someone to choose a compatible implementation?

**Comment by AlekseiS** [comment]
I'd like to discuss it offline with you and also describe and finalize the new protocol.
I think supporting both clients at least for some time provides more flexibility and allows for smooth migration. Also, it allows for iterative process of making a new client better by having a new implementation checked in and tested even though it's not yet used in prod.

**Comment by AlekseiS** [comment]
Rebased

**Comment by AlekseiS** [comment]
Rebased and added 2 more commits.

**Comment by AlekseiS** [comment]
Added as part of big PR for Protocol v2 https://github.com/prestodb/presto/pull/9607

**Pull request closed without merging**
