### PR TITLE
Issue:11202 Optimise StageStateMachine for memory

### PR DESCRIPTION
**Pull request by rajeshbalamohan**

### CODE REVIEW

**Comment by rajeshbalamohan** [comment]
I have completed my CLA.

**Comment by electrum** [comment]
Can you explain more about the problem being solved here? `ImmutableList.copyOf()` on an `ImmutableList` is free -- it returns the same instance.

**Comment by rajeshbalamohan** [comment]
Intention is to reduce the memory usage in presto. Here is the snippet of the heap in presto. And based on monitoring data allocation rates were higher from query processing threads like "Query-20180807_232303_56018_8er2s-1168" and it was adding lots of operator stats in "StageStateMachine::getStageInfo".  


```
  #      Instances          Bytes  Type
   1:      19350539    16325490736  [B
   2:     140328012    15351276600  [C
   3:      11691595    12432730640  [I
   4:     133565843     4274106976  java.lang.String
   5:     118329048     3786529536  io.airlift.units.Duration
   6:      74660023     2389120736  io.airlift.units.DataSize
   7:      32566511     2097832896  [Ljava.lang.Object;
   8:      25417278     2033382240  [Ljava.util.concurrent.TimeUnit;
   9:       7104684     1705124160  com.facebook.presto.operator.OperatorStats
  10:       8013165     1238660840  [Ljava.util.HashMap$Node;
  11:      15350908     1105265376  [Lio.airlift.units.DataSize$Unit;
  12:      16739831     1071349184  java.util.HashMap
  13:       5670055      816487920  java.net.URI
  14:      12264134      784904576  java.util.LinkedHashMap$Entry
```

I would double check on whether the ImmutableList copies over all data or is it just making a reference to the array. I should have posted this patch as 0.1 version and not the final version.

**Comment by nezihyigitbasi** [comment]
The reason there are lots of TimeUnit, DataSize, etc. and lots of Object[] on heap is probably this issue that I have recently fixed: https://github.com/airlift/units/pull/5

The next release (0.208) that will go out shortly will include that fix (with the 399ff7e commit).

**Pull request closed without merging**
