### PR TITLE
Update Kafka Connector

### PR DESCRIPTION
**Pull request by dcfocus**
This PR improves Kafka connector implementation and performance.

1. Replaced `SimpleConsumer` with `KafkaConsumer` for Kafka connector.
2. Push collecting offsets for each partition from coordinator to workers to resolve the bottleneck.
3. Use a separate consumer for each thread as `KafkaConsumer` is not thread safe, and remove `consumerCache`.
4. Added parser for `ROWTYPE` string in format `ROW<VARCHAR>('a')` extracted from table description file (some_topic.json).
5. Use `_timestamp` to limit segment offsets for each partition.
6. Besides static mode, add Zookeeper to discover Kafka brokers and decouple it from static broker implementation.

### CODE REVIEW

**Comment by asantoz** [comment]
First of all, congrats! Great improvement 🎉 
We currently don't support SSL connections on Kafka Connector, can you add here? 🙏 
https://github.com/prestodb/presto/issues/13665

**Comment by dcfocus** [comment]
> First of all, congrats! Great improvement 🎉
> We currently don't support SSL connections on Kafka Connector, can you add here? 🙏
> #13665

Thanks @asantoz 
Good point, we will definitely look into integration of SSL.

**Comment by rongrong** [comment]
Thanks for contributing @dcfocus! A few generic comment:
* Each commit should be logically independent, which means, if you are fixing some errors from earlier commit, you should squash the change into that commit.
* Try to break the change into smaller commits if possible. A 1200+ commit is very hard to review. Maybe it makes sense to try to break it by the bullet points you listed out.

**Comment by dcfocus** [comment]
> Thanks for contributing @dcfocus! A few generic comment:
> 
> * Each commit should be logically independent, which means, if you are fixing some errors from earlier commit, you should squash the change into that commit.
> * Try to break the change into smaller commits if possible. A 1200+ commit is very hard to review. Maybe it makes sense to try to break it by the bullet points you listed out.

Thanks @rongrong 
Will do and resubmit

**Comment by dcfocus** [comment]
Will send another PR with refactoring.

**Pull request closed without merging**
