### PR TITLE
Quarantine TestHiveTableStatistics.testStatisticsForPartitionedTable

### PR DESCRIPTION
**Pull request by ArturGajowy**
as it hangs the build.

A fix will be provided in a separate PR.

### CODE REVIEW

**Comment by losipiuk** [comment]
It seems to be travis issue (new images). We are testing with older images. And depending on build tests hang on different tests.

**Comment by electrum** [comment]
Reverting to the older image seems to fix it: https://github.com/prestodb/presto/pull/8321/commits/1507d01826297f621a5fbbfe57802d264a1885d3

**Comment by electrum** [comment]
PR for revert: https://github.com/prestodb/presto/pull/8353

**Comment by cawallin** [comment]
We were running into somewhat similar issues with the SQLServer tests with the old images with the same characteristics -- the sql server docker container was just hung and completely unresponsive. It could be that the new images are more resource constrained so we run into this more frequently.

**Pull request closed without merging**
