### PR TITLE
Remove raptor.properties

### PR DESCRIPTION
**Pull request by ClarenceThreepwood**
Delete raptor.properties. It prevents startup of PrestoServer in dev environments

== NO RELEASE NOTE ==

### CODE REVIEW

**Comment by majetideepak** [comment]
@ClarenceThreepwood Should we create an `examples` folder inside the `catalog` and move this there? Keeping this helps as a reference for raptor.

**Comment by majetideepak** [comment]
We can probably move a couple of such catalogs into examples and save time during development.

**Comment by ClarenceThreepwood** [comment]
What you are suggesting is true for catalogs that are not commonly used. But in this specific case, the raptor connector was removed entirely in https://github.com/prestodb/presto/commit/61439780447a8e14a7f974dc45419a056cab2629 . I think this file was just overlooked

**Review by ajaygeorge — APPROVED** [review]
LGTM

**Review by majetideepak — APPROVED** [review]
@ClarenceThreepwood thanks for the clarification.

**Pull request merged**
