### PR TITLE
Upgrade slice to 0.38

### PR DESCRIPTION
**Pull request by jagill**
Previous version was 0.36.  There was one minor incompatibility.

```
== RELEASE NOTES ==

General Changes
* Upgrade airlift/slice to 0.38.
```

### CODE REVIEW

**Comment by wenleix** [comment]
@jagill : Any plan to use https://github.com/prestodb/slice ? ;)

**Comment by jagill** [comment]
@wenleix This is a very small PR that does not change any philosophical orientation.  prestodb/slice can be a follow-up commit, which will take advantage of the fact that this commit solves one backwards-incompatibility :)

**Comment by wenleix** [comment]
@jagill : Sounds reasonable. Just keep in mind you might have to backport some changes to prestodb/slice if we start to rely on features in newer version in airlift/slice :)

**Comment by wenleix** [comment]
Merged #14014, thanks for the contribution!

**Pull request merged**
