### PR TITLE
Fix thrift remote funciton

### PR DESCRIPTION
**Pull request by wills-feng**
## Description
This PR amis to fix the presto starting error when thrift remote function configured. Otherwise Presto compains `com.facebook.drift.transport.client.MethodInvokerFactory<java.lang.annotation.Annotation> is not explicitly bound.`

## Impact
No

## Test Plan
1. create mysql function namespace config `mysql.properties`
```
function-namespace-manager.name=mysql
database-url=jdbc:mysql://127.0.0.1:3306/presto?user=root&password=password
function-namespaces-table-name=example_function_namespaces
functions-table-name=example_sql_functions
supported-function-languages=sql, anyvalue
anyvalue.function-implementation-type=THRIFT
anyvalue.thrift-page-format=PRESTO_SERIALIZED
anyvalue.thrift.client.addresses=localhost:7779
```
2. create remote funciton
```
create function mysql.default.echo_external(x varchar) returns varchar language anyvalue external;
```
3. test
```
presto> select mysql.default.echo_external('aaabbb');
 _col0
--------
 aaabbb
```

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by steveburnett** [comment]
Nit - please update the release notes section of the PR, even if it's only to delete everything but 
 
```
== NO RELEASE NOTE ==
```
under the Release Notes heading.

**Review by tdcmeehan — APPROVED** [review]

**Comment by tdcmeehan** [comment]
@wills-feng does this fix only Java clusters, or does it apply to C++ clusters as well?

**Comment by wills-feng** [comment]
It’s only for Java cluster.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Timothy Meehan ***@***.***>
Sent: Thursday, July 11, 2024 8:41:05 AM
To: prestodb/presto ***@***.***>
Cc: Wills Feng ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [prestodb/presto] Fix thrift remote funciton (PR #23169)

@wills-feng does this fix only Java clusters, or does it apply to C++ clusters as well? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: <prestodb/presto/pull/23169/c2223276805@ github. com>


@wills-feng<https://github.com/wills-feng> does this fix only Java clusters, or does it apply to C++ clusters as well?

**Review by tdcmeehan — APPROVED** [review]

**Comment by tdcmeehan** [comment]
@wills-feng can you please rebase to address the test failure?

**Comment by wills-feng** [comment]
@tdcmeehan rebased and CI passed.

**Pull request merged**
