### PR TITLE
Optimize joins with similar subqueries

### PR DESCRIPTION
**Pull request by zhenxiao**
Follow
https://github.com/facebook/presto/issues/1732

A first step, optimize queries of the following shape:

SELECT \* 
FROM (
SELECT k, agg1, agg2
FROM t
GROUP BY k
) a
JOIN (
SELECT k, agg3, agg4
FROM t
GROUP BY k
) b
ON (a.k = b.k)

as

SELECT k, agg1, agg2, agg3, agg4
FROM T
GROUP BY k

### CODE REVIEW

**Comment by yuananf** [comment]
There are tests failures 
```
2015-09-15 07:20:55 SEVERE Query 20150915_013554_00000_2f5jx failed
java.lang.IllegalArgumentException: Unhandled target type: CreateHandle
	at com.facebook.presto.sql.planner.optimizations.BeginTableWrite$Rewriter.createWriterTarget(BeginTableWrite.java:136)
	at com.facebook.presto.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableWriter(BeginTableWrite.java:81)
	at com.facebook.presto.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableWriter(BeginTableWrite.java:62)
	at com.facebook.presto.sql.planner.plan.TableWriterNode.accept(TableWriterNode.java:116)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:100)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.lambda$defaultRewrite$113(PlanRewriter.java:74)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.defaultRewrite(PlanRewriter.java:75)
	at com.facebook.presto.sql.planner.plan.PlanRewriter.visitPlan(PlanRewriter.java:39)
	at com.facebook.presto.sql.planner.plan.PlanRewriter.visitPlan(PlanRewriter.java:23)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitExchange(PlanVisitor.java:150)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:161)
	at com.facebook.presto.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableCommit(BeginTableWrite.java:104)
	at com.facebook.presto.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableCommit(BeginTableWrite.java:62)
	at com.facebook.presto.sql.planner.plan.TableCommitNode.accept(TableCommitNode.java:80)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:100)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.lambda$defaultRewrite$113(PlanRewriter.java:74)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.defaultRewrite(PlanRewriter.java:75)
	at com.facebook.presto.sql.planner.plan.PlanRewriter.visitPlan(PlanRewriter.java:39)
	at com.facebook.presto.sql.planner.plan.PlanRewriter.visitPlan(PlanRewriter.java:23)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:50)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
	at com.facebook.presto.sql.planner.plan.PlanRewriter.rewriteWith(PlanRewriter.java:28)
	at com.facebook.presto.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:59)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:97)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:266)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:245)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:209)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$83(QueuedExecution.java:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

BTW, is the first BeginTableWrite duplicate?

**Comment by zhenxiao** [comment]
@yuananf the failure seems not related to this PR. I just rebased against the current master

**Comment by yuananf** [comment]
@zhenxiao your change add another BeginTableWrite in PlanOptimizersFactory, can it cause the problem?

**Comment by zhenxiao** [comment]
@yuananf oh, yes, my typo when rebasing the PR. Get it fixed. Thank you.

**Comment by zhenxiao** [comment]
kindly ping

**Comment by zhenxiao** [comment]
rebased @martint could you please review when you are free?

**Comment by kokosing** [comment]
@zhenxiao Do you think this PR is still relevant? If not lets close it.

BTW.
```
SELECT *
FROM (
SELECT k, agg1, agg2
FROM t
GROUP BY k
) a
JOIN (
SELECT k, agg3, agg4
FROM t
GROUP BY k
) b
ON (a.k = b.k)
```

as

```
SELECT k, agg1, agg2, agg3, agg4
FROM T
GROUP BY k
```

Above does not look as correct rewrite, it would only work when column `k` contains only distinct values.

**Comment by zhenxiao** [comment]
oh, did not rebase for a while. I would like to continue.
@kokosing I did not get it. could you please give a detail example that the rewrite is not working correctly? I thought it is a valid rewrite.

**Comment by kokosing** [comment]
Oh... I am sorry, it  looks correct, I missed the `GROUP BY k` .

**Comment by kokosing** [comment]
Finding similar subqueries is a difficult problem, please see the discussion here: https://github.com/prestodb/presto/issues/6944.

Your PR seems to handle very simple case. Do you think it is common case? Do you think your rewrite will help with TPC-DS q09?

**Comment by raghavsethi** [comment]
@kokosing @martint Could you revisit this PR and either close or apply the requested changes?

**Pull request closed without merging**
