### PR TITLE
Fix passing arguments to product tests runner

### PR DESCRIPTION
**Pull request by losipiuk**

### CODE REVIEW

**Comment by losipiuk** [comment]
Just a small fix. Please merge when you have a chance

**Comment by losipiuk** [comment]
When `$@` was wrapped in `"`, for some reason, product test runner did not get all of the parameters in case when more than a pair was passed to it.
just `-g testGroup` worked. But `-g testGroup -t testsList` did not work.

This is log for errornous run:
```
++./presto-product-tests/bin/../conf/docker/singlenode/compose.sh run -d application-runner java -Djava.util.logging.config.file=/docker/volumes/conf/tempto/logging.properties -classpath /docker/volumes/jdbc/driver.jar:/docker/volumes/presto-product-tests/presto-product-tests-executable.jar com.facebook.presto.tests.TemptoProductTestRunner --report-dir /docker/volumes/test-reports --config-local /docker/volumes/tempto/tempto-configuration-local.yaml '-g tpcds -x big_query,quarantine -t q0,q1'
```

**Comment by electrum** [comment]
This way doesn't handle parameters with spaces.

**Comment by kokosing** [comment]
See https://github.com/prestodb/presto/pull/6516

**Comment by losipiuk** [comment]
You are right @electrum. #6516 does the job in the proper way. 
Please merge that one

**Pull request closed without merging**
