### PR TITLE
don't hold metadata connection during query

### PR DESCRIPTION
**Pull request by jefimm**
The metadata connection is no longer held during the query aa the required metadata is cached in memory.
This prevents multiple queries from running out of metadata connections since it is no longer held during the query and also prevent possible connection leaks (we experienced this  but are not able to pinpoint the cause).

### CODE REVIEW

**Comment by jefimm** [comment]
How much data are we talking about? 
Is it worth the effort for streaming?

Current design holds the metadata connection during the query and if there are complex queries with multiple raptor tables referenced one can run out of connections. 
We had experienced problem where are connections were leaked - no raptror queries were running and no metadata connections were  available - this is the primary reason for this pull request.

**Comment by electrum** [comment]
With hundreds of thousands or millions of shards, it can be significant. Anytime something is unbounded based on the input data size, it usually ends up being a problem past some scale. It also puts more pressure on the JVM GC since you are forced to allocate all the objects at once and keep them alive for longer.

I'm interested in the connection leak. Were you able to track down exactly which connections were leaked? I'd like to understand how `ShardIterator` can leak, since we should always be closing it.

**Comment by jefimm** [comment]
At least from quick examination looks like DistributedExecutionPlanner::plan will leak acquired resources if one of the substages will fail 

        ImmutableList.Builder<StageExecutionPlan> dependencies = ImmutableList.builder();
        for (SubPlan childPlan : root.getChildren()) {
            dependencies.add(plan(childPlan, session));
        }

I have looked at it by putting breakpoint in constructor of ShardIterator and running TestRaptorIntegrationSmokeTest.

**Comment by electrum** [comment]
Nice find! That would affect all connectors. Will investigate.

**Comment by electrum** [comment]
Fix: https://github.com/prestodb/presto/pull/7129

**Comment by jefimm** [comment]
While your changes looks like a step in good direction I'm still missing some kind of try-catch on the original loop in DistributedExecutionPlanner, for example if the query involves some nesting and nested planning fails, but my understanding of inner workings of presto is not as good as yours.

**Comment by electrum** [comment]
You're right, I had thought that `DistributedExecutionPlanner` was safe, since it's just building a data structure and doesn't call anything else, but a call to `getSplits()` could fail, which would leak previously acquired split sources. This could require some refactoring to fix.

**Comment by electrum** [comment]
Fix: https://github.com/prestodb/presto/pull/7137

**Comment by jefimm** [comment]
Thank you, looking forward to the next GA

**Pull request closed without merging**
