### PR TITLE
[native] Advance Velox.

### PR DESCRIPTION
**Pull request by spershin**
Advance Velox.

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by pranjalssh — DISMISSED** [review]

**Comment by tdcmeehan** [comment]
Weighted split scheduling was added here: https://github.com/prestodb/presto/pull/16668

Ideally, this should have been added to our developer documentation (https://prestodb.io/docs/0.285.1/develop.html).  We should create an issue for this.

**Comment by steveburnett** [comment]
> Weighted split scheduling was added here: #16668
> 
> Ideally, this should have been added to our developer documentation (https://prestodb.io/docs/0.285.1/develop.html). We should create an issue for this.

Just saw this: I will open a docs issue about this.

**Review by mbasmanova — CHANGES_REQUESTED** [review]
@spershin Please, extract "Advance Velox" logic into a separate commit.

**Comment by spershin** [comment]
> @spershin Please, extract "Advance Velox" logic into a separate commit.

@mbasmanova 

Why is that needed?

**Review by gggrace14 — APPROVED** [review]
All green

**Review by mbasmanova — APPROVED** [review]
Thanks. No need for a separate PR though. A separate commit would be just fine.

**Pull request merged**
