### PR TITLE
Use Collections#isEmpty() instead of comparing size()

### PR DESCRIPTION
**Pull request by yeikel**
Non functional change to improve the code quality. See https://rules.sonarsource.com/java/RSPEC-1155

This is the result of running the recipe `org.openrewrite.java.cleanup.IsEmptyCallOnCollections` from the OpenRewrite project

Read more : https://docs.openrewrite.org/reference/recipes/java/cleanup/isemptycalloncollections

Created with: [Moderne](https://app.moderne.io)

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by NikhilCollooru** [comment]
Please fix the commit message and PR title according to guidelines https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests

**Comment by yeikel** [comment]
> Please fix the commit message and PR title according to guidelines https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests

I updated the PR and did my best. I am new to this commit so please let me know if you have any additional feedback. 

Thank you!

**Comment by NikhilCollooru** [comment]
nit: Please also fix the commit message to only have 72 characters per line.

**Review by NikhilCollooru — APPROVED** [review]

**Comment by yeikel** [comment]
> nit: Please also fix the commit message to only have 72 characters per line.

It should be good to go now. Thanks!

**Review by highker — APPROVED** [review]
Could you also please add a lint rule if possible?

**Pull request merged**
