### PR TITLE
Add contributing guidelines on README page

### PR DESCRIPTION
**Pull request by pratyakshsharma**
Fix https://github.com/prestodb/presto/issues/17936

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by yingsu00 — CHANGES_REQUESTED** [review]
@pratyakshsharma Thanks for submitting a fix!

Maybe I'm too tired, but I don't quite get how this commit solves the original issue. It seems the original issue was about the "community.html" page (https://github.com/prestodb/prestodb.github.io/blob/1718238c541f4c573830dc9ab19b2227a1f41a87/website/static/community.html) of the https://github.com/prestodb/prestodb.github.io repo had wrong link to the CLA page in its homepage. Instead of pointing to https://github.com/prestodb, it was pointing to https://developers.facebook.com/opensource/cla. We're supposed to fix it in the prestodb.github.io repo, not this presto repo. As I checked that repo one minute ago, it still had the wrong link to the facebook address.

Also I don't get why moving the text from README.md to CONTRIBUTING.md would help anything. 

Thirdly, there is a test failure. The next time you open a PR, would you please make sure the tests all pass before requesting any reviews?

**Comment by v-jizhang** [comment]
@prestobot kick off tests

**Comment by pratyakshsharma** [comment]
@yingsu00 From what I observed on the latest presto website, there is no mention of contributing guidelines on the [community page](https://prestodb.io/community.html) now. It looks like this section was removed in the new website, if it was existing earlier (which I am not sure about) on this page.

> As I checked that repo one minute ago, it still had the wrong link to the facebook address.

Can you please point me to the place where you see this broken link now on the latest [community.html page](https://github.com/prestodb/prestodb.github.io/blob/1718238c541f4c573830dc9ab19b2227a1f41a87/website/static/community.html). I am happy to fix it. 

Also I moved the text from README.md to CONTRIBUTING since I feel that is the right place for this information. Rather than having the contributing instructions scatterd across different pages, it is good to have them consolidated at one place.

**Review by jainxrohit — APPROVED** [review]

**Review by yingsu00 — APPROVED** [review]

**Comment by yingsu00** [comment]
@pratyakshsharma I verified the facebook link was no longer existing. Could you please make the test pass?

**Comment by pratyakshsharma** [comment]
@yingsu00 This is good to merge now!

**Pull request merged**
