### PR TITLE
Add documentation on how to invalidate hive metastore cache and list files cache

### PR DESCRIPTION
**Pull request by imjalpreet**
If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by tdcmeehan — APPROVED** [review]

**Comment by steveburnett** [comment]
LGTM

**Comment by imjalpreet** [comment]
@tdcmeehan Is it okay to merge if there is a unrelated test failure in this PR? 

I have re-run the test multiple times but it's failing every time. It looks like this product tests suite is failing for most of the recent PRs. We probably need to look into whether it's happening because of a recent change or some other intermittent reason.

**Comment by imjalpreet** [comment]
@tdcmeehan The concerned test suite is removed for now(https://github.com/prestodb/presto/issues/20388), so I have rebased my PR to have a clean run and merge this.

**Comment by tdcmeehan** [comment]
It is never OK to merge PRs with test failures.  We can disable the test and raise an issue (and tag as `flaky-test`), or investigate the test failure, but we can't proceed as if it's business as usual if tests are failing.

**Pull request merged**
