### PR TITLE
Make tests more independent

### PR DESCRIPTION
**Pull request by elharo**
Starts with one of the flaky tests for #22072 and #22090

## Description
One test method per test

## Motivation and Context
Allows tests to run and fail or pass independently of each other

## Impact
none

## Test Plan
CI

## Release Notes

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by elharo** [comment]
[ERROR]   TestPrestoNativeGeneralQueriesThrift>AbstractTestNativeGeneralQueries.testSystemTables:1413->AbstractTestQueryFramework.assertQuery:154 Execution of 'actual' query failed: SELECT * FROM    (SELECT DISTINCT regionkey FROM tmp_presto_8f9726bb783949fd83b0cbf002db99bd) t INNER JOIN    (SELECT regionkey FROM "tmp_presto_8f9726bb783949fd83b0cbf002db99bd$partitions") p ON t.regionkey = p.regionkey
[INFO]

**Comment by elharo** [comment]
This time falky failures were

2024-03-04T17:37:03.8524194Z [ERROR] com.facebook.presto.hive.TestHiveDistributedQueries.testViewAccessControlInvokerDefault  Time elapsed: 0.044 s  <<< FAILURE!
2024-03-04T17:37:03.8525273Z java.lang.RuntimeException: View already exists: 'tpch.test_view_access'

**Comment by elharo** [comment]
After multiple reruns everything finally passed, so I'm marking this ready for review.

**Review by pramodsatya — APPROVED** [review]
Thanks for the fix and for investigating the issue @elharo, LGTM!

Nit: The tests could be renamed following camel case convention to be consistent, `testFirstValueOrderkey` instead of `testFirstValue_orderkey`

**Comment by elharo** [comment]
Thanks. I've camel cased the test names.

**Review by tdcmeehan — APPROVED** [review]

**Pull request merged**
