### PR TITLE
The partition/table schema compatibility check in HiveSplitManager is not working as expected for external tables.

### PR DESCRIPTION
**Pull request by wenleix**
Method `Table.getSd().getCols()` and `Partition.getSd().getCols()` only work for managed table but not external tables. The `getCols()` methods in `org.apache.hadoop.hive.ql.Table/Partition` would work for all types of tables.

### CODE REVIEW

**Comment by wenleix** [comment]
The test error doesn't seem to relate to the change. Is there anyway to rerun the CI test?

**Comment by electrum** [comment]
I restarted the build

**Comment by haozhun** [comment]
@wenleix Can you please provide the steps to reproduce this issue? i.e. the steps in Hive to create an external table that doesn't have column metadata in the Hive metastore.

**Comment by haozhun** [comment]
I just did an experiment. Presto seems to work fine without this pull request. Did I miss something?

```
hive> CREATE EXTERNAL TABLE test_hjin_external_partitioned(
    >   a string
    > )
    > PARTITIONED BY (pk string)
    > ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001'
    > STORED AS TEXTFILE
    > LOCATION 'hdfs://localhost:8020/user/hive/warehouse/test_hjin_external_partitioned';
OK
Time taken: 0.03 seconds
hive> alter table test_hjin_external_partitioned add partition(pk='a');
OK
Time taken: 0.137 seconds
hive> alter table test_hjin_external_partitioned add partition(pk='b');
OK
Time taken: 0.167 seconds
```
```
presto:default> select * from test_hjin_external_partitioned;
  a  | pk
-----+----
 iop | b
 jkl | b
 bnm | b
 qwe | a
 asd | a
 zxc | a
(6 rows)

Query 20160603_175402_00006_77rcx, FINISHED, 1 node
http://localhost:8080/query.html?20160603_175402_00006_77rcx
Splits: 3 total, 3 done (100.00%)
CPU Time: 0.0s total,   600 rows/s, 2.34KB/s, 1% active
Per Node: 0.0 parallelism,     7 rows/s,    28B/s
Parallelism: 0.0
0:01 [6 rows, 24B] [7 rows/s, 28B/s]
```

**Comment by wenleix** [comment]
@haozhun Thank you for the experiments! This shows my issue description is not accurate. As you noted, the root cause is not because of the external table but where does the schema come from. The issue raised when the table schema is from SerDe rather than from the table StorageDescriptor. I will try to provide an example that reproduces this issue later :)

**Comment by haozhun** [comment]
@wenleix and I agreed that this is a very specific issue of their setup. Closing.

**Pull request closed without merging**
