### PR TITLE
Add release notes for 0.274

### PR DESCRIPTION
**Pull request by highker**
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by arunthirupathi — APPROVED** [review]

**Comment by rohanpednekar** [comment]
@highker Do you know why this release is not reflected yet on prestodb.io ?

**Comment by highker** [comment]
@rohanpednekar lol, no idea. Feel free to take a look.

**Comment by rohanpednekar** [comment]
@highker,

Seems the data for the new version needs to be updated in this file: https://github.com/prestodb/prestodb.github.io/blob/source/website/static/static/js/version.js 

We are on version 0.275 but https://prestodb.io/docs/current/release.html is not getting updated since the 0.273.3 release.

Not sure why this GitHub action not working anymore.

**Comment by highker** [comment]
@rohanpednekar interesting; thanks for the investigation. While we are working on figuring out the issue with our release bot, is it possible to send out a PR to this repo to fix it manually?

**Comment by rohanpednekar** [comment]
@highker i can do that.

**Comment by ericyuliu** [comment]
@rohanpednekar 
Just FYI, I am in the process to publish 0.275 release notes, will provide an update soon.

**Comment by ericyuliu** [comment]
@rohanpednekar 
0.275 doc is published to github succesfully
https://github.com/prestodb/prestodb.github.io

**Pull request merged**
