### PR TITLE
Added documentation for Presto on Spark

### PR DESCRIPTION
**Pull request by Ravion**
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by Ravion** [comment]
@arhimondr  Referred from #14824 . All updates done as per review comments by you, @wenleix and @aweisberg . Thanks a lot for all help

**Comment by Ravion** [comment]
Deleted the binary files

**Comment by wenleix** [comment]
Merged #14824. Thanks for the contirubtion!

**Comment by Ravion** [comment]
@wenleix

Thanks for help. I wanted to commit one more change, # 14826 which was
referring binary files. The binary files are removed, references were not.
Apologies, thanks.

Will definitely keep a note to make sure to avoid rebasing in future.
Thanks..

Regards,
ravion

**Comment by arhimondr** [comment]
No worries. @Ravion Please create one more PR removing the references

**Comment by Ravion** [comment]
#14826.. thanks

Regards, Ravion

**Pull request closed without merging**
