### PR TITLE
Refactor the decryption code in Parquet PageSource files

### PR DESCRIPTION
**Pull request by shangxinli**
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by shangxinli** [comment]
@zhenxiao @beinan Do you have time to have a look at this PR?

**Comment by vinothchandar** [comment]
+1 on this kind of code consolidation.

**Review by zhenxiao — APPROVED** [review]
looks good.
@shangxinli could you please add "No release notes" in the PR message?

**Comment by zhenxiao** [comment]
thank you, @shangxinli all looks good
@NikhilCollooru could you please take a review? could not merge without all reviewers' approval :)

**Comment by NikhilCollooru** [comment]
I am on leave, may be Arun can help review.

**Review by arunthirupathi — APPROVED** [review]

**Review by arunthirupathi — APPROVED** [review]

**Comment by arunthirupathi** [comment]
It is waiting for code owner review from @vinothchandar  @7c00 before I can merge this code.
Screen Shot 2022-07-19 at 10 19 45 PM

**Review by beinan — APPROVED** [review]
lgtm

**Comment by beinan** [comment]
@7c00 and @vinothchandar could you two help take a look on this pr? thanks!

**Review by 7c00 — APPROVED** [review]
LGTM

**Pull request merged**
