### PR TITLE
Unqarantine TestAllDatatypes tests

### PR DESCRIPTION
**Pull request by kokosing**
Unqarantine TestAllDatatypes tests

### CODE REVIEW

**Comment by martint** [comment]
Typo in commit message: "unqarantine"

**Comment by kokosing** [comment]
Comment addressed.

**Comment by kokosing** [comment]
I am going to rerun this a couple of times to see if it is stable. So please hold on with merging this for a while.

**Comment by kokosing** [comment]
@martint It seems to be stable. No failures spotted. So I think it is eligible to be merged.

**Pull request merged**
