### PR TITLE
Allow the REST /statement/ response to be of a configurable target size

### PR DESCRIPTION
**Pull request by michaelcullum**
Adds an option to requests made to `v1/statement/{queryId}/{?token}` to include a header to set the preferred target response size so that the default value of 1MB can be overridden by the requesting client.

Discussion point:
* Should there be a hardcoded maximum target response size?

### CODE REVIEW

**Comment by michaelcullum** [comment]
Any update on this (if it needs discussion on whether or not to implement or code changes etc.)

**Comment by electrum** [comment]
Can you explain the motivation for this change?

**Comment by michaelcullum** [comment]
This can actually reduce the overall net time of medium sized queries as sometimes the limiting factor is HTTP time to setup sending a request and retrieving a response; doing this allows users to make a choice (dependent on intelligent knowledge of the likely size of a query) and knowledge of their infrastructure to request less but larger response objects (which can be streamed). This also solves any issues that projects might have had from the removal of the old `execute` endpoint and moves the responsibility for the decision of how large the response should be to the client as opposed to an arbitrary value hard coded into Presto so that individual setups can configure their 'sweet spot'.

**Comment by michaelcullum** [comment]
@electrum Thoughts?

**Comment by dain** [comment]
This patch doesn't apply anymore, so I rewrote it in #11619.  I changed the encoding of the target data size in the protocol to match the style used for the `maxWait` parameter.  If #11619, doesn't match your needs, please comment on that PR.

**Pull request closed without merging**
