### PR TITLE
Add set_ugi method to Hive Metastore

### PR DESCRIPTION
**Pull request by Tartarus0zm**
[#9785] Add set_ugi method to Hive Metastore

### CODE REVIEW

**Comment by Tartarus0zm** [comment]
@electrum  hello, I've update my pull request, please review, thx

**Comment by Tartarus0zm** [comment]
@findepi  thank you ,  Can you quest a review for me again ?

**Comment by Tartarus0zm** [comment]
@electrum   hello, I've updated my pull request, please review, thx

**Comment by electrum** [comment]
Merged, thanks!

**Comment by Tartarus0zm** [comment]
@electrum   thank you ~

**Pull request closed without merging**
