### PR TITLE
In memory join

### PR DESCRIPTION
**Pull request by pnowojski**
Pull request addressing https://github.com/facebook/presto/issues/4567

After profiling and investigating the problematic function was `com.facebook.presto.operator.PagesHashStrategy#positionEqualsPosition`, which was taking up over 90% time of `com.facebook.presto.operator.InMemoryJoinHash#InMemoryJoinHash`. 

This pull request consists of two fixes which one speeds up `positionEqualsPosition` globally but only for queries using `optimize_hash_generation=true`. Second fix further improves `InMemoryJoinHash` for both `optimize_hash_generation=true` and `optimize_hash_generation=false`

In our cluster query:
```
select book_id, customer_id, quantity, genre from transactions join books on (book_id = id) where transaction_year >= 2014 and year_published >= 2014 and publisher not in ('Oxford University Press', 'Cambridge University Press') and price + quantity > 300;
```
has sped up around 10 seconds for distributed joins (from ~2minutes), 20 seconds for broadcast joins with `task_hash_build_concurrency=4` (also from ~2minutes) and over one minute with `task_hash_build_concurrency=1` (from over 3 minutes).

JMH results are following:

Base results (before changes):
```
Benchmark                                      (buildHashEnabled)  Mode  Cnt  Score   Error  Units
BenchmarkHashBuildOperator.benchmarkBuildHash               false  avgt   10  8.623 ± 0.168  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash                true  avgt   10  4.819 ± 0.117  ms/op
```

With optimized `JoinCompiler`:
```
Benchmark                                      (buildHashEnabled)  Mode  Cnt  Score   Error  Units
BenchmarkHashBuildOperator.benchmarkBuildHash               false  avgt   10  8.417 ± 0.125  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash                true  avgt   10  3.498 ± 0.066  ms/op
```

Final results (with changes in `InMemoryJoinHash`)
```
Benchmark                                      (buildHashEnabled)  Mode  Cnt  Score   Error  Units
BenchmarkHashBuildOperator.benchmarkBuildHash               false  avgt   10  7.182 ± 0.121  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash                true  avgt   10  3.158 ± 0.378  ms/op
```

### CODE REVIEW

**Comment by pnowojski** [comment]
CC @losipiuk @kokosing

**Comment by dain** [comment]
What is the type of 'book_id'?  I am asking because I would be surprised if there is a speed up for `BIGINT` types, since the hash is the same as the value.  I would actually expect to see a slight slowdown.  Additionally, for joins on unique values, this would also just be extra cost.

If there is a speedup for `BIGINT` types, there should be a bigger win in fixing the general slowness.

**Comment by KBP-TDC** [comment]
Yes, book_id is BIGNIT. The schema was derived from here: http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/query-impala-create-tables.html

**Comment by pnowojski** [comment]
@dain here are the results of more detailed benchmark, with single `VARCHAR`, single `BIGINT` or two `BIGINT` and `VARCHAR` as `hashColumns`. Additionally added comparison for non unique values in build table:

Before changes:
```
Benchmark                                      (buildHashEnabled)  (hashColumns)  (valuesRepetition)  Mode  Cnt    Score    Error  Units
BenchmarkHashBuildOperator.benchmarkBuildHash               false        varchar                   1  avgt    5  180.441 ±  6.239  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash               false        varchar                   5  avgt    5  137.639 ±  2.005  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash               false         bigint                   1  avgt    5  115.679 ± 13.836  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash               false         bigint                   5  avgt    5  115.966 ±  9.372  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash               false            all                   1  avgt    5  207.165 ±  2.333  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash               false            all                   5  avgt    5  218.213 ±  3.864  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash                true        varchar                   1  avgt    5  133.810 ±  6.440  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash                true        varchar                   5  avgt    5  127.020 ±  5.199  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash                true         bigint                   1  avgt    5  107.059 ±  2.086  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash                true         bigint                   5  avgt    5  113.760 ±  3.454  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash                true            all                   1  avgt    5  133.882 ±  7.277  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash                true            all                   5  avgt    5  182.045 ±  4.586  ms/op
```

After changes:
```
Benchmark                                      (buildHashEnabled)  (hashColumns)  (valuesRepetition)  Mode  Cnt    Score    Error  Units
BenchmarkHashBuildOperator.benchmarkBuildHash               false        varchar                   1  avgt    5  112.351 ±  3.736  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash               false        varchar                   5  avgt    5  144.651 ±  3.644  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash               false         bigint                   1  avgt    5   75.284 ± 23.733  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash               false         bigint                   5  avgt    5  115.308 ± 23.932  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash               false            all                   1  avgt    5  138.974 ±  3.405  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash               false            all                   5  avgt    5  222.746 ±  7.552  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash                true        varchar                   1  avgt    5   73.931 ± 46.395  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash                true        varchar                   5  avgt    5  149.307 ±  7.006  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash                true         bigint                   1  avgt    5   74.140 ± 47.255  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash                true         bigint                   5  avgt    5  116.149 ±  3.439  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash                true            all                   1  avgt    5   72.318 ± 18.933  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash                true            all                   5  avgt    5  181.415 ±  6.184  ms/op
```

Keep in mind that the most significant improvement are not the changes in `JoinCompiler` but added quick look up array in `InMemoryJoinHash`. 

So indeed for joins on single `BIGINT` column we can expect large improvements (33%). Today I have spent some time reading JIT'ed code to make sure that there is no unexpected issue with `PagesHashStrategy` and to me it looks like there is no such problem. Simply using array of integers for storing hashes indexed by position is much quicker compared to accessing values stored in some column within `PagesHashStrategy`. Accessing such value (even if it's single `BIGINT`) requires:

1. get `pageAddress from `addresses` for given `position` (including boundary check)
2. decoding `blockIndex` and `blockPosition` from `pageAddress`
3. jumping to block in list of blocks using `blockIndex` (including boundary check)
4. reading value from block using `blockPosition` (including boundary check)

And you have to do all of that twice (for `possition` and `currentKey`) for single call to `positionEqualsPosition`.

Compare that to shortcut:
```
if (positionToHashes[position] == positionToHashes[currentKey] && 
    positionEqualsPosition(currentKey, position))
```
First of all, `positionToHashes[position]` is still in the registry after computing it's value earlier, so all we have to do is:

1. load `positionToHashes[currentKey]` (including boundary check)
2. compare it with value in registry

which basically translates to 5 assembler instructions.

I'm not sure how would did you mean by fixing it more generally? One way that I had in mind (but didn't want to over engineer) is to create wrapper around PagesHashStategy that have  `positionToHashes`  array. Then this same trick that I have used to speed up `InMemoryJoinHash` would be used automatically in whole code base and this array would be re-used.

Or did you have in mind something more hardcore, like changing how the columns are stored in memory?

Generally speaking this optimization works best for columns with unique values. With non unique values there is still an improvement when `buildHashEnabled=false`.

**Comment by dain** [comment]
This is a really impressive speedup. 

I'm still curious why this is faster.  Assuming we have a low collision rate in the hash table, when we are doing a lookup for a value in the hash, the first cell checked should be the correct cell, so the hash comparison would always pass, so it is just "extra" work.  Are you testing hash misses?

As for the more "general" solution... I was thinking that maybe positionEqualsPosition or maybe even getting a Type value from a block was overly expensive.

So one possible issue is we are increasing the size of the hash by 4 bytes per entry.  This seems like a fair trade off for such a big perf gain to me, but I'll check if @martint or @cberner think it is a problem.

**Comment by pnowojski** [comment]
Define what do you mean by "low collision rate"? Currently it's around 40%-50% for joins on column with unique values. In this JMH benchmark with 1 000 000 positions, we now have 455 207 collisions with hash table of size 2 097 152. To reduce collisions, we need bigger hash table. When I rise it's size to 4 194 304, we still have 156 679 collisions for 1 000 000 entries. That's poor trade off considered increased memory footprint by 2097152 * 4 bytes. Additional `positionToHashes` array takes only 1000 000 * 4 bytes and reduce number of calls to `positionEqualsPosition` (by far the most costly effect of a collision) down to 98.

**Comment by raghavsethi** [comment]
We have also spent some time figuring out why some of our aggregation queries spend so long in positionEqualsPosition, and our (actually @cberner's) best guess so far is that we end up having less than 32 bits of entropy in our hash. This is because we also distribute based on the hashes, and so we end up losing a couple of bits of entropy on every worker. This can have serious consequences in terms of clumping - we might end up spend up way more time probing than you would expect statistically. We believe that moving to 64 bit hashes could mitigate the entropy loss and improve performance. If that does turn out to be the case, then the memory tradeoff in this approach might not be worth it.

**Comment by pnowojski** [comment]
@raghavsethi I understand your potential issue, but that's not the case here. First of all, we started looking into this "slowness" for broadcast joins with `task_hash_build_concurrency=1`, where all hash entropy is used only for `InMemoryJoinHash`.

Secondly, this JMH benchmark  guarantees perfect hash scenario.

Lastly, with current size of `key` table in `InMemoryJoinHash` statistically/mathematically in best case scenario we can expect 30% of hash collisions and up to 150% for worst case scenario (with ideal hash). 

So whatever you will do to improve randomness of values distribution, we should still be prepared for hash collisions.

Maybe it is other way around? Maybe you suffer from the same issue as here and just `positionEqualsPosition` is too slow? Later this week I'm planning to look around the code base and check whether and how same optimization/fix as here can be used in other places (like aggregation/window functions).

**Comment by pnowojski** [comment]
I have small update @dain. 

First of all, I have dropped the change in the `JoinCompiler`, it didn't make sense with extensive use of `pagesToHashes` array. 

Secondly I have found out that constructing `positionToHashes` is much faster when it's done is separate loop. I'm not sure why, but it is (benchmarks below). I was looking into JIT'ed code, but hasn't found any clue, code looks basically similar in both versions, so it might have something to do with memory access. Or maybe when there are two loops instead of one, each one of them can use the CPU registers more effectively (with less offloading to memory?). 

As a reminder JMH results of hash build performance with `InMemoryJoinHash's` construction in one loop, but already with `positionToHashes` optimization. (the following table is copied paste from one of my previous posts): 

```
Benchmark                                      (buildHashEnabled)  (hashColumns)  (valuesRepetition)  Mode  Cnt    Score    Error  Units
BenchmarkHashBuildOperator.benchmarkBuildHash               false        varchar                   1  avgt    5  112.400 ± 17.160  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash               false        varchar                   5  avgt    5  145.207 ±  5.241  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash               false         bigint                   1  avgt    5   72.081 ±  3.560  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash               false         bigint                   5  avgt    5  112.367 ±  3.709  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash               false            all                   1  avgt    5  135.116 ±  2.160  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash               false            all                   5  avgt    5  206.728 ±  7.362  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash                true        varchar                   1  avgt    5   67.325 ±  1.794  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash                true        varchar                   5  avgt    5  139.034 ±  1.684  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash                true         bigint                   1  avgt    5   65.619 ±  1.637  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash                true         bigint                   5  avgt    5  100.291 ±  3.145  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash                true            all                   1  avgt    5   68.186 ±  7.439  ms/op
BenchmarkHashBuildOperator.benchmarkBuildHash                true            all                   5  avgt    5  190.411 ±  6.763  ms/op
```

The same benchmark with two separate loops in the constructor:
```
Benchmark                                              (buildHashEnabled)  (hashColumns)  (valuesRepetition)  Mode  Cnt    Score   Error  Units
BenchmarkHashBuildAndJoinOperators.benchmarkBuildHash               false        varchar                   1  avgt    5   71.624 ± 5.355  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkBuildHash               false        varchar                   5  avgt    5  128.337 ± 4.694  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkBuildHash               false         bigint                   1  avgt    5   47.119 ± 1.374  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkBuildHash               false         bigint                   5  avgt    5  101.466 ± 3.613  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkBuildHash               false            all                   1  avgt    5   86.438 ± 2.214  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkBuildHash               false            all                   5  avgt    5  186.427 ± 9.107  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkBuildHash                true        varchar                   1  avgt    5   52.610 ± 1.964  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkBuildHash                true        varchar                   5  avgt    5  112.519 ± 2.538  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkBuildHash                true         bigint                   1  avgt    5   43.787 ± 7.321  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkBuildHash                true         bigint                   5  avgt    5   95.850 ± 2.471  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkBuildHash                true            all                   1  avgt    5   52.491 ± 0.706  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkBuildHash                true            all                   5  avgt    5  152.818 ± 3.023  ms/op
```

Lastly, I have used `positionToHashes` in `InMemoryJoinHash.getJoinPosition` and this improved the actual hash joining by 10%-25%. So summing up, here are the latest results of both hash building and hash joining. In the following results, I have changed the number of pages from 1 000 000 down to 700 000.

Results before my changes:
```
Benchmark                                             (buildHashEnabled)  (hashColumns)  Mode  Cnt    Score    Error  Units
BenchmarkHashBuildOperator.benchmarkBuildAndJoinHash               false        varchar  avgt    5  537.103 ± 30.008  ms/op
BenchmarkHashBuildOperator.benchmarkBuildAndJoinHash               false         bigint  avgt    5  427.539 ± 16.921  ms/op
BenchmarkHashBuildOperator.benchmarkBuildAndJoinHash               false            all  avgt    5  592.554 ± 18.444  ms/op
BenchmarkHashBuildOperator.benchmarkBuildAndJoinHash                true        varchar  avgt    5  526.489 ± 25.400  ms/op
BenchmarkHashBuildOperator.benchmarkBuildAndJoinHash                true         bigint  avgt    5  444.495 ± 16.074  ms/op
BenchmarkHashBuildOperator.benchmarkBuildAndJoinHash                true            all  avgt    5  545.993 ± 29.077  ms/op
```

Optimized HashBuildOperator (InMemoryJoinHash constructor):
```
Benchmark                                             (buildHashEnabled)  (hashColumns)  Mode  Cnt    Score    Error  Units
BenchmarkHashBuildOperator.benchmarkBuildAndJoinHash               false        varchar  avgt    5  434.505 ± 20.431  ms/op
BenchmarkHashBuildOperator.benchmarkBuildAndJoinHash               false         bigint  avgt    5  352.301 ± 13.553  ms/op
BenchmarkHashBuildOperator.benchmarkBuildAndJoinHash               false            all  avgt    5  467.271 ± 13.389  ms/op
BenchmarkHashBuildOperator.benchmarkBuildAndJoinHash                true        varchar  avgt    5  433.748 ± 23.855  ms/op
BenchmarkHashBuildOperator.benchmarkBuildAndJoinHash                true         bigint  avgt    5  378.929 ± 26.891  ms/op
BenchmarkHashBuildOperator.benchmarkBuildAndJoinHash                true            all  avgt    5  450.636 ± 25.388  ms/op
```

All changes together - optimized both HashBuildOperator and HashJoinOperator:
```
Benchmark                                             (buildHashEnabled)  (hashColumns)  Mode  Cnt    Score     Error  Units
BenchmarkHashBuildOperator.benchmarkBuildAndJoinHash               false        varchar  avgt    5  333.764 ±  13.854  ms/op
BenchmarkHashBuildOperator.benchmarkBuildAndJoinHash               false         bigint  avgt    5  288.131 ±  12.473  ms/op
BenchmarkHashBuildOperator.benchmarkBuildAndJoinHash               false            all  avgt    5  369.712 ± 26.822  ms/op
BenchmarkHashBuildOperator.benchmarkBuildAndJoinHash                true        varchar  avgt    5  334.241 ±  13.941  ms/op
BenchmarkHashBuildOperator.benchmarkBuildAndJoinHash                true         bigint  avgt    5  315.357 ±  14.749  ms/op
BenchmarkHashBuildOperator.benchmarkBuildAndJoinHash                true            all  avgt    5  344.928 ±  28.220  ms/op
```

**Comment by dain** [comment]
One thing I have been thinking about is "how many bits of the hash do we have to compare to get the benefit"?  Could we use a `short[]` or even a `byte[]` instead of the `int[]`?

On another note, I think we will need to change `key` and `positionLinks` to LongBigArray, so we can support large hash tables, so it might be worth testing the performance impact of that.

**Comment by pnowojski** [comment]
> One thing I have been thinking about is "how many bits of the hash do we have to compare to get the benefit"? Could we use a short[] or even a byte[] instead of the int[]?

Nice catch. Indeed last byte of the hash is just as good for hash conflict resolution and reduces memory footprint. Construction has slowed down (because I had to drop this trick with two separate loops), but actual joining speed has remained unchanged or even improved slightly.

```
Benchmark                                                     (buildHashEnabled)  (hashColumns)  (valuesRepetition)  Mode  Cnt     Score     Error  Units
BenchmarkHashBuildAndJoinOperators.benchmarkBuildAndJoinHash               false        varchar                   1  avgt    5   313.189 ±  19.231  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkBuildAndJoinHash               false         bigint                   1  avgt    5   289.726 ±   8.855  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkBuildAndJoinHash               false            all                   1  avgt    5   361.317 ±  16.563  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkBuildAndJoinHash                true        varchar                   1  avgt    5   306.665 ±  30.431  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkBuildAndJoinHash                true         bigint                   1  avgt    5   291.688 ±  14.167  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkBuildAndJoinHash                true            all                   1  avgt    5   331.388 ±  21.544  ms/op
```  

> On another note, I think we will need to change key and positionLinks to LongBigArray, so we can support large hash tables, so it might be worth testing the performance impact of that.

Do we really need to store more then 2^31 values in those arrays? Even if we are joining only plain BIGINTers exceeding this limit would require something between 32GB and 128GB of memory. Doesn't the `task_hash_build_concurrency` solves this issue by effectively raising this limit even further? Isn't there also a limitation in fastuilt library? Something like it's limited to 111 millions of values?

Besides, can w treat this `LongBigArray`  change as separate issue to not complicate things too much?

**Comment by dain** [comment]
Awesome news about a single byte working! 

I was talking to @cberner about this this morning and we can to the same conclusion.  Lets leave it with the 2^31 limit and use local parallel to deal with really bug stuff.

Can you try changing `key` and `positionLinks` to IntBigArray, and `positionToHashes` to ByteBigArray, and measure the performance?  The benefit of ByteBigArray is that they are "segmented" arrays under the cover and don't require large contiguous memory allocations, which plays better with G1.

In the mean time, I'll do a full review.

**Comment by pnowojski** [comment]
Ok, I have changed arrays as you requested. There is a small performance penalty for using `BigArrays`:
```
Benchmark                                                     (buildHashEnabled)  (hashColumns)  Mode  Cnt    Score   Error  Units
BenchmarkHashBuildAndJoinOperators.benchmarkBuildAndJoinHash               false        varchar  avgt   10  331.980 ± 8.515  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkBuildAndJoinHash               false         bigint  avgt   10  306.439 ± 7.020  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkBuildAndJoinHash               false            all  avgt   10  378.446 ± 7.475  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkBuildAndJoinHash                true        varchar  avgt   10  329.110 ± 7.510  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkBuildAndJoinHash                true         bigint  avgt   10  298.754 ± 7.068  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkBuildAndJoinHash                true            all  avgt   10  351.917 ± 7.379  ms/op
```
Which version do you prefer?

**Comment by pnowojski** [comment]
@dain There is something wrong with this JMH benchmarking - maybe because it's using too small data set. I have rerun end to end tests on our cluster (8 nodes, 24 cores each) and they revealed that both `byte[]` and `BigArray` versions perform significantly worse compared to `int[]`. Here are full results:

https://docs.google.com/spreadsheets/d/12KviLlHqM7_4kkTIZ3vDemc0CnII-AdUBboz77S03f4/pubchart?oid=497588325&format=image

tested queries were:
```
SELECT count(*)
FROM
  "lineitem" AS l,
  "part" AS p
WHERE
  l.partkey = p.partkey
  AND l.shipdate >= DATE '1995-09-01'
  AND l.shipdate < DATE '1995-09-01' + INTERVAL '1' MONTH
```
on 1TB TPCH Hive schema and unmodified tpch/q14 on 100GB TPCH Hive schema. Difference is of course the bigger the larger is data set passed to `InMemorJoinHash`.

**Comment by dain** [comment]
Can you normalize the results in terms of "speedup" over the original?   The graph is a bit hard to read.

I have been messing with the benchmark myself, and I found that the hash build speed up is good ~2.5 (1.3 to 4.3), but the build+join speed up is not ~1.28 (0.96 to 4.3).  The speed up for build+join for repeated 5 is just about zero.

I think this will work and am still messing with it.  I think we need to look at:
- I think the compiler change might be necessary
- I think the benchmark should only have a standalone build and standalone join benchmark
    - Join is the most important as builds are small compared to a join
- We need to test with misses.  Every value we lookup is in the hash which cause the code to predicts to match.

**Comment by dain** [comment]
The problems when distributed could be cause by not having enough entropy in the hash.

**Comment by pnowojski** [comment]
Chart updated to relative times compared to original.

I have thought about this difference in JMH vs real world results. My best guess is that in the JMH benchmark build table and probe tables have the same size. In real world/code path, splitting/distributing build table scales way worse compared to the probe table. For 8 nodes with 24 cores and `task_hash_build_concurrency=1` each node there is one thread that process 1/8th of the build table. Probe table processing is being split per each node AND each core, giving in my case 1/192 of the probe table per core. 

So probably for better accuracy this JMH benchmark should have much bigger build table compared to probe table.

Tomorrow I will add some debug info to test this entropy issue.

**Comment by dain** [comment]
More notes:

Here is my latest benchmark code: https://gist.github.com/dain/5c1d1f2e62d038cc8933
For real measurement runs you need to increase the iterations an forks or you get unreliable results... unfortunately it takes 45 minutes to run.

I looked at the compiler changes, and I don't think a change there is needed.

The 5 repeated doesn't seem much speedup because only the first lookup benefits from the hash optimization, and the other 4 lookups follow the hash chain.  Additionally, since the hash table is sized based on the entry count instead of distinct entry count, we should get a much lower collision rate (because the hash table is 5x the necessary size).
I don't think repeated is a common case, and instead I think we should look at having "extra" values in the hash that never match, so a "hit rate".  With my change to the benchmark (where join is separate) it should be fairly easy to build a table with "extra" values.

I think we can simulate the problem of reduced entropy by when distributed by masking off some of the bits of the hash.  Typically distribute to 100-200 machines so masking off 7 or 8 bits should work.

**Comment by pnowojski** [comment]
I have updated JMH benchmark to the one you proposed, with one change that reduces the size of the probe table (down to 200 000 from 700 000), to better reflect real world situation. I have also squashed some commits, so that there are 3 versions on the table:

1. `int[]`
2. `byte[]`
3. `BigArrays`

Quick performance comparison for `bigint` with no repetitions:
```
Benchmark                                              Mode  Cnt   Score    Error  Units
IntArray:
BenchmarkHashBuildAndJoinOperators.benchmarkBuildHash  avgt   15  43.346 ± 13.580  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash   avgt   15  73.467 ±  7.077  ms/op
ByteArray:
BenchmarkHashBuildAndJoinOperators.benchmarkBuildHash  avgt   15  55.150 ± 11.710  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash   avgt   15  69.298 ±  1.590  ms/op
BigArrays:
BenchmarkHashBuildAndJoinOperators.benchmarkBuildHash  avgt    5  57.290 ± 11.804  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash   avgt    5  75.417 ±  5.529  ms/op
Original:
BenchmarkHashBuildAndJoinOperators.benchmarkBuildHash  avgt   15  109.584 ± 0.998  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash   avgt   15   74.155 ± 5.307  ms/op
```

> I don't think repeated is a common case, and instead I think we should look at having "extra" values in the hash that never match, so a "hit rate". With my change to the benchmark (where join is separate) it should be fairly easy to build a table with "extra" values.

What did you mean by that?

**Comment by dain** [comment]
> I don't think repeated is a common case, and instead I think we should look at having "extra" values in the hash that never match, so a "hit rate". 

So, my guess is that many joins have rows that are not used because the probe is filtered, and that having multiple matches is much less common.  So I suggest instead of having "repeated values" of 1 and 5, we have "match rate", with say 10%, 50%, 100%, 200%, 500%?

> With my change to the benchmark (where join is separate) it should be fairly easy to build a table with "extra" values.

The old code would have been difficult to add since it used the same code to build the hash table, and that code requires that the build have the same number of rows as the probe.  

Now that I think about this more, we most likely need to split the build and the join into two separate benchmark classes.

**Comment by pnowojski** [comment]
Replaced `valuesRepetition` with `matchRate` param. Probe table will have always same number of rows, but it is expected that each row will join `matchRate` times to build table.

> Now that I think about this more, we most likely need to split the build and the join into two separate benchmark classes.

Why do you think so? Both share hash building code.

**Comment by martint** [comment]
Let us know when you've updated it based on the conversation we had today

**Comment by pnowojski** [comment]
@dain @martint: I have came up with another idea that worked. It joins best of both of the words (byte[] vs int[]). Low memory footprint and faster joining for byte[] and faster construction of int[]. I'm processing positions in batches and I extract each batch hashes to int[]. Because batches have fixed size, memory int[] has always constant size regardless of the size of the build table.

**Comment by pnowojski** [comment]
JMH results:

byte[] version
```
BenchmarkHashBuildAndJoinOperators.benchmarkBuildHash               false        varchar          N/A  avgt   60   67.157 ±  6.933  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkBuildHash               false         bigint          N/A  avgt   60   49.333 ±  0.256  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkBuildHash               false            all          N/A  avgt   60   83.692 ±  1.498  ms/op

BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash                false        varchar          0.1  avgt   60  146.333 ±  1.659  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash                false        varchar            1  avgt   60  287.799 ±  1.953  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash                false        varchar            2  avgt   60  258.874 ±  2.446  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash                false         bigint          0.1  avgt   60  174.401 ±  1.245  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash                false         bigint            1  avgt   60  259.194 ±  3.094  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash                false         bigint            2  avgt   60  247.430 ±  3.288  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash                false            all          0.1  avgt   60  166.623 ±  1.861  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash                false            all            1  avgt   60  314.221 ±  2.039  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash                false            all            2  avgt   60  302.748 ± 19.111  ms/op
```

int[] version:
```
int[] run 2
Benchmark                                              (hashColumns)  (matchRate)  Mode  Cnt    Score   Error  Units
BenchmarkHashBuildAndJoinOperators.benchmarkBuildHash        varchar          N/A  avgt   60   51.999 ± 0.343  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkBuildHash         bigint          N/A  avgt   60   39.790 ± 4.226  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkBuildHash            all          N/A  avgt   60   63.274 ± 0.489  ms/op

BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash         varchar          0.1  avgt   60  186.128 ± 1.447  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash         varchar            1  avgt   60  301.182 ± 6.415  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash         varchar            2  avgt   60  270.933 ± 3.667  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash          bigint          0.1  avgt   60  231.678 ± 2.172  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash          bigint            1  avgt   60  281.045 ± 2.693  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash          bigint            2  avgt   60  239.445 ± 2.033  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash             all          0.1  avgt   60  201.924 ± 1.203  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash             all            1  avgt   60  333.971 ± 3.366  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash             all            2  avgt   60  297.348 ± 3.261  ms/op
```

byte[] + partial int[]
```
Benchmark                                              (buildHashEnabled)  (hashColumns)  (matchRate)  Mode  Cnt    Score    Error  Units
BenchmarkHashBuildAndJoinOperators.benchmarkBuildHash               false        varchar          N/A  avgt   60   46.752 ±  0.411  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkBuildHash               false         bigint          N/A  avgt   60   38.600 ±  0.158  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkBuildHash               false            all          N/A  avgt   60   59.121 ±  0.261  ms/op

BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash                false        varchar          0.1  avgt   60  146.427 ±  0.728  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash                false        varchar            1  avgt   60  291.661 ±  6.000  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash                false        varchar            2  avgt   60  266.757 ±  2.584  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash                false         bigint          0.1  avgt   60  175.083 ±  0.890  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash                false         bigint            1  avgt   60  269.781 ±  3.887  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash                false         bigint            2  avgt   60  250.010 ±  3.511  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash                false            all          0.1  avgt   60  161.506 ±  0.715  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash                false            all            1  avgt   60  323.585 ±  6.088  ms/op
BenchmarkHashBuildAndJoinOperators.benchmarkJoinHash                false            all            2  avgt   60  297.170 ±  4.137  ms/op
```

**Comment by martint** [comment]
As we discussed offline, let's write a standalone benchmark that replicates what the current join code is doing and see if we can figure out what's contributing to the slowdown, and see the effects of removing layers of abstraction, bounds checks, etc.

**Comment by pnowojski** [comment]
@martint @dain rebased to the latest master

**Comment by dain** [comment]
I have pulled out the changes to the InMemoryJoin and integrated it with the changes for null checks, and we are running this in one of our production clusters.  I will merge the extracted code once the release goes out.  After that, we should go thought this PR and any other ones you have for JOIN perf to see if there are pieces I missed or performance improvements to be made.

**Comment by pnowojski** [comment]
Ok thanks.

**Comment by dain** [comment]
I merged the new `InMemoryJoinHash` code.  If there are other changes we should include, please open a new PR.  Thanks!

**Pull request closed without merging**
