### PR TITLE
Fix SQL function compilation failure

### LINKED ISSUE #13737: SQL function compilation failed when input parameter not referenced
```
> CREATE FUNCTION testing.foo.bar(x integer) RETURNS integer RETURN 1
> SELECT testing.foo.bar(1)
```
Fails with `Compiler failed`.
```
Caused by: java.lang.NullPointerException
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1492)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at com.facebook.presto.sql.relational.SqlFunctionUtils.getSqlFunctionRowExpression(SqlFunctionUtils.java:107)
        at com.facebook.presto.sql.gen.RowExpressionCompiler$Visitor.visitCall(RowExpressionCompiler.java:117)
        at com.facebook.presto.sql.gen.RowExpressionCompiler$Visitor.visitCall(RowExpressionCompiler.java:98)
        at com.facebook.presto.spi.relation.CallExpression.accept(CallExpression.java:107)
        at com.facebook.presto.sql.gen.RowExpressionCompiler.compile(RowExpressionCompiler.java:95)
        at com.facebook.presto.sql.gen.RowExpressionCompiler.compile(RowExpressionCompiler.java:88)
        at com.facebook.presto.sql.gen.PageFunctionCompiler.generateEvaluateMethod(PageFunctionCompiler.java:357)
        at com.facebook.presto.sql.gen.PageFunctionCompiler.definePageProjectWorkClass(PageFunctionCompiler.java:237)
        at com.facebook.presto.sql.gen.PageFunctionCompiler.compileProjectionInternal(PageFunctionCompiler.java:189)
        at com.facebook.presto.sql.gen.PageFunctionCompiler.compileProjection(PageFunctionCompiler.java:163)
        at com.facebook.presto.sql.gen.ExpressionCompiler.lambda$compilePageProcessor$3(ExpressionCompiler.java:108)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Collections$2.tryAdvance(Collections.java:4727)
        at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4735)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at com.facebook.presto.sql.gen.ExpressionCompiler.compilePageProcessor(ExpressionCompiler.java:109)
        at com.facebook.presto.sql.gen.ExpressionCompiler.compilePageProcessor(ExpressionCompiler.java:96)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitScanFilterAndProject(LocalExecutionPlanner.java:1283)
        ... 75 more
```

### PR DESCRIPTION
**Pull request by rongrong**
Fixes #13737

RowExpression compilation for SQL function could fail when the input
is not referenced in function body.

```
== RELEASE NOTES ==

General Changes
* Fix SQL function compilation failure when the function parameter is not referenced in function body.

```

### CODE REVIEW

**Comment by caithagoras** [comment]
Can you add a unit test?

**Comment by rongrong** [comment]
Alternatively we could check this at function creation and throw to disallow this. But in general there's no rule against not using input parameters in functions and ideally we should be smart enough to know how to optimize this (which currently we don't do). Once we do inlining at planning time this would be optimized automatically.

**Comment by rongrong** [comment]
> Can you add a unit test?

We still yet to build a test framework for SQL functions. 🤣

**Comment by wenleix** [comment]
Aha, just see the comment about tests. Ignore my comments.

**Pull request merged**
