### PR TITLE
Allow hbo stats for failed stages with local memory

### PR DESCRIPTION
**Pull request by jaystarshot**
## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ... :pr:`12345`
* ... :pr:`12345`

Hive Connector Changes
* ... :pr:`12345`
* ... :pr:`12345`
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by jaystarshot** [comment]
@feilong-liu What do you think? any particular reason to not do this before?

**Comment by feilong-liu** [comment]
> @feilong-liu What do you think? any particular reason to not do this before?

Why EXCEEDED_LOCAL_MEMORY_LIMIT is special, I mean will the statistics be accurate for this error?

**Comment by jaystarshot** [comment]
The failed stage will likely have metrics of the worst offending one so should help in joins?

**Comment by feilong-liu** [comment]
> The failed stage when there is a oom error will likely have metrics of the worst offending task so should help in joins/aggs?

HBO considers the statistics recorded accurate, and it will be shared among queries which has the same plan hash (not necessarily the same query). 
Also this change will record statistics for all plan nodes, rather than the specific join/aggregation which has OOM. I think a better way is to record the statistics only for this failed node and add new type of statistics saying it's at least this number, rather than an accurate estimation.

**Comment by jaystarshot** [comment]
Yes filtering by plannode is better but its a bigger change than this. I think using OOM stats as accurate won't have an adverse effect since OOM is a special case because If the current plan is seen again in any query it will again oom.

**Comment by feilong-liu** [comment]
> Yes filtering by plannode is better but its a bigger change than this. Also operator stast are not always awailable for all operators within a stage. I have typically seen only 1-2 operators per stage having runtime stats. I think using OOM stats as accurate won't have an adverse effect since OOM is a special case because If the current plan is seen again in any query it will again oom.

If you want to try, I suggest to add a session property to gate it.

**Comment by jaystarshot** [comment]
Closing for now, will check if considering the individual operator stats can be filtered

**Pull request closed without merging**
