### PR TITLE
Remove syntax highlighting from coordinator UI

### PR DESCRIPTION
**Pull request by haozhun**
* Syntax highlighting provided by this library doesn't really work.
  It doesn't like the way ARRAY and VARCHAR are used in Presto.
  Needless to say, it also has no idea about lambda.
* The performance of this library has always been bad for certain queries
  in FireFox, slowing down page rendering and scrolling. There isn't
  much improvement when this library is run inside FireFox Quantum.

### CODE REVIEW

**Comment by martint** [comment]
Why?

**Comment by martint** [comment]
Oh, just saw the commit message. We should look for another alternative.

**Comment by raghavsethi** [comment]
We decided to spend a little more time looking at alternatives first.

**Comment by raghavsethi** [comment]
Closing now, we can re-open if this is still an issue.

**Pull request closed without merging**
