### PR TITLE
chore(clickhouse): bump clickhouse-jdbc to v0.6.0 (latest)

### LINKED ISSUE #21846: Upgrade clickhouse-jdbc to latest 0.6.0
Now clickhouse jdbc is moved to com.clickhouse also the current version 0.2.4 is old and has some CVE vulnerabilities related https://mvnrepository.com/artifact/ru.yandex.clickhouse/clickhouse-jdbc/0.2.4

We should plan to upgrade clickhouse-jdbc to https://mvnrepository.com/artifact/com.clickhouse/clickhouse-jdbc/0.6.0

## Expected Behavior or Use Case
Upgrade clickhouse-jdbc to latest 0.6.0

## Presto Component, Service, or Connector
Clickhouse connector

## Context
Good to move to latest jdbc version which doesn't have vulnerabilities

### PR DESCRIPTION
**Pull request by hainenber**
## Description
Bump `clickhouse-jdbc` to latest version, 0.6.0. The groupID has been changed so there are refactoring accordingly.

## Motivation and Context
Closes #21846 

- BAU
- Remediate [57 vulnerabilities](https://mvnrepository.com/artifact/ru.yandex.clickhouse/clickhouse-jdbc/0.2.4)

## Impact

No impact

## Test Plan

Use CI to ensure no breakages

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* Upgrade clickhouse-jdbc to v0.6.0

```

### CODE REVIEW

**Comment by steveburnett** [comment]
Following the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines), suggest revising the release note entry. Suggested:

```
== RELEASE NOTES ==

Security Changes
* Upgrade clickhouse-jdbc to v0.6.0

```

**Comment by hainenber** [comment]
Thanks Steve for the callout, appreciate it!

**Comment by agrawalreetika** [comment]
Hi @hainenber 
Thank you for the PR. 
It looks to me that `clickhouse` tests are not enabled in Circle CI. I have tried to run exiting `clickhouse` tests manually on local with your change, which seems to be failing with below error:
```
2024-02-11T05:07:36.802-0600 INFO Waiting for database connection to become available at jdbc:clickhouse://localhost:49468/default using query 'SELECT 1'
2024-02-11T05:07:36.944-0600 WARNING Error when creating APACHE_HTTP_CLIENT, fall back to HTTP_URL_CONNECTION
java.lang.NoClassDefFoundError: org/apache/hc/client5/http/io/HttpClientConnectionManager
```

Could you please confirm how did you test your change?

@tdcmeehan Could you please suggest if we are open to enable `clickhouse` tests in Circle CI or if there is any reason we have not enabled it?

**Comment by hainenber** [comment]
That was my mistake 😵‍💫 . I was assuming this is covered by the CI and didn't run `presto-clickhouse` tests locally. I'll try to replicate your error locally and revert soon!

**Comment by hainenber** [comment]
Hi @agrawalreetika, I've ran Maven's `test` lifecycle on `presto-clickhouse` for this change but to my surprise, the job completes without any issues!

image

Is there any info that can assist me reproducing your issue locally?

**Comment by agrawalreetika** [comment]
Looks like in clickhouse connector pom `TestClickHouseDistributedQueries` is excluded so it didn't run as part of Tests. It just ran 3 tests which are in `TestClickHouseConfig` & `TestClickHousePlugin`

Try running Query tests in `TestClickHouseDistributedQueries`

**Pull request closed without merging**
