### PR TITLE
Skip returning peer token in SPNEGO response

### PR DESCRIPTION
**Pull request by electrum**
The token is not used by existing clients and thus seems not to be needed.

### CODE REVIEW

**Comment by martint** [comment]
Are you sure this is valid? If I remember correctly, it's required for it to be a valid spnego response.

**Comment by martint** [comment]
I think not including the token has the same shape as an initial challenge, which could confuse clients.

**Comment by electrum** [comment]
I’ll read the RFC again, but to my knowledge, no existing clients use it. They actually should preemptively send the authentication for each request when configured for Kerberos in order to avoid the extra round trip.

**Comment by martint** [comment]
See https://tools.ietf.org/html/rfc4559

> If the server receives a request for an access-protected object, and
   if an acceptable Authorization header has not been sent, the server
   responds with a "401 Unauthorized" status code, and a "WWW-
   Authenticate:" header as per the framework described in [RFC2616].
   The initial WWW-Authenticate header will not carry any gssapi-data.

> If the gss_accept_security_context returns a token for the client,
   this directive contains the base64 encoding of an
   initialContextToken, as defined in [RFC2743].  This is not present in
   the initial response from the server.

Also,

>  A client may initiate a connection to the server with an
   "Authorization" header containing the initial token for the server.
   This form will bypass the initial 401 error from the server when the
   client knows that the server will accept the Negotiate HTTP
   authentication type.

**Comment by electrum** [comment]
I think this is the relevant part:

>  A status code 200 status response can also carry a "WWW-Authenticate"
   response header containing the final leg of an authentication.  In
   this case, the gssapi-data will be present.  Before using the
   contents of the response, the gssapi-data should be processed by
   gss_init_security_context to determine the state of the security
   context.  If this function indicates success, the response can be
   used by the application.

> For example, the authentication could have failed on the final leg if
   mutual authentication was requested and the server was not able to
   prove its identity.  In this case, the returned results are suspect.

It says *can*, not *must*, so this sounds optional. Given that we only perform SPNEGO over TLS, the client has already authenticated the identity of the server before sending the token.

**Comment by electrum** [comment]
I skipped the last part of the paragraph, which is quite relevant to our scenario:

>  It is not always possible to mutually authenticate the server before
   the HTTP operation.  POST methods are in this category.

The client has already sent the authentication token and performed the operation, so attempting to validate the server's identity at this point doesn't seem useful.

**Comment by martint** [comment]
The way I read that is that the response can include the header or not, not that it can have a header without the token: "in this case, the gssapi-data will be present"

**Comment by electrum** [comment]
Yes, we are removing the header entirely for the 200 response.

The motivation to remove it is that it simplifies adding multiple authentication types, and I'd rather not have complexity for something that no one uses and that is not tested.

**Comment by martint** [comment]
I see. I got confused by the title of the PR, which seems to imply that a SPNEGO response is being returned without a token.

**Comment by electrum** [comment]
Ah, makes sense. I will update the commit description to better explain the change.

**Comment by electrum** [comment]
Closing as this is part of #9287

**Pull request closed without merging**
