### PR TITLE
Add S3 custom credential provider documentation

### LINKED ISSUE #5703: Document S3 custom credentials providers
We should add documentation for #5667. Maybe add a section to the Hive connector docs about S3 and add a sub-section for this.

### PR DESCRIPTION
**Pull request by nezihyigitbasi**
Fixes #5703.

### CODE REVIEW

**Comment by dain** [comment]
@electrum can you review this?

**Comment by electrum** [comment]
Sorry for the delay on this. I just merged #5701 which adds `hive.s3.encryption-materials-provider` and related documentation. I think we should go ahead and do the same here, for consistency. Can you add a new `HiveClientConfig` for this and update the documentation for the new S3 docs?

**Comment by electrum** [comment]
Actually, I think we can just add a new section to the S3 docs for this and decide if we want to add a property.

**Comment by electrum** [comment]
I think I like the way the encryption materials provider works better. Instead of requiring a Hadoop `Configuration` object, we have the constructor only take a `URI` and instead check if the object is an instance of `Configurable`. That makes the dependency on Hadoop optional, for cases where you have a credentials provider that doesn't need extra configuration.

**Comment by electrum** [comment]
Merged, thanks!

**Pull request closed without merging**
