### PR TITLE
Add presto-bechto service

### PR DESCRIPTION
**Pull request by losipiuk**
Add benchto-service for benchmark data collection.

### CODE REVIEW

**Comment by losipiuk** [comment]
@martint As we discussed this is PR which adds presto-benchmark module for managing presto banchmarking results.
Please merge when you have a chance.

cc: @ilfrin

**Comment by electrum** [comment]
This is awesome! I notice the diff is 77,000+ lines, mostly due to a lot of JS libraries. Can we split that into a separate commit to make it easier to manage?

**Comment by electrum** [comment]
We were just thinking that it'd be nice if all these common JS libraries were in Maven, and it turns out there's a project already doing that. Check out the documentation for "Servlet 3": http://www.webjars.org/documentation

If that doesn't work already, we should fix Airlift HTTP server to make it work.

**Comment by kokosing** [comment]
@electrum please file an issue about JS dependences for existing modules. This sounds like a good idea.

There are also migration files which could be merged into single `init_schema` file.

**Comment by martint** [comment]
Woohoo! This is great. We currently don't have a good way to measure performance consistently to make sure we don't introduce regressions (and that we make it better over time). We were about to start looking into something like it over the next few months. This will help a LOT!

Looking at the code more closely, I think it'd make sense to pull it out as a separate repo in prestodb, sinceI expect it to evolve and be released at a different rate.

**Comment by martint** [comment]
I just created https://github.com/prestodb/benchto. Can you submit the PR there?

**Comment by losipiuk** [comment]
That makes perfect sense. Thanks @martint :)

**Pull request closed without merging**
