### PR TITLE
[native] Advance velox.

### PR DESCRIPTION
**Pull request by amitkdutta**
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by xiaoxmeng — APPROVED** [review]
@amitkdutta thanks!

**Comment by aditi-pandit** [comment]
linux-presto-e2e-tests has failed : [ERROR]   TestPrestoNativeIcebergTpcdsQueriesParquetUsingThrift.doDeletesAndQuery:400->runAllQueries:126->AbstractTestNativeTpcdsQueries.testTpcdsQ76:1010->AbstractTestQueryFramework.assertQuery:169 Execution of 'actual' query failed: SELECT

@imjalpreet @agrawalreetika @nmahadevuni : Please can you take a look.

**Comment by nmahadevuni** [comment]
Failing with error from Velox `Caused by: VeloxRuntimeError: rawResultNulls_ && rawValues_ `. Looks like something changed from previous velox commit that's causing this.

**Comment by nmahadevuni** [comment]
Commit `fa6abe67efcd1b0e2610a9d1c4e428e04d20b1bc (Table scan execution path code cleanup (#10893))` is causing this issue with TPCDS-Q76.

**Comment by nmahadevuni** [comment]
Can reproduce with IcebergExternalQueryRunner by using the below query 

```
SELECT ss_ext_sales_price FROM store_sales WHERE ("ss_store_sk" IS NULL);
```

**Comment by amitkdutta** [comment]
Thanks folks for jumping in. @xiaoxmeng fixed it in https://github.com/facebookincubator/velox/pull/10956 
Closing this one since we have a more recent velox commit PR including the fix https://github.com/prestodb/presto/pull/23621

**Pull request closed without merging**
