### PR TITLE
Upgrade hive-apache to new version 3.0.0-6

### PR DESCRIPTION
**Pull request by shangxinli**
Test plan - (Please fill in how you tested your changes)

Please make sure your submission complies with our [Development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [Formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), and [Commit Message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests) guidelines. Don't forget to follow our [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution) for any code copied from other projects.

Fill in the release notes towards the bottom of the PR description.
See [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) for details.

```
== RELEASE NOTES ==

General Changes
Upgrade hive-apache to new version 3.0.0-6

Hive Changes
Fix NoClassDefFoundError for JsonNode
```

### CODE REVIEW

**Comment by shangxinli** [comment]
To solve the test error below. We need to make several other changes in Hive and presto-hive-apache repro. 

java.lang.NoClassDefFoundError: com/facebook/presto/hive/$internal/org/codehaus/jackson/JsonNode
presto-worker_1       | 	at org.apache.hadoop.hive.serde2.avro.AvroSerDe.getSchemaFromCols(AvroSerDe.java:178)

1.  We need the [PR](https://github.com/prestodb/presto-hive-apache/pull/49) to fix the above failure. 
2.  The [commit](https://github.com/apache/hive/commit/f26fe63c8f2875c6976a3d536f48235fb86da672) need to be ported to Hive 3.0+( presto-hive-apache uses 3.0.0-5). And then release a new version of Hive 3.0+, and then upgrade presto-hive-apache.

**Comment by beinan** [comment]
Thank you!  it looks good to me, but I'm not sure the impact on Facebook side. Let's wait for the test result.

btw, could you please update the release note section in this PR? Thanks!

**Comment by shangxinli** [comment]
Thanks @beinan for having a look! Yeah, this PR disabled quite a few tests. I am not sure if that is acceptable. The root cause is the new version of Avro changed the signature of Avro Schema(not backward compatible), and Hive has a hard dependency on the old signature. A fix in Hive is needed and that is done in Hive 2.x.x but not Hive 3.x.x, but our Hive-apache repo is using Hive 3.x.x. 

So there are 3 solutions now. 1) Push Hive community to port the fix from 2.x.x to 3.x.x and have a new release. 2) Revert https://github.com/prestodb/presto/pull/15805 to let Presto have its own Parquet upgrading path independent of the hive-apache repo. 3) Disable tests(not sure if real user scenarios also having issues).

**Comment by beinan** [comment]
> Thanks @beinan for having a look! Yeah, this PR disabled quite a few tests. I am not sure if that is acceptable. The root cause is the new version of Avro changed the signature of Avro Schema(not backward compatible), and Hive has a hard dependency on the old signature. A fix in Hive is needed and that is done in Hive 2.x.x but not Hive 3.x.x, but our Hive-apache repo is using Hive 3.x.x.
> 
> So there are 3 solutions now. 1) Push Hive community to port the fix from 2.x.x to 3.x.x and have a new release. 2) Revert #15805 to let Presto have its own Parquet upgrading path independent of the hive-apache repo. 3) Disable tests(not sure if real user scenarios also having issues).
> 
> #1 seems a better solution but it seems the Hive community has no interest, for now, to help on releasing Hive 3.x.x. I started an [email thread](https://www.mail-archive.com/user@hive.apache.org/msg22328.html) for asking Hive community but not response.

Thanks a lot for these solutions!
Any chance to override the change you made in hive in presto-hive-apache?  we might be able to put  AvroDeserializer.java into here https://github.com/prestodb/presto-hive-apache/tree/master/src/main/java/org/apache/hadoop/hive/serde2/avro
I'm just guessing,  not sure if it works or not.  Thanks!

**Comment by shangxinli** [comment]
@beinan The change I made in pesto-hive-apache helped JsonNode no class finding error. Now the failing tests is failing with the following stack. 

	at org.apache.hadoop.hive.serde2.avro.TypeInfoToSchema.createAvroField(TypeInfoToSchema.java:76)
	at org.apache.hadoop.hive.serde2.avro.TypeInfoToSchema.convert(TypeInfoToSchema.java:61)
	at org.apache.hadoop.hive.serde2.avro.AvroSerDe.getSchemaFromCols(AvroSerDe.java:179)
	at org.apache.hadoop.hive.serde2.avro.AvroSerDe.initialize(AvroSerDe.java:117)
	at com.facebook.presto.hive.HiveUtil.initializeDeserializer(HiveUtil.java:496)
	at com.facebook.presto.hive.HiveUtil.getDeserializer(HiveUtil.java:456)
	at com.facebook.presto.hive.GenericHiveRecordCursor.<init>(GenericHiveRecordCursor.java:144)
	at com.facebook.presto.hive.GenericHiveRecordCursorProvider.lambda$createRecordCursor$1(GenericHiveRecordCursorProvider.java:79)
	at com.facebook.presto.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
	at com.facebook.presto.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:81)
	at com.facebook.presto.hive.GenericHiveRecordCursorProvider.createRecordCursor(GenericHiveRecordCursorProvider.java:75)
	at com.facebook.presto.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:466)
	at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:184)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:63)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:80)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:249)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:418)
	at com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:301)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:722)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:294)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:599)
	at com.facebook.presto.$gen.Presto_0_261_SNAPSHOT_280493b____20210824_183044_1.run(Unknown Source)

So I am not totally getting your point. Can you explain?

**Comment by shangxinli** [comment]
Did you find something @beinan?

**Comment by beinan** [comment]
> > > The way I can think of is to shade the Hive jar. 1) Create a new project which references hive-2.3.8 and shade it 2) Include this project in presto-hive-apache 3) Change presto to reference the shaded class
> > > gotcha, let me try something in this weekend and get back to you:)
> 
> Do you have updates @beinan?

Hi @shangxinli , sorry for my delay, I post a PR for this issue https://github.com/prestodb/presto-hive-apache/pull/51
I copied some of classes from hive and made change on it.  The pr fixed some of the unit tests, but there still are tests failing.  Could you help take a look?  I think you would be more familiar with avro stuff.  Thanks a lot!  Feel free take over the PR if you got some ideas.

**Comment by aweisberg** [comment]
I'll take a look at this soon and try deploying the whole thing.

**Comment by aweisberg** [comment]
I deployed this to a cluster and ran 20k test queries. There was one failure that I haven't resolved yet, but I am guessing it was transient and specific to that query and am retesting it now.

**Comment by beinan** [comment]
> I deployed this to a cluster and ran 20k test queries. There was one failure that I haven't resolved yet, but I am guessing it was transient and specific to that query and am retesting it now.

Thank you @aweisberg ! any updates? looks like the ci is still failing.

**Comment by aweisberg** [comment]
I fought with it a bit yesterday morning. I think that `mvn deploy` of snapshots isn't working for some reason.

I can see the snapshot artifacts getting uploaded, but it can't find them at build time. It might be a config option in maven somewhere.

**Comment by aweisberg** [comment]
There is something wrong with snapshots. I can upload them and even see them in `https://oss.sonatype.org/#nexus-search;gav~com.facebook.presto.hive~hive-apache~~~~kw,versionexpand`, but I can't get them to download.

I also get the error
```
Unable to identify component: org.sonatype.nexus.proxy.ItemNotFoundException: Path com/facebook/presto/hive/hive-apache/3.0.0-7-SNAPSHOT/hive-apache-3.0.0-7-20211006.154738-15.jar not found in local storage of repository "Snapshots" [id=snapshots]
```
When I try to look at component info in the Nexus web UI.

How snapshots are deployed is defined in airbase and it looks correct.
```
    <repositories>
        <repository>
            <id>sonatype-nexus-snapshots</id>
            <name>Sonatype Nexus Snapshots</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
```

The build tries to fetch from that location
```
[ERROR] Failed to execute goal on project presto-hive-metastore: Could not resolve dependencies for project com.facebook.presto:presto-hive-metastore:jar:0.264-SNAPSHOT: Could not find artifact com.facebook.presto.hive:hive-apache:jar:3.0.0-7-20211006.154738-15 in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project presto-hive-metastore: Could not resolve dependencies for project com.facebook.presto:presto-hive-metastore:jar:0.264-SNAPSHOT: Could not find artifact com.facebook.presto.hive:hive-apache:jar:3.0.0-7-20211006.154738-15 in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots)
```

**Comment by aweisberg** [comment]
I think it's working now. I had to deploy a few times to get the timestamps to match.

**Comment by beinan** [comment]
Awesome!!! @aweisberg Thank you! 

Hello @shangxinli, looks like all good except the iceberg connector one, I will take a look soon.

**Pull request closed without merging**
