### PR TITLE
Remove enableTimestampMicroPrecision option

### PR DESCRIPTION
**Pull request by vigneshwarselvaraj**
ORC supported reading timestamp as Microseconds via a config option. This was done as the type system at that time only had Milliseconds support. Now TIMESTAMP_MICROSECONDS is available so this change removes the option. In the following change, microseconds support will be introduced via types.

Test plan

- Existing tests.

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by vigneshwarselvaraj** [comment]
@sdruzkin @arunthirupathi Please help review.

**Review by arunthirupathi — APPROVED** [review]
Change looks good to me, you can publish this change and I will merge it in.

**Comment by sdruzkin** [comment]
LGTM

**Review by sdruzkin — APPROVED** [review]

**Comment by vigneshwarselvaraj** [comment]
> Change looks good to me, you can publish this change and I will merge it in.

Thanks! Please help merge it.

**Pull request merged**
