### PR TITLE
[native] Add native e2e tests for unicode in JSON

### PR DESCRIPTION
**Pull request by gggrace14**
## Description
Add Native e2e tests for unicode encoding when casting unicode to JSON.

## Motivation and Context
To test the same behavior of Native and Presto Java in encoding unicode when casting unicode to JSON.

## Impact
None

## Test Plan
The change is to add e2e tests.

## Release Notes
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by amitkdutta — COMMENTED** [review]
@gggrace14 Please add "[native]" prefix and fill the PR submission template for motivation and context description.

**Comment by aditi-pandit** [comment]
@gggrace14 : Please do not put "Advance Velox" and presto-native-execution module changes in the same PR. We separate them. In any case, Velox has been advanced since and you will have to rebase.

**Comment by gggrace14** [comment]
> @gggrace14 : Please do not put "Advance Velox" and presto-native-execution module changes in the same PR. We separate them. In any case, Velox has been advanced since and you will have to rebase.

Hi @aditi-pandit , I will remove the "Advance Velox" version part from this PR afterwards, after the velox commit that I want to pick up is merged.

**Review by amitkdutta — APPROVED** [review]
Looks good. Thanks @gggrace14

**Pull request merged**
