### PR TITLE
Add cassandra.properties to presto-main/etc/catalog

### PR DESCRIPTION
**Pull request by sanjay990**
Add cassandra properties to presto-main/etc/catalog similar to
what we have for other connectors.

### CODE REVIEW

**Comment by sanjay990** [comment]
CC: @cawallin

**Comment by cawallin** [comment]
@electrum -- what's the general practice for this? It looks like some but not all connectors have properties files in `presto-main/etc/catalog`. In this case, if you don't have Cassandra set up, Presto will start in Intellij, but fail when you try to query the cassandra catalog (similar to hive).

**Comment by dain** [comment]
I personally stopped using the full service, which is what uses these files, since we have added main methods to the query runners.  I see that `CassandraQueryRunner` doesn't have one... I'd copy over one from `TpchQueryRunner`.  Once you have this, you can just start a distributed, multi-server, environment with your connector installed, which makes debugging really fast.

**Comment by sanjay990** [comment]
I'll close this PR as this isn't needed.

**Comment by sanjay990** [comment]
I created a new issue - https://github.com/prestodb/presto/issues/7809

**Comment by electrum** [comment]
It's fine to add these as long as they don't prevent the server from starting, but it makes startup take a little longer, so if it's not useful to most developers I'd avoid it.

**Pull request closed without merging**
