### PR TITLE
Fix the logic in LocalExchange for acquiring the bucket count

### PR DESCRIPTION
**Pull request by kewang1024**
If release note is NOT required, use:

```
== RELEASE NOTES ==

General Changes
* Fix the logic in LocalExchange for acquiring the bucket count.

```

### CODE REVIEW

**Comment by highker** [comment]
Why the previous logic is failing? Can we add a unit test to it?

**Comment by kewang1024** [comment]
So it actually a bug where we called the wrong function
To acquire the bucket count, we originally called `getBucketNodeMap` to first get `connectorBucketNodeMap ` which is not right during worker execution, which would also be stuck since the worker doesn't know the node list in the logic:
`createBucketNodeMap(Stream.generate(() -> sortedNodes).flatMap(List::stream).limit(bucketCount).collect(toImmutableList())`

The correct way to acquire the bucket count is to use `getBucketCount`.

**Review by highker — APPROVED** [review]
there are style check failures

**Comment by highker** [comment]
@kewang1024, could you also add release note?

**Pull request merged**
