### PR TITLE
[WIP] Testing optmized hdp-2.6-hive docker image

### PR DESCRIPTION
**Pull request by kokosing**

### CODE REVIEW

**Comment by findepi** [comment]
@kokosing travis is green, i restarted it now. However, `Stress product tests` is ineffective, Travis removed duplicate matrix configurations.

**Comment by kokosing** [comment]
`However, Stress product tests is ineffective, Travis removed duplicate matrix configurations.`

Yeah ... I have noticed that. Let met overcome this.

**Comment by kokosing** [comment]
It looks like this change do not change much ; /. Among the failures I found: 
```

presto-worker_1       | # There is insufficient memory for the Java Runtime Environment to continue.
presto-worker_1       | # Native memory allocation (mmap) failed to map 213909504 bytes for committing reserved memory.
```

What do you think we should with this? From the one point of view change is working, images are smaller but they are a bit hacked.

**Comment by findepi** [comment]
If this doesn't change much, let's not merge this. 

(btw As to JVM OOM, this is "sporadically" observable on master too.)

**Pull request closed without merging**
