### PR TITLE
Upgrade Airlift to 0.215

### PR DESCRIPTION
**Pull request by NikhilCollooru**
## Description
Upgrade Airlift to 0.215

## Motivation and Context
The latest 0.215 airlift has update Jetty version which helps resolve the CPU contention on coordinator

## Impact
None

## Test Plan
exisiting Tests

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [x] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* Upgrade Airlift to 0.215 :pr:`23356`
```

### CODE REVIEW

**Comment by steveburnett** [comment]
Nit suggestion for the release note entry for consistency with the [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines): 

```
== RELEASE NOTES ==

General Changes
* Upgrade Airlift to 0.214 :pr:`23356`
```

**Review by rschlussel — DISMISSED** [review]

**Review by feilong-liu — DISMISSED** [review]

**Comment by rschlussel** [comment]
You can rebase to pick up the fix for the docker-compose failures.

**Comment by jaystarshot** [comment]
Any reason to not upgrade to latest? https://github.com/airlift/airlift/releases

**Comment by rschlussel** [comment]
> Any reason to not upgrade to latest? https://github.com/airlift/airlift/releases. Nvm I am not sure if we are using this or some facebook airlift repo

we use a fork https://github.com/prestodb/airlift

**Review by feilong-liu — APPROVED** [review]

**Pull request merged**
