### PR TITLE
[native] Update Presto protocol

### PR DESCRIPTION
**Pull request by majetideepak**
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by majetideepak** [comment]
@imjalpreet, FYI since you are making changes to the Presto protocol to support Iceberg.

**Review by mbasmanova — APPROVED** [review]
Thanks. Please, confirm that you auto-generated the presto_protocol.h,cpp files, not edited them manually.

**Comment by majetideepak** [comment]
@mbasmanova yes, I confirm. I did not modify the generated `presto_protocol.h,cpp files`.

**Comment by aditi-pandit** [comment]
@majetideepak : Apologize saw this only now. What is this change for ?

**Comment by majetideepak** [comment]
While working on some protocol changes, I noticed the current files are out of sync with Presto java. I made this independent change.

**Pull request merged**
