### PR TITLE
Update airbase to 0.60

### PR DESCRIPTION
**Pull request by kokosing**
Update airbase to 0.60

### CODE REVIEW

**Comment by kokosing** [comment]
Build is passing locally, once airbase got released I will rerun the travis.

**Comment by martint** [comment]
I've released airbase 60

**Comment by kokosing** [comment]
There is a conflict in tests between presto-cassandra and presto-main (in presto-cassandra module). Both are using conflicting version of guava. I am not sure how to tackle this. The best way would be to make tests to load a connector classes in the same isolated manner as we do in production. Which requires more effort, maybe you know the easier way?

In the meantime I opened a pull request to cassandra driver in which I upgrade guava. See https://github.com/datastax/java-driver/pull/783

**Comment by martint** [comment]
What tests conflict? TestCassandraDistributed tests use DistributedQueryRunner, which runs a full embedded Presto server.

I see that the cassandra module depends on presto-main for testing. Do you know why that is? That seems like a bad idea:

> ```
> 
> <dependency>
>     <groupId>com.facebook.presto</groupId>
>     <artifactId>presto-main</artifactId>
>     <scope>test</scope>
> </dependency>
> ```

**Comment by kokosing** [comment]
This the way how we test connectors. Each connector tests starts up a light presto server within a custom (hard-wired) query runner (see `QueryRunner` in presto-main). 

Tests are not using `a full embedded Presto server`, but the `TestingPrestoServer` which is not using things like isolated classloader for each of the connectors.

Also it seems that shadowing guava in this driver is also not trivial as guava is part of its public API (see https://datastax-oss.atlassian.net/browse/JAVA-1328).

I think it should be part of #6910 to use somehow regular presto server in tests (or at least as much of it as possible), that way it should both version should behave in the same manner. However, this might complicate the build process. When connector libraries are downloaded with `io.airlift.resolver.ArtifactResolver` then to test connector we would need to install artifacts to maven local repo and the run tests:
```
mvn install -DskipTests -pl presto-cassandra
mvn test -pl presto-cassandra
# or alternatively
mvn test -pl presto-tests -Dtest=TestCassandraDistributedQueries
``` 

Maybe I should revert the upgrade for a while till we solve the #6910 ? Together with @ArturGajowy  we are thinking how to address this, so shortly (two weeks or so) we should produce some design-doc. What do you think?

BTW. datastax is not willing to update guava in the short-term future (see https://datastax-oss.atlassian.net/browse/JAVA-1328)

**Comment by martint** [comment]
> Tests are not using a full embedded Presto server, but the TestingPrestoServer which is not using things like isolated classloader for each of the connectors.

Oh, I think you're right. I was convinced that TestingPrestoServer was loading plugins in classloaders.

This seems very broken. I'm surprised anything works at all.

**Comment by kokosing** [comment]
> This seems very broken. I'm surprised anything works at all.

Me too. Dependency conflicts like this are very common, it is some kind of fortune we went so far with a current design.

**Comment by electrum** [comment]
I think the solution here is for us to shade the driver. We can namespace their version of Guava under `com.datastax.driver.guava` and use that package to reference them in the code that uses the driver.

**Comment by martint** [comment]
> I think the solution here is for us to shade the driver. We can namespace their version of Guava under com.datastax.driver.guava and use that package to reference them in the code that uses the driver.

It might be an ok workaround (depending on how the code uses Guava -- e.g., it may require adapting from the driver's Guava to Presto's Guava in cumbersome ways). It's not a scalable solution, though, and I'm sure we'll hit similar issues in the future for other libraries.

**Comment by kokosing** [comment]
The other option would be to use `PluginManager` to load `CassandraPlugin` from `target/classes` directory in `TestCassandraDistributedQueries`, so it should load its classes in separated and isolated classloader. 
That way it will behave similarly to what Presto does in production.

**Comment by kokosing** [comment]
Closing as #7310 is continuation of this.

**Pull request closed without merging**
