### PR TITLE
Reorganize docker images to use the same tag

### PR DESCRIPTION
**Pull request by sanjay990**

### CODE REVIEW

**Comment by sanjay990** [comment]
TD internal review is here: https://github.com/Teradata/presto/pull/354/commits/6cd51c1591c3532659cc13929cbaeb8e31b93650

**Comment by ebd2** [comment]
LGTM once Travis passes.

**Comment by sanjay990** [comment]
CC @martint

**Comment by electrum** [comment]
Merged, thanks!

**Pull request closed without merging**
