### PR TITLE
upgrade kudu version to 1.10.0

### PR DESCRIPTION
**Pull request by eskabetxe**
upgrade kudu version to last available

### CODE REVIEW

**Comment by highker** [comment]
@eskabetxe thanks for the upgrade. Could you squash the two commits into one?

**Comment by eskabetxe** [comment]
@highker done..

**Comment by highker** [comment]
@eskabetxe, the kudu tests failed; could you take a look?

**Comment by eskabetxe** [comment]
@highker should be fine now

**Comment by highker** [comment]
Seems quite a few testing scripts have been changed. I'm not an expert in docker experts would like to take a look? @ggreg, @mayankgarg1990, @caithagoras

**Comment by eskabetxe** [comment]
@highker any news?

**Comment by caithagoras** [comment]
Sorry, I don't have much context on this @highker

**Comment by caithagoras** [comment]
@highker should we merge this?

**Comment by Ennosigaeon** [comment]
Any updates on this pull request?

**Pull request closed without merging**
