### PR TITLE
Upgrade Esri to 2.2.4

### PR DESCRIPTION
**Pull request by jagill**
This includes several fixes, two that affect our users that we reported:
https://github.com/Esri/geometry-api-java/issues/247
https://github.com/Esri/geometry-api-java/issues/266

The second, in particular, caused workers to hang when they tried to
perform a union of two geometries.

Release notes:
https://github.com/Esri/geometry-api-java/releases/tag/v2.2.4

Test plan - (Please fill in how you tested your changes)
Added test case that reproduces the hang.  It does not hang anymore!

depended by https://github.com/facebookexternal/presto-facebook/pull/1182

```
== RELEASE NOTES ==

Geospatial Changes
* Upgrade Esri to [2.2.4](https://github.com/Esri/geometry-api-java/releases/tag/v2.2.4).  This includes two fixes for bug (https://github.com/Esri/geometry-api-java/issues/266 and https://github.com/Esri/geometry-api-java/issues/247) that were seen in production.
```

### CODE REVIEW

**Review by mbasmanova — APPROVED** [review]

**Comment by mbasmanova** [comment]
[test-facebook]

**Comment by jagill** [comment]
Upgrade changed some union results; I'll look into it and fix.

**Comment by jagill** [comment]
[test-facebook]

**Comment by jagill** [comment]
[test-facebook]

**Pull request merged**
