### PR TITLE
Optimize Metastore Code

### PR DESCRIPTION
**Pull request by konjac-h**
## Description

Optimize the Code by reducing unnecessary for loop. Reducing time complexity from O(2n) to O(n)

## Motivation and Context

See Description Above  

## Impact

Improve time complexity of Metastore 

## Test Plan

Simple Code Optimization.
Ran Verifier test to ensure nothing breaks 

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [x] CI passed.

== NO RELEASE NOTE ==

### CODE REVIEW

**Review by elharo — CHANGES_REQUESTED** [review]
This needs a test

**Comment by konjac-h** [comment]
@elharo Hey thanks for reviewing. I totally agree that we should have a regression test. I filed a separate task, [T188102626](https://www.internalfb.com/intern/tasks/?t=188102626), to track it but I don't think the test will be the blocker of this PR given that this is a really straightforward optimization which improves time complexity from O(2n) to O(n)

**Comment by steveburnett** [comment]
The checkbox for "If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines)." is checked but there is no release note. 

Please add a release note following the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines), even if it's only 
```
== NO RELEASE NOTE ==
```

**Comment by elharo** [comment]
Was this an outright bug (valid query failed, incorrect results reported) or a performance problem? If the former I would expect a test that exposes the bug to be written first before a fix is attempted. Otherwise it's likely to regress again even if it's manually verified this time

**Comment by jainxrohit** [comment]
@konjac-h can you please add in the PR description on what exactly was the issue?

**Review by jainxrohit — APPROVED** [review]

**Comment by rschlussel** [comment]
A few comments:
1. it would be great to add more details to the issue description about what kind of issue we were seeing (e.g latency regression when fetching xxx from the metastore, failure when xxx, etc.), what the root cause of the problem was, and how this change addresses it.
2. it's great that you provided queryids for Meta employees, but you should make sure to provide an example query or category of query for the general public outside of meta to be able to see what kind of queries were causing problems.
3. If you are fixing a bug you should add a test.  The fact that a fix was needed indicates that there was something not working properly in the code, and even if your fix is simple, adding a test ensures that we don't regress.

**Comment by konjac-h** [comment]
@rschlussel Sounds good. thanks for comments/review. I will fill out the information you mentioned.

**Comment by rschlussel** [comment]
> this is a really straightforward optimization improving the time complexity from O(2n) to O(n)

I'm surprised that iterating through a list 2x instead of 1x is enough to cause query failures.  That seems like a very sensitive threshold, and I would expect in that case we would have already been seeing similar failures for something using 2x as many partitions. Also the error for the failing query occurs the metastore, but it seems like the fix only touches the cache, and not even the method that was in the other stack trace. Are you sure this is the root cause of the issue?

**Comment by konjac-h** [comment]
@rschlussel These two PRs were originally suspected to be the problem so I optimized the only one that could do better. After this, we found another PR that actually contributes to the majority of the delay.

**Comment by rschlussel** [comment]
Got it, thanks for the explanation! So i would update the PR description and commit message, as this isn't really related to the metastore regression described above.  Instead i would describe it as an opportunistic code improvement that removes an extra iteration through a list.  You also shouldn't need to add a test then.

**Comment by konjac-h** [comment]
@rschlussel do you mind taking a look and stamp it when you get a chance? Thanks

**Review by rschlussel — APPROVED** [review]

**Pull request merged**
