### PR TITLE
Typo in bitwise_right_shift documentation (value, shift, digits)

### PR DESCRIPTION
**Pull request by Akanksha-kedia**

### CODE REVIEW

**Comment by Akanksha-kedia** [comment]
@tdcmeehan @steveburnett please review

**Review by skairali — APPROVED** [review]
looks good to me

**Comment by steveburnett** [comment]
I'll wait to do a docs review until @tdcmeehan's comment is addressed.

**Comment by Akanksha-kedia** [comment]
@tdcmeehan 
Screenshot 2023-10-02 at 6 59 39 PM
 if We see Bitwise function, two aruguments are passed and which is similar to bitwise_left_shift() and also if example in documentation you check its miss directing, i think this was the only typo mistake, kindly check and let me know.

**Comment by tdcmeehan** [comment]
My mistake, I got the before/after reversed. :)

**Review by tdcmeehan — APPROVED** [review]

**Comment by Akanksha-kedia** [comment]
@tdcmeehan please help to merge.

**Review by steveburnett — APPROVED** [review]
LGTM! (docs)

**Pull request merged**
