### PR TITLE
Fix BenchmarkPartitionedOutputOperator

### PR DESCRIPTION
**Pull request by yingsu00**
OptimizedPartitionedOutputFactory#createOutputOperator() now takes a new parameter `Optional<OutputPartitioning> outputPartitioning` and require it to be present. The change came from the "Refactor LocalExecutionPlanner" commit in https://github.com/prestodb/presto/pull/14099. However the call site in  BenchmarkPartitionedOutputOperator was passing in an empty `outputPartitioning`, which broke the benchmark with the following call stack:
```
java.lang.IllegalArgumentException: outputPartitioning is not present
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:141)
	at com.facebook.presto.operator.repartition.OptimizedPartitionedOutputOperator$OptimizedPartitionedOutputFactory.createOutputOperator(OptimizedPartitionedOutputOperator.java:286)
	at com.facebook.presto.operator.repartition.BenchmarkPartitionedOutputOperator$BenchmarkData.createOptimizedPartitionedOutputOperator(BenchmarkPartitionedOutputOperator.java:290)
	at com.facebook.presto.operator.repartition.BenchmarkPartitionedOutputOperator$BenchmarkData.access$000(BenchmarkPartitionedOutputOperator.java:127)
	at com.facebook.presto.operator.repartition.BenchmarkPartitionedOutputOperator.optimizedAddPage(BenchmarkPartitionedOutputOperator.java:119)
	at com.facebook.presto.operator.repartition.generated.BenchmarkPartitionedOutputOperator_optimizedAddPage_jmhTest.optimizedAddPage_avgt_jmhStub(BenchmarkPartitionedOutputOperator_optimizedAddPage_jmhTest.java:191)
	at com.facebook.presto.operator.repartition.generated.BenchmarkPartitionedOutputOperator_optimizedAddPage_jmhTest.optimizedAddPage_AverageTime(BenchmarkPartitionedOutputOperator_optimizedAddPage_jmhTest.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:453)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:437)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
This PR is to fix the problem.

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by mbasmanova** [comment]
@yingsu00 Would you describe the problem being fixed?

**Comment by wenleix** [comment]
We usually don't have commit with message like "BenchmarkPartitionedOutputOperator Nits". Either squash the two commits, or maybe rename it to "Minor fix to BenchmarkPartitionedOutputOperator"? :)

**Comment by yingsu00** [comment]
> "Minor fix to BenchmarkPartitionedOutputOperator"

@wenleix  Sure I renamed it to "Minor fix to BenchmarkPartitionedOutputOperator" as you suggested

**Comment by yingsu00** [comment]
> @yingsu00 Would you describe the problem being fixed?

@mbasmanova I updated the PR comment message and commit message to explain what the problem is. Let me know if you still have questions. Thanks!

**Comment by yingsu00** [comment]
@mbasmanova Thanks for the suggestion. I added the test methods in the new commit `Add test methods to BenchmarkPartitionedOutputOperator`.

**Comment by mbasmanova** [comment]
@yingsu00 Thank you.

**Pull request merged**
