### PR TITLE
Revert "[native] Advance Velox and apply TaskState changes"

### PR DESCRIPTION
**Pull request by zuyu**
This reverts commit 0ee4687d038c2f4dd8b513a1375a39ffd8bda1eb.

Let's advance velox again after https://github.com/facebookincubator/velox/pull/11681 is merged.

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by yingsu00 — COMMENTED** [review]
@zuyu https://github.com/facebookincubator/velox/pull/11681 has been merged. Do we still need this PR?

btw PR title "Revert "[native] Advance Velox and apply TaskState changes" 
-->
"[native] Revert "[native] Advance Velox and apply TaskState changes"

**Review by yingsu00 — COMMENTED** [review]
Can you please add meaningful commit and PR message to explain why this needs to be done? Thanks!

**Comment by zuyu** [comment]
This PR is needed as a transaction to revert the changes of TaskState in Prestissimo. After merging this PR, we would create a new PR to advance Velox again, as if TaskState changes never exist before.

Regarding PR title: like https://github.com/prestodb/presto/pull/23959 and https://github.com/prestodb/presto/pull/23566, the title are just generated by `git revert <commit>`. And I don't think adding additional `[native]` is needed, as the original commit already contains it.

**Comment by aditi-pandit** [comment]
@zuyu : Why not advance Velox again as https://github.com/facebookincubator/velox/pull/11681 is merged now, and also fix Prestissimo code side by side for it ? The revert makes timelines confusing.

**Review by aditi-pandit — APPROVED** [review]

**Pull request merged**
