### PR TITLE
Add google sheet connector document to connector list

### PR DESCRIPTION
**Pull request by agrawalreetika**
## Description
Add google sheet connector document to connector list

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by backkem** [comment]
I wonder if it's also useful to ship this connector in the presto-server package. Are there rules around which plugins are included and which aren't?

**Review by backkem — APPROVED** [review]

**Comment by tdcmeehan** [comment]
@backkem there's no rules, however our overall package is now quite large and it sometimes times out when publishing the release artifacts, so we need to be judicious on what we add.

**Review by tdcmeehan — APPROVED** [review]
Thank you!

**Review by steveburnett — APPROVED** [review]
LGTM! (docs)

**Pull request merged**
