### PR TITLE
Add support for limit param to DistributedQueryResource

### PR DESCRIPTION
**Pull request by singcha**
Test plan - 
1. Testing by running tests with & without limit param
2. Added automated test for same
3. Ran test in a loop 30 times to ensure flakiness is no longer present

```
== RELEASE NOTES ==

General Changes
Adding limit param support for /v1/query endpoint for Multi coordinator

### CODE REVIEW

**Review by swapsmagic — APPROVED** [review]
Looks good to me. Squash it into single commit and good to merge.

**Comment by swapsmagic** [comment]
Looping in @tdcmeehan  who can help merging this PR once all it green.

**Comment by singcha** [comment]
> Looks good to me. Squash it into single commit and good to merge.

Done!

**Comment by singcha** [comment]
@tdcmeehan - Can you please help with merge? Thanks!

**Review by tdcmeehan — APPROVED** [review]

**Pull request merged**
