### PR TITLE
[native] Use Velox::TypeParser instead of Antlr and remove Antlr

### PR DESCRIPTION
**Pull request by majetideepak**
## Description
Use Velox::TypeParser instead of Antlr.
Remove Antlr dependency.

## Motivation and Context
Resolves https://github.com/prestodb/presto/issues/21334

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [x] CI passed.

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by majetideepak** [comment]
@kevinwilfong can you share your feedback? Thanks.

**Comment by kevinwilfong** [comment]
Thanks! This looks great, it makes it more consistent with the rest of the code, and gets rid of that annoying issue with ANTLR messing with preprocessor identifiers.  Also, thank you for preserving the caching logic.

cc: @xiaoxmeng  @mbasmanova for a review, the change looks good to me, but I'm not a code owner yet

**Comment by kevinwilfong** [comment]
@majetideepak  the broken linux-*-e2e-tests look like they're due to a parsing error

**Comment by majetideepak** [comment]
> @majetideepak the broken linux-*-e2e-tests look like they're due to a parsing error

@kevinwilfong The parsing error was fixed in Velox. CI now passed with rebasing.

**Comment by majetideepak** [comment]
@mbasmanova, @xiaoxmeng can you also review? Thanks.

**Review by mbasmanova — APPROVED** [review]
Very nice. Thank you, Deepak.

**Pull request merged**
