### PR TITLE
ignore non-existent partition location

### PR DESCRIPTION
**Pull request by nazgul33**
hive and impala simply ignore partitions with non-existent hdfs location,
but presto throws an exception in this case.

test scenario:
1. create a partition
2. hdfs dfs -rmdir "location of created partition"
3. run a select references that partition
4. you'll see a "Partition location does not exist" exception.

### CODE REVIEW

**Comment by cberner** [comment]
I think there should be a config flag for this. It seems scary to silently skip missing data

**Comment by nazgul33** [comment]
OMG should I kill this PR and do a new one?
I just rebased on master yesterday.

anyway, I've added a switch "hive:ignore-missing-data" and a test case.
ran the test case itself, and checked again on my local hive installation.

thanks.

**Comment by nazgul33** [comment]
i found that i lost a few lines of code in the process of rebasing. fixed and simplified test code.

**Comment by nazgul33** [comment]
I guess there had been a network problem with the build system.
can you retrigger the failed job @cberner ?

**Comment by cberner** [comment]
Yep, will do

**Comment by cberner** [comment]
Is deleting the data directly from HDFS part of your normal operations? Having a missing partition location would seem to indicate data corruption to me, so I'm not sure a flag to work around that is a good idea.

**Comment by nazgul33** [comment]
there's a case where
- old logics delete hdfs files directly and regularly
- cleanup logic deletes hive partitions later

this happens with old mr jobs.

**Comment by cberner** [comment]
Is that something you consider best practice? Our approach is to always delete from the metastore, which then drops the data at the appropriate time

**Comment by nazgul33** [comment]
i know this is not a best practice,
but i cant fix all the corporate logic by myself.

like cobol is still used in a lot of companies..

if you feel this is not a feature for presto
then dont merge this. i will just keep this patch by myself and use it in this company only.

한동훈 (Steven Han)


2016. 5. 3. 01:02 Christopher Berner <notifications@github.com<mailto:notifications@github.com>> 작성:


Is that something you consider best practice? Our approach is to always delete from the metastore, which then drops the data at the appropriate time

**Comment by cberner** [comment]
I see. Ya, I don't think this is general enough to merge into upstream

**Pull request closed without merging**
