### PR TITLE
Add a test for adding a new column

### PR DESCRIPTION
**Pull request by mayankgarg1990**
Test plan - This PR adds a test and will ensure that it succeeds

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by mayankgarg1990** [comment]
@rschlussel - it will be great if you can help with reviewing this PR . thanks :)

**Review by rschlussel — APPROVED** [review]

**Comment by rschlussel** [comment]
Actually, can you also add a test for drop column?

**Comment by mayankgarg1990** [comment]
@rschlussel  - I have made your requested changes and the tests are also green. It will be great if you can merge the PR if there are no more comments. Thanks !

**Review by rschlussel — APPROVED** [review]
Thanks, looks great!

**Pull request merged**
