### PR TITLE
Using canonical host name when updating kerberos principal name

### PR DESCRIPTION
**Pull request by ywskycn**
Changing getHostName() to getCanonicalHostName() to make kerberos work when we replace "_HOST" in principal name.

### CODE REVIEW

**Comment by cawallin** [comment]
Looks like this PR is a duplicate of https://github.com/prestodb/presto/pull/6978, % getCanonicalHostName() for the host

**Comment by ywskycn** [comment]
@cawallin yes, the first change is covered by #6978 , but we still the 2nd change (getCanonicalHostName() one).

**Comment by cawallin** [comment]
@ywskycn can you comment on that PR, and then we can update that one and close this one?

**Comment by cawallin** [comment]
Actually, if you don't mind, I will go ahead and cherry-pick your getCanonicalHostName() change to that other PR. That one'll have to go in first anyway, and has testing for _HOST.

**Comment by ywskycn** [comment]
@cawallin sure, pls go ahead

**Comment by cawallin** [comment]
Merged to https://github.com/prestodb/presto/pull/6978, thanks for the fixup!

**Pull request closed without merging**
