### PR TITLE
Basic spill functionality for joins and order by

### PR DESCRIPTION
**Pull request by amccurry**
This patch adds basic spill to the hash join, parallel hash join, and order by operators.  The basic idea is that when data is buffered for a given operation the PagesIndex is used.  As the blocks are added to PagesIndex the blocks are converted to a spilled block.  The spill blocks are basically Slice only backed versions of their normal heap based versions.  However the Slices are converted to being memory mapped ByteBuffers and relocated outside the heap (and spilled to disk as needed).

There is another patch required for this one to work (https://github.com/amccurry/slice/commit/8915897d3b8f42d49ed1445b303c6e741d01e18c#diff-3d0e1010e4278b057223ac8f18b3d0d4L114) that I can create another pull request for that project if needed.  The only change to the airlift slice project is that if the ByteBuffer is a direct buffer and is a memory mapped buffer is has 0 capacity in the constructor, which is really just the retained size in bytes for the slice.

The current state of the patch:

Spilled joins and order bys work, however many tests need to be created.  Also there are areas where optimizations could be done and likely some of the lifecycle hooks for the spill context will need to modified.  I took a best guess as to where they should fit into the project.  Also there are incomplete implementations of the spill blocks and some of the supporting data structures.

I know that it is likely that many changes to what I have created that will need to happen before this pull request will be approved.  I am happy to work with the community to make the needed changes.

Let me know how I can help.

Aaron

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by martint** [comment]
There's another ongoing effort to add support for spilling: https://github.com/prestodb/presto/pull/5142

**Comment by amccurry** [comment]
I saw that issue, but it looked like the scope of that issue was to spill group by operations.  I needed this spill functionality on joins and order bys for another project.  So I pieced together a functional spill capability on an older version of Presto.  This is a bit of a rewrite of that same functionality and I thought I would try to offer to the project.  I realize that my implementation will likely need to change to fit into the presto project.

**Comment by facebook-github-bot-8** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by pnowojski** [comment]
Please correct me if I'm wrong, but it seems like you have replaced blocks and arrays by `MappedByteBuffer` to some file, right? Such approach indeed might work and is cheap to implement, but what about performance of such spilling? In Presto joins and aggregations are implemented using hash maps, thus with your implementation they would produce lots of tiny random writes and reads to the underlying file system. Even assuming that most of the data fits in file system cache (and in such case why do you need spilling? why not increasing JVM memory?), I would expect very significant performance overhead on every `LongArray`/`IntArray`/`...` access (even if there is lots of free memory in the cluster). 

For joins we were planning to add something like this https://cwiki.apache.org/confluence/display/Hive/Hybrid+Hybrid+Grace+Hash+Join,+v1.0 in a near future.

For sorting, disk based merge sort would be better BUT first of all we should implement distributed in memory merge sort. Currently `OrderByOperator` is executed only on single node and it could be distributed on more nodes.

**Comment by amccurry** [comment]
- Please correct me if I'm wrong, but it seems like you have replaced
blocks and arrays by MappedByteBuffer to some file, right?

Correct.

- Such approach indeed might work and is cheap to implement, but what about
performance of such spilling?

I assume that it would be costly to spill when linux unloads the memory to
disk.  I would likely only recommend this setup with SSDs.

- In Presto joins and aggregations are implemented using hash maps, thus
with your implementation they would produce lots of tiny random writes and
reads to the underlying file system.

Due to the way the join works there are a lot of tiny writes in the address
list in the PagesIndex during the join calculation, however the block data
is written sequentially as the Pages are added to the PagesIndex.  As for
reading yes is it lot of small random reads.

- Even assuming that most of the data fits in file system cache (and in
such case why do you need spilling? why not increasing JVM memory?), I
would expect very significant performance overhead on every LongArray/
IntArray/... access (even if there is lots of free memory in the cluster).

True, I as I said earlier in this reply I would only use this with SSDs.

Overall I realize that this is not an ideal solution and for spill to work
effectively the operators such as order by and join would need to be
rewritten (parallel for order by and Hybrid Hybrid Grace Hash Join for the
join operator or something similar).  However in the mean time this is a
solution that will allow much larger joins and sorts to be completed
assuming you have the correct hardware.

Is there any sort of estimate of when the current spill effort will be in a
release, experimental or not?

Thanks!

Aaron

**Comment by pnowojski** [comment]
Even for SSDs this can have significant unnecessary performance penalty.

Spill for aggregation will be in Teradata's Q3 release of the Presto and probably joins will also be there in some basic form (we will start working on joins in the next couple of weeks). As for official Facebook release, I don't know.

**Comment by dain** [comment]
We are going to focus on the version in #5142.

**Pull request closed without merging**
