### PR TITLE
Fix Aria case of constant false filter.

### PR DESCRIPTION
**Pull request by oerling**

### CODE REVIEW

**Comment by mbasmanova** [comment]
@oerling Orri, when does this happen? Shouldn't the optimizer catch this case and convert TableScan into empty Values?

Style checks are failing:

```
[INFO] --- maven-checkstyle-plugin:3.0.0:check (checkstyle) @ presto-main ---
[INFO] There is 1 error reported by Checkstyle 8.16 with checkstyle/airbase-checks.xml ruleset.
[ERROR] src/main/java/com/facebook/presto/operator/ScanFilterAndProjectOperator.java:[316] (indentation) Indentation: 'method def modifier' has incorrect indentation level 0, expected level should be 4.
```

**Comment by oerling** [comment]
This happens in select … where null;

 

This is in one of the hive tests and readily reproducible with any table.

 

 

BTW, the …SSmoke… map cases work.

**Comment by mbasmanova** [comment]
@oerling 

> This happens in select … where null;

I see. I think a proper fix it to have the optimizer detect allways-false filter and convert scan node into empty values node.

**Comment by oerling** [comment]
You can have arbitrary expressions that are independent of columns and that still get put into filters of a scan. To know if they are always false you have to evaluate them. And they could be nondeterministic, like now() < <date>. This will not work unless you can evaluate these. Can constant folding evaluate every single such case? If not, you need to make an executable filter and actually run it.

**Comment by mbasmanova** [comment]
@oerling 

> You can have arbitrary expressions that are independent of columns and that still get put into filters of a scan. To know if they are always false you have to evaluate them. And they could be nondeterministic, like now() < <date>. This will not work unless you can evaluate these. 

This is a good point. Thanks for explaining. This issue doesn't seem to be aria-specific, hence, a generic solution is preferable. Would you move the code that determines whether the filter is always false outside of `setupAria`? I would even go further and submit a PR against master.

However, what about non-deterministic filters? The logic in this PR doesn't seem to handle these.

**Comment by oerling** [comment]
This is independent of Aria in concept. The specific code is however different because Aria has a list of filters and baseline has exactly one.  The Aria case is therefore as presented but there can be a similar one for master.

**Comment by mbasmanova** [comment]
Aria scan has been moved into aria-scan-research branch. Please, resubmit against that branch.

**Pull request closed without merging**
