### PR TITLE
WIP: do not re-shuffle when doing GROUP BY on constant

### PR DESCRIPTION
**Pull request by kokosing**
WIP: do not re-shuffle when doing GROUP BY on constant

### CODE REVIEW

**Comment by kokosing** [comment]
I am sharing this early pull request as I want to validate if my idea is correct. What I did here is that I do not partition when all the partition requirement symbols refer to constant value. 

Although I think the better idea would be to just remove the symbol from partition requirements which refers to constant value.

**Comment by kokosing** [comment]
```
presto:tiny> explain SELECT 123, sum(totalprice) FROM orders group by 1;
                                                     Query Plan
---------------------------------------------------------------------------------------------------------------------
 - Output[_col0, _col1] => [expr:integer, sum:double]
         _col0 := expr
         _col1 := sum
     - Project => [expr:integer, sum:double]
         - Aggregate(FINAL)[expr][$hashvalue] => [expr:integer, $hashvalue:bigint, sum:double]
                 sum := "sum"("sum_9")
             - RemoteExchange[GATHER] => expr:integer, sum_9:double, $hashvalue:bigint
                 - Aggregate(PARTIAL)[expr][$hashvalue_10] => [expr:integer, $hashvalue_10:bigint, sum_9:double]
                         sum_9 := "sum"("totalprice")
                     - Project => [totalprice:double, expr:integer, $hashvalue_10:bigint]
                             $hashvalue_10 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("expr"), 0))
                         - Project => [totalprice:double, expr:integer]
                                 expr := 123
                             - TableScan[tpch:tpch:orders:sf0.01, originalConstraint = true] => [totalprice:double]
                                     totalprice := tpch:totalprice

(1 row)
```

**Comment by kokosing** [comment]
This fixes #6898

**Comment by electrum** [comment]
I'm not sure you can simply remove the symbol, since all the data needs to be shuffled to a single node. (but I'm not very familiar with the planner so I might be misunderstanding what you're saying)

**Comment by kokosing** [comment]
I won't have time to work on this in the near future, so I am closing this.

**Pull request closed without merging**
