### PR TITLE
Include presto-clickhosue in presto-tar plugin

### LINKED ISSUE #18217: Clickhouse plugin should be packed in tarball after 0.273
In version 0.273, a new Presto connector for Clickhouse was added as mentioned in [this relase note](https://prestodb.io/docs/current/release/release-0.273.html). 

However, the provided tarball did not include clickhouse connector in plugin directory by default. This connector was well documented in release note and connector docs, but when implemented，coordinator failed to start due to errors below：
`2022-08-23T19:17:46.901+0800	ERROR	main	com.facebook.presto.server.PrestoServer	No factory for connector clickhouse
java.lang.IllegalArgumentException: No factory for connector clickhouse
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:216)`

Just suggest presto-clickhouse connector to be packed into official relase tarballs so that it won't confuse end users. Thanks~

### PR DESCRIPTION
**Pull request by agrawalreetika**
Fixes #18217 

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by ajaygeorge — APPROVED** [review]
LGTM

**Comment by ajaygeorge** [comment]
@agrawalreetika  There is a small typo in the commit message. 
clickhosue -> clickhouse

**Comment by agrawalreetika** [comment]
> @agrawalreetika There is a small typo in the commit message. clickhosue -> clickhouse

@ajaygeorge Corrected

**Comment by agrawalreetika** [comment]
@tdcmeehan Can we merge this?

**Review by tdcmeehan — APPROVED** [review]

**Pull request merged**
