### PR TITLE
Bing tile coordinate accessors

### PR DESCRIPTION
**Pull request by jagill**
Add ST_XMax, ST_XMin, ST_YMax, ST_YMin, ST_Centroid for Bing Tiles.

Bing Tiles are canonically convertible to a geometry, which is what `bing_tile_polygon` does.  Users commonly convert to the polygon just get these properties.  These allow the users to access these properties directly.

I'm open to not overloading the ISO-specified ST_ functions, the other option would be adding more functions just for this, which seems less user-friendly.

```
== RELEASE NOTES ==

General Changes
* Add ST_XMax, ST_XMin, ST_YMax, ST_YMin, ST_Centroid for Bing Tiles.
```

### CODE REVIEW

**Comment by jagill** [comment]
cc @mbasmanova

**Comment by jagill** [comment]
cc @aweisberg

**Comment by mbasmanova** [comment]
@jagill Can this be achieved using new SQL functions? CC: @rongrong

**Comment by jagill** [comment]
@mbasmanova It's worth trying!  As these are currently written, they are more efficient than converting to a polygon (since calculating x/y min/max is quick), and the centroid is potentially slightly more accurate (averaging x min/max has fewer numerical losses than the centroid of an arbitrary 4-polygon), but that might not justify the additional code complexity.

**Comment by mbasmanova** [comment]
We'd like to keep ST_* prefix for functions that comply with the standard. How about using bing_tile_* names for these new functions? 

- bing_tile_xmax
- bing_tile_xmin
- bing_tile_ymax
- bing_tile_ymin
- bing_tile_centroid

**Pull request closed without merging**
