### PR TITLE
Introduced protections against predictable RNG abuse

### PR DESCRIPTION
**Pull request by zcarroll4**
## Description
This change replaces all new instances of `java.util.Random` with the marginally slower, but much more secure `java.security.SecureRandom`.

We have to work pretty hard to get computers to generate genuinely unguessable random bits. The `java.util.Random` type uses a method of pseudo-random number generation that unfortunately emits fairly predictable numbers.

If the numbers it emits are predictable, then it's obviously not safe to use in cryptographic operations, file name creation, token construction, password generation, and anything else that's related to security. In fact, it may affect security even if it's not directly obvious.

Switching to a more secure version is simple and our changes all look something like this:

```diff
- Random r = new Random();
+ Random r = new java.security.SecureRandom();
```

<details>
  <summary>More reading</summary>

  * [https://owasp.org/www-community/vulnerabilities/Insecure_Randomness](https://owasp.org/www-community/vulnerabilities/Insecure_Randomness)
  * [https://metebalci.com/blog/everything-about-javas-securerandom/](https://metebalci.com/blog/everything-about-javas-securerandom/)
  * [https://cwe.mitre.org/data/definitions/330.html](https://cwe.mitre.org/data/definitions/330.html)
</details>

Powered by: [pixeebot](https://docs.pixee.ai/) (codemod ID: [pixee:java/secure-random](https://docs.pixee.ai/codemods/java/pixee_java_secure-random)) 

## Motivation and Context

More secure solution.

## Impact

May be poorer performance. 

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [x] CI passed.

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by yhwang** [comment]
Could you share why you closed the PR? Because of the performance penalty or is it generated by a bot?

**Comment by zcarroll4** [comment]
@yhwang Yes, Pixee is an automated Security Scanning bot that helps teams finding vulnerabilities in their code. I closed this pr for now because I want to make sure the changes are valuable enough to consider. I will circle back in the future. For security findings such as the one above, do you prefer we reach out to your team directly before opening the pr?

**Comment by yhwang** [comment]
You can reach out the the Presto community on the Presto Slack channel (join [here](https://communityinviter.com/apps/prestodb/prestodb)).  You can also create an issue to describe the problem you encounter or a feature you'd like to add. Then create a PR to solve the issue.

**Comment by zcarroll4** [comment]
@yhwang Sounds good, will do moving forward!

Thanks!

**Pull request closed without merging**
