### PR TITLE
Update Iceberg to 0.14.0

### PR DESCRIPTION
**Pull request by nastra**
This PR updates the `presto-iceberg` connector to the latest Iceberg version 0.14.0 ([Release Notes](https://iceberg.apache.org/releases/#0140-release)).
Additionally, it updates a few places (tests around namespace/branch visibility and table properties) related to the `NessieCatalog` that have been fixed/improved in Iceberg 0.14.0.

```
== RELEASE NOTES ==

Iceberg Changes
* Update Iceberg to 0.14.0
```

### CODE REVIEW

**Comment by nastra** [comment]
The one failing test seems to be not related to the changes proposed here

**Review by ChunxuTang — COMMENTED** [review]
LGTM.
Hi @nastra, thanks a lot for the contribution! Would you mind editing the description of this PR, following the pull request template? (https://github.com/prestodb/presto/blob/master/pull_request_template.md)

**Comment by ChunxuTang** [comment]
For the failed tests, I would suggest rerunning them by running `git push --force` as we couldn't merge your code until all tests have passed.

**Comment by nastra** [comment]
@ChunxuTang I updated the PR description and tests are passing now. Thanks for your review!

**Review by ChunxuTang — APPROVED** [review]
LGTM! @nastra 
Hi @beinan, would you also like to take a review of this PR?

**Review by beinan — APPROVED** [review]
lgtm

**Pull request merged**
