### PR TITLE
Bump tempto version from 1.27 to 1.30

### PR DESCRIPTION
**Pull request by kokosing**
Bump tempto version from 1.27 to 1.30

### CODE REVIEW

**Comment by electrum** [comment]
There are a bunch of seemingly legitimate product test failures:
```
com.teradata.tempto.query.QueryExecutionException: java.sql.SQLException: Error while compiling statement: FAILED: ParseException line 1:34 character '?' not supported here

**Comment by kokosing** [comment]
@electrum There was a simple bug in tempto, now it should be ok. Thanks for looking into that.

**Comment by kokosing** [comment]
Urgh... there is still one failure. Let me check if it is legit.

**Comment by kokosing** [comment]
@electrum this time it should be ok

**Pull request merged**
