### PR TITLE
 Add memory bin packing support for local dispatcher

### PR DESCRIPTION
**Pull request by raghavsethi**
Depends on local dispatcher. Only last commit is for review.

### CODE REVIEW

**Comment by sopel39** [comment]
What is local dispatcher and why it needs bin packing?

**Comment by wenleix** [comment]
@raghavsethi : What's the status of this PR? Thanks!

**Comment by raghavsethi** [comment]
I'm working with Dain on a private dispatcher branch that must land before this, and it is taking far longer than expected.

**Comment by raghavsethi** [comment]
The last commit is a work-in-progress meant to be applied after https://github.com/prestodb/presto/pull/12801 and should function as a reference for a future implementor. cc @tdcmeehan @wenleix

**Pull request closed without merging**
