### PR TITLE
Add release notes for 0.231.1

### PR DESCRIPTION
**Pull request by caithagoras**
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by rongrong** [comment]
We decided to do official releases for fixes now?

**Comment by caithagoras** [comment]
For a known correctness with a fix that have minimum area of impact, we should hoxfix it.
This is part of our release process, and our community guideline suggest we just need one thumb up and no thumb down from the committers.

**Comment by caithagoras** [comment]
Test just passed, but I added a small change: s/timestamp/timestamps

**Comment by wenleix** [comment]
Merged #14060. Thanks for the contribution!

**Pull request merged**
