### PR TITLE
Add logging of all presto queries

### PR DESCRIPTION
**Pull request by billonahill**
Adds logging of all queries executed, their end state, user and duration. We'd like to be able to post-process these logs and track the number of successful and failed queries over time. This could certainly be done more fancy with pluggable logging modules or a new query.log file, but this seems like a reasonable first pass.

Format (tab-delimited):
```QUERY_ID STATE ERROR_TYPE ERROR_CODE USER ELAPSED_TIME QUERY```

Executing this in the shell:
```
presto> set session
     -> invalid.property.key='foo';
...
presto> show catalogs;
...
```
Produces this in ```server.log```:
```
2016-02-24T14:44:10.398-0800	INFO	query-execution-1	com.facebook.presto.execution.SqlQueryManager	Query complete	20160224_224410_00001_rjae5	FAILED	USER_ERROR	SYNTAX_ERROR:1	billg	594.74us	set session invalid.property.key='foo'
2016-02-24T14:44:25.726-0800	INFO	query-execution-2	com.facebook.presto.execution.SqlQueryManager	Query complete	20160224_224424_00002_rjae5	FINISHED	null	null	billg	811.80ms	show catalogs
```

### CODE REVIEW

**Comment by billonahill** [comment]
Ping. Any thoughts about this patch? We've been running with it for a while and it's been helpful.

**Comment by maciejgrzybek** [comment]
I am not convinced by having such a log on `INFO` level.
What is more, logging a SQL text may be a security issue in some cases.

Maybe it would be enough to differentiate `INFO` and `DEBUG` information - provide all of the information (minus SQL text) on `INFO` and SQL text on `DEBUG` only?

How does it affect performance?

**Comment by billonahill** [comment]
The debug logging is pretty noisy and typically not enabled in a production system. This change logs a single line for every query so it's minimal and has no effect on performance.

What if we instead provided an config option to disable it for those with security concerns?

**Comment by nezihyigitbasi** [comment]
@billonahill Seems like #2917 is related.

**Comment by maciejgrzybek** [comment]
@billonahill +1 for config option but it should be not displayed by default (security by default).

**Comment by billonahill** [comment]
Updated to have a flag to enable query logging.

@nezihyigitbasi thanks for the pointer to PR #2917. This ticket could be a precursor to that one, where this adds an option to enable logging and PR #2917 makes the format extensible. Or vice-versa but we should move forward with one of these.

**Comment by billonahill** [comment]
Related to PR #4897

**Comment by martint** [comment]
Closing this, since it will be covered by the event listener plugin support @raghavsethi is working on (https://github.com/prestodb/presto/issues/5254)

**Pull request closed without merging**
