### PR TITLE
[native] Add e2e tests for to_iee754_64 Presto scalar function

### PR DESCRIPTION
**Pull request by pdabre12**
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by aditi-pandit — APPROVED** [review]

**Comment by pdabre12** [comment]
The query `SELECT to_ieee754_64(totalprice) FROM orders` is failing.

**Review by aditi-pandit — CHANGES_REQUESTED** [review]
@pdabre12 : Please investigate the failure.

**Comment by pdabre12** [comment]
@aditi-pandit  It failed probably because the Velox version was not advanced , I tried locally , works fine for me now. Is there a way I can re-run the tests or is it triggered by a commit only?

**Comment by aditi-pandit** [comment]
> @aditi-pandit It failed probably because the Velox version was not advanced , I tried locally , works fine for me now. Is there a way I can re-run the tests or is it triggered by a commit only?

@pdabre12 : Ah I see. The other ones involve constants so they got evaluated at the co-ordinator itself. Please rebase and push your code. It will trigger the tests.

**Comment by pdabre12** [comment]
@aditi-pandit  Sorry I messed up the PR, opening a new one for this soon.

**Pull request closed without merging**
