### PR TITLE
Fix NaN value for double and float partition columns

### PR DESCRIPTION
**Pull request by gupteaj**
Cherry-pick of https://github.com/trinodb/trino/pull/15727 (https://github.com/trinodb/trino/pull/15727)

Co-authored-by: ebyhr <ebyhry@gmail.com>

issue - https://github.com/prestodb/presto/issues/20366
Test plan - (Please fill in how you tested your changes)

create table test.part_double (c1 varchar, c2 double) with (partitioning =array['c2']);
insert into test.part_double values ('fix', real 'NaN');
insert into test.part_double values ('fix', double 'NaN');
presto:test> select * from part_double where c1 = 'fix';
 c1  | c2  
-----+-----
 fix | NaN 
 fix | NaN 
(2 rows)

Please make sure your submission complies with our [Development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [Formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), and [Commit Message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests) guidelines. Don't forget to follow our [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution) for any code copied from other projects.

Fill in the release notes towards the bottom of the PR description.
See [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) for details.

```
== RELEASE NOTES ==

Iceberg Changes 

* Fix incorrect results when reading or writing `NaN` with `real` or `double` types on partitioned columns.

```

### CODE REVIEW

**Review by imjalpreet — CHANGES_REQUESTED** [review]
@gupteaj thanks for your contribution. Can you please add a test as well?

**Review by s-akhtar-baig — APPROVED** [review]
Changes look good to me!

**Review by brajeshkpandey — APPROVED** [review]
+1

**Comment by gupteaj** [comment]
> @gupteaj thanks for your contribution. Can you please add a test as well?

@imjalpreet  Test added, please review.

**Comment by imjalpreet** [comment]
@gupteaj Thanks for adding the test, before I submit my review, I can see some test failures, can you please rebase on the latest master and push again?

Also, in the commit message, can you please add the email to the Co-authored-by tag as mentioned here: https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#example-commit-message

**Comment by gupteaj** [comment]
> @gupteaj Thanks for adding the test, before I submit my review, I can see some test failures, can you please rebase on the latest master and push again?
> 
> Also, in the commit message, can you please add the email to the Co-authored-by tag as mentioned here: https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#example-commit-message

@imjalpreet , tests have passed after rebase.

**Comment by imjalpreet** [comment]
@gupteaj thanks, can you please use rebase to add your commit on top of master? Currently, its showing multiple commits as part of this PR.

**Comment by gupteaj** [comment]
> @gupteaj thanks, can you please use rebase to add your commit on top of master? Currently, its showing multiple commits as part of this PR due to the merge commit. Also, please squash the commits into one.

@imjalpreet , it looks I made mistake in squash command. I will delete this PR and create a new.

**Comment by gupteaj** [comment]
it looks I made mistake in squash command. I will delete this PR and create a new.

**Pull request closed without merging**
