### PR TITLE
Fix potential incorrect initialization of Hadoop FileSystem of iceberg connector

### PR DESCRIPTION
**Pull request by liupan664021**
The fix is discussed in #16958

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by ChunxuTang — APPROVED** [review]
@liupan664021 
Wow! Thanks for your nice catch!

**Review by beinan — CHANGES_REQUESTED** [review]
The code change looks good to me except the first line of the commit message is too long  (github will wrap it).

Also, could you put a release note section in your PR.  It could be "no release note" as below :)
```
== NO RELEASE NOTE ==
```

**Comment by liupan664021** [comment]
@beinan @ChunxuTang Thanks for reviewing! I've updated the commit message and the release note section :)

**Review by beinan — APPROVED** [review]

**Review by DjSeMARM — COMMENTED** [review]
- [ ]

**Pull request merged**
