### PR TITLE
Fix NPE when a FlatMap column is all empty

### PR DESCRIPTION
**Pull request by bhhari**
In few cases where the all the map values are empty the encoding is not present in the stripe footer causing NPE.

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by mbasmanova — APPROVED** [review]
LGTM. Please, add a test.

**Comment by zzhao0** [comment]
Thanks for making the fix!

**Comment by bhhari** [comment]
> LGTM. Please, add a test.

As presto does not write flatmap, I tried to generate a table using spark but it always writes a direct encoding. Need to figure out when the flatmap encoding is used. @zzhao0 any ideas here in generating a test file?

**Comment by kaikalur** [comment]
Hmm, are we sure this will cause problems elsewhere in the code? What value will you use for that field - null or map()? It's not clear. So yeah tests will be good, but may be we shouldn't even fix this?

**Comment by kaikalur** [comment]
Definitely add a session property (default to false) if we want to merge it.

**Review by yingsu00 — APPROVED** [review]

**Comment by bhhari** [comment]
> Hmm, are we sure this will not cause problems elsewhere in the code? What value will you use for that field - null or map()? It's not clear. So yeah tests will be good, but may be we shouldn't even fix this? Instead maybe just assert that it can't be null?

Incase of nulls encoding is present. @zzhao0

**Comment by bhhari** [comment]
> Definitely add a session property (default to false) if we want to merge it.

we don't need a session property here. this check is protecting against encoding not present similar to additionalSequenceEncodings is empty

**Pull request merged**
