### PR TITLE
Make check for existing column in AddColumnTask case insensitive

### PR DESCRIPTION
**Pull request by maciejgrzybek**
This fixes https://github.com/facebook/presto/issues/4580

### CODE REVIEW

**Comment by maciejgrzybek** [comment]
Rebased on master and resolved conflicts.

**Comment by maciejgrzybek** [comment]
Rebased on master and resolved conflicts + adjusted Hive configuration for product tests.

**Comment by maciejgrzybek** [comment]
Already fixed by @electrum in 394637c851f613d1b8510074bb63b5e426f3fece
@electrum: What was wrong with this PR that you implemented this by yourself even though this PR was already assigned to you (for review)? I was rebasing this for 1.5 month on every conflicts against master.
Fortunately this was a small change so there is not so much to regret but it's silly we do the same work.
@electrum: you didn't update `AlterTableTests` after your change. I updated it in a separate PR (https://github.com/prestodb/presto/pull/4985).

**Comment by electrum** [comment]
@maciejgrzybek I apologize, I didn't see this PR (unfortunately, GitHub doesn't send notifications on assignment). I'll review and merge the tests. Sorry.

**Pull request closed without merging**
