### PR TITLE
Pushdown fields to update column handle and implement Parquet nested fields pruning

### PR DESCRIPTION
**Pull request by Yaliang**
1. Add `fields` variable to `Symbol` and `SymbolReference` so that they are aware of referred nested fields.
2. Dereference expressions give the hints of possible nested fields of the Symbols, push down those nested fields until the Symbols in TableScan. Right now, there are three rules:

   *  `PruneFilterColumnFields `:  For Example:
   ```
   - Project
         f1 = k.x
      - Filter
            k.y > 5
         - TableScan
               k = ColumnHandle("s")
   ```
   
   ```
   - Project
         f1 = k.x
      - Filter
            k.y > 5
         - Project
               k{"x", "y"} = k{"x", "y"}
            - TableScan
                  k = ColumnHandle("s")
   ```

   * `PruneProjectColumnFields `:  For Example:
   ```
   - Project
         f1 = k.x
      - Project
           k = k
         - TableScan
               k = ColumnHandle("s")
   ```
   
   ```
   - Project
         f1 = k.x
      - Project
           k{"x"} = k{"x"}
         - TableScan
               k = ColumnHandle("s")
   ```

   -  `PruneTableScanColumnFields`: For Example:
   ```
   - Project
        m = k.x
        n = k.y
      - TableScan
         k = ColumnHandle("s")
   ```
   
   ```
   - Project
        m = k.x
        n = k.y
      - TableScan
         k{"x", "y"} = ColumnHandle("s")
   ```
3. Use all nested fields as a Constraint to update the table layout. If the connector returns updated column handles, then replace the original column handles. Those updated column handles could carry the list of nested fields.
For Example:
```
- TableScan
    k{"x", "y"} = ColumnHandle("s")
```

```
- TableScan
    k{"x", "y"} = ColumnHandle("s", {"x", "y"})
```
4. Readers use the `ColumnHandle` to determine which nested fields need to read  (for example `ColumnHandle("s", {"x", "y"}) -> only read "x" and "y" for "s")`) . Since we use Parquet at Twitter, only the nested fields pruning in `ParquetPageSourceFactory` has been implemented.

### CODE REVIEW

**Comment by Yaliang** [comment]
Try to fix issue: #2508, #11326
some related pr: #5547, #10064
+cc @zhenxiao @martint @qqibrow @nezihyigitbasi who have looked into this
+cc @luohao for Twitter folks

**Comment by qqibrow** [comment]
Thank you @Yaliang 

Here is the [original design of nested column pushdown](https://github.com/prestodb/presto/pull/5547#issuecomment-267202680) and here is the implementation based on [that](https://github.com/prestodb/presto/pull/10064). Shall we collaborate more on that approach? :)

**Comment by mbasmanova** [comment]
@Yaliang This work overlaps with Aria project where we are aiming to do nested column pruning for ORC. I'd like to start reviewing this PR. Any chance you could rebase to the top of tree?

**Comment by highker** [comment]
Please refer to the query plan pushdown work (https://github.com/prestodb/presto/pull/12375). That patch enables connectors to write rules to optimize query plan. The pruning better lives inside a connector rather than in the engine given this is specific to Hive connector. I'm not object to a cleaner approach if we believe struct type is general enough for all kinds of data sources.

**Comment by mbasmanova** [comment]
@Yaliang I'm closing this PR as it seems to have been superseded by #10064 (and, perhaps, #12375). Please, reopen if I'm mistaken.

**Pull request closed without merging**
