### PR TITLE
Revert "Execute PickTableLayout before AddExchanges"

### LINKED ISSUE #9800: Executing PickTableLayout before AddExchanges breaks index joins
In particular commit e6d963b1b3 causes index joins to fail with `"Tuple domain handles must have assigned symbols"`.

### PR DESCRIPTION
**Pull request by nezihyigitbasi**
Fixes #9800.

ce6744c6ea cannot be reverted so I had to disable the check.

/cc @martint @kokosing

### CODE REVIEW

**Comment by findepi** [comment]
@nezihyigitbasi would it be possible to have a regression test preventing this from happening again?

**Comment by nezihyigitbasi** [comment]
@findepi with a connector supporting index joins it should be possible I think, I will try to come up with a test.

**Comment by nezihyigitbasi** [comment]
Superseded by #9816.

**Pull request closed without merging**
