### PR TITLE
Update types.rst

### PR DESCRIPTION
**Pull request by renurajagop**
## Description
Follow up to https://prestodb.slack.com/archives/C07JH9WMQ/p1706090216555849

## Motivation and Context
None

## Test Plan

== NO RELEASE NOTE ==

### CODE REVIEW

**Comment by skairali** [comment]
@steveburnett  Steve.  the changes look necessary to me as the older information in the docs is incorrect

**Review by skairali — APPROVED** [review]
Changes look good to me

**Comment by steveburnett** [comment]
Suggest editing the release notes part of this PR's Description from 
`(x) This is not user-visible or is docs only, and no release notes are required.`
to 

```
== NO RELEASE NOTE ==
```

Everything else looks good. Thanks!

**Review by steveburnett — APPROVED** [review]
LGTM! (docs) 

Pulled branch, local build of docs, reviewed local build. Everything looks good. Thanks for the docs improvement!

**Comment by renurajagop** [comment]
> Suggest editing the release notes part of this PR's Description from `(x) This is not user-visible or is docs only, and no release notes are required.` to
> 
> ```
> == NO RELEASE NOTE ==
> ```
> 
> Everything else looks good. Thanks!

Updated the PR  description as suggested.

**Review by tdcmeehan — APPROVED** [review]

**Review by kiersten-stokes — APPROVED** [review]
Thanks for this! LGTM

**Pull request merged**
