### PR TITLE
fix JDBC Connector, WHERE clauses aren't being pushed down.

### PR DESCRIPTION
**Pull request by toyama0919**
Hello.

I uses Presto, with Mysql and Postgresql. 
※Mysql and Redshift

JDBC Connector(mysql and postgresql), WHERE clauses aren't being pushed down.
But BIGINT, DOUBLE, BOOLEAN is WHERE clauses being pushed down.

I add VARCHAR, DATE, TIMESTAMP WHERE clauses.

Such as query on presto
```
select count(*) from postgresql.public.pageview where log_date > cast ('2015-07-25' as timestamp)
```

Then running query in redshift.
```
select count(*) from postgresql.public.pageview where log_date > '2015-07-25'
```

These are same case.
https://groups.google.com/forum/#!topic/presto-users/Pj-ta_FO0OQ
https://github.com/facebook/presto/issues/2341

### CODE REVIEW

**Comment by yuananf** [comment]
This should be rebased on #3135 , because different database has different syntax.

**Comment by toyama0919** [comment]
Thank you for your reply!

OK.
This pull request be rebase.

https://github.com/facebook/presto/pull/3135

There are a questions, sorry.

> because different database has different syntax.
・QueryBuilder.java make every Connector？

**Comment by yuananf** [comment]
Connectors that based on ```presto-base-jdbc```, MySQL, Postgresql etc. can overwrite the function ```supportPredicateOnType``` and ```encode```.

**Comment by toyama0919** [comment]
OK!
thanks!

**Comment by toyama0919** [comment]
Hello!

I send pull request to Mr. AshwinJay.
https://github.com/AshwinJay/presto/pull/1

thanks.

**Comment by toyama0919** [comment]
reviewing this pull request.
https://github.com/AshwinJay/presto/pull/1

**Comment by toyama0919** [comment]
Hello.

rebased complete this pull request.
https://github.com/facebook/presto/pull/3135

**Comment by electrum** [comment]
My sincere apologies on the duplication of work here. Your SQL range tests are good and I'm going to integrate them.

**Comment by electrum** [comment]
Merged, thanks!

**Pull request closed without merging**
