### PR TITLE
Add continuous uniform distribution

### PR DESCRIPTION
**Pull request by dowi**
Test plan - (Please fill in how you tested your changes)

Please make sure your submission complies with our [Development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [Formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), and [Commit Message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests) guidelines. Don't forget to follow our [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution) for any code copied from other projects.

Fill in the release notes towards the bottom of the PR description.
See [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) for details.

```
== RELEASE NOTES ==

General Changes
added continuous uniform distribution
* ...

Hive Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by leepface** [comment]
Code review:
- [ ] squash commits together into one commit

**Comment by dowi** [comment]
Commits squashed

**Comment by ajaygeorge** [comment]
@dowi Can you please take a look at resolving the merge conflicts.
cc @jbapple

**Comment by rongrong** [comment]
For commit message, please use `Add` instead of `added`. `Add continuous uniform distribution functions`

**Comment by steveburnett** [comment]
Closing due to lack of activity and age. If this is still relevant, please re-open this PR, rebase, and resolve any file conflicts.

**Pull request closed without merging**
