### PR TITLE
Extract NULL_LITERAL

### PR DESCRIPTION
**Pull request by kokosing**
Extract NULL_LITERAL

It is very similar to BooleanLiteral.TRUE_LITERAL and FALSE_LITERAL.

### CODE REVIEW

**Comment by kokosing** [comment]
Then we should get rid of BooleanLiteral.TRUE_LITERAL and FALSE_LITERAL

**Comment by martint** [comment]
> While Nodes can be sometimes compared by reference (NodeRef) and NullLiteral is also a Node, i think this is not a safe change and may introduce subtle nuances even if it passes all tests today.

I may have missed it, but I didn't see any place in this PR that relies on comparing nodes by reference. TRUE/FALSE_LITERAL are there for convenience (they are constants), and NULL_LITERAL could get the same treatment.

**Comment by findepi** [comment]
@martint i didn't refer to any code change in this PR. 
I am thinking about places like `com.facebook.presto.sql.analyzer.Analysis#coercions` where we attach something to a particular occurrences of an Expression. 
If a `NULL_LITERAL` gets a coercion, this coercion will be incorrectly applied to all other occurrences of the very same `NULL_LITERAL` within the query.

**Comment by findepi** [comment]
Yes, as soon as they are safe to use, constants are more convenient to me.

BTW regarding constants and convenience, this is being touched upon in https://github.com/prestodb/presto/pull/11625, see initial commits there :)

**Comment by martint** [comment]
Also, btw, the reason that we don’t (and can’t) use them in the AST that makes them somewhat safer is that we need to record the position where those literals originated during parsing. So they have to be distinct instances.

**Comment by kokosing** [comment]
I changed from constant to a method. Now it will be very easy to change to constant once they become safe. Nevertheless I am not sure of the value of this refactor.

**Pull request closed without merging**
