### PR TITLE
Use precision parameter for VARCHAR columns in tpch connector

### PR DESCRIPTION
**Pull request by losipiuk**

### CODE REVIEW

**Comment by losipiuk** [comment]
@Martint, could you please release airlift-tpch 0.8. This patch depends on that changes. When you do I will replace pom.xml in this PR to not use `-SNAPSHOT` version.

**Comment by martint** [comment]
Done.

**Comment by losipiuk** [comment]
Thanks! Updated this PR to use 0.8

**Comment by martint** [comment]
I'll merge this after the current release goes out

**Comment by martint** [comment]
There are test failures. Please take a look.

**Comment by losipiuk** [comment]
Yeah - actually this one have to wait until VARCHAR(x) support for other connectors get merged :/ That is because tpch connector serves as source for test data for others.

**Comment by losipiuk** [comment]
@martint this one should be mergable now.
Please take a look at 3 added commits which fix some minor test issues related to upgrading airlift-tpch version.

**Comment by martint** [comment]
I'll merge this after the current release goes out.

**Comment by martint** [comment]
Merged, thanks!

**Pull request closed without merging**
