### PR TITLE
Upgrade to aws-java-sdk 1.11.29

### PR DESCRIPTION
**Pull request by z-york**
This pull request upgrades the aws java sdk to 1.11.25 (the latest version)

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by nezihyigitbasi** [comment]
Related #4022

**Comment by z-york** [comment]
@nezihyigitbasi as you mentioned in #4022, I have also upgraded the jackson.version.

**Comment by nezihyigitbasi** [comment]
The latest aws java sdk version is `1.11.29`, let's move to that.

**Comment by z-york** [comment]
I'll submit an updated pull request after I can confirm it builds.

**Comment by nezihyigitbasi** [comment]
I ran some tests with v `1.11.29` and I didn't have any issues so far, looks good.

@martint @electrum are you guys OK with updating the version of jackson? Any issues that you guys are aware of? Also should we upgrade jackson version in airbase instead of doing it in Presto?

**Comment by electrum** [comment]
We should upgrade Jackson in Airbase and Airlift. There might be additions needed for `ObjectMapperProvider` to turn off newly added Jackson "features".

We just released Presto, so it's a good time to make a major change like this (more time to find problems before the next release). I can take a look at this today.

**Comment by z-york** [comment]
@electrum would you like me to submit a PR without upgrading jackson? It will fail to build until the Airbase change is in. Just let me know what I can do to help!

**Comment by z-york** [comment]
@nezihyigitbasi I have removed the jackson dependency from the PR. Should be ready to merge when the CI build comes back.

**Comment by z-york** [comment]
@nezihyigitbasi @electrum is this ready to merge?

**Comment by electrum** [comment]
Looks like 1.11.30 is out now. I'll test with that and merge.

**Comment by z-york** [comment]
Cool. Thanks!

**Comment by electrum** [comment]
Merged, thanks!

**Pull request closed without merging**
