### PR TITLE
Bump Iceberg from 1.2.0 to 1.2.1

### PR DESCRIPTION
**Pull request by nastra**
== RELEASE NOTES ==

Iceberg Changes
* Upgrade from 1.2.0 to 1.2.1

### CODE REVIEW

**Review by ChunxuTang — APPROVED** [review]
LGTM. Thanks for the contribution!

**Review by ajaygeorge — APPROVED** [review]

**Comment by ChunxuTang** [comment]
Re-running failed jobs...

**Comment by ChunxuTang** [comment]
> @ChunxuTang any idea why CI keeps failing? The failure doesn't seem to be related to the version bump.

@nastra I agree that the failure is not related to your PR as your code has nothing related to the presto-native module. I triggered a rerun of the failed tests to see whether they could pass this time.

@ajaygeorge Do you happen to have any insights into why the test fails?

**Comment by ajaygeorge** [comment]
@amitkdutta, any idea why the native tests are failing.

**Comment by amitkdutta** [comment]
@ajaygeorge This issue is fixed in https://github.com/prestodb/presto/pull/19551

**Comment by nastra** [comment]
I've rebased the PR but now I see test failures in `TestTpcdsCostBasedPlan` and `TestExternalHiveTable`

**Comment by ChunxuTang** [comment]
Hi @amitkdutta and @ajaygeorge, there are still some native module testing failures unrelated to this code change. Do you happen to have any insights? 
Does @nastra need to merge the current master branch again to pick up any latest fixes?

**Pull request merged**
