### PR TITLE
Benchmarks for Join performance

### PR DESCRIPTION
**Pull request by pnowojski**
**disclaimer 1. This code is not intended to bo committed to Presto.** It contains only some dirty benchmarks showing some of the problems of current Join code. 

**disclaimer 2. Don't be scared of the size of this pull request.** It's has only one commit with some dirty optimization to the presto code and bunch of different benchmarks, which have mostly copy pasted code from presto-main module. So here it goes

Each benchmark tests 4 things. `InMemoryJoinHash` build performance and join performance and on the other axis each of the join/build benchmark with and without byte[] hack from this pull request: https://github.com/prestodb/presto/pull/4570 

**BenchmarkOriginalJoin**. It has copied/pasted code from presto master (148-SNAPSHOT). Using it I have produced 2 results.

_148-SNAPSHOT_ - plain master code (kudos for @haozhun for greatly improving performance with avoiding calling `Page::getBlocks()`. My results includes your improvements)
_148-SNAPSHOT no null/boundary checks_ - removed null checks and some boundary checks (using modified airlift version)

**BenchmarkOriginalJoinInlineHashRow**. Same as above, original code, but where I could I replaced `Page` with single `FixedWidthBlock`. In the results table it is called as: _148-SNAPSHOT no checks hardcoded BIGINT_.

**BenchmarkJoinWithNativeArrays**

That was created other way around. I have replaced Block concept with native `long[]`. Column is basically `long[][]`, and Table consists of hardcoded 2 `long[][]` columns.

```
+---------------------------------------------+------------+-----------+-------+------------+-----------+-------+
|                   Benchmark                 | No hack                        | byte[] hack                    |
|  inner join on unique BIGINT key column     +------------+-----------+-------+------------+-----------+-------+
|  every probe row matches one build row      | Build time | Join time | Total | Build time | Join time | Total |
+---------------------------------------------+------------+-----------+-------+------------+-----------+-------+
| 1. 148-SNAPSHOT                             |        115 |       222 |   337 |         39 |       165 |   204 |
| 2. 148-SNAPSHOT no null/boundary checks     |         92 |       175 |   267 |         37 |       135 |   172 |
| 3. 148-SNAPSHOT no checks hardcoded BIGINT  |         75 |       147 |   222 |         35 |       103 |   138 |
| 4. BenchmarkJoinWithNativeArrays            |         54 |       106 |   154 |         31 |        77 |   108 |
+---------------------------------------------+------------+-----------+-------+------------+-----------+-------+
```

My conclusions are that we can easily drop null checks for joins and get some speedup right away. Secondly, data access to Pages is slow/suboptimal. Boundary checks do not help (as shown in 2. benchmark). Storing columns as an array in Page does not help (shown by 3. benchmark) and `Slice`'s usage of `sun.misc.Unsafe;` does not help neither (4. benchmark). 

But implementing in reasonable way 3rd and 4th improvement might be tricky and would require custom code for each native data type for key and number of columns in the key. We can follow this path in similar fashion as I have proposed optimized `InMemoryJoinHash` for `BIGINT`s here https://github.com/prestodb/presto/pull/4735.

Regardless of that changes, `byte[] hack` (https://github.com/prestodb/presto/pull/4570) always give significant improvements (especially with joins on unique columns). What is more, `byte[] hack` works for every data type(s) combination out of the box.

Once we resolve those issues, we can think about further improving/reworking join algorithm (in Warsaw office we have at least couple of ideas for that which need investigation). Nevertheless I strongly recommend addressing data access problems first so we at least have some reasonable baseline for future algorithm improvements.

CC @sopel39 @losipiuk @dain @martint

### CODE REVIEW

**Comment by dain** [comment]
I agree we should get in the removal of the null check for join as soon as possible.  Can you put up a PR that works for aggregations and joins? 

I'm currently working on writing new blocks for all of the fixed width type using primitive arrays, and we are seeing a 1.3x - 1.4x speedup (or a ~25% reduction in cpu usage) for joins and aggregations.  There is a related optimization for VariableWidthBlock that has a similar speedup.  This seems similar to the speedup you saw with native arrays. I'll let you know when it is up for review so we can compare to these results.

Finally, I think the byte[] hash trick is a good win.  @cberner are we ok with adding one additional byte per entry for JOIN hash tables, or do you think this need a config option?

**Comment by cberner** [comment]
One byte sounds fine to me

**Comment by pnowojski** [comment]
Yes, I have code for those null checks almost ready. I will push it by Monday. After that I will update https://github.com/prestodb/presto/pull/4570

Hmmm, we were thinking how to speed up slice up to native arrays speed, but somehow we have missed obvious solution that implementing blocks backed up by primitive arrays is much easier and will do the trick.

**Comment by pnowojski** [comment]
https://github.com/prestodb/presto/pull/5410 created and https://github.com/prestodb/presto/pull/4570 updated. Closing this one.

**Pull request closed without merging**
