### PR TITLE
Enable cache stats when CacheBuilder.newBuilder is called #7081

### PR DESCRIPTION
**Pull request by ebyhr**
This is my first PR to this repository. If there's bad point or missing information, I'm sorry but please tell me.

Added function's hitRate() returns hit rate as double.

ex) OrderingCompiler.java
orderingCacheStats().hitRate()

reference)
http://google.github.io/guava/releases/snapshot/api/docs/com/google/common/cache/Cache.html#stats--
http://google.github.io/guava/releases/snapshot/api/docs/com/google/common/cache/CacheStats.html

### CODE REVIEW

**Comment by electrum** [comment]
These stats aren't used or exported. What is the purpose of adding them?

**Comment by martint** [comment]
This is probably for https://github.com/prestodb/presto/issues/7081

**Comment by ebyhr** [comment]
Yes, this PR is for [#7081](https://github.com/prestodb/presto/issues/7081)

**Comment by electrum** [comment]
We need these stats exported via JMX. You can do that like this:
```java
@Managed
@Nested
public CacheStatsMBean getPageProcessorsCache()
{
    return new CacheStatsMBean(pageProcessors.stats());
}
```
You'll need to create the `CacheStatsMBean` wrapper that exposes the stats as `@Managed` methods.

**Comment by electrum** [comment]
Additionally, the classes such as `ExpressionCompiler` will need to be exported via JMX so that the `@Managed` methods actually get picked up.

That's done in the Guice module where they are bound. For example, in `ServerMainModule`:
```java
binder.bind(NodeScheduler.class).in(Scopes.SINGLETON);
newExporter(binder).export(NodeScheduler.class).withGeneratedName();
```

This gets trickier for things like `JoinCompiler` which is a singleton inside of `PagesIndex`. For that, we'll need to refactor `PagesIndex` to accept a `JoinCompiler` in the constructor, then change all the usages to have it injected, so that there is a singleton `JoinCompiler` created by Guice. This is a larger change (easy but touches lots of code), so it makes sense to do that as a separate commit (that is done before adding the cache stats).

**Comment by electrum** [comment]
Alternatively, if you don't want to tackle the `PagesIndex` change, you can skip adding stats for those and only do the ones that are already Guice singletons.

**Comment by ebyhr** [comment]
Thanks for the detailed explanation! I will modify codes and resend PR.

**Comment by ebyhr** [comment]
First I modified only `ExpressionCompiler` and added `CacheStatsMBean` wrapper for the change.
screen shot 2017-01-21 at 0 14 19

**Comment by electrum** [comment]
Looking good! @martint what other stats do you want? Probably at least `requestCount()` so the rates have some meaning?

**Comment by martint** [comment]
Just hit/miss would be sufficient, but adding request count wouldn't hurt.

**Pull request closed without merging**
