### PR TITLE
Support for FLOAT in Hive

### PR DESCRIPTION
**Pull request by maciejgrzybek**
This is a rebased and a bit polished version of https://github.com/prestodb/presto/pull/5661 since https://github.com/prestodb/presto/pull/5758 got merged. Made a "Add product tests for FLOAT" (f3b9efc) a bit cleaner - not touching CHAR part of tests anymore.
Teradata internal review: Teradata#235

CC: @cberner

### CODE REVIEW

**Comment by maciejgrzybek** [comment]
Rebased on master and resolved conflicts.

**Comment by cberner** [comment]
Could you two decide on the REAL vs FLOAT naming, then assign back to me? I'm focused on getting the `char(x)` PR in at the moment

**Comment by maciejgrzybek** [comment]
@cberner taking this offline with @martint, to avoid unnecessary delay. Will bring back here whatever we agree on.

**Comment by maciejgrzybek** [comment]
As per offline discussion with @martint we agreed to rename FLOAT to REAL.
When we decide to implement parametrized FLOAT it should work similarly to DECIMAL in a way:
1. unparameterized `FLOAT` = `FLOAT(MAX_PRECISION)` = `DOUBLE`
2. parametrized `FLOAT(x)` = `REAL` / `DOUBLE`, depending on a precision.

Rationale:
Standard defines `REAL` < `DOUBLE` and guarantees that `FLOAT(x)` should have a precision equal or greater than the value specified by parameter.
Standard does not specify what should be precision of `FLOAT` when no precision is given.
For consistency with `DECIMAL` implementation where unparameterized `DECIMAL` = `DECIMAL(MAX_PRECISION)`, unparameterized `FLOAT` will become `FLOAT(MAX_PRECISION)` which will be equal to `DOUBLE`.

**Comment by maciejgrzybek** [comment]
Closing for now. I will start a new PR when the new data type will be renamed as described above.

**Pull request closed without merging**
