### PR TITLE
Add pushed down filter to the output of EXPLAIN

### PR DESCRIPTION
**Pull request by mbasmanova**
Add filters pushed down into the Hive connector (by setting `hive.pushdown-filter-enabled=true`) to the output of EXPLAIN command under `LAYOUT` section of `TableScan`.

```
EXPLAIN SELECT orderkey FROM lineitem WHERE linenumber % 2 = 0
            
- Output[orderkey] => [orderkey:bigint]
        Estimates: {rows: 60175 (528.88kB), cpu: 541575.00, memory: 0.00, network: 541575.00}
    - RemoteStreamingExchange[GATHER] => [orderkey:bigint]
            Estimates: {rows: 60175 (528.88kB), cpu: 541575.00, memory: 0.00, network: 541575.00}
        - TableScan[TableHandle {connectorId='hive', connectorHandle='HiveTableHandle{schemaName=tpch, tableName=lineitem, analyzePartitionValues=Optional.empty}', layout='Optional[tpch.lineitem{filter=((linenumber) % (INTEGER 2)) = (INTEGER 0)}]'}] => [orderkey:bigint]
                Estimates: {rows: 60175 (528.88kB), cpu: 541575.00, memory: 0.00, network: 0.00}
                LAYOUT: tpch.lineitem{filter=((linenumber) % (INTEGER 2)) = (INTEGER 0)}
                orderkey := orderkey:bigint:0:REGULAR
)

EXPLAIN SELECT orderkey FROM lineitem WHERE orderkey < 1000 AND linenumber % 2 = 0
            
- Output[orderkey] => [orderkey:bigint]
        Estimates: {rows: 60175 (528.88kB), cpu: 541575.00, memory: 0.00, network: 541575.00}
    - RemoteStreamingExchange[GATHER] => [orderkey:bigint]
            Estimates: {rows: 60175 (528.88kB), cpu: 541575.00, memory: 0.00, network: 541575.00}
        - TableScan[TableHandle {connectorId='hive', connectorHandle='HiveTableHandle{schemaName=tpch, tableName=lineitem, analyzePartitionValues=Optional.empty}', layout='Optional[tpch.lineitem{filter=((linenumber) % (INTEGER 2)) = (INTEGER 0), domains={orderkey=[ [(<min>, 1000)] ]}}]'}] => [orderkey:bigint]
                Estimates: {rows: 60175 (528.88kB), cpu: 541575.00, memory: 0.00, network: 0.00}
                LAYOUT: tpch.lineitem{filter=((linenumber) % (INTEGER 2)) = (INTEGER 0), domains={orderkey=[ [(<min>, 1000)] ]}}
                orderkey := orderkey:bigint:0:REGULAR
)

EXPLAIN SELECT orderkey FROM lineitem WHERE linenumber > 3
            
- Output[orderkey] => [orderkey:bigint]
        Estimates: {rows: 60175 (528.88kB), cpu: 541575.00, memory: 0.00, network: 541575.00}
    - RemoteStreamingExchange[GATHER] => [orderkey:bigint]
            Estimates: {rows: 60175 (528.88kB), cpu: 541575.00, memory: 0.00, network: 541575.00}
        - TableScan[TableHandle {connectorId='hive', connectorHandle='HiveTableHandle{schemaName=tpch, tableName=lineitem, analyzePartitionValues=Optional.empty}', layout='Optional[tpch.lineitem{domains={linenumber=[ [(3, <max>)] ]}}]'}] => [orderkey:bigint]
                Estimates: {rows: 60175 (528.88kB), cpu: 541575.00, memory: 0.00, network: 0.00}
                LAYOUT: tpch.lineitem{domains={linenumber=[ [(3, <max>)] ]}}
                orderkey := orderkey:bigint:0:REGULAR
)

EXPLAIN SELECT orderkey FROM lineitem WHERE linenumber IN (1, 2, 3)
            
- Output[orderkey] => [orderkey:bigint]
        Estimates: {rows: 60175 (528.88kB), cpu: 541575.00, memory: 0.00, network: 541575.00}
    - RemoteStreamingExchange[GATHER] => [orderkey:bigint]
            Estimates: {rows: 60175 (528.88kB), cpu: 541575.00, memory: 0.00, network: 541575.00}
        - TableScan[TableHandle {connectorId='hive', connectorHandle='HiveTableHandle{schemaName=tpch, tableName=lineitem, analyzePartitionValues=Optional.empty}', layout='Optional[tpch.lineitem{domains={linenumber=[ [[1], [2], [3]] ]}}]'}] => [orderkey:bigint]
                Estimates: {rows: 60175 (528.88kB), cpu: 541575.00, memory: 0.00, network: 0.00}
                LAYOUT: tpch.lineitem{domains={linenumber=[ [[1], [2], [3]] ]}}
                orderkey := orderkey:bigint:0:REGULAR
)

EXPLAIN SELECT orderkey FROM lineitem

- Output[orderkey] => [orderkey:bigint]
        Estimates: {rows: 60175 (528.88kB), cpu: 541575.00, memory: 0.00, network: 541575.00}
    - RemoteStreamingExchange[GATHER] => [orderkey:bigint]
            Estimates: {rows: 60175 (528.88kB), cpu: 541575.00, memory: 0.00, network: 541575.00}
        - TableScan[TableHandle {connectorId='hive', connectorHandle='HiveTableHandle{schemaName=tpch, tableName=lineitem, analyzePartitionValues=Optional.empty}', layout='Optional[tpch.lineitem{}]'}] => [orderkey:bigint]
                Estimates: {rows: 60175 (528.88kB), cpu: 541575.00, memory: 0.00, network: 0.00}
                LAYOUT: tpch.lineitem{}
                orderkey := orderkey:bigint:0:REGULAR
)
```

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by mbasmanova** [comment]
@highker @hellium01 James, Yi, Jiexi. thanks for reviews. Jiexi had a suggestion to replace ConnectorSession and RowExpressionService parameters with a single Function<RowExpression, String> . What are your thoughts? Should I make the change or keep things are they are?

> Adding ConnectorSession and RowExpressionService to the layout handle seems to be an overkill for the formatting usage in toString(). How about we pass a Function<RowExpression, String> object to the HiveTableLayoutHandle constructor?

**Comment by highker** [comment]
@mbasmanova, That is a good choice. Actually, can we just directly save the formatted string in layout handle instead of constructing it in `toString()`?

**Comment by mbasmanova** [comment]
@highker @jessesleeping I need to keep the session parameter, because it is used for format TupleDomain. I can replace RowExpressionService with Function<RowExpression, String>. I can also add `String layoutString;` to store the output of toString. Here is what it looks like?

```
    private final String layoutString;


        // on coordinator
        requireNonNull(session, "session is null");
        requireNonNull(rowExpressionFormatter, "rowExpressionFormatter is null");

        layoutString = toStringHelper(schemaTableName.toString())
                .omitNullValues()
                .add("buckets", bucketHandle.map(HiveBucketHandle::getReadBucketCount).orElse(null))
                .add("filter", TRUE_CONSTANT.equals(remainingPredicate) ? null : rowExpressionFormatter.apply(remainingPredicate))
                .add("domains", domainPredicate.isAll() ? null : domainPredicate.toString(session))
                .toString();


    @Override
    public String toString()
    {
        return layoutString;
    }
```

Somehow this doesn't look like an improvement to me, but I'm happy to make this change if you feel like it is. Please, let me know.

**Comment by highker** [comment]
Got it. Ya sure, let's do `Function<RowExpression, String>`

**Comment by mbasmanova** [comment]
@highker @jessesleeping @hellium01 Updated the PR to replace `RowExpressionService` with `Function<RowExpression, String>`.

**Pull request merged**
