### PR TITLE
Removed unsupported data types on read/write paths in jdbc connectors

### PR DESCRIPTION
**Pull request by pratyakshsharma**
Cherrypick of https://github.com/prestodb/presto/pull/12231/commits
Test plan - (Please fill in how you tested your changes)

Please make sure your submission complies with our [Development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [Formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), and [Commit Message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests) guidelines. Don't forget to follow our [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution) for any code copied from other projects.

Fill in the release notes towards the bottom of the PR description.
See [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) for details.

```
== RELEASE NOTES ==

General Changes
* QueryBuilder and BaseJdbcClient see the changes
* 

```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by pratyakshsharma** [comment]
@NikhilCollooru Can you please take a pass.

**Comment by NikhilCollooru** [comment]
I am on parental leave. May be @highker can help review.

**Comment by highker** [comment]
There is no harm to keep it around right?

**Comment by highker** [comment]
We actually have dependency of this client to fall back from `TIMESTAMP_WITH_TIME_ZONE` to `TIMESTAMP` (or `TIME_WITH_TIME_ZONE` to `TIME`). Deleting these two types could cause regression.

**Comment by pratyakshsharma** [comment]
> We actually have dependency of this client to fall back from TIMESTAMP_WITH_TIME_ZONE to TIMESTAMP (or TIME_WITH_TIME_ZONE to TIME). Deleting these two types could cause regression.

@highker Where do we have this dependency? Can you point me to the relevant files?

**Comment by pratyakshsharma** [comment]
@highker ping.

**Comment by tdcmeehan** [comment]
Anyone who extends the JDBC connector may have a dependency on those types.  Why delete them?

**Comment by pratyakshsharma** [comment]
Got you, closing this PR. Thank you for reviewing.

**Pull request closed without merging**
