### PR TITLE
fbcode/github/presto-trunk/presto-docs/src/main/sphinx/include

### PR DESCRIPTION
**Pull request by bigfootjon**
Reviewed By: bigfootjon

Differential Revision: D44454761

### CODE REVIEW

**Comment by bigfootjon** [comment]
We're going to revert the internal codemod instead

**Comment by ClarenceThreepwood** [comment]
This commit breaks the build
https://github.com/prestodb/presto/actions/runs/4866292367/jobs/8677658826?pr=19345

**Comment by miaoever** [comment]
+1 on this
https://github.com/prestodb/presto/actions/runs/4865500879/jobs/8677938988?pr=19517

**Comment by bigfootjon** [comment]
Go ahead and revert this diff then, I was just fixing diff train

**Pull request merged**
