### PR TITLE
Fix travis non-reporting of product and integration test failures

### PR DESCRIPTION
**Pull request by ArturGajowy**
The errors were introduced in #5421 and #5471. Sorry about that.

Luckily, there are no test failures in master: https://travis-ci.org/Teradata/presto/builds/145496921

Proof that this commit fixes the false-positive problem: https://travis-ci.org/Teradata/presto/builds/145498113

### CODE REVIEW

**Comment by ArturGajowy** [comment]
Pushed a better version that runs kerberos product tests even if `singlenode` tests fail (previously a `&&` conjunction was used). Similarly for full `mvn install` after failing integration tests.

**Comment by ArturGajowy** [comment]
Please note that using `$?` is not reliable in .travis.yml: https://docs.travis-ci.com/user/customizing-the-build/#Note-on-%24%3F

**Comment by ArturGajowy** [comment]
@cberner Please have a look. I think this should be landed quickly as it might affect all devs.

**Comment by electrum** [comment]
It took us a bit to understand the problem. To summarize, we have shell script like this:
```sh
if [ ... ]; then
  cmd1
  cmd2
fi
```
The `if` block will run both `cmd1` and `cmd2` and return the output status of `cmd`. Thus, the status of `cmd1` will be ignored.

This means it doesn't make sense to use `if`, since you should only ever have command, as the return value will only be used from the last one.

We should instead write it like this:

```yaml
script:
  - |
    test -v TEST_MODULES &&
      ./mvnw test $MAVEN_SKIP_CHECKS_AND_DOCS -B -pl $TEST_MODULES
  - |
    test -v PRODUCT_TESTS &&
      presto-product-tests/bin/run_on_docker.sh \
        singlenode -x quarantine,big_query,storage_formats,mysql_connector,postgresql_connector,profile_specific_tests
  - |
    test -v PRODUCT_TESTS &&
      presto-product-tests/bin/run_on_docker.sh \
        singlenode-kerberos-hdfs-impersonation -g storage_formats,cli,hdfs_impersonation,authorization
...

**Comment by ArturGajowy** [comment]
Done :)

**Comment by ArturGajowy** [comment]
Seems I was too fast with applying the change. `test -v cond && cmd` gives a non-zero return value whenever cond is false. Which will cause all the jobs in a build to fail, each because of at least one condition / script row.

Do I revert to the 'if' version?

Or negate the conditions and use `||` ? (less readable, IMHO)

**Comment by ArturGajowy** [comment]
Results here: https://travis-ci.org/Teradata/presto/builds/145633419

**Comment by cberner** [comment]
I would use `test ! cond ||`, the `if` way seems more error prone to me

**Comment by cberner** [comment]
Actually, is `-v` a valid argument for `test`? I don't see it in the manpage, and it doesn't work on Centos

**Comment by cberner** [comment]
Looks good

**Comment by ArturGajowy** [comment]
@cberner works on ubuntu, and on travis - that's for sure: https://travis-ci.org/Teradata/presto/builds/145647714

**Comment by cberner** [comment]
Merged. Thanks!

**Pull request closed without merging**
