### PR TITLE
Provide workaround for: Count(*) on empty relation return NULL when optimize_mixed_distinct_aggregations = true

### LINKED ISSUE #8894: Incorrect results produced by mixed distinct aggregations
COUNT(*) with COUNT(DISTINCT x) produces NULL for COUNT(*) when all input data is filtered out.

```
presto:tiny> SELECT COUNT(DISTINCT linenumber), COUNT(*) from lineitem where linenumber < 0;
 _col0 | _col1
-------+-------
     0 | NULL
(1 row)
```

### PR DESCRIPTION
**Pull request by kaka11chen**
Workaround for #8894
Introduce an arbitrary_ext() function to resolve this issue when use count(), count_if(), approx_distinct() functions.

### CODE REVIEW

**Comment by findepi** [comment]
@kaka11chen how does this fix the mixed distinct aggregations optimization?

**Comment by kaka11chen** [comment]
@findepi Because count(), count_if(), approx_distinct() will return 0 when empty, the mixed distinct aggregation optimization will use arbitrary to handle the non-distinct aggregation, arbitrary(null) will return null. So I introduce another special arbitrary which will retur 0 to handle this case.

**Comment by kaka11chen** [comment]
@findepi I have no idea what is best method to handle this incorrect case in the presto. For me, it is a fix method. Could you give me some suggestions, thanks.
BTW, spark sql handle this case by these source  codes. https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/optimizer/RewriteDistinctAggregates.scala
` // Some aggregate functions (COUNT) have the special property that they can return a`
`  // non-null result without any input. We need to make sure we return a result in this case.`
       ` val resultWithDefault = af.defaultResult match {`
          `case Some(lit) => Coalesce(Seq(result, lit))`
         ` case None => result`
       ` }`

**Comment by findepi** [comment]
@kaka11chen i don't know the proper fix either. One would need to look into what `optimize_mixed_distinct_aggregations` is doing.

**Comment by electrum** [comment]
Wouldn't it be simpler to wrapper in `coalesce(..., 0)`?

**Comment by kaka11chen** [comment]
@electrum I think use coalesce function will introduce a project node, I don't know whether it will be some side effects when complex sql.

**Comment by sopel39** [comment]
@kaka11chen please use coalesce node, additional projection shouldn't be a big problem.

Please add proper tests to: `com.facebook.presto.sql.planner.optimizations.TestOptimizeMixedDistinctAggregations`

**Comment by kaka11chen** [comment]
@sopel39 Got it, I will do it.

**Comment by kaka11chen** [comment]
@sopel39, when I add the projection node to do coalesce on the top level as the aggregation node's result plan node(visitAggregation()), how to change the parent node's source node to this project node?
For example: The parent node is output node, it throws the following error:
Invalid node. Expression dependencies ([count_1]) not in source plan output ([count])

**Comment by kaka11chen** [comment]
@sopel39 Open the new PR to use coalesce projection node#12115

**Comment by findepi** [comment]
Superseded by https://github.com/prestodb/presto/pull/12115

**Pull request closed without merging**
