### PR TITLE
Fix handling of REAL type for MySQL and PostgreSQL

### PR DESCRIPTION
**Pull request by electrum**
For both connectors, the data was inserted incorrectly. Additionally, for
MySQL, tables were created with the column type as double instead of real.

### CODE REVIEW

**Comment by electrum** [comment]
Fixes #8635

**Comment by findepi** [comment]
Dear @electrum , you might wish to rebase this PR onto @electrum 's #9393, which significantly changes the code being modified here.

**Comment by electrum** [comment]
Thanks, I forgot about this PR. It still has some test failures that I need to investigate. I’ll rebase onto the PageSink change after it’s merged.

I’d like to have a better way of doing RecordReader while still supporting lazy reads.

**Comment by electrum** [comment]
Replaced with #9413

**Pull request closed without merging**
