### PR TITLE
Revert "Propagate partition properties for full outer join"

### PR DESCRIPTION
**Pull request by rongrong**
This reverts commit 801347e3c6409c649370a3b55951ef7a73c4f04c.

### CODE REVIEW

**Comment by caithagoras** [comment]
Let's just make sure Travis is green

**Comment by kokosing** [comment]
@rongrong What was the issue?

**Comment by rongrong** [comment]
@kokosing Our verifier run found correctness issues. It removed a shuffle when it's needed.

**Comment by rongrong** [comment]
Reintroduces this feature with #12355

**Pull request merged**
