### PR TITLE
Remove redundant type arguments

### PR DESCRIPTION
**Pull request by kokosing**
Remove redundant type arguments

### CODE REVIEW

**Comment by kokosing** [comment]
Fixed travis and rebased.

**Comment by kokosing** [comment]
Rebased, fixed conflicts. Previous travis failure was unrelated.

**Comment by martint** [comment]
I merged all but the last two commits due to merge failures. Can you rebase them and resolve conflicts?

**Comment by fiedukow** [comment]
As this merge caused master to fail, I've rebased it and fix the problem in separate commit.
Please consider that high priority for that reason.
@martint

**Comment by martint** [comment]
Merged, thanks!

**Pull request closed without merging**
