### PR TITLE
Unify PlanBuilder::join with only RowExpression

### PR DESCRIPTION
**Pull request by kewang1024**
…ssion

### CODE REVIEW

**Comment by kewang1024** [comment]
> Unify PlanBuilder::join with only RowExpression



> Could you rename the commit title to be
> **Unify PlanBuilder::join with only RowExpression**

Sure, thanks!

**Comment by rongrong** [comment]
I might want to rename `castToRowExpression` to just `rowExpression`. Alternatively you can call this `originalExpression` to be more clear what it is. It's taking a `String` as parameter, not a `Expression` so it's not really a "cast". But that's not really related to this change. So maybe add another commit for the rename. 😛

**Comment by kewang1024** [comment]
> I might want to rename `castToRowExpression` to just `rowExpression`. Alternatively you can call this `originalExpression` to be more clear what it is. It's taking a `String` as parameter, not a `Expression` so it's not really a "cast". But that's not really related to this change. So maybe add another commit for the rename. 😛

There are actually two kinds of castToRowExpression function😂. One is taking a 'String' as parameter, the other one is taking 'Expression' as parameter.
public static RowExpression castToRowExpression(Expression expression).
Do you think we should rename both? or just the one that's taking 'String' as parameter.

**Comment by rongrong** [comment]
> > I might want to rename `castToRowExpression` to just `rowExpression`. Alternatively you can call this `originalExpression` to be more clear what it is. It's taking a `String` as parameter, not a `Expression` so it's not really a "cast". But that's not really related to this change. So maybe add another commit for the rename. 😛
> 
> There are actually two kinds of castToRowExpression function😂. One is taking a 'String' as parameter, the other one is taking 'Expression' as parameter.
> public static RowExpression castToRowExpression(Expression expression).
> Do you think we should rename both? or just the one that's taking 'String' as parameter.

No, I'm only talking about the `castToRowExpression` in `PlanBuilder`.

**Comment by hellium01** [comment]
Probably it is better to be named as `originalExpression`? We will need to build `rowExpression` from `String` later.

**Pull request merged**
