### PR TITLE
Make TestHiveIntegrationSmokeTest extensible

### PR DESCRIPTION
**Pull request by haozhun**

### CODE REVIEW

**Comment by electrum** [comment]
I think if we add the extra constructor, you can squash the second two commits.

**Comment by electrum** [comment]
@martint should take a look at the TestNG change, but seems fine to me

**Comment by haozhun** [comment]
@electrum suggested that instead of splitting TestHiveIntegrationSmokeTest into two and subclass the parent class, I can subclass it directly. Subclassing a concrete class doesn't sound like a good idea to me. But I can do that if @martint agrees.

**Comment by haozhun** [comment]
@electrum  updated.

**Pull request merged**
