### PR TITLE
Enforce output row limit

### PR DESCRIPTION
**Pull request by ugurmeet**
Test plan - (Please fill in how you tested your changes)
unit test and tested on real cluster.

```
== RELEASE NOTES ==

General Changes
* Add session property ``query_max_output_positions`` and configuration property ``query.max-output-positions`` to control how many rows a query can output. The query can end up returning more results than the limit specified here since the check is done periodically and asynchronously. 

```

### CODE REVIEW

**Comment by ugurmeet** [comment]
Hi @tdcmeehan , can someone take a look at this one. Thanks.

**Comment by ajaygeorge** [comment]
@ugurmeet , wondering what is the goal here?. A natural question is what use cases are we trying to address which `LIMIT` does not address?

**Comment by ugurmeet** [comment]
@ajaygeorge , thanks for looking. The idea here is to fail queries quickly which end up sending huge amounts of results. Since Presto is an analytics rather than a data serving system we want to discourage such queries. We have seen cases where queries end up returning huge datasets and ultimately timeout (INSUFFICIENT_RESOURCES - EXCEEDED_TIME_LIMIT) because the client has to pull millions of records and it takes times. The query meanwhile takes up one slot and prevents a new query from coming in. The user gets frustated with the failure but does not has a clue that the query failed because of huge result set. With this change, the query will fail with a proper error message and will allow us (the administrators) to set a upper limit to ensure fair usage of the cluster resources.
Using limit is an option as well but we want the user to know that he/she did not get the whole result set (in cases where it is important for accuracy reasons). The users can always retry their queries with a limit after seeing the failure if it is okay for them. 
Would be happy to discuss more.

**Comment by ugurmeet** [comment]
Abandon to create https://github.com/prestodb/presto/pull/17921

**Pull request closed without merging**
