### PR TITLE
Extend MongoDB connector support binData

### PR DESCRIPTION
**Pull request by exxiang**
## Description

Extend MongoDB connector support binData
## Motivation and Context

Extend MongoDB connector support [binData] #23083 
## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```

== NO RELEASE NOTE ==

### CODE REVIEW

**Review by elharo — CHANGES_REQUESTED** [review]
This needs tests

**Comment by exxiang** [comment]
> This needs tests

I have add tests. Please preview again. thank u

**Review by elharo — APPROVED** [review]

**Review by tdcmeehan — APPROVED** [review]

**Comment by tdcmeehan** [comment]
Thanks @exxiang !

**Comment by exxiang** [comment]
> Thanks @exxiang !

you are welcome

**Comment by tdcmeehan** [comment]
@exxiang can you please squash the commits?

**Comment by exxiang** [comment]
> @exxiang can you please squash the commits?

please tell me, my squash is it ok?

**Comment by tdcmeehan** [comment]
@exxiang it is not, as there are 167 unrelated commits.  This guide may help: https://www.freecodecamp.org/news/git-squash-commits/

**Pull request closed without merging**
