### PR TITLE
Fix build failures caused by new method in HiveMetastore interface

### PR DESCRIPTION
**Pull request by beinan**
Fix the build failure in FB caused by this PR. https://github.com/prestodb/presto/pull/16983

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by beinan** [comment]
hello @abhiseksaikia , as you suggested I just added the default impl into HiveMetastore which would fix the build.   Just let me know if you saw any other failures in your build.  Sorry for the inconvenience caused.

**Comment by abhiseksaikia** [comment]
@beinan  Thank you so much for the quick fix!

**Review by abhiseksaikia — APPROVED** [review]
LGTM

**Review by ChunxuTang — APPROVED** [review]
LGTM. @beinan Thanks for your quick fix!

**Pull request merged**
