### PR TITLE
[native] Advance Velox version.

### PR DESCRIPTION
**Pull request by isadikov**
Test plan - Build and existing tests.

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by isadikov** [comment]
@aditi-pandit Could you review this PR? I need to advance Velox version to get the recent function changes for the integration test. Thank you.

**Comment by aditi-pandit** [comment]
@isadikov : I'm re-running the failed tests here, but I see a crash in presto_server_test. for test native/build-and-test. We will have to investigate this.

**Comment by isadikov** [comment]
The regression is caused by 1ea8d65d2f3207583fcdec4e5e6b346389bf7983 Combine the root memoryPool for Velox and Koski. (https://github.com/facebookincubator/velox/pull/3754).

The `initPool` function was incorrectly refactored in the PR. We should only assign a memory tracker if the pool is not initialised.

**Comment by gggrace14** [comment]
Hi @isadikov https://github.com/prestodb/presto/pull/18976 had advanced Velox version and picked up the fix https://github.com/facebookincubator/velox/pull/3815. Just to let you know.

**Pull request closed without merging**
