### PR TITLE
Add support for row filtering

### PR DESCRIPTION
**Pull request by agrawalreetika**
```
== RELEASE NOTES ==

General Changes
* Add support for row level filtering
```

### CODE REVIEW

**Comment by pettyjamesm** [comment]
This appears to be code extracted from https://github.com/trinodb/trino/pull/2891, specifically https://github.com/trinodb/trino/pull/2891/commits/7efb49ca76782ef83b347b8d51ea422057bca1e0. Please review the commit guidelines related to [attribution](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution) and update the commit accordingly

**Comment by agrawalreetika** [comment]
@pettyjamesm Would you be able to help me review this PR?

**Comment by agrawalreetika** [comment]
Closing in favor of https://github.com/prestodb/presto/pull/24277

**Comment by agrawalreetika** [comment]
Closing in favor of https://github.com/prestodb/presto/pull/24277

**Pull request closed without merging**
