### PR TITLE
[native] Advance velox.

### PR DESCRIPTION
**Pull request by amitkdutta**

### CODE REVIEW

**Comment by amitkdutta** [comment]
The error is
```
../../presto_cpp/main/common/Configs.cpp:673:34: error: 'kCodegenEnabled' is not a member of 'facebook::velox::core::QueryConfig'
  673 |           BOOL_PROP(QueryConfig::kCodegenEnabled, c.codegenEnabled()),
  ```
  
  `kCodegenEnabled` is guarded inside `VELOX_ENABLE_BACKWARD_COMPATIBILITY`. Somehow advancing velox disable passing this? Facing the same issue locally as well.
  
  CC: @kgpai @majetideepak

**Comment by amitkdutta** [comment]
> The error is
> 
> ```
> ../../presto_cpp/main/common/Configs.cpp:673:34: error: 'kCodegenEnabled' is not a member of 'facebook::velox::core::QueryConfig'
>   673 |           BOOL_PROP(QueryConfig::kCodegenEnabled, c.codegenEnabled()),
> ```
> 
> `kCodegenEnabled` is guarded inside `VELOX_ENABLE_BACKWARD_COMPATIBILITY`. Somehow advancing velox disable passing this? Facing the same issue locally as well.
> 
> CC: @kgpai @majetideepak

Actually its deleted in https://github.com/facebookincubator/velox/pull/9176. Deleting here as well.

**Review by majetideepak — APPROVED** [review]
Thanks, @amitkdutta

**Comment by amitkdutta** [comment]
This is redone in https://github.com/prestodb/presto/pull/22331/files
closing this.

**Pull request closed without merging**
