### PR TITLE
Improve MakeSetDigest function Generic Parameter

### PR DESCRIPTION
**Pull request by Akanksha-kedia**
SELECT make_set_digest(value)
FROM (VALUES 'Trino', 'SQL', 'on', 'everything') T(value);

https://github.com/prestodb/presto/pull/20685 - ADDED SUPPORT FOR GENERIC PARAMETER

### CODE REVIEW

**Comment by Akanksha-kedia** [comment]
@tdcmeehan @steveburnett PLEASE REVIEW AND APPROVE

**Review by steveburnett — CHANGES_REQUESTED** [review]
The change as shown LGTM. I would suggest that, and I can't add this as a comment to the following line, delete "Set Digest" in line 87/83 "Set Digest structures". In the screenshot, notice how the sentence reads 
"...the individual ``setdigest`` Set Digest structures."

Also in line 59, consider formatting as follows:
"An example might include using ``to_utf8()`` or ``from_utf8()``."

**Comment by Akanksha-kedia** [comment]
@steveburnett @tdcmeehan please review and help to merge

**Review by steveburnett — APPROVED** [review]
LGTM! (doc)

**Review by tdcmeehan — APPROVED** [review]

**Pull request merged**
