### PR TITLE
Checkstyle for whitespaces before closing brackets

### PR DESCRIPTION
**Pull request by kokosing**
Checkstyle for whitespaces before closing brackets

### CODE REVIEW

**Comment by electrum** [comment]
Please see Travis failures

**Comment by kokosing** [comment]
> I think "))*" can be ")+".

Thanks. Applied.

> I'm confused about what the regex is matching. Is it actually checking multiple things? Please add a comment explaining the intent and why.

I added a commit message to explain why regex looks how it looks.

> It would be nice if we could unit test the checks against negative examples...

Yeah... that would be nice. Any ideas? IMO to achieve that we would to separate `check.xml` andas separate project where we could test the check style on synthetic code.

> Please see Travis failures

It should be fixed now, lets wait for travis.

**Comment by electrum** [comment]
Great comment! For the special case, on option is to require writing that weird for-loop like this:
```java
for (int i = 0; i < len; /**/) {
    ...
}
```
Personally, I dislike that syntax and would write it using a while loop. But this has the disadvantage of leaking the variable outside the loop, and cases like `LongBitPacker` utilize this to reuse the same variable in subsequent loops. So the for loop is arguably better, even though it looks weird.

**Comment by martint** [comment]
While I agree that in general it looks better, it's not always a win. In some cases, being able to make the nesting structure explicit by placing the parentheses in separate lines is important for readbility.

**Comment by kokosing** [comment]
> While I agree that in general it looks better, it's not always a win. In some cases, being able to make the nesting structure explicit by placing the parentheses in separate lines is important for readability.

It sounds ok, but ;)
 - the **main purpose of this to streamline the pull request review process**. My personal goal would be to avoid formatting comments at all. Instead, I would like to have code style check which which ensures all the formatting rules. Such formatting comments just waste our time and introduces unnecessary noise.
 - this is an argument which can be used for most of formatting rules which are enforced by the checkstyle. It is a trade off. Here, IMO we gain more than we lose.
 - In whole code base I haven't found any place where I should keep parentheses in separate lines (have I missed some?)
 - readability is very subjective. People can adapt. Just before working on Presto I used to use completely different formatting scheme which now tends to look weird to me. IMO much more important is consistency.

**Comment by electrum** [comment]
I looked through all of the changes in the "Remove whitespace" commit and didn't see anything where the extra newlines seemed to help. Everything is indented on the top side, so the closing parenthesis don't help. It's very similar to what seems to be the [common style](https://stackoverflow.com/questions/2207255/lisp-parentheses) for Lisp languages.

**Comment by martint** [comment]
There may be nothing in the current codebase, but I can tell you that I've certainly had to do that in the prototypes of the new optimizer & new IR to keep my sanity. For deeply nested expressions, it can also make it easier to manipulate, change and move terms around.

**Comment by kokosing** [comment]
I will leave it up to you guys. If you do not decide within couple of days, I will close this PR to avoid aimless rebasing.

I just wanted to avoid pointless discussions about formatting during PR reviews (time wasting).

**Comment by martint** [comment]
I'm ok with merging this with the caveat that if it gets in the way in the future, we'll back it out.

Regardless, the reformatting as you did look good, so that could be merged independently from the checkstyle rule change.

**Comment by kokosing** [comment]
@martint 
> I'm ok with merging this with the caveat that if it gets in the way in the future, we'll back it out.
>
> Regardless, the reformatting as you did look good, so that could be merged independently from the checkstyle rule change.

I completely agree!

**Comment by kokosing** [comment]
I merging this as travis failure is not related.

**Pull request merged**
