### PR TITLE
Fix LambdaDefinitionExpression canonicalization

### PR DESCRIPTION
**Pull request by rongrong**
Test plan - added new test in AbstractTestQueries

```
== RELEASE NOTES ==

General Changes
* Fix LambdaDefinitionExpression canonicalization to correctly canonicalize Block constant. Bug introduced in {pr:`14524`}.
```

### CODE REVIEW

**Comment by rongrong** [comment]
Only the first commit is needed to fix the issue. But I figured it's nice to include `hashCode` in `Block.toString` functions anyways.

**Review by highker — APPROVED** [review]

**Review by kaikalur — CHANGES_REQUESTED** [review]
Given that convoluted class organization of Block, I suggest adding a utility class/function that takes a block and returns toString based on instanceof check with an assert if none of the instances match so we can catch any new block subclasses added quickly and more importantly that will just fail instead of potentially incorrect results.

**Comment by kaikalur** [comment]
> Given that convoluted class organization of Block, I suggest adding a utility class/function that takes a block and returns toString based on instanceof check with an assert if none of the instances match so we can catch any new block subclasses added quickly and more importantly that will just fail instead of potentially incorrect results.

OK I see you are not using the toString. Maybe they don't belong in this PR?

**Review by kaikalur — APPROVED** [review]
LGTM

**Pull request merged**
