### PR TITLE
OrcWriter close errors are masked

### PR DESCRIPTION
**Pull request by arunthirupathi**
If there are errors in the ColumnWriter close, it is masked by reset's checkState
https://github.com/prestodb/presto/blob/master/presto-orc/src/main/java/com/facebook/presto/orc/writer/SliceDictionaryColumnWriter.java#L559

This change Split's the code into flushColumnWriters and rest, so that flushColumnWriters can be moved outside of the
try block. Previously any failure in the flushColumnWriters part would have been masked  by the reset's IllegalStateException.

It is tedious to write test for this use case, unless the column writers are refactored into the ColumnWriterFactory and the factory is injected. So will rely on the existing tests. I spent close to an hour trying to find a suitable place to inject failure and found none.

This regression was introduced in https://github.com/prestodb/presto/pull/13508

Other approach to this problem is make reset not throw, but I am not sure what the implications of such a change would be.

Test plan - (Please fill in how you tested your changes)

Please make sure your submission complies with our [Development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [Formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), and [Commit Message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests) guidelines. Don't forget to follow our [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution) for any code copied from other projects.

Fill in the release notes towards the bottom of the PR description.
See [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) for details.

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by sdruzkin — COMMENTED** [review]
I don't understand why do we need the `finally` block in `flushStripe()`. If `flushStripe` or `writeRecord` failed, then there is no way to recover the writer back to a healthy state. As I understand the whole writer should be discarded in case of a failure.

Specifically for this issue I'd look into removal of surrounding try-catch statement, then there would be no chance for masking.

**Comment by arunthirupathi** [comment]
> I don't understand why do we need the `finally` block in `flushStripe()`. If `flushStripe` or `writeRecord` failed, then there is no way to recover the writer back to a healthy state. As I understand the whole writer should be discarded in case of a failure.
> 
> Specifically for this issue I'd look into removal of surrounding try-catch statement, then there would be no chance for masking.

I started with that exactly, but then changed the fix, after looking at https://github.com/prestodb/presto/pull/13508

**Comment by sdruzkin** [comment]
> I started with that exactly, but then changed the fix, after looking at #13508
Interesting enough, that PR #13508 "Close ColumnWriters in OrcWriter when IOException is thrown" doesn't have any code for closing.

By moving `flushColumnWriters` out of `bufferedBytes` you probably broke the memory accounting happening in the `finally` of `flushStripe`. Please double-check it.

Imho this method and the write method should be reworked in something like this:
1. Extract `columnWriters.forEach(ColumnWriter::close)` into a separate method.
2. Extract `columnWriters.forEach(ColumnWriter::reset)` into a separate method.
3. Call close-/resetColumnWriters from the `try` based on the flushReason. Right now it's not clear what and where happening with the column writers.
4. In case of an error -> close and discard everything. Right now we leave it hanging around, that can cause issues downstream.
5. Decide what to do with the accounting from the `finally` block.

This would make it a bit more clear and would let it explicitly support failures. 

Would be nice to do similar discarding in case of failure in the `write`, but I understand that this is a bit out of scope of this PR.

**Comment by arunthirupathi** [comment]
@sdruzkin  Thanks for the hint on the memory accounting. I investigated it and the memory accounting is fine.

If the stream is closed successfully, then the memory accounting happens prior to this change. If the stream closing fails, the writer is in invalid state and need to be discarded anyway.

Now on looking closer at the previous change, the previous change assumes that, while flushing a stripe if the IO fails, it expects the writer to reset before the stripe was flushed, so that it can retry the stripe by sending the same data again. This is incorrect. Because most of the time, IO makes no guarantees that when it fails the data is not written. It could be partial failure (partial data is written) or the write actually succeeded but it still returned an error.

The best option would be to revert the original PR.

**Comment by zzhao0** [comment]
this feels counterintuitive to me that the logic will call close() then reset() even for the happy path.

previous PR explained that reset() has check on !closed, but I don't see it now. Likely i'm completely missing something here?

**Comment by arunthirupathi** [comment]
Synced up with @zzhao0  offline. Two writers SliceDictionaryColumnWriter and SliceDirectColumnWriter have this assert.

The options here are (in my order of preference are)
1. Revert the original PR https://github.com/prestodb/presto/pull/13508
2. Ship this PR.
3. Remove the asserts in the writers.

**Comment by yingsu00** [comment]
@wenleix Will you be able to take a look at this PR?

**Comment by bhhari** [comment]
The change looks safe to me, should not change any existing behavior other than moving the close related exception out of the try.

**Review by bhhari — APPROVED** [review]

**Review by highker — APPROVED** [review]
LGTM

**Pull request merged**
