### PR TITLE
[Verifier] Fix broken link in presto-verifier README

### PR DESCRIPTION
**Pull request by palashgoel7**
Fix broken link in presto-verifier README

Test plan - (Please fill in how you tested your changes)
Checked that the link works in my fork

Please make sure your submission complies with our [Development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [Formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), and [Commit Message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests) guidelines.

Fill in the release notes towards the bottom of the PR description.
See [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) for details.

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by rongrong — APPROVED** [review]
Thanks for fixing this! Do you mind changing the commit title to `Fix broken link in presto-verifier README`? Thanks!

**Comment by palashgoel7** [comment]
> Thanks for fixing this! Do you mind changing the commit title to `Fix broken link in presto-verifier README`? Thanks!

Fixed

**Review by caithagoras — APPROVED** [review]

**Comment by caithagoras** [comment]
The Facebook Integration test failure seems unrelated, but could you rebase? Thanks! Will merge once that's green.

**Comment by palashgoel7** [comment]
@caithagoras Yes, rebasing fixed the issue with FB integration. Thanks for the suggestion.

**Pull request merged**
