### PR TITLE
Add row ID support to batch ORC reader

### PR DESCRIPTION
**Pull request by elharo**
## Description
Previously only done in selective reader

## Motivation and Context
Fill in row IDs on more paths

## Impact
none

## Test Plan
CI

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [x] CI passed.

## Release Notes

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by sdruzkin — APPROVED** [review]
LGTM

**Comment by NikhilCollooru** [comment]
Can we add some unit tests ?

**Review by NikhilCollooru — DISMISSED** [review]

**Review by elharo — COMMENTED** [review]
PTAL. Adding unit tests invalidated existing approvals.

**Review by NikhilCollooru — APPROVED** [review]

**Comment by NikhilCollooru** [comment]
The test added in this PR is failing . please check

```
Method TestHivePageSourceProvider.testCreatePageSource_withRowIDMissingPartitionComponent()[pri:0, instance:com.facebook.presto.hive.TestHivePageSourceProvider@c017175] should have thrown an exception of type class java.lang.IllegalArgumentException
	at org.testng.internal.invokers.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:81)
	at org.testng.internal.invokers.TestInvoker.considerExceptions(TestInvoker.java:853)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:714)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    TestHivePageSourceProvider.testCreatePageSource_withRowIDMissingPartitionComponent » Test 
Method TestHivePageSourceProvider.testCreatePageSource_withRowIDMissingPartitionComponent()[pri:0, instance:com.facebook.presto.hive.TestHivePageSourceProvider@c017175] should have thrown an exception of type class java.lang.IllegalArgumentException
[INFO] 
Error:  Tests run: 2976, Failures: 1, Errors: 0, Skipped: 90
```

**Comment by elharo** [comment]
Fixed. Unfortunately that invalidates existing approvals. :-(

**Comment by elharo** [comment]
Remaining failure looks flaky, rerunning

**Pull request merged**
