### PR TITLE
[docs] Fix header formatting in docs files

### PR DESCRIPTION
**Pull request by steveburnett**
## Description
Fixed title and header formatting that produces errors during a build of the docs. I started to make a very few minor text changes, but realized that applying consistency for those text changes would a) take a lot longer and b) not reduce the number of errors in the build, so I stopped doing that. 

Example error that I fixed in this PR: 

``/Users/steveburnett/Documents/GitHub/presto/presto-docs/src/main/sphinx/overview/concepts.rst:34: WARNING: Title underline too short.``

## Motivation and Context
These errors don't stop the build but they're annoying me and it's an easy and low-risk fix. 

## Impact
Local docs build, before the changes in this PR: 
``build succeeded, 730 warnings.``

After:
``build succeeded, 677 warnings.``

## Test Plan
Local docs build (resulting in statements in Impact. Also, CI. 

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [x] CI passed.

## Release Notes
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by elharo — APPROVED** [review]

**Review by agrawalreetika — APPROVED** [review]
Yeah, I have observed these types of warnings as well and tried to fix few in my past docs PRs. 
Thanks for this PR. LGTM 👍🏻 

Just checking, are we planning to suppress those existing 677 warnings as well in future PRs?

**Comment by steveburnett** [comment]
> Yeah, I have observed these types of warnings as well and tried to fix few in my past docs PRs. Thanks for this PR. LGTM 👍🏻
> 
> Just checking, are we planning to suppress those existing 677 warnings as well in future PRs?

Over time, yes! I'd like to get most or all the errors that cause these various warnings fixed eventually. This was a quick low-effort fix of one set of the errors, and I limited the scope of this PR to fixing ``Title underline too short`` errors in the doc builds for a simpler PR and an even simpler review process.

**Review by tdcmeehan — APPROVED** [review]
Thank you @steveburnett

**Comment by steveburnett** [comment]
It appears that updating the Presto docs Sphinx theme in #22887 fixed another 24 docs build warnings: my new local docs build with that and this PR both merged results in 
``build succeeded, 653 warnings.`` down from 730. So that's nice.

**Pull request merged**
