### PR TITLE
Remove VisibleForTesting annotation

### PR DESCRIPTION
**Pull request by leoluan2009**
Remove VisibleForTesting annotation in createSqlTaskExecution method in the class of SqlTaskExecution. 
This patch will fix the issue #10404

### CODE REVIEW

**Comment by mbasmanova** [comment]
@leoluan2009 Could you sign up the CLA at https://code.facebook.com/cla ?

There is a checkstyle error:

https://travis-ci.org/prestodb/presto/builds/367520418?utm_source=github_status&utm_medium=notification

[INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle) @ presto-main ---
[INFO] There is 1 error reported by Checkstyle 8.7 with checkstyle/airbase-checks.xml ruleset.
[ERROR] src/main/java/com/facebook/presto/execution/SqlTaskExecution.java:[33,8] (imports) UnusedImports: Unused import - com.google.common.annotations.VisibleForTesting.

**Comment by mbasmanova** [comment]
@leoluan2009 The change looks good. Could you squash the commits?

Also, consider shortening commit title to "Remove VisibleForTesting annotation"

**Comment by leoluan2009** [comment]
hi @mbasmanova ,
I have changed the commit title. 
Also I am new to Github, so I do not know how to squash the commits, could you give me some steps or doc ? thanks for you help.

**Comment by mbasmanova** [comment]
@leoluan2009 

I'm using interactive rebase to squash commits. First, start interactive rebase with this command:

> git commit -i HEAD~3

, then follow the instructions on the screen to mark 2 commits with `s` (squash), save and exit. 

To update commit message, I use `git commit --amend`.

I see the PR title updated, but commit messages are not. It is a bit confusing, but PR title is a separate thing from commit title.

**Comment by martint** [comment]
I squashed the commits, fixed the commit message and merged it. Thanks!

**Pull request closed without merging**
