### PR TITLE
Use same window operator for identical window specifications

### PR DESCRIPTION
**Pull request by harunurhan**
#4358 
I tested in on a random table from tpch.
Before plan:
```
presto:sf100> explain SELECT rank() OVER (PARTITION BY tax), dense_rank() OVER (PARTITION BY tax) FROM lineitem;
                                                     Query Plan                                                     
--------------------------------------------------------------------------------------------------------------------
 - Output[_col0, _col1] => [rank:bigint, dense_rank:bigint]                                                         
         _col0 := rank                                                                                              
         _col1 := dense_rank                                                                                        
     - Exchange[GATHER] => rank:bigint, dense_rank:bigint                                                           
         - Project => [rank:bigint, dense_rank:bigint]                                                              
             - Window[partition by (<tax>)] => [tax:double, rank:bigint, $hashvalue_9:bigint, dense_rank:bigint]    
                     dense_rank := dense_rank()                                                                     
                 - Project => [tax:double, rank:bigint, $hashvalue_9:bigint]                                        
                         $hashvalue_9 := "combine_hash"(0, COALESCE("$operator$hash_code"("tax"), 0))               
                     - Window[partition by (tax)] => [tax:double, $hashvalue:bigint, rank:bigint]                   
                             rank := rank()                                                                         
                         - Exchange[REPARTITION] => tax:double, $hashvalue:bigint                                   
                             - Project => [tax:double, $hashvalue:bigint]                                           
                                     $hashvalue := "combine_hash"(0, COALESCE("$operator$hash_code"("tax"), 0))     
                                 - TableScan[tpch:tpch:lineitem:sf100.0, originalConstraint = true] => [tax:double] 
                                         tax := tpch:tax    
```

After plan
```
presto:sf100> explain SELECT rank() OVER (PARTITION BY tax), dense_rank() OVER (PARTITION BY tax) FROM lineitem;
                                                 Query Plan                                                  
-------------------------------------------------------------------------------------------------------------
 - Output[_col0, _col1] => [rank:bigint, dense_rank:bigint]                                                  
         _col0 := rank                                                                                       
         _col1 := dense_rank                                                                                 
     - Exchange[GATHER] => rank:bigint, dense_rank:bigint                                                    
         - Project => [rank:bigint, dense_rank:bigint]                                                       
             - Window[partition by (tax)] => [tax:double, $hashvalue:bigint, rank:bigint, dense_rank:bigint] 
                     rank := rank()                                                                          
                     dense_rank := dense_rank()                                                              
                 - Exchange[REPARTITION] => tax:double, $hashvalue:bigint                                    
                     - Project => [tax:double, $hashvalue:bigint]                                            
                             $hashvalue := "combine_hash"(0, COALESCE("$operator$hash_code"("tax"), 0))      
                         - TableScan[tpch:tpch:lineitem:sf100.0, originalConstraint = true] => [tax:double]  
                                 tax := tpch:tax     
```

I hope I didn't miss anything, because I am not so familiar how planner works.

Also I have some doubts:

- Using `.forEach` looks cleaner to me here https://github.com/facebook/presto/compare/master...harunurhan:fix4358#diff-21d31cb9d487772413eff4f67b8555deR475 ,but code is full of for each loops, should I use for-each loop instead?
- Is putting all window functions with window as key into a Muptimap in forEach good here or should I use `Multimaps.index` instead to group window functions by window 
- I didn't go too much into details but I guess stuff between https://github.com/facebook/presto/compare/master...harunurhan:fix4358#diff-21d31cb9d487772413eff4f67b8555deR499 and https://github.com/facebook/presto/compare/master...harunurhan:fix4358#diff-21d31cb9d487772413eff4f67b8555deR550 loops, must be done between, in other words these loops can't be merged right?

Thanks in advance for responses.

### CODE REVIEW

**Comment by martint** [comment]
@erichwang, can you review this?

**Comment by akshatnair** [comment]
Is there a way you can test this? If so then add that test.

**Comment by maciejgrzybek** [comment]
I would merge both loops: https://github.com/prestodb/presto/compare/master...harunurhan:fix4358#diff-21d31cb9d487772413eff4f67b8555deR499 and https://github.com/prestodb/presto/compare/master...harunurhan:fix4358#diff-21d31cb9d487772413eff4f67b8555deR550 since the latter does not depend on any rewrites to partition, order, nor frame.
@akshatnair I'd add a test covering execution of two window functions in one query. To make sure results are the same before and after this change. This could be written using `LocalQueryRunner`.

What about some benchmarks? Do we need any microbenchmarks for it?

**Comment by erichwang** [comment]
@harunurhan awesome! This is something that we have needed for some time. A couple comments:
1) This type operation is best suited (and more easily implemented) as an optimizer. The optimizer can just look for 2 window functions that are next to each other and merge them if they have the same specifications. For example: see SetFlatteningOptimizer or MergeProjections
2) As mentioned above, you are definitely going to want to add some tests for the different cases here.

**Comment by martint** [comment]
One this goes in, we can add tests that verify we get the expected plan: https://github.com/prestodb/presto/pull/4404

**Comment by petroav** [comment]
Closing because https://github.com/prestodb/presto/pull/5463 got merged.

**Pull request closed without merging**
