### PR TITLE
Allow to extend Kafka connector

### PR DESCRIPTION
**Pull request by yangy0000**
cherry-pick of https://github.com/trinodb/trino/commit/92e8b7b6a1b16b66ff00a87e7fe494f08db97f46

Co-Authored-By: Grzegorz Kokosiński <7569403+kokosing@users.noreply.github.com>

Planned to cherry-pick https://github.com/trinodb/trino/commit/0e379a36959dcd6676a4a1cdba2608f360a24d52 that depends on this PR.

### CODE REVIEW

**Review by beinan — APPROVED** [review]
Looks good to me, thank you for the cherry-pick @yangy0000 !

**Comment by dborkar** [comment]
@beinan can you merge in ?

**Comment by dborkar** [comment]
@zhenxiao @beinan @highker can you please merge. thx.

**Comment by dborkar** [comment]
Also @tdcmeehan if you can.

**Pull request merged**
