### PR TITLE
Add function to return Nth instance of substring

### PR DESCRIPTION
**Pull request by codope**
Implements issue [10771](https://github.com/prestodb/presto/issues/10771)
@rongrong Could you please review? I have rebased my changes on top of master and squashed all commits into one.

### CODE REVIEW

**Comment by rongrong** [comment]
Generally looks good. Thanks for working on this! Sorry that I didn't clarify earlier. After discussing with the team, we adjusted the syntax to introduce a `strrpos` rather than allowing negative instance. The issue is updated with the latest syntax. I should have given you a heads up. Sorry about that. Do you mind updating the PR accordingly?

Thanks!

**Comment by codope** [comment]
Sure, no problem. I will update the PR this weekend.

**Comment by rongrong** [comment]
@codope  Seems like you didn't do a `git pull --rebase upstream master`. That would remove the existing commits in master from this branch. Thanks!

**Comment by codope** [comment]
@rongrong It was a rookie mistake. I did `git rebase upstream/master` but then git push "failed to push some refs." Here, instead of doing git push -f i did git pull and then it polluted my branch. 
Anyway could you please review [#12707](https://github.com/prestodb/presto/pull/12707) and merge, if everything looks good.

**Pull request closed without merging**
