### PR TITLE
Use airbase flags for checkstyle defaults

### PR DESCRIPTION
**Pull request by electrum**

### CODE REVIEW

**Comment by ArturGajowy** [comment]
I'm not sure how, but I believe this works :) LGTM as long as you've tested that pass `-Dair.check.skip-all=true` disables checkstyle analysis and that the analysis runs otherwise

**Comment by electrum** [comment]
@ArturGajowy Yep, I verified this

**Comment by electrum** [comment]
```
$ mvn validate -pl .
...
[INFO] --- maven-checkstyle-plugin:2.17:check (default) @ presto-root ---
[INFO] Starting audit...
Audit done.
[INFO] 

$ mvn validate -pl . -Dair.check.skip-all
...
[INFO] --- maven-checkstyle-plugin:2.17:check (default) @ presto-root ---
[INFO] 

$ mvn validate -pl . -Dair.check.skip-basic
[INFO] --- maven-checkstyle-plugin:2.17:check (default) @ presto-root ---
[INFO] 
```

**Comment by electrum** [comment]
Another trick is you can run Maven with `-X` and it will show you the plugin config:
```
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (default)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
...
  <skip default-value="false">false</skip>
...
</configuration>

**Pull request closed without merging**
