### PR TITLE
Implement JDBC PreparedStatement.getMetaData

### PR DESCRIPTION
**Pull request by adamjshook**
Addresses #14029 

```
== RELEASE NOTES ==

JDBC Changes
* Adds PreparedStatement support for getMetaData
```

### CODE REVIEW

**Comment by aweisberg** [comment]
After you sign the CLA you will need to push an update to get the bot to notice you signed.

The commit also needs to be authored by you and co-authored by the original author.

Commit message should be <= 50 characters and not end with a period.

**Comment by adamjshook** [comment]
@aweisberg Thank you for the review.  The `ColumnInfo` here wants a `TypeSignature` whereas PrestoSQL wants a `ClientTypeSignature`.  There is additional functionality there to convert the type string into a `ClientTypeSignature`.  The difference to the user, from what I can tell, is that complex types like rows and maps do not have the full information in PrestoSQL, e.g. this commit returns `row(x integer, y array(integer))` where as PrestoSQL returns `row`.

As far as the test coverage, I noticed there are some `TODO` items related to date types with time zones here and I was curious if `getMetaData` would be unable to return those types.  Seems like it works okay.

**Comment by adamjshook** [comment]
@aweisberg Any more changes suggested? Or is it ok to merge? Thank you!

**Comment by rschlussel** [comment]
The Type class was moved to a different package, and I think that's what's causing the travis failure.  Can rebase on master and fix the import.  Code otherwise looks good

**Comment by adamjshook** [comment]
Thank you @rschlussel!  Back at you for another review.

**Pull request merged**
