### PR TITLE
WIP Very preliminary work in progress for presto query queues

### PR DESCRIPTION
**Pull request by elonazoulay**
This is a very preliminary work in progress for presto query queues.

### CODE REVIEW

**Comment by elonazoulay** [comment]
Submitting update shortly, this is still in a very preliminary state.

**Comment by cberner** [comment]
Adding configs to `QueryManagerConfig` is not the right way to do this. That approach is deprecated. Instead it should be loaded from JSON or a database. Before adding it to the JSON file format though, we need to redo the format to be better aligned with the features that resource groups support. In particular, queues (resource groups) will have to form a tree

**Comment by cberner** [comment]
Also, the build is failing

**Comment by elonazoulay** [comment]
Will fix the build and redo the format.

**Comment by cberner** [comment]
Can you split out just the changes that load the configs from a database, and I'll review those first?

**Comment by cberner** [comment]
Can you rebase and then submit a PR for the DB changes, and a separate one for new features?

**Pull request closed without merging**
