### PR TITLE
Remove unused methods from Metadata

### PR DESCRIPTION
**Pull request by kokosing**
Remove unused methods from Metadata

### CODE REVIEW

**Comment by electrum** [comment]
If we're going to remove this, we should also remove `TableIdentity` and `ColumnIdentity`. This was part of the materialized query table work which has since been abandoned, so I'm fine with removing, but we can wait a bit and see if anyone else objects.

**Comment by kokosing** [comment]
@joy-yao I saw you introduced these entities, are you ok with removing them?

**Comment by kokosing** [comment]
@electrum I applied your suggestion. Do you we are ok to move this in?

**Comment by kokosing** [comment]
ping

**Comment by kokosing** [comment]
Rebased

**Pull request merged**
