### PR TITLE
[Document] how to install Presto on an M1 Mac using Homebrew

### PR DESCRIPTION
**Pull request by steveburnett**
## Description
- Adds instructions of how to install Presto onto an M1 chip Mac to the existing doc how to install Presto onto an Intel chip Mac. 
- Reformats some of the existing text in how to install Presto onto an Intel chip Mac for consistency. 

## Motivation and Context
While working on #20518 , @yhwang tested the steps in install Presto on Intel Macs by using Rosetta to install onto an M1 Mac. 

I asked @yhwang to walk me through how he tested #20518 (thank you!) and I felt that it would be valuable to document this install process. 

## Impact
Users new to Presto who have M1 chip Macs will be able to install and run Presto successfully.

## Test Plan
Developed and tested all steps on an M1 CPU MacBook Pro running OS X.

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [x] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by tdcmeehan — APPROVED** [review]
LGTM!

**Comment by yhwang** [comment]
@steveburnett LGTM!

one minor input is:
Not sure if you want to mention Rosetta, since that is required for the M1/M2 Mac?

**Review by yhwang — APPROVED** [review]

**Comment by steveburnett** [comment]
@yhwang thanks for the review, and also my thanks for your showing me how to do this in the first place!

Great question about Rosetta. I had decided not to mention Rosetta because: 

1) If Rosetta is already present on the user's Mac, they don't have to do anything.
2) If Rosetta is not present Apple will prompt, download, and install Rosetta with minimal user interaction.
3) It's not a third-party issue - Apple detects if it's needed and guides the user through install. 
Note: this is the important one for me: if Rosetta was not managed by the native OS I would definitely have included it in the docs.
3) Pre-installing Rosetta, as you showed me from the command line, is one more command that the user can potentially type wrong, so let's rely on Apple's built-in process as likelier to succeed for the user. 

Does that make sense to you? I'm open to adding Rosetta in the doc if you feel differently, let me know!

**Comment by yhwang** [comment]
good points. sold!
Because my system already has Rosetta, I actually don't know about the item 2 you mentioned. Thanks for the explanation.

**Pull request merged**
