### PR TITLE
Fix kafka issue when query with time range

### PR DESCRIPTION
**Pull request by liusuquan**
```
== NO RELEASE NOTE ==
when exec this SQL like selce * from kafkatop where __timestamp > 152332342442, exception will  happen for kafka connector ;
```

### CODE REVIEW

**Comment by ajaygeorge** [comment]
@liusuquan Can you please post the exception stacktrace you saw.

**Comment by liusuquan** [comment]
> @liusuquan Can you please post the exception stacktrace you saw.
when i run sql  "select * from nfv where _timestamp > 1595819333261"

com.facebook.presto.spi.PrestoException: Cannot list splits for table 'nfv' reading topic 'test3'
        at com.facebook.presto.kafka.KafkaSplitManager.getSplits(KafkaSplitManager.java:143)
        at com.facebook.presto.split.SplitManager.getSplits(SplitManager.java:87)
        at com.facebook.presto.split.CloseableSplitSourceProvider.getSplits(CloseableSplitSourceProvider.java:51)
        at com.facebook.presto.sql.planner.SplitSourceFactory$Visitor.lambda$visitTableScan$0(SplitSourceFactory.java:152)
        at com.facebook.presto.sql.planner.LazySplitSource.getDelegate(LazySplitSource.java:96)
        at com.facebook.presto.sql.planner.LazySplitSource.getConnectorId(LazySplitSource.java:48)
        at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStageScheduler(SectionExecutionFactory.java:281)
        at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStreamingLinkedStageExecutions(SectionExecutionFactory.java:243)
        at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStreamingLinkedStageExecutions(SectionExecutionFactory.java:221)
        at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createSectionExecutions(SectionExecutionFactory.java:167)
        at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.createStageExecutions(LegacySqlQueryScheduler.java:268)
        at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.<init>(LegacySqlQueryScheduler.java:158)
        at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.createSqlQueryScheduler(LegacySqlQueryScheduler.java:117)
        at com.facebook.presto.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:441)
        at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:315)
        at com.facebook.presto.$gen.Presto_0_237_e369a5a____20200727_022017_1.run(Unknown Source)
        at com.facebook.presto.execution.SqlQueryManager.createQuery(SqlQueryManager.java:231)
        at com.facebook.presto.dispatcher.LocalDispatchQuery.lambda$startExecution$4(LocalDispatchQuery.java:106)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Invalid Kafka Offset start/end pair: **1595819333261 - 0**
        at com.facebook.presto.kafka.KafkaSplitManager.getSplits(KafkaSplitManager.java:109)
        ... 20 more

**Comment by ajaygeorge** [comment]
Thanks @liusuquan 

Wondering why the endTimeStamp is not getting set from here : https://github.com/prestodb/presto/blob/29acdbaff128fff2de185c28fb26031be1d88019/presto-kafka/src/main/java/com/facebook/presto/kafka/KafkaMetadata.java#L224

Is that a valid scenario?

cc @zhenxiao who reviewed the Kafka connector upgrade PR.

**Comment by zhenxiao** [comment]
thank you for catching it, @liusuquan 
could you please add testcase in the second commit?

**Pull request closed without merging**
