### PR TITLE
Bump Apache Iceberg from 0.14.0 to 0.14.1

### PR DESCRIPTION
**Pull request by snazy**
Test plan - CI

```
== RELEASE NOTES ==

General Changes
* Bump Apache Iceberg from 0.14.0 to 0.14.1
```

### CODE REVIEW

**Review by ChunxuTang — APPROVED** [review]
LGTM. @snazy Thanks for your contribution!
Would you mind rerunning the tests to pass all checks?

**Comment by snazy** [comment]
Hm, seems I cannot just rerun the tests, so I force-pushed the PR again.

**Comment by snazy** [comment]
Oh, looks like there are legit failures. Making this a draft PR.

**Review by nastra — APPROVED** [review]

**Review by beinan — APPROVED** [review]
lgtm, thx!

**Pull request merged**
