### PR TITLE
Make planner tests use iterative optimizer

### PR DESCRIPTION
**Pull request by findepi**

### CODE REVIEW

**Comment by ArturGajowy** [comment]
One concern though is the impact of this on test times

**Comment by findepi** [comment]
Planning tests' times will surely ~double.

**Comment by ArturGajowy** [comment]
>Planning tests' times will surely ~double at the "cost" of increased coverage.

No way... :D I've seen the travis build passed in a reasonable time, so my concerns are no longer :)

**Comment by findepi** [comment]
> I am not sure if we need this, while legacy is disabled by default I am not sure we need to test it

Sure. Alternativele we could test with iterative _only_, but it's just not the case now.

@martint, what do you think?

**Comment by martint** [comment]
Agreed, I don't think we need this. For optimizers where there's an option, tests should run against the iterative version (the legacy version should be removed within a few releases once the iterative is proven to work well in production).

If there are tests that are not running the iterative version, we need to fix them.

**Comment by findepi** [comment]
@martint, OK. Tests extending `BasePlanTest` (eg `TestReoderJoins`) all use
non-iterative. I will change `BasePlanTest` to default to iterative then.

**Comment by findepi** [comment]
I pulled @ArturGajowy's commit from #7536 instead of mine.

**Comment by findepi** [comment]
The reason I needed this was i was based on `teradata:master`. In `prestodb:master` @martint's 264424778a2dffb0a6642bac66049a3b61b9fe56 obsoletes this.

**Pull request closed without merging**
