### PR TITLE
Fixes in product tests execution script c'ed

### PR DESCRIPTION
**Pull request by maciejgrzybek**
Supersedes https://github.com/prestodb/presto/pull/8685

### CODE REVIEW

**Comment by kokosing** [comment]
It would be nice to test this with presto checks. But I dont know how to do it without the merge.

**Comment by kokosing** [comment]
Ups... there are product tests failures for LDAP. There is still something missing.

**Comment by maciejgrzybek** [comment]
Product tests fixed, commits squashed.
@kokosing in order to run presto-checks on non-master branch, simply use `presto-trigger-travis-checks` job on our internal Jenkins. Make sure that Travis build finishes first, before you trigger presto-checks because they rely on artifacts being uploaded to S3.
I'll run presto-checks once the build finishes here.

**Comment by maciejgrzybek** [comment]
I changed it a bit because it was failing presto-checks. Now it should be better. I made it so we don't spin up other daemons than `hadoop-master` unless we need them (e.g. `ldap` for `singlenode-ldap` or `sqlserver` for `singlenode-sqlserver`).

Here are the presto checks, all green:
CDH: https://travis-ci.org/Teradata/presto-checks/builds/268112844
HDP: https://travis-ci.org/Teradata/presto-checks/builds/268112803
IOP: https://travis-ci.org/Teradata/presto-checks/builds/268112662

**Comment by kokosing** [comment]
Great, well done! Thank for taking care of this.

**Pull request merged**
