### PR TITLE
[Native] Add missing nodeId in TaskInfo

### PR DESCRIPTION
**Pull request by kewang1024**
```
== NO RELEASE NOTE ==
```

See analysis in https://github.com/prestodb/presto/issues/19229

### CODE REVIEW

**Review by spershin — COMMENTED** [review]
@kewang1024 Thanks for tackling this one!
So, because we've never set any node id, the Coordinator considered all tasks running on just one node?

The change looks good, lets fix the formatting and double-check the failing E2E test query.

**Review by xiaoxmeng — APPROVED** [review]
@kewang1024 Thanks for the change!

**Comment by amitkdutta** [comment]
Thanks @kewang1024 for this change.

**Comment by amitkdutta** [comment]
E2E tests are broken for a different reason. Merging this one.

**Comment by amitkdutta** [comment]
E2E tests are fixed https://github.com/prestodb/presto/pull/19243

**Pull request merged**
