### PR TITLE
Presto ranger plugin

### PR DESCRIPTION
**Pull request by cquptEthan**
#8980 
Presto Ranger Plugin is a SystemAccessControl implementations, this plugin adds Apache Ranger integration support for Presto.
Most code from https://github.com/troels/nz-presto/tree/master/presto-ranger-plugin
I spent sometime dealing with restapi dependency conflict, and adding a column level access control.

As documentation of [system-access-control](https://prestodb.io/docs/current/develop/system-access-control.html) mentioned,  it is configured using an `etc/access-control.properties` file.The `access-control.name` and some ranger property must set in `access-control.properties`.

Example configuration file:

```properties
access-control.name=ranger-access-control
ranger.service.store.rest.url=http://localhost:6080
ranger.service.store.rest.username=admin
ranger.service.store.rest.password=admin
ranger.plugin.presto.policy.rest.url=http://localhost:6080
ranger.plugin.presto.policy.cache.dir=/tmp/presto/policycache
ranger.plugin.presto.service.name=presto
ranger.plugin.presto.policy.source.impl=org.apache.ranger.admin.client.RangerAdminRESTClient
```

A ranger plugin for presto must be add in your ranger admin. 
This plugin must have 4 resources, `catalog`,`database`,`table` and `column`.

### CODE REVIEW

**Comment by tooptoop4** [comment]
Does this require kerberos to work? Are any ranger-side commits required ie https://jira.apache.org/jira/browse/RANGER-1784?

**Comment by gray-eb** [comment]
I'm confused on how the configuration is accomplished on the Ranger admin side. What url would be used for the jdbc url defined in the example configuration?

**Comment by cquptEthan** [comment]
@tooptoop4 
Ranger don't have a function for identity authentication, it is just a authority authentication.
It support kerberos, but dosen't require kerberos to work. 
You can use kerberos or other identity authentications,and then you should add policy for user in ranger with kerberos principle or presto username.

For ranger-side, you can follow this [README](https://github.com/cquptEthan/presto/blob/presto-ranger-plugin/presto-ranger-plugin/README.md) to add a custom ranger-presto-plugin.It needs impl a _RangerServicePresto_ for _RangerBaseService_.

**Comment by tooptoop4** [comment]
gentle ping

**Pull request closed without merging**
