### PR TITLE
 Update Airlift to 0.202

### PR DESCRIPTION
**Pull request by ShashwatArghode**
Depends on https://github.com/facebookexternal/presto-facebook/pull/1721
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by aweisberg — APPROVED** [review]

**Comment by aweisberg** [comment]
@highker can you merge this?

**Comment by ShashwatArghode** [comment]
Messed up the branch by mistakenly using it for other changes, have restored it.
Sorry for the inconvenience.

**Comment by aweisberg** [comment]
I just rebased (this and the presto-facebook), deployed and tested this on a cluster.

@ajaygeorge waiting for the tests to finish.

**Comment by aweisberg** [comment]
@highker All tests passing here and in presto-facebook. Can you merge this?

**Pull request merged**
