### PR TITLE
Add several improvements to the Accumulo connector

### PR DESCRIPTION
**Pull request by adamjshook**
- Add ExecutorServices for index/metric retrieval
- Add short circuit feature for metrics fetch
- Add row-based threshold for lowest cardinality usage
- Add a new `ValueSummingIterator` to sum metrics on the server side
- Remove unused tracking of first and last row ID
- Improve ingestion API via a PrestoBatchWriter
- Refactor and create abstract metrics storage
- Add timestamp truncation feature
- Add a maximum limit to the index lookup

### CODE REVIEW

**Comment by adamjshook** [comment]
This is a collection of various improvements we have made to the Accumulo connector since the initial PR.  Sorry to drop a bunch of code on you all -- I can try and break it up into a series of more digestible chunks, if desired.

**Comment by dain** [comment]
Can you add a bit on how each of the changes above help (so more why over what)?

**Comment by adamjshook** [comment]
- Add `ExecutorServices` for index/metric retrieval

The index and metric retrievals were previously done serially, but we can improve query planning time by adding an `ExecutorService` for both processes.  For each column with a predicate, the metrics are queried in parallel, and then the index is queried in parallel if need be.  The additional parallelism gave us significant gains in query planning time.

- Add short-circuit feature for metrics fetch

When querying the metrics (now in parallel), a thread with a low cardinality would often finish before the others.  This thread's value would satisfy the "low cardinality threshold", meaning that we are just going to use this column's row IDs and let Presto filter out the rest (vs. row ID intersection).  With the addition of the `ExecutorService`, we can not continue with query planning using this individual column while the other threads finish retrieving the metrics which are then cached by Guava.

- Add row-based threshold for lowest cardinality usage

As our tables grew, the percentage-based threshold for using the lowest cardinality column would result in many row IDs.  It was decided that adding a fixed "number of row IDs" as well as the percentage would give users enough flexibility to tune their queries.

- Add a new `ValueSummingIterator` to sum metrics on the server side

Previously, metrics were being fetched from Accumulo and aggregated on the client side.  We developed a new server-side iterator that pushes a bulk of this aggregation to Accumulo, summing the values across all keys and returning a partial sum.  The client then aggregates the final sum, reducing the overall query planning time.

- Remove unused tracking of first and last row ID

There was some additional metadata that were tracking the first and last row IDs in the table, information that Accumulo itself does not have.  This was being used in the past, but the use of it was eventually dropped.  We kept it in, but we don't see us using this in the future.  Best to remove it.

- Improve ingestion API via a `PrestoBatchWriter`

Third-party applications typically do the data ingestion, and the API was not very clean and unified to ingest the data, indices, and metrics.  The new `PrestoBatchWriter` simplifies this process and aligns how Presto writes data with how the other applications will write data.

- Refactor and create abstract metrics storage

We refactored the metrics storage to remove the tight coupling from the indexing code, as well as allowing for additional methods for storing the metrics.  We’ve got a prototype of storing metrics in Redis (instead of Accumulo), but it isn’t ready for use.

- Add timestamp truncation feature

Event record time is typically the column that was to be used in the index, but the millisecond precision of the cardinality metric was too fine-grained, requiring millions of numbers to be aggregated for the final metric.  By truncating timestamps from millisecond to second, minute, hour, and day levels, then storing and aggregating metrics at these levels, we are able to reduce query planning time by querying the rolled-up entries.

- Add a maximum limit to the index lookup

Some queries would fetch tens of millions of row IDs from the index tables, causing the coordinator to crash.  This adds a configurable hard limit to avoid pulling rows from the index table, preferring to use other columns or a full table scan.

**Comment by adamjshook** [comment]
@dain I think we may be better off incrementally adding PRs for these various features.  It's a lot to take in at once -- I don't want to have this sit for a while and end up with another batch of features to contribute back.  Thoughts?

**Comment by adamjshook** [comment]
Going to close this in favor of smaller PRs for each feature.  I'll open the first PR sometime soon.

**Pull request closed without merging**
