### PR TITLE
First cut port of reading/storing column stats for Glue metastore

### PR DESCRIPTION
**Pull request by aaneja**
Draft PR. TODO
- Test stats for multiple glue tables
- Fixup commit to attribute sources

### CODE REVIEW

**Comment by majetideepak** [comment]
@aaneja  how is this related to analyze stats? Can you clarify the scope?

**Comment by wanglinsong** [comment]
@aaneja we need to merge this into master asap. Catalog settings have been updated to use `hive.metastore.glue.column-statistics-enabled=true`, which is not supported in OSS now. This will cause deployment failures.

**Comment by wanglinsong** [comment]
@aaneja can you create another PR with master as the base branch?

**Comment by aaneja** [comment]
> @aaneja can you create another PR with master as the base branch?

Hey @wanglinsong I will connect with you offline for this

**Comment by v-jizhang** [comment]
@prestobot kick off tests

**Pull request closed without merging**
