### PR TITLE
[native] Add new shared arbitrator configs

### PR DESCRIPTION
**Pull request by tanjialiang**
Adding new arbitrator configs to presto native, in preparation of utilizing the new config mechanism for memory arbitrator, and deprecating the old ones.
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by xiaoxmeng — APPROVED** [review]
@tanjialiang LGTM. Thanks!

**Comment by steveburnett** [comment]
Suggest documenting these new native configs in https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/presto_cpp/properties.rst.

**Comment by tanjialiang** [comment]
> Suggest documenting these new native configs in https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/presto_cpp/properties.rst.

Good point, I'll add the missing documentations there.

**Comment by tanjialiang** [comment]
> Suggest documenting these new native configs in https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/presto_cpp/properties.rst.

These configs are currently not in use. So adding the documentations in this PR would not make sense. I will add them in the followup PR in which I remove the old configs and make the switch to the new ones.

**Review by xiaoxmeng — APPROVED** [review]

**Pull request merged**
