### PR TITLE
Resolves #6550: Uncategorized error for from_unixtime

### LINKED ISSUE #6550: Uncategorized error for from_unixtime
```
Invalid offset minutes 1080
java.lang.IllegalArgumentException
    com.facebook.presto.spi.type.TimeZoneKey.checkArgument(TimeZoneKey.java:300)
    com.facebook.presto.spi.type.TimeZoneKey.getTimeZoneKeyForOffset(TimeZoneKey.java:140)
    com.facebook.presto.spi.type.DateTimeEncoding.packDateTimeWithZone(DateTimeEncoding.java:41)
    com.facebook.presto.operator.scalar.DateTimeFunctions.fromUnixTime(DateTimeFunctions.java:149)
    com_facebook_presto_$gen_PageProcessor_14559.project_1(Unknown Source)
    com_facebook_presto_$gen_PageProcessor_14559.process(Unknown Source)
    com.facebook.presto.operator.FilterAndProjectOperator.getOutput(FilterAndProjectOperator.java:111)
    com.facebook.presto.operator.Driver.processInternal(Driver.java:378)
    com.facebook.presto.operator.Driver.processFor(Driver.java:301)
    com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
    com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:534)
    com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:670)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by striderarun**

### CODE REVIEW

**Comment by striderarun** [comment]
@martint  Can you please take a look and review this when you get time?

**Comment by electrum** [comment]
Can you add a test for this?

**Comment by striderarun** [comment]
Added test. Travis seems to be failing the build because of some worker nodes being unavailable. Build is successful on my local though.

**Comment by haozhun** [comment]
`TimeZoneKey.checkArgument` is used in a lot of places. We definitely should not blindly throw `PrestoException(ILLEGAL_FUNCTION_ARGUMENT, ...)`. I'm going to close this PR and briefly explain in the issue on the right approach. Feel free to submit a new PR if you're still interested.

**Pull request closed without merging**
