### PR TITLE
Fix SimpleArrayAllocator to be able to allocate max number of arrays

### PR DESCRIPTION
**Pull request by bhhari**
Fix SimpleArrayAllocator to be able to allocate max number of arrays
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by bhhari** [comment]
> @bhhari I don't think I understand how would this help. Would you explain?

I believe for repartition we are giving 10,000 as max size, so once we allocate it should be <= right, may be I got it wrong on the first look

**Comment by mbasmanova** [comment]
> I believe for repartition we are giving 10,000 as max size, so once we allocate it should be <= right, may be I got it wrong on the first look

@bhhari I'm not sure I understand. Is this fixing the query failure?

**Comment by yingsu00** [comment]
I think we should increase the number of max arrays for arrayAllocator in PagePartitioner

**Comment by mbasmanova** [comment]
@yingsu00 

> I think we should increase the number of max arrays for arrayAllocator in PagePartitioner

Why do we need so many arrays for this query? Could there be a leak? Can you make a TPC-H-based repro?

If we need to raise the limit, then we should make it configurable. 

CC: @tdcmeehan

**Comment by bhhari** [comment]
> > I believe for repartition we are giving 10,000 as max size, so once we allocate it should be <= right, may be I got it wrong on the first look
> 
> @bhhari I'm not sure I understand. Is this fixing the query failure?

Yup, my fix is wrong, read the code wrong. Thanks @mbasmanova

**Comment by tdcmeehan** [comment]
> @yingsu00
> 
> > I think we should increase the number of max arrays for arrayAllocator in PagePartitioner
> 
> Why do we need so many arrays for this query? Could there be a leak? Can you make a TPC-H-based repro?
> 
> If we need to raise the limit, then we should make it configurable.
> 
> CC: @tdcmeehan

Just to provide context, this check was added to alert when there's a memory leak (when arrays aren't being returned when they should be).  If this number of arrays is expected to be allocated, then the limit is already configurable via the constructor argument to SimpleArrayAllocator, otherwise we should investigate the leak.  BTW I also noticed that when we added `byte[]` support we grouped that into the same check with `int[]`, we may want to consider separating the counters to make the error more helpful.

**Comment by mbasmanova** [comment]
@tdcmeehan Tim, thanks for adding context. When I mentioned that the check should be configurable, I meant that we should have a configuration property that allows to change it. Currently, it is hardcoded and cannot be changed without a code change. Agree that it would be helpful to have different counters for different array types.

This is not the right fix and @yingsu00 is going to investigate the issue and come up with a new one. Hence, closing the PR.

**Pull request closed without merging**
