### PR TITLE
Run PruneCountAggregationOverScalar only for single output default aggregation

### PR DESCRIPTION
**Pull request by kokosing**
Run PruneCountAggregationOverScalar only for single output default aggregation

### CODE REVIEW

**Comment by rschlussel** [comment]
Can you explain in the commit message why this change is necessary? (e.g. what cases would have been incorrect before)

**Comment by findepi** [comment]
@rschlussel, @martint this fixes planning failure (issue #8828)

**Comment by rschlussel** [comment]
@findepi @kokosing for the future it would be helpful to include that kind of information in the commit message too, so it's easier when looking back to understand why things changed.

**Comment by kokosing** [comment]
@rschlussel I am sorry about that. I thought that information above that this PR is referenced in issue is enough. Next will I will be more verbose. Generally any invocation of this rule for anything other than ` single output default aggregation` was incorrect.

**Comment by rschlussel** [comment]
no problem :)

**Pull request merged**
