### PR TITLE
Skip Parquet pages if stats does not match predicate

### PR DESCRIPTION
**Pull request by zhenxiao**
```
== RELEASE NOTES ==

Hive Changes
* pushdown predicate at Parquet page level, skip reading parquet pages when page statistics do not match predicate

```

### CODE REVIEW

**Comment by rschlussel** [comment]
@mbasmanova is on vacation until the end of the month.  maybe @yingsu00 can review.

**Comment by yingsu00** [comment]
cc @bhhari @oerling

**Comment by rongrong** [comment]
@oerling  @bhhari  Please take a look.

**Comment by oerling** [comment]
Hi Zhenxiao

 

Are you at the event tomorrow? Let’ catch up and talk about aligning table scan between ORC and Parquet.

 

The PR looks reasonable. You skip ahead on the column until there is something that matches the predicate. What keeps the other columns in sync with the advance?

 

Orri

**Comment by zhenxiao** [comment]
thank you, @oerling 
nice catch, seems we have to leverage selectiveReader to align read positions. 
Yes, I will be in the meetup, let's chat about selectiveReader in Parquet.

**Comment by oerling** [comment]
If you want to discuss this further, you can always give me a call. We are interested in adoption and the ORC side is getting debugged at a pretty good pace so you can take stuff from there with some confidence.  Next we want to make things run from memory, so let’s stay on the case.

 

Orri

**Comment by zhenxiao** [comment]
@oerling nice. Am in progress prototyping selectiveReader for Parquet.
in China now, will be back in a week. Will sync with you soon :)

**Comment by oerling** [comment]
Hi Zhenxiao

 

Now we are pretty much production ready with selective scan on ORC. To make this  more broadly useful, we need to have this on Parquet as well.

How are you doing on this?  Is there some work in  progress we could look at? 

Will you be at the event tomorrow night? Masha is also visiting. She and I will give a talk.

              

We could cooperate more closely if this would accelerate the Parquet path. We could talk about what this would look like.

 

Thanks

Orri

**Comment by zhenxiao** [comment]
Hi @oerling I will be in the meetup tomorrow. Let's sync :)
Yep, I'd love to have selective scan in Parquet. not much progress recently. Will try to have a prototype soon.

**Comment by ryanrupp** [comment]
@zhenxiao just a heads up I think newer versions of parquet-mr will stop writing these statistics, see - https://issues.apache.org/jira/browse/PARQUET-1365 as they're replaced in favor of column indexes that have page level statistics in them instead of inline with the page, see https://github.com/apache/parquet-format/blob/master/PageIndex.md  - My understanding is the new layout would allow optimizing IO because the stats can be pulled from the footer of the file and then potentially just a single page could be read from disk (or subset of adjacent pages) instead of the previous approach which required basically reading the page to get at the stats.

Anyway, I think even the old approach would have a CPU benefit here even if the data gets read from disk. The old page level statistics are optional though and with newer versions no longer written so maybe Presto should wrap into `Optional` write away for clarity of handling code. Looks like maybe this always ends up being non-null anyway since both place pages are constructed they're using Presto's `MetadataReader.readStats` which always returns an empty/initialized `Statistics` object even if the Parquet format `Statistics` are null. 

I will also note I'm not sure about the implementation of `MetadataReader.readStats` how it defaults like that (even when the input statistics is null) because when my page statistics are null and I have an int column for instance I get back a `LongStatistics` object where `isEmpty()` == false due to `isNumNullsSet()` == true (even though it wasn't actually ever set). Looking into this it looks like the Parquet code is expecting this to be set to `-1` in this case (it's checking num_null >= 0) but for some reason the default constructor just initializes this to 0 but if you look at `org.apache.parquet.column.statistics.Statistics.Builder` it initializes this to -1 (Presto code is not using the builder currently though). The result of this is my `LongStatistics` has min = 0 and max = 0 due to the use of `long` primitives and because `stats.isEmpty()` == false the statistics will be taken as valid even though they're incorrect/not actually initialized. I actually ran into something with today when debugging an issue of incorrect stat filtering, see https://github.com/prestosql/presto/issues/2166#issuecomment-564322633

**Pull request closed without merging**
