### PR TITLE
Fix a typo in CBO doc

### PR DESCRIPTION
**Pull request by v-jizhang**
Fixed a type in cost-based-optimizations.rst

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by v-jizhang** [comment]
@bot kick off tests

**Comment by v-jizhang** [comment]
@bot kick off tests

**Comment by v-jizhang** [comment]
@bot kick off tests

**Review by ajaygeorge — APPROVED** [review]
LGTM

**Review by rschlussel — APPROVED** [review]

**Pull request merged**
