### PR TITLE
Exclude zookeeper dependency from ranger shaded jar to resolve conflicts

### PR DESCRIPTION
**Pull request by agrawalreetika**
Test plan - (Please fill in how you tested your changes)

Please make sure your submission complies with our [Development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [Formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), and [Commit Message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests) guidelines. Don't forget to follow our [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution) for any code copied from other projects.

Fill in the release notes towards the bottom of the PR description.
See [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) for details.

```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by NikhilCollooru** [comment]
The code changes look good. 
Just to get a better understanding for myself, @agrawalreetika  can you briefly explain the motivation for this exclusion ?

**Review by ajaygeorge — APPROVED** [review]
LGTM.
Please clean up the RELEASE NOTES section as well and keep just  `NO RELEASE NOTE`

**Comment by shangxinli** [comment]
Just out of curiosity, does presto already have [Apache Ranger](https://ranger.apache.org/) included? The reason I ask is we have parquet column encryption changes merged. If we already have the ranger in Presto, we can develop something using ranger KMS for decryption.

**Comment by agrawalreetika** [comment]
> Just out of curiosity, does presto already have [Apache Ranger](https://ranger.apache.org/) included? The reason I ask is we have parquet column encryption changes merged. If we already have the ranger in Presto, we can develop something using ranger KMS for decryption.

Hi @shangxinli ,
Yes, Ranger-Based Authorization for Hive connector is added as part of the presto-0.275  release. https://prestodb.io/docs/current/connector/hive-security.html#hive-ranger-based-authorization
Let me know if you have any questions.

**Comment by agrawalreetika** [comment]
@ajaygeorge @NikhilCollooru We may not need this PR anymore because I have shaded the zookeeper dependency from ranger dependency and there is a different PR for that change #18270 
So I will close this one.

**Pull request closed without merging**
