### PR TITLE
[native] Remove Protobuf dependency

### PR DESCRIPTION
**Pull request by majetideepak**
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by majetideepak** [comment]
Please remove the Makefile changes before merging.

**Comment by majetideepak** [comment]
I will make this available for review once the Velox side changes land and is advanced in Prestissimo.

**Comment by czentgr** [comment]
Looks good. I saw there were additional changes needed when I did a test build based on the velox PR. This addresses it nicely.

**Review by mbasmanova — APPROVED** [review]
Nice. Would you add [native] prefix to the commit message before merging?

CC: @amitkdutta

**Comment by majetideepak** [comment]
> Nice. Would you add [native] prefix to the commit message before merging?

Done! I missed it while rebasing.

**Review by kgpai — APPROVED** [review]
Thanks for this Deepak !

**Pull request merged**
