### PR TITLE
Add Alluxio client jar to hive-hadoop2

### PR DESCRIPTION
**Pull request by apc999**
```
== RELEASE NOTES ==

Hive Changes
* Add an Alluxio client jar to `plugin/hive-hadoop2/` (as a runtime dependency) 
  to avoid copying Alluxio client jar to all Presto servers manually to connect to Alluxio.
```

### CODE REVIEW

**Comment by rongrong** [comment]
Thanks for contributing! Content looks good in general. I think you can squash all commits into one. Please fix the build failure related presto-docs.

**Comment by shixuan-fan** [comment]
Travis failure (on presto-docs) seems related.

**Comment by apc999** [comment]
Fix the doc build. thanks

**Comment by rongrong** [comment]
Can you squash all changes into 1 commit? Thanks!

**Comment by apc999** [comment]
@rongrong I have squashed this PR with source code change

**Pull request merged**
