### PR TITLE
Row level security

### PR DESCRIPTION
**Pull request by Phelodas**
Introducing changes to support Row Level Security as discussed in #12491 and the design doc mentioned there. This is Phase 1 of the changes as per the design doc which basically introduces a UnaryExpression filter.

### CODE REVIEW

**Comment by Phelodas** [comment]
@highker looks like there might be some redundancies in the IR structures (RowExpression).

CC: @elonazoulay

**Comment by Phelodas** [comment]
@highker  @elonazoulay  I reworked the diff to use RowExpression as the filter format. We can talk more offline but please take a look if you guys get a chance.

**Comment by tooptoop4** [comment]
rebase? @Phelodas

**Comment by highker** [comment]
Superseded by https://github.com/prestodb/presto/pull/12993. Row-level security will be enforced by connector optimizer.

**Pull request closed without merging**
