### PR TITLE
[Verifier] Add application-name config

### PR DESCRIPTION
**Pull request by palashgoel7**
Test plan - (Please fill in how you tested your changes)
Verified Jar is created and works with config in Docs. Also, verified generated config in logs.

Please make sure your submission complies with our [Development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [Formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), and [Commit Message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests) guidelines.

Fill in the release notes towards the bottom of the PR description.
See [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) for details.

```
== RELEASE NOTES ==

Verifier Changes
* Add application-name config to override source passed in ClientInfo

```

### CODE REVIEW

**Comment by palashgoel7** [comment]
Fixes #15191

**Comment by palashgoel7** [comment]
@caithagoras Could you please review this?

**Comment by caithagoras** [comment]
Looks like the 2nd commit is updating the documentation that is just updated in the 1st commit. We should avoid that. For this case, let's just merge the 2 commits.

**Review by caithagoras — APPROVED** [review]

**Comment by caithagoras** [comment]
Thank you for contributing. I'll merge once the comment is addressed.

**Comment by palashgoel7** [comment]
@caithagoras Thanks for reviewing my work. I have fixed the issue.

**Pull request merged**
