### PR TITLE
Refactor needed classes from spi to common

### PR DESCRIPTION
**Pull request by v-jizhang**
Window Frame changes need "Type.java" (in presto-common) to be able to
reference classes in presto-spi but in maven build, presto-spi depends on
presto-common. In order to reference classes from presto-common to
presto-spi, as we did in #14457, we have to refactor more classes from spi
to common.
This PR refactors the needed classes.

For example,
Type.java(presto-common) references a new class TypeOperators which
references InvocationConvention in presto-spi, InvocationConvention
has to be refactored from spi to common.
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by aweisberg** [comment]
I asked @v-jizhang  for some clarification as to why this needed to move from presto-spi to common. Basically in Trino there is no trino-common and there ended up being references from common -> spi that drove this refactor. I asked @v-jizhang  to post the other PR that relies on this so we can understand how they are being used from common.

@highker @NikhilCollooru can you explain what belongs in presto-common vs presto-spi?

**Comment by highker** [comment]
Yes. A very intuitive way of thinking is presto-common is a library and presto-spi is an interface. presto-common contains almost all building blocks of very basic presto concepts like Block, Type, etc. It has no idea of what a connector is. presto-spi on the other hand is an interface/adaptor only for connectors so they can be plugged into the main engine.

**Comment by v-jizhang** [comment]
> Yes. A very intuitive way of thinking is presto-common is a library and presto-spi is an interface. presto-common contains almost all building blocks of very basic presto concepts like Block, Type, etc. It has no idea of what a connector is. presto-spi on the other hand is an interface/adaptor only for connectors so they can be plugged into the main engine.

This

> Yes. A very intuitive way of thinking is presto-common is a library and presto-spi is an interface. presto-common contains almost all building blocks of very basic presto concepts like Block, Type, etc. It has no idea of what a connector is. presto-spi on the other hand is an interface/adaptor only for connectors so they can be plugged into the main engine.

@highker 
I'm working on a cherry pick of Trino PR in which Type.java needs to indirectly reference classes in SPI (for example interface FunctionHandleResolver). Please advise should I refactor more classes from SPI to common or move Type back to SPI?

Thanks

**Comment by v-jizhang** [comment]
> I asked @v-jizhang for some clarification as to why this needed to move from presto-spi to common. Basically in Trino there is no trino-common and there ended up being references from common -> spi that drove this refactor. I asked @v-jizhang to post the other PR that relies on this so we can understand how they are being used from common.
> 
> @highker @NikhilCollooru can you explain what belongs in presto-common vs presto-spi?

#16532 Improve Window frame Posted.

**Comment by highker** [comment]
> I'm working on a cherry pick of Trino PR in which Type.java needs to indirectly reference classes in SPI (for example interface FunctionHandleResolver). Please advise should I refactor more classes from SPI to common or move Type back to SPI?

Can we move out `FunctionHandleResolver` instead?

**Comment by v-jizhang** [comment]
> > I'm working on a cherry pick of Trino PR in which Type.java needs to indirectly reference classes in SPI (for example interface FunctionHandleResolver). Please advise should I refactor more classes from SPI to common or move Type back to SPI?
> 
> Can we move out `FunctionHandleResolver` instead?

`FunctionHandleResolver` is just one example, there are many classes involved.

**Comment by highker** [comment]
We probably will need some design discussion then. Will need to understand a bit more on this PR

**Comment by rongrong** [comment]
It's not clear to me which classes are moved / need to be moved and why. I think moving `InvocationConvention` to presto-common is reasonable. Not sure why other classes need to be moved. It's also very hard to tell which files are moved since this commit touched over 1000 files. The only few I see were marked as deleted / added rather than moved, which made reviewing this even harder. Can we first produce a detailed list of class dependencies and start the discussion from there? Thanks!

**Comment by rongrong** [comment]
Also, Trino introduced `TypeOperators` to formalize operators. We don't have this concept in Presto, and I don't think we have to introduce `TypeOperators` to make RANGE BETWEN work. So maybe instead of trying to port the change, understand their logic, and reimplement the concept in Presto would be easier.

**Pull request closed without merging**
