### PR TITLE
Float type - first part continuation

### PR DESCRIPTION
**Pull request by maciejgrzybek**
This supersedes #5257.

### CODE REVIEW

**Comment by cberner** [comment]
One minor comment: https://github.com/prestodb/presto/commit/71a7a43ba568e2265543e03e584e8e3b3a3bb9f5#commitcomment-17706305

I'll merge this after the release of 0.148 is done

**Comment by maciejgrzybek** [comment]
Good point. Fixed in b0e1fcf19ce40908c91dbd9e05422a8bffcd9ee8

**Comment by maciejgrzybek** [comment]
Pushed c22d99ca38f09055bc5d8eff2daa9dc4ce6d8b81 (tiny change (`new Long` vs `Long.valueOf()`)) to restart build. Looks like there was some problem with infra (pulling docker image).

**Comment by maciejgrzybek** [comment]
The problem with build is because of docker-engine unsatisfied dependency.
Fix for this is published here: https://github.com/prestodb/presto/pull/5395
Once the fix gets in, current PR will pass build as it did previously (and here https://travis-ci.org/maciejgrzybek/presto/builds/134780234).

**Comment by maciejgrzybek** [comment]
Rebased on master to restart build.

**Comment by maciejgrzybek** [comment]
@cberner: added cdb9da8 to fix problem with non-numeric FLOAT values (e.g. `NaN`, `Infinity`) in Presto-Cli. They were displayed incorrectly (as a byte array, instead of parsing it as a FLOAT value and displaying using Float's `toString`).

**Comment by cberner** [comment]
Merged. Thanks!

**Pull request closed without merging**
