### PR TITLE
Update use-cases.rst

### PR DESCRIPTION
**Pull request by steveburnett**
Update use-cases.rst to include new member companies and Linux Foundation

### CODE REVIEW

**Comment by tdcmeehan** [comment]
Now may actually be a great time to reword this whole section, since it doesn't operate under the auspices of Meta anymore, rather it operates under the auspices of the Linux Foundation.

**Comment by steveburnett** [comment]
@tdcmeehan I worked with Rohan Pednekar to revise the "Who Uses?" part of the page, updated with a new commit, and squashed the commits to a single commit. When you have time, could you look at this and let me know what you think? Is there anything else I need to do for this PR?

**Review by tdcmeehan — COMMENTED** [review]
Looks good, except I would still include Meta in the list of companies that develop Presto.

**Review by tdcmeehan — COMMENTED** [review]
Looks good, except I would still include Meta in the list of companies that develop Presto.

**Comment by steveburnett** [comment]
@tdcmeehan Good advice! I added Meta to the text and made a new commit. Let me know if there is anything else I can do to help this finish.

**Review by tdcmeehan — APPROVED** [review]

**Comment by tdcmeehan** [comment]
Looks good!  Please squash commits and I'll merge

**Comment by steveburnett** [comment]
Commits squashed! I believe this is ready for you to merge.

**Comment by wanglinsong** [comment]
Please clean up the PR message.

**Comment by steveburnett** [comment]
@wanglinsong I believe I have cleaned up the PR message, as you requested. Let me know if there is anything else I can do!

**Pull request merged**
