### PR TITLE
Make export_canonical_path resolve wildcards

### PR DESCRIPTION
**Pull request by ArturGajowy**
this fixes a regression from previous commit

### CODE REVIEW

**Comment by ArturGajowy** [comment]
The regression mentioned above breaks the build for master branch on presto-checks: https://travis-ci.org/Teradata/presto-checks/builds

**Comment by ArturGajowy** [comment]
@kokosing please have a look

**Comment by ArturGajowy** [comment]
@electrum please have a look

**Comment by electrum** [comment]
The commit description should be a full sentence.

**Comment by electrum** [comment]
Merged, thanks!

**Pull request closed without merging**
