### PR TITLE
Update Tableau Web Connector to jQuery 2.2.3

### PR DESCRIPTION
**Pull request by chrisunder**
Also move the needed tableauwdc js file to the vendor directory

### CODE REVIEW

**Comment by BrickXu** [comment]
0.149 tableau web connector has a javascript error and this patch could fix it. good work.

**Comment by raghavsethi** [comment]
Looks good to me.

**Comment by haozhun** [comment]
@nezihyigitbasi Can you confirm that this works for you?

**Comment by nezihyigitbasi** [comment]
@haozhun LGTM if tested with a Tableau installation. If not let me know and I can try setting up a test environment.

**Comment by chrisunder** [comment]
I tested this with Tableau 9.2.7.  For the test to be successful I also needed https://github.com/prestodb/presto/pull/5538

**Comment by haozhun** [comment]
Merged #5537. Thank you.

**Pull request closed without merging**
