### PR TITLE
Remove state from more scalar functions

### PR DESCRIPTION
**Pull request by kaikalur**
Removing the PageBuilder as state from all array/map transform functions.

Test plan - test exist

Please make sure your submission complies with our [Development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [Formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), and [Commit Message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests) guidelines. Don't forget to follow our [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution) for any code copied from other projects.

Fill in the release notes towards the bottom of the PR description.
See [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) for details.

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by kaikalur** [comment]
> Can you run the `BenchmarkArrayTransform` benchmark and share the numbers of before and after? Thanks!

About that :) - it's actually giving slightly worse numbers, I will add them. But most real queries are giving good latency/dircu savings upto 20% latency and about 1-2% dircu savings pretty consistently.

**Comment by kaikalur** [comment]
> Can you run the `BenchmarkArrayTransform` benchmark and share the numbers of before and after? Thanks!

Done

**Comment by rongrong** [comment]
> > Can you run the `BenchmarkArrayTransform` benchmark and share the numbers of before and after? Thanks!
> 
> About that :) - it's actually giving slightly worse numbers, I will add them. But most real queries are giving good latency/dircu savings upto 20% latency and about 1-2% dircu savings pretty consistently.

Why is that? Can we update the benchmark to reflect a more realistic scenario then?

**Comment by kaikalur** [comment]
> > > Can you run the `BenchmarkArrayTransform` benchmark and share the numbers of before and after? Thanks!
> > 
> > 
> > About that :) - it's actually giving slightly worse numbers, I will add them. But most real queries are giving good latency/dircu savings upto 20% latency and about 1-2% dircu savings pretty consistently.
> 
> Why is that? Can we update the benchmark to reflect a more realistic scenario then?

Not sure but I just added a SQL Benchmark that showing slight improvement. Let me know if you want me to remove the old benchmark.

**Comment by kaikalur** [comment]
I know this is merge but finally found a benchmark that shows little or no difference. basically changing the array size from being fixed 4 to random(10) is giving 1.4-1.5 ns/op consistently:
```
-                blocks[i] = createChannel(POSITIONS, ARRAY_SIZE, arrayType);
+                blocks[i] = createChannel(POSITIONS, (int)ThreadLocalRandom.current().nextLong() % 10, arrayType);
```
this is a more appropriate way to test anyway because that's a common scenario - most arrays are small < 10 elements.

**Comment by rongrong** [comment]
> I know this is merge but finally found a benchmark that shows little or no difference. basically changing the array size from being fixed 4 to random(10) is giving 1.4-1.5 ns/op consistently:
> 
> ```
> -                blocks[i] = createChannel(POSITIONS, ARRAY_SIZE, arrayType);
> +                blocks[i] = createChannel(POSITIONS, (int)ThreadLocalRandom.current().nextLong() % 10, arrayType);
> ```
> 
> this is a more appropriate way to test anyway because that's a common scenario - most arrays are small < 10 elements.

Feel free to send another PR to change the benchmark. ;)

**Pull request merged**
