### PR TITLE
Configurable cassandra LoadBalancingPolicy and NoHostAvailable retry …

### PR DESCRIPTION
**Pull request by toxeh**
…count.
New cassandra config parameters:
cassandra.load-policy.use-dc-aware
cassandra.load-policy.dc-aware.local-dc
cassandra.load-policy.dc-aware.used-hosts-per-remote-dc
cassandra.load-policy.dc-aware.allow-remote-dc-for-local-consistency-level

cassandra.load-policy.use-token-aware
cassandra.load-policy.token-aware.shuffle-replicas

cassandra.load-policy.use-white-list
cassandra.load-policy.white-list.addresses

cassandra.no-host-available-retry-count

### CODE REVIEW

**Comment by toxeh** [comment]
Travis CI Error: The log length has exceeded the limit of 4 Megabytes (this usually means that test suite is raising the same exception over and over).
The build has been terminated.

**Comment by electrum** [comment]
Thanks! Can you add these new config properties to the Cassandra connector documentation?

**Comment by toxeh** [comment]
@electrum, done.

**Comment by electrum** [comment]
I started working on this, but the boolean configs like `use-dc-aware`, `use-token-aware`, etc. are actually exclusive and should be an enum.

**Comment by toxeh** [comment]
@electum, TokenAwarePolicy is not exclusive. It can include any other LoadBalancingPolicy (http://docs.datastax.com/en/drivers/java/3.0/com/datastax/driver/core/policies/TokenAwarePolicy.html) and DCAwareRoundRobinPolicy too.

**Comment by caraboides** [comment]
HI how is the state of this pull request?  I am very interesting in having data center awareness upstream.

**Comment by electrum** [comment]
@toxeh You're right, I see now that it is building a chain of policies. I'll review this soon.

**Comment by electrum** [comment]
Merged, thanks!

**Pull request closed without merging**
