### PR TITLE
Specializing Functional Interfaces

### PR DESCRIPTION
**Pull request by ameyaKetkar**
This PR is generated by a tool I am working on. I tested the tool upon this project, and found these results. It specializes functional interfaces for example `Function<Double,Double>` to `DoubleUnaryOperator` or `Consumer<Object,Long>` to `ObjLongConsumer`.
 This change eliminates auto-boxing overhead, improving performance and type safety. 
Thank you for making your source-code available on GitHub. :)

### CODE REVIEW

**Comment by ameyaKetkar** [comment]
Hello, 
I have signed the CLA agreement.
Could any one take a look at it ?

**Comment by haozhun** [comment]
I was able to understand what you are doing here after reading the actual code changes. However, I would hope that the commit message be a bit more informative. Can you improve it please?

We would also like to see the changes to Block interface be in a separate commit.

@electrum and I believe that the changes otherwise look reasonable.

**Comment by findepi** [comment]
we use `OptionalInt` in the code and it's not uncommon when it hurts (eg. "uh, where is my `optional.map(..)` method?)
therefore  i second @martint 's opinion.

**Comment by ameyaKetkar** [comment]
@haozhun - I have split the commit into 2, with one dealing with `Block` interface only. I have also updated the commit message. 
@martint - Yes, readability might be a concern for some developers. But this also eliminates auto-boxing giving performance, memory and type-safety benefits. 
@findepi I agree the specialized Optional api (`OptionalInt`) does not ship with some important functionality, hence is not a complete replacement of `Optional<Integer>`. But a developer can always switch back to using `Optional<Integer>` when required. (The tool I am developing can help in this switching :) ).
But the specialized functional interfaces api (`DoubleUnaryOperator`) is much better. Majority of them can completely replace their generic counterparts, giving performance benefits for no loss in functionality.

**Comment by electrum** [comment]
@martint Your example is comparing two different interfaces (function vs consumer). These would be equivalents:

* `Function<Long, T>` to `LongFunction<T>`
* `BiConsumer<T, Long>` to `ObjLongConsumer<T>`

**Comment by findepi** [comment]
> Majority of them can completely replace their generic counterparts, giving performance benefits for no loss in functionality.

Do you have some particular numbers in mind? Is it 10%, 1%, 0.1%?

**Pull request closed without merging**
