### PR TITLE
Dispatcher Phase 1

### PR DESCRIPTION
**Pull request by raghavsethi**
Reviewed at https://github.com/prestosql/presto/pull/95

Original issue: #10174 
More detail on motivation: https://github.com/prestosql/presto/issues/391

### CODE REVIEW

**Comment by raghavsethi** [comment]
Rebased onto master.
Tests are green.

giphy

**Comment by tooptoop4** [comment]
bump @raghavsethi @tdcmeehan @shixuan-fan @wenleix

**Comment by raghavsethi** [comment]
@tooptoop4: As per my last conversation with @tdcmeehan, he plans to work on this later this year. In the meantime you could try cherry-picking the commits from https://github.com/prestosql/presto/pull/95 if you have an urgent use case.

**Comment by tdcmeehan** [comment]
@tooptoop4 out of curiosity what's your use case for this PR?

**Comment by tdcmeehan** [comment]
#14104 adds these changes

**Pull request closed without merging**
