### PR TITLE
Add TPC-DS queries as product tests

### PR DESCRIPTION
**Pull request by kokosing**
Add TPC-DS queries as product tests

tpcds tests are disabled to be run in each travis build. It is going to
be run externally in prest-checks. This is due that execution duration
in about 2 hours.

Result files for quarantined could be not formatted properly to be
accepted by tempto. It is because, typically result files are generated
by tempto, but for queries which returns incorrect results result files
comes from TPC-DS benchmark.

### CODE REVIEW

**Comment by fiedukow** [comment]
Please keep only first 100 rows in results of TPCDS queries.

**Comment by kokosing** [comment]
@fiedukow I checked the specification and I could not find anything that I can limit the output that way. I would prefer to stick with the specification as much as possibile.

**Comment by kokosing** [comment]
I fixed the generator tempto code and got more queries passing.

@electrum Can you please take a look? It does not affect the automation. It is going to be run outside of the regular travis builds. We want to have external build run periodically in https://github.com/Teradata/presto-checks

**Comment by kokosing** [comment]
Rebased and fixed some queries.

**Comment by ArturGajowy** [comment]
Added the q14_1, q18, q64 to quarantine till we sort out the Travis failures

**Comment by kokosing** [comment]
@electrum I rebased this. Is there any concern regarding this pull request? 

It does not affect the current automation flow. TPC-DS are excluded from regular travis builds. We want to have external build run them periodically in https://github.com/Teradata/presto-checks Currently we test them for teradata branches, but we are unable to run them for presto/master branch since this pull request is not yet merged.

**Comment by ArturGajowy** [comment]
Also, not having this on master makes presto-checks fail on the beginning of each our sprints, until we apply this and related patches on the new sprint branch. This in turn obscures the view (is there a legitimate presto-checks product test failure? or is it just sprint-start hiccup?) and makes the tests rot (it's hard to spot regressions when the build is not green). See my last commit in this PR.

**Comment by kokosing** [comment]
@electrum gentle reminder

**Comment by kokosing** [comment]
Rebased.

@electrum yet another gentle reminder - YAGR :)

**Comment by kokosing** [comment]
I extracted two PRs form this one:
 - https://github.com/prestodb/presto/pull/7308
 - https://github.com/prestodb/presto/pull/7309

Hopefully, now it will be easier to review this one.

**Comment by kokosing** [comment]
@electrum I rebased and extracted independent changes out this PR. 

Would it be possible to merge this? This is a very problematic pull request to me. It takes me about a day of work per each teradata sprint (once per two week), which I think could spend in more productive way.

This is not touching the main (product) codebase at all. It is only about extending the test coverage, what is more this coverage is not going to affect regular test automation as it is only part of presto-checks project.

**Comment by electrum** [comment]
Update the message "Quarantine tests which fails due #6991" to be `Quarantine tests which fail due to 'null IN subquery'`

**Comment by electrum** [comment]
Change the description for "Add TPC-DS queries as product tests" to just say "Do not run tpcds tests in Travis." or simply remove the description.

**Comment by electrum** [comment]
Minor comments about commit messages, otherwise looks good

**Comment by electrum** [comment]
Merged, thanks!

**Comment by kokosing** [comment]
Thank you!

wt., 7.02.2017, 22:41 użytkownik David Phillips <notifications@github.com>
napisał:

**Pull request closed without merging**
