### PR TITLE
Add SourceLocation to PlanNode

### PR DESCRIPTION
**Pull request by kaikalur**
Adding source location information to PlanNode and populate it from the AST and also propagate it appropriately through the plan rewrites. 

Test plan - None 

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by kaikalur** [comment]
This is part 2 of source locations in the plan. Please take a look.

**Review by highker — APPROVED** [review]
@kaikalur, is there a followup PR? I didn't find the place where we carry the location information from AST nodes to PlanNode. It might be buried somewhere in the commit that I missed.

**Comment by kaikalur** [comment]
> @kaikalur, is there a followup PR? I didn't find the place where we carry the location information from AST nodes to PlanNode. It might be buried somewhere in the commit that I missed.

It's all in RelationPlanner.java

**Comment by highker** [comment]
> It's all in RelationPlanner.java

I see. `getSourceLocation` was landed in the previous PR. Could you help to rebase the commit so we can merge?

**Pull request merged**
