### PR TITLE
Batch partition loading from the metastore

### PR DESCRIPTION
**Pull request by nezihyigitbasi**
OK here is the initial implementation that does batching based on time (a new parameter ``hive.metastore-partition-load-batch-interval`` is introduced) to address #1981 . Currently each hive-metastore thread does batching independently (instead of using locking and letting one thread do the batching as the same ``BackgroundCacheLoader`` is shared by all metastore threads). For keeping the state this implementation uses thread local variables to get rid of synchronization & make the code more concise. Once the code is ready to merge I will update the docs with the new parameter.

### CODE REVIEW

**Comment by nezihyigitbasi** [comment]
@martint rebased & addressed your comments. Can you please take a look?

**Comment by cberner** [comment]
@nezihyigitbasi is this the same as https://github.com/prestodb/presto/pull/2838 and which one should we be merging?

**Comment by nezihyigitbasi** [comment]
@cberner at some point @joy-yao started working on this and @martint was telling me that there are some issues with these PRs. If we still want this feature I can have a fresh look at it and create a new PR.

**Comment by cberner** [comment]
k. I'll sync up with @martint about it

**Comment by cberner** [comment]
Talked to @martint. Sounds like this isn't needed anymore. The new transactional connector interface can handle this in a way that doesn't involve caches.

**Pull request closed without merging**
