### PR TITLE
Support more types in BlackHole connector

### PR DESCRIPTION
**Pull request by arhimondr**
Support TINYINT, SMALLINT, INTEGER and DECIMAL type in BlackholePageSource

### CODE REVIEW

**Comment by martint** [comment]
@raghavsethi, can you review?

**Comment by raghavsethi** [comment]
Yep :)

**Comment by raghavsethi** [comment]
While you're at it, would you mind adding float as well?

**Comment by arhimondr** [comment]
Will do

**Comment by arhimondr** [comment]
Done

**Comment by raghavsethi** [comment]
Merged, thanks!

**Pull request merged**
