### PR TITLE
Add BIT(n) type that represents a sequence of bits

### PR DESCRIPTION
**Pull request by electrum**
This is a work in progress. The basic type works, but we still need bitwise operators, concat, etc. Additionally, casting to unbounded varchar needs to be fixed (it tries to create a bit type of MAX_INT and fails).

When converting to a bit type, the bit type must be at least as large as the input data (no data truncation). The bit type can then be truncated by casting to a smaller bit type.

### CODE REVIEW

**Comment by martint** [comment]
We should consider using a different representation for n < 64, like DECIMAL.

The semantics of comparison operations (<, >) are "interesting": should it behave like a sequence (e.g., like an array, where the first element is the one that's compared first), or like a binary, where the first element is the least significant).   I.e., it's a question about endianness and whether those operations even make sense. Similar issues will come up when we define shift operations: what's "left" and "right". Or maybe they need to be "up/down"?

For string/binary to bit casts, there's also the question of whether the element in the string/binary sequence is bit 0 or n-1.

**Comment by electrum** [comment]
I agree we should have an optimized version of the type for <= 64 bits, though that can be done later either affecting the SQL interface. It might not be important since people use bigint today for that.

For comparison, treating them as strings/numbers seems to be the most natural way (you can only compare identical length types), thinking of it like a decimal number, only it’s base 2 instead of base 10.

Endianness seems to matter when converting a numeric value to/from bits. But once it’s in bits, you’re past that point (the same as how endianness doesn’t matter with a printed decimal number).

I don’t understand your last point. Can you explain further?

**Comment by martint** [comment]
> For comparison, treating them as strings/numbers seems to be the most natural way (you can only compare identical length types), thinking of it like a decimal number, only it’s base 2 instead of base 1

And that's why I say it's interesting. If it's considered a sequence of bits, it'd be natural for bit 0 to compare first, just like an array. If it's a binary string, the opposite would be more natural.

For the comment about casts, given cast('10' as bit(2)), is 1 bit 0 or bit 1? Again, similar discussion regarding whether it's considered a sequence of bits or a binary string.

**Comment by electrum** [comment]
I see what you mean now. In PostgreSQL, they are actually bit strings, so truncation happens on the right, not the left. You can use several of the normal string functions on them.

**Comment by amitna1r** [comment]
One comment about binary string vs sequence of bits... having it has a binary string might cause confusion and make it non-intuitive... since visually I would expect the least significant bit to be the right most one.

About comparison, etc... I agree with @electrum ... that I would expect it to behave like numbers, just that its base 2. If so the lengths of the two values need not be the same to be compared.

**Pull request closed without merging**
