### PR TITLE
Update StatementAnalyzer.java

### PR DESCRIPTION
**Pull request by econtreras78ve**
When having 1 or more external catalog, this change will provide correct catalog and schema when view that belong to external catalog is being analyzed. Lets say, if we have external_catalog.schema_a.view_b with definition as select * from table_b, current code is looking table_b in local catalog (throwing exception because neither view schema and table_b exist in local catalog), when it should look in catalog and schema associated to the view analyzed (external_catalog). I detected this problem in release 0.267, however in master branch I can see it still persist.

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by tdcmeehan** [comment]
Could you create a unit test in `TestAnalyzer` that reproduces this issue, and passes with your code change?  To be clear, you're saying this fixes queries that reference in the SQL statement the catalog and schema of the view (rather than letting it be associated implicitly with the session's catalog and schema)?

**Comment by econtreras78ve** [comment]
> Could you create a unit test in `TestAnalyzer` that reproduces this issue, and passes with your code change? To be clear, you're saying this fixes queries that reference in the SQL statement the catalog and schema of the view (rather than letting it be associated implicitly with the session's catalog and schema)?

Hi, Sure!

Let's say we have 2 catalogs registered under presto/conf/catalog: **local_catalog** and **external_catalog** (crossaccount)
then we connect to local_catalog,
`presto-cli --catalog local_catalog --schema local_schema`
then when running following query:
`select count(1) from external_catalog.external_schema.external_view;`
where view definition for external view is: create view external_view as select * from external_table;
we will get this error: 
_Query 20230830_203429_00002_c4fr8 failed
com.facebook.presto.sql.analyzer.SemanticException: line 1:22: Failed analyzing stored view 'external_catalog.external_schema.external_view': line 108:3: Schema external_schema does not exist_

After doing some debug, I saw the problem is when analyzing the view it is checking external_table in local_catalog instead of external_catalog

**Comment by tdcmeehan** [comment]
@econtreras78ve I'm not able to reproduce this problem in a unit test, could you try to add it to `TestAnalyzer`?  It has various catalogs, schemas and tables registered as part of the test setup and should be easily reproducible within that test.

**Comment by econtreras78ve** [comment]
> @econtreras78ve I'm not able to reproduce this problem in a unit test, could you try to add it to `TestAnalyzer`? It has various catalogs, schemas and tables registered as part of the test setup and should be easily reproducible within that test.

Hi @tdcmeehan,

I just created 1 unit test trying to mimic the error I described previously,

https://github.com/prestodb/presto/compare/master...econtreras78ve:presto:patch-1

**Pull request closed without merging**
