### PR TITLE
Fix presto-product-tests on Mac - docs and scripts.

### PR DESCRIPTION
**Pull request by fiedukow**
This change introduces:
 * Changes in run_on_travis.sh script to make it cross-platform.
 * Changes in docker-compose to open ports required for SOCKS proxy
   available in new version of teradata/chd5-hive docker image.
 * Changes in documentation to clarify some things and fix commands
   for Mac OS X environment.

Reviewers: @kokosing @arhimondr

### CODE REVIEW

**Comment by fiedukow** [comment]
This is now part of https://github.com/prestodb/presto/pull/4877

**Comment by raghavsethi** [comment]
This is great. As per my conversation with @maciejgrzybek can you please add instructions for the use case when we want to run Presto locally, which talks to a dockerized hadoop cluster (and on OS X)? That will be the use case for the Presto team a majority of the time.

**Comment by raghavsethi** [comment]
Ah never mind, I saw this was closed and thought it was merged into master. The instructions look good.

**Comment by petroav** [comment]
@raghavsethi see https://github.com/prestodb/presto/pull/4877. The README there has instructions on setting up a local run.

**Pull request closed without merging**
