### PR TITLE
Extend ConnectorSession with getProperties

### PR DESCRIPTION
**Pull request by highker**
There are cases we might be interested getting all the properties in a
connector session. Add an interface to expose them.

### CODE REVIEW

**Comment by electrum** [comment]
Typo in commit message. Should be "extend"

**Comment by electrum** [comment]
As a general philosophy, we only add things to the SPI when there is a specific need to do so with concrete use cases. Once you go down the path of "might be interested", you add all sorts of random, useless stuff that has the wrong API (because there were no specific use cases).

**Comment by highker** [comment]
@electrum, it's for https://github.com/prestodb/presto/pull/7723; if connector is able to get all properties, I assume the new interface is redundant

**Comment by electrum** [comment]
The connector already declares all of its properties to the engine, so of course it knows them all.

**Comment by highker** [comment]
Thanks @electrum for clarification; will close the PR as discussed.

**Pull request closed without merging**
