### PR TITLE
Optimize Mongodb connector

### PR DESCRIPTION
**Pull request by redandblack1899**
MongoSession.java 
1. Add function getChunkInfo to get a collection's detail chunks infomation;
2. Add function getChunkInfo to get a collection's sharded type;
3. Modify function translateValue: add translating ObjectIdType;
4. Modify function translateValue: add translating TimestampType;
5. Modify function getTableMetadata: When Presto visits am empty collection first time, it will insert the collection's metadata into collection _schema with empty fields, and client will get error COLUMN_NAME_NOT_SPECIFIED. If the collection is inserted records later and then presto visits the collection again, client will still get error COLUMN_NAME_NOT_SPECIFIED. Because the fields of the collection's metadata in _schema is still empty.  Optimization: When a collection is empty, its metadata should not be inserted into _schema.

MongoSplitManager.java
1. Modify the constructing splitSource strategy: when a collection is range-sharded, construct a fixedSplitSource containing splits, with one split mapped to a chunk; others construct the fixedSplitSource with one split mapped to the whole collection.

### CODE REVIEW

**Comment by kokosing** [comment]
To make this PR be eligible to be reviewed, please rebase your work on recent master. Make sure commits like `sync source presto` or `Merge...` are not needed. Squash commits like `Fix checkstyle`. Make sure your all the commits messages follow: https://chris.beams.io/posts/git-commit/

**Comment by redandblack1899** [comment]
Fix Checkstyle violations;

**Comment by redandblack1899** [comment]
OK. Thank u. I am new here， sorry to bother u.



发自我的小米手机
在 Grzegorz Kokosiński <notifications@github.com>，2018年1月4日 下午4:40写道：

To make this PR be eligible to be reviewed, please rebase your work on recent master. Make sure commits like sync source presto or Merge... are not needed. Squash commits like Fix checkstyle. Make sure your all the commits messages follow: https://chris.beams.io/posts/git-commit/

**Comment by kokosing** [comment]
> OK. Thank u. I am new here， sorry to bother u.

No problem. Welcome in community then :)

**Pull request closed without merging**
