### PR TITLE
[native] Change SSD Cache Executor to use CPUThreadPool

### PR DESCRIPTION
**Pull request by duxiao1212**
## Description

Use CPUThreadPoolExecutor for SSD cache

## Motivation and Context

Prestissimo's SSD Executor is using IOThreadPoolExecutor even though we are not using evb or io_uring at all. We have no need for IOThreadPoolExecutor. Given that IOThreadPoolExecutor can suffer from head of line blocking because it picks threads in a round robin manner and each thread has its own queue.

## Test Plan

N/A; Low impact

## Contributor checklist

- [x] Please make sure your submission complies with our [contributing guide](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md), in particular [code style](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#code-style) and [commit standards](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#commit-standards).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [x] CI passed.

## Release Notes

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by kewang1024** [comment]
Thanks @duxiao1212 
1. Change the commit message prefix to [native] prefix 
2. There is format check failing

**Comment by zacw7** [comment]
Thanks for making the change. If release note is NOT required, please add
```
== NO RELEASE NOTE ==
```

**Comment by duxiao1212** [comment]
> Thanks @duxiao1212
> 
> 1. Change the commit message prefix to [native] prefix
> 2. There is format check failing

**Review by kewang1024 — APPROVED** [review]
LGTM, thanks @duxiao1212 !

**Review by xiaoxmeng — APPROVED** [review]

**Pull request merged**
