### PR TITLE
Add decimal support to TPCH connector

### PR DESCRIPTION
**Pull request by sopel39**

### CODE REVIEW

**Comment by sopel39** [comment]
FYI: @cberner @dain @ilfrin 

Currently `DOUBLE` is still used as default type for numeric columns. If you use `decimal` suffix (e.g: `tiny_decimal`) when specifying TPCH schema, then numeric columns would have `DECIMAL(12, 2)` type.

In the future, we think that `DECIMAL` should be used as a default type for TPCH numeric columns. To achieve this, we want to switch TPCH schema from `DOUBLE` to `DECIMAL` in each connector tests one by one. When all code is adjusted to use `DECIMAL` TPCH columns, then we want to remove `DOUBLE` numeric type from TPCH connector.

**Comment by martint** [comment]
Instead of adding the hybrid functionality to the TPCH connector, can we adjust the tests for all connectors that don't support DECIMAL to cast the numbers to double when inserting into the testing tables?

**Comment by sopel39** [comment]
I would prefer to do this step by step even in small PRs. This way PRs would be easier to review and maybe could land in master quicker. What is your opinion @martint? For us it's better when parts of our work gradually land in master then to maintain one large PR with long lifespan.

**Comment by sopel39** [comment]
ping @martint.

I have looked at what code depends on double in TPCH connector. It seems that gradually dependencies could be removed by using casts. However, there is `BenchmarkQueryRunner`, which is used to test if benchmarks work. There are benchmarks like `DoubleSumAggregationBenchmark` which require double column. I am not sure how this dependency can be easily removed. `BenchmarkQueryRunner` uses TPCH connector directly and adding casts to benchmarks seems like a wrong idea.

Anyway, I still think that landing this code gradually would make our lives easier :)

**Comment by martint** [comment]
We don't use those benchmarks much anymore, so we can just delete the ones that are problematic.

**Comment by KBP-TDC** [comment]
@sopel39 @fiedukow @kokosing is this PR still needed?

**Comment by sopel39** [comment]
This is still valid PR (it is on our sprint branches). It needs to be extended. We have technical debt here.

**Comment by sopel39** [comment]
@martint I would queue work on this one after https://github.com/prestodb/presto/pull/5378 is merged, so decimals is supported in various aggregations.

**Comment by maciejgrzybek** [comment]
Why do we change `TPCHConnector` instead of patching Airlift/tpch properly? Have a look e.g. https://github.com/Teradata/tpcds. We use decimal there.

**Comment by sopel39** [comment]
@maciejgrzybek airlift is already patched. It produces unscaled longs for decimal/double columns which are converted in `TPCHConnector` to decimal.

**Comment by kokosing** [comment]
Is this still valid PR?

**Comment by sopel39** [comment]
It should be superceeded by refined version. I think we can close it for now

**Pull request closed without merging**
