### PR TITLE
Update Iceberg from 1.2.1 to 1.3.0

### PR DESCRIPTION
**Pull request by nastra**
```
== RELEASE NOTES ==

Iceberg Changes
* Update Iceberg from 1.2.1 to 1.3.0
```
We just released Iceberg 1.3.0 that contains numerous improvements and bug fixes. Release notes can be found [here](https://iceberg.apache.org/releases/#130-release).

### CODE REVIEW

**Review by yingsu00 — COMMENTED** [review]
@nastra Could you elaborate a bit what the reason to update Iceberg to this version? Was it some feature upgrade? If such, could you please state it in the PR message? Thanks.

**Comment by nastra** [comment]
@yingsu00 it's mostly because numerous features/improvements and bug fixes went into Iceberg 1.3.0, which we just released. I've updated the PR description and added a link to the release notes.

**Comment by nastra** [comment]
@ChunxuTang could you take a look please?

**Review by ChunxuTang — APPROVED** [review]
LGTM. @nastra Thanks for your consistent contribution! :)

**Pull request merged**
