### PR TITLE
Ensure resource group concurrency tests have enough time time succeed

### PR DESCRIPTION
**Pull request by tdcmeehan**
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by rschlussel** [comment]
Do you know why they need more time now?  Is it an issue with the test environment, or was there a regression in how long these things take generally?

**Comment by tdcmeehan** [comment]
@rschlussel not sure why this suddenly became flakey, but what I noticed is that the majority of the 60s test time was being taken by the setUp method.  This didn't leave much time for the actual test to run, and it's conceivable that due to the heavy process forking and copying of the data during startUp, this may take varying amounts of time and not leave enough time for the setup required in the test itself.

**Comment by rschlussel** [comment]
If the problem is the set up method, should all tests in the class be updated from 60s -> 120s?

**Comment by tdcmeehan** [comment]
> If the problem is the set up method, should all tests in the class be updated from 60s -> 120s?

I created this PR to verify if that's the behavior (I'm re-running the tests to see if the problem re-occurs).  If that's the case, the better solution is to move these tests out of this class entirely, since they create their own query runner in the test and don't even use what's set up during initialization.

**Comment by rschlussel** [comment]
Actually, I'm also not sure that the setup method counts towards the test method timeout.

**Comment by tdcmeehan** [comment]
I see that both the test failed again and that a local test with a sleep of 60s in the init method doesn't count toward the test timeout, back to the drawing board.

**Pull request closed without merging**
