### PR TITLE
Add flag to remove redundant progress logs in CIs

### LINKED ISSUE #22164: Don't log "Counting Objects" in CIs
CI logs are full of pages of useless Counting objects: messages. I think these come from git. Figure out if there's a flag somewhere to turn off these logs. A quick google search suggests we might even be able to speed things up by not doing this at all.

https://github.blog/2015-09-22-counting-objects/

2024-03-12T11:29:02.3499810Z [command]/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +6ec5993653b5bb518b2918e33a40e4d16972eb8e:refs/remotes/pull/22163/merge
2024-03-12T11:29:02.7161696Z remote: Enumerating objects: 13566, done.        
2024-03-12T11:29:02.7162887Z remote: Counting objects:   0% (1/13566)        
2024-03-12T11:29:02.7164044Z remote: Counting objects:   1% (136/13566)        
2024-03-12T11:29:02.7164863Z remote: Counting objects:   2% (272/13566)        
2024-03-12T11:29:02.7165514Z remote: Counting objects:   3% (407/13566)        
2024-03-12T11:29:02.7166455Z remote: Counting objects:   4% (543/13566)        
2024-03-12T11:29:02.7167025Z remote: Counting objects:   5% (679/13566)        
2024-03-12T11:29:02.7167609Z remote: Counting objects:   6% (814/13566)        
2024-03-12T11:29:02.7168272Z remote: Counting objects:   7% (950/13566)        
2024-03-12T11:29:02.7168826Z remote: Counting objects:   8% (1086/13566)        
2024-03-12T11:29:02.7169417Z remote: Counting objects:   9% (1221/13566)

### PR DESCRIPTION
**Pull request by tlm365**
## Description
Resolves #22164.

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by elharo** [comment]
Looking in the output from this run at  https://productionresultssa8.blob.core.windows.net/actions-results/fce0642e-2b5c-42d3-9304-d1347575824b/workflow-job-run-8caa2f7b-afd7-58db-1c7c-2d149bbbb5bf/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-03-12T15%3A55%3A06Z&sig=OtXlDSeziYcnbcWj4qBEbtzSMbloX2Huptfb7sRff6c%3D&sp=r&spr=https&sr=b&st=2024-03-12T15%3A45%3A01Z&sv=2021-12-02 I still see those messages

**Comment by tlm365** [comment]
> Looking in the output from this run at https://productionresultssa8.blob.core.windows.net/actions-results/fce0642e-2b5c-42d3-9304-d1347575824b/workflow-job-run-8caa2f7b-afd7-58db-1c7c-2d149bbbb5bf/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-03-12T15%3A55%3A06Z&sig=OtXlDSeziYcnbcWj4qBEbtzSMbloX2Huptfb7sRff6c%3D&sp=r&spr=https&sr=b&st=2024-03-12T15%3A45%3A01Z&sv=2021-12-02 I still see those messages

hi @elharo, would you re-run this process pls. I just updated the commit.

**Comment by elharo** [comment]
Know flake: 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TestPrestoNativeGeneralQueriesThrift>AbstractTestNativeGeneralQueries.testSystemTables:1448->AbstractTestQueryFramework.assertQuery:154 Execution of 'actual' query failed: SELECT * FROM    (SELECT DISTINCT regionkey FROM tmp_presto_3f632701ec7a4899ba67f87da2862f5d) t INNER JOIN    (SELECT regionkey FROM "tmp_presto_3f632701ec7a4899ba67f87da2862f5d$partitions") p ON t.regionkey = p.regionkey
[INFO] 
[ERROR] Tests run: 111, Failures: 1, Errors: 0, Skipped: 0
[INFO]

**Comment by elharo** [comment]
I still see 300 lines of Counting Objects, Retrieving Objects, and Resolving deltas in https://productionresultssa17.blob.core.windows.net/actions-results/2f562173-de74-4bd4-af3f-f0a13eea8092/workflow-job-run-620a21eb-788c-555f-a35f-b85781ff7ced/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-03-12T17%3A46%3A28Z&sig=NAebra3JR4LbTuUIOgVEclyuPsEtUdX8A9W5x05C5EM%3D&sp=r&spr=https&sr=b&st=2024-03-12T17%3A36%3A23Z&sv=2021-12-02

Are you sure this is the right flag?

```
2024-03-12T15:58:16.1258920Z [command]/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +c905e20130348358b8ebc851b7a61304558e5aec:refs/remotes/pull/22167/merge
2024-03-12T15:58:16.3180587Z remote: Enumerating objects: 13567, done.        
2024-03-12T15:58:16.3181634Z remote: Counting objects:   0% (1/13567)        
2024-03-12T15:58:16.3183075Z remote: Counting objects:   1% (136/13567)        
2024-03-12T15:58:16.3183977Z remote: Counting objects:   2% (272/13567)        
2024-03-12T15:58:16.3184840Z remote: Counting objects:   3% (408/13567)        
2024-03-12T15:58:16.3185935Z remote: Counting objects:   4% (543/13567)        
2024-03-12T15:58:16.3186990Z remote: Counting objects:   5% (679/13567)        
2024-03-12T15:58:16.3187930Z remote: Counting objects:   6% (815/13567)        
2024-03-12T15:58:16.3188694Z remote: Counting objects:   7% (950/13567)        
```

**Comment by tlm365** [comment]
> I still see 300 lines of Counting Objects, Retrieving Objects, and Resolving deltas in https://productionresultssa17.blob.core.windows.net/actions-results/2f562173-de74-4bd4-af3f-f0a13eea8092/workflow-job-run-620a21eb-788c-555f-a35f-b85781ff7ced/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-03-12T17%3A46%3A28Z&sig=NAebra3JR4LbTuUIOgVEclyuPsEtUdX8A9W5x05C5EM%3D&sp=r&spr=https&sr=b&st=2024-03-12T17%3A36%3A23Z&sv=2021-12-02
> 
> Are you sure this is the right flag?
> 
> ```
> 2024-03-12T15:58:16.1258920Z [command]/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +c905e20130348358b8ebc851b7a61304558e5aec:refs/remotes/pull/22167/merge
> 2024-03-12T15:58:16.3180587Z remote: Enumerating objects: 13567, done.        
> 2024-03-12T15:58:16.3181634Z remote: Counting objects:   0% (1/13567)        
> 2024-03-12T15:58:16.3183075Z remote: Counting objects:   1% (136/13567)        
> 2024-03-12T15:58:16.3183977Z remote: Counting objects:   2% (272/13567)        
> 2024-03-12T15:58:16.3184840Z remote: Counting objects:   3% (408/13567)        
> 2024-03-12T15:58:16.3185935Z remote: Counting objects:   4% (543/13567)        
> 2024-03-12T15:58:16.3186990Z remote: Counting objects:   5% (679/13567)        
> 2024-03-12T15:58:16.3187930Z remote: Counting objects:   6% (815/13567)        
> 2024-03-12T15:58:16.3188694Z remote: Counting objects:   7% (950/13567)        
> ```

@elharo yes, it resolved now.

**Review by tdcmeehan — APPROVED** [review]

**Pull request merged**
