### PR TITLE
TaskInfo Thrift fixes

### PR DESCRIPTION
**Pull request by ajaygeorge**
- Fix TaskResource to convert TaskInfo response to thrift
- Add TaskInfo thrift support for HttpRemoteTask

Test plan - 
Verifier tests.
With the fix : https://www.internalfb.com/intern/presto/verifier/results/?test_id=89780

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by ajaygeorge** [comment]
Lot of github checks are getting cancelled after 60 min. I can see the same happening for other PRs as well.
Native tests are failing for other PRs as well.  cc @mshang816

**Review by tdcmeehan — APPROVED** [review]

**Comment by ajaygeorge** [comment]
@tdcmeehan all checks are passing % native build which is failing for everyone.

**Comment by pranjalssh** [comment]
test native is not required to pass for merging. @tdcmeehan can we merge?

@ajaygeorge did you check tw logs for any null pointer exception?

**Comment by ajaygeorge** [comment]
@pranjalssh yes. No Exceptions in log.

**Pull request merged**
