### PR TITLE
Support Nested Schema Evolution in Parquet for Presto #6675. Copy of …

### PR DESCRIPTION
**Pull request by sathiscode**
Copy of code from https://github.com/prestodb/presto/pull/6675 and migrated to support recent code changes.

### CODE REVIEW

**Comment by afranzi** [comment]
Hi @sathiscode & @zhenxiao, 

Is there any intention of merging this useful code to master? We are using Presto in Production with this Patch and it works fine too.

It would be great if nested fields and schema evolution where supported by default in Presto.

**Comment by sathiscode** [comment]
@afranzi I'm not an admin, so don't have permission to merge the code. Waiting for someone to merge the code.

**Comment by sajjoseph** [comment]
I noticed that the newer codebase (0.211 and 0.213 were tested) supports this feature and so this PR might not be needed. With https://github.com/prestodb/presto/pull/10737/, parquet reader was rewritten and the changes in this PR are no longer valid. 
The only change remains to be done is the enhancements to the test cases to validate nested schema evolution.

**Comment by Pjack** [comment]
Amazon Athena utilizes this parquet parser and AWS support refuses to apply the fix on their end until this PR is merged. Do you have plan for this?  Thanks!

**Comment by Pjack** [comment]
#6675 is closed, does it mean this issue is resolved too?

**Pull request closed without merging**
