### PR TITLE
Upgrade Delta Standalone to 3.0.0

### PR DESCRIPTION
**Pull request by dnskr**
This PR upgrades Delta Standalone dependency to [3.0.0](https://github.com/delta-io/delta/releases/tag/v3.0.0) for Delta Lake Connector.

Test plan - Existing tests

```
== RELEASE NOTES ==

Delta Lake Changes
* Upgrade Delta Standalone to 3.0.0
```

### CODE REVIEW

**Comment by agrawalreetika** [comment]
Hi, @dnskr, 
Wanted to confirm does this upgrade also fix `_last_checkpoint` file check-related exception which was mentioned here - https://github.com/prestodb/presto/issues/18898

**Comment by dnskr** [comment]
> Hi @dnskr, Wanted to confirm does this upgrade also fix `_last_checkpoint` file check-related exception which was mentioned here - #18898

I don't think so. I'm not sure I can check it, because unfortunately I'm quite limited in Presto development and debugging by Windows machine I use.

**Comment by tdcmeehan** [comment]
@dnskr have you done any end to end tests on this upgrade?

**Comment by agrawalreetika** [comment]
> Hi @dnskr, Wanted to confirm does this upgrade also fix `_last_checkpoint` file check-related exception which was mentioned here - #18898

@dnskr, I tried query on this upgrade. Looks like `_last_checkpoint` file check exception is not handled here as well.

**Comment by dnskr** [comment]
@tdcmeehan Unfortunately, I cannot build Presto or run tests locally, because I use Windows. So, I rely on passing CI/CD pipelines and [existing delta tests](https://github.com/prestodb/presto/tree/d9fc66d73c0f3aadb6df1116420251ff7cc4f688/presto-delta/src/test/java/com/facebook/presto/delta) to check that the upgrade is fine.

@agrawalreetika There is at least one performance improvement in Delta Standalone according to [release notes](https://github.com/delta-io/delta/releases/tag/v3.0.0https://github.com/delta-io/delta/releases/tag/v3.0.0):

> The key features in this release are:
> 
> - [Support](https://github.com/delta-io/delta/commit/baf54ffd) for disabling Delta checkpointing during commits - For very large tables with millions of files, performing Delta checkpoints can become an expensive overhead during writes. Users can now disable this checkpointing by setting the hadoop configuration property io.delta.standalone.checkpointing.enabled to false. This is only safe and suggested to do if another job will periodically perform the checkpointing.
> - [Performance](https://github.com/delta-io/delta/commit/f11c3556) improvement to snapshot initialization - When a delta table is loaded at a particular version, the snapshot must contain, at a minimum, the latest protocol and metadata. This PR improves the snapshot load performance for repeated table changes.
> - [Support adding absolute paths](https://github.com/delta-io/delta/commit/02a46d19) to the Delta log - This now enables users to manually perform SHALLOW CLONEs and create Delta tables with external files.
> - [Fix](https://github.com/delta-io/delta/commit/4dadc028) in schema evolution to prevent adding non-nullable columns to existing Delta tables


@agrawalreetika @tdcmeehan I would like to be transparent about the amount of effort from my side for the changes.
I upgraded Delta Standalone just to keep the dependency up to date, without expecting any significant improvements.
During the preliminary upgrade to 3.0.0rc1 I found and reported a [minor bug](https://github.com/delta-io/delta/issues/1892), which is fixed in 3.0.0.
I would be happy if someone could take the opportunity to manage Delta Lake upgrades in more careful way.

BTW, as far as I know, next Delta Standalone 3.1.0 release will be based on Delta Kernel, which might require more effort for upgrade, but also can provide more capabilities for Delta Lake connector in Presto.

**Comment by dnskr** [comment]
Close in favor of https://github.com/prestodb/presto/pull/22596

**Pull request closed without merging**
