### PR TITLE
Make HashTable computation lazy in MapBlockBuilder (Redo)

### PR DESCRIPTION
**Pull request by arunthirupathi**
This change was originally done in https://github.com/prestodb/presto/pull/16027
but reverted as it regressed the Broadcast joins. 
The analysis of the regression is here. 
https://github.com/prestodb/presto/pull/16172#issuecomment-850780629

The regression is addressed by computing the hashtable
before the mapblock is encoded. 

Original commit message:
#12198 made hash computation
lazy in the MapBlock, but MapBlockBuilder computed the hash tables
always.

Always computing the hash table had 2 issues
MapBlockBuilder always computed the hash and it is not used in some
cases (OrcWriter). Hash computation took around 5-10% of the CPU.
Null keys in map, failed the hash computation part.
Note: Presto query engine does not support null keys in map. But we
are using Presto orc writer as a stand alone library and this requires null
keys support in map.

Making the Hash table lazy solves both the issues.

Test plan - (Please fill in how you tested your changes)

Added more unit tests
Ran Presto verifier few times and verifier passed.
Ran Presto shadow tests on multiple regions for query with map_agg, element_at and map. Verified that no regression in performance was identified.
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by rschlussel** [comment]
A concern i have is that the regression is possible any time there is a mapblock with a join.  The fix addresses this by computing the hashtable before shuffling.  This is more aggressive than necesssary if there is no join, but also still leaves the problem if a mapblock is created on the same node as the join (so there is no shuffle).  It would be better for the fix to directly address the problem.

**Comment by arunthirupathi** [comment]
These are all the different scnearios and how this fix impacts them.  Please let me know if there is a missed scenario and it should be added to the table.

<meta charset="utf-8"><div dir="ltr" style="margin-left:0pt;" align="left">

Scenario | Before | After
-- | -- | --
MapBlock created from Builder encoding/decoding | HashTable is included in the encoding and decoded | Same
MapBlock created from key/value blocks (Not using builder, ORC reader does this) encoding/decoding | Hashtable is not included while encoded. | Same
MapBlock created from Builder, No encoding/decoding (no copy) | HashTable is computed | HashTable is lazily computed when required. Will save Compute costs on the ORC writer, as Writer does not require a hash table.
MapBlock created from Builder, No encoding/decoding (but copied) | HashTable is computed once. | HashTable is computed as many times as the copy. (Performance will regress, but I don’t know of active use cases)

</div>

So if the MapBlock is created from MapBlockBuilder, but block is repeatedly copied, it might result in a regression. But I believe such scenario is going to be very small and the gains from 3 (no copy) would more than offset the CPU loss from 4 (copy case).

**Comment by rschlussel** [comment]
I still don't love the solution to materialize the hash table before encoding. A much better solution would be to fix the root cause issue to have the join operator materialize the hash table once.  That would be more intuitive since it would address the root problem instead of trying to limit the cases where we run into it (without eliminating them).  It would also allow a bigger efficiency win for the lazy map block since we would be able to keep the map block lazy accross shuffle boundaries, and it would fix the existing problem with the map blocks created by the orc reader that are already lazy.

**Comment by arunthirupathi** [comment]
I would prefer the Join solution as well. But the Join solution is very complicated and has other down sides. 

There are many different join operators. This would require all build side to move to dictionary blocks, which is a much broader change. The impact of moving everything to move to Dictionary blocks is also a much harder change. 

Fixing NestedLoopJoin when there is a single row is easy, but that may not solve other use cases. I can include that fix in this PR if required.

**Comment by kaikalur** [comment]
One thing I was thinking of at some point is to compute the hashtable only when someone calls element_at. Not sure if that addesses the broadcast join issue though.

**Comment by kaikalur** [comment]
Yet another idea would be to always build the hashtable for any global (non-group by) map_agg which we should be able to do locally in MapAggregationFunction

**Comment by arunthirupathi** [comment]
https://github.com/prestodb/presto/pull/16432 commit moved to this PR for merging.

**Comment by arunthirupathi** [comment]
https://github.com/prestodb/presto/pull/16415 is moved to here for merging.

**Review by rschlussel — APPROVED** [review]
Thank you for being so thorough!

**Pull request merged**
