### PR TITLE
[WIP] Reservoir sample udf

### PR DESCRIPTION
**Pull request by atavory**
Add UDFs for reservoir sampling, both weighted and unweighted.

### CODE REVIEW

**Comment by highker** [comment]
Can't wait!

**Comment by atavory** [comment]
Hello @highker, 

I'm trying to run unittests from `TestUnweightedIntAggregation`, but am getting an error I don't understand. Could you please advise? Many thanks!

image

**Comment by rongrong** [comment]
It's complaining about cannot find the method when look up method handle. It seems that you defined the input function method handle with `long` but the actual function is `int`. Maybe that's related.

**Comment by atavory** [comment]
> It's complaining about cannot find the method when look up method handle. It seems that you defined the input function method handle with `long` but the actual function is `int`. Maybe that's related.

Thanks, @rongrong, appreciate it!

It turned out to be something a bit different, IIUC. When registering the function class, the constructor was throwing an exception. Am (slowly) fixing things.

**Comment by atavory** [comment]
@rongrong  @highker 

Am getting the error in the screenshot image when the testsuite is trying to load the udf. The exact error is "java.lang.IllegalArgumentException: com.facebook.presto.operator.aggregation.reservoirsample.UnweightedIntReservoir".

Like last time, I've looked through the code to see what is going on, but it's somewhere throwing an exception, and I just see where it was caught. Could you please suggest how to proceed? Many thanks!

**Comment by rongrong** [comment]
It's likely because you didn't setup your serialization / deserialization of the state correctly.

**Comment by rongrong** [comment]
Screen Shot 2019-11-11 at 12 43 11 PM

**Pull request closed without merging**
