### PR TITLE
Fix error message when view creation fails because of lack of grant privilege

### PR DESCRIPTION
**Pull request by amrutagokhale**
Fixes https://github.com/prestodb/presto/issues/5632.

Teradata's internal review: https://github.com/Teradata/presto/pull/256.

Note: I am going to add a product test for this in another pull request where product tests for all access control checks in Presto will go in.

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by dain** [comment]
@raghavsethi can you look at this one?

**Comment by raghavsethi** [comment]
@amrutagokhale: The commit message is too long. Maybe just 'Improve error message for view creation denial'? Also, could you rebase and push to get Travis to be green?
@dain: Looks good to me

**Comment by amrutagokhale** [comment]
Updated the commit message and rebased.

**Comment by raghavsethi** [comment]
@amrutagokhale: did you sign the CLA?

**Comment by petroav** [comment]
@martint & @raghavsethi, she's had to sign the CLA a bunch of times, I think every time she does a pull request. Not sure what's going on ...

**Comment by raghavsethi** [comment]
Merged, thanks!

**Pull request closed without merging**
