### PR TITLE
[native]Advance velox and remove legacy memory apis

### PR DESCRIPTION
**Pull request by xiaoxmeng**
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by aditi-pandit — APPROVED** [review]
Thanks @xiaoxmeng

**Review by aditi-pandit — CHANGES_REQUESTED** [review]
@xiaoxmeng : Please fix the format-check failure.

**Comment by xiaoxmeng** [comment]
> @xiaoxmeng : There is a format-check failure. PTAL.

@aditi-pandit it has been fixed now. Thanks for pointing out!

**Review by aditi-pandit — APPROVED** [review]
Thanks @xiaoxmeng

**Pull request merged**
