### PR TITLE
[WIP] Split special form of row expressions to separate node

### PR DESCRIPTION
**Pull request by rongrong**

### CODE REVIEW

**Comment by raghavsethi** [comment]
`Special form` is, funnily enough, a very generic name, and not as descriptive as I would like. What were some other names you considered?

**Comment by rongrong** [comment]
Funny enough, we discussed about this already, and cannot come up with any good names. Names that came up are: BuiltInExpression, SqlBuiltInExpression, SqlLanguageExpression, SqlReservedExpression, BuiltInCallExpression. I guess the last one is the best one we came up, but it's still a bit strange. Since @dain  gave it the name `SpecialForm` (without the `Expression`, so it's even more confusing), we figured we'd just honor the original author and keep it. Here's the original diff: https://github.com/prestosql/presto/pull/196/commits/f6f70dc53a9c792f970609ee75c73142e8ed7552 I copied the commit title.

**Comment by rongrong** [comment]
BTW, this is not for review, I'm rebasing and want to make sure each commit is correct. And this is the PR for that purpose. Actual PR is here: https://github.com/prestodb/presto/pull/12444/

**Comment by rongrong** [comment]
@raghavsethi  If you are good at giving names, please help!

**Comment by raghavsethi** [comment]
@rongrong and I discussed offline and came to a consensus.

**Pull request closed without merging**
