### PR TITLE
[native] Fix docker-compose and add etc config into native worker docker image

### PR DESCRIPTION
**Pull request by wypb**
## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```
CC: @majetideepak

### CODE REVIEW

**Review by majetideepak — APPROVED** [review]
Thanks, @wypb

**Review by majetideepak — CHANGES_REQUESTED** [review]
@wypb please prepend [native] prefix and update the commit for adding `etc` to indicate this.

**Comment by wypb** [comment]
@majetideepak Thank you for you review. I have made changes according to the review comments.

**Comment by majetideepak** [comment]
@wypb Sorry for the confusion. I was expecting two commits like you had before. Since you squashed them into one, can you change the commit title? In Presto, the commit title is what gets reflected and not the PR title.

**Comment by wypb** [comment]
@majetideepak Sorry, I misunderstood. I have changed the commit title.

**Review by majetideepak — APPROVED** [review]

**Pull request merged**
