### PR TITLE
[native] Move writer test to a central place

### PR DESCRIPTION
**Pull request by kewang1024**
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by aditi-pandit** [comment]
@kewang1024 : Please can you rebase your code. Will review after that.

**Comment by kewang1024** [comment]
@aditi-pandit I just rebased, thanks!

**Comment by aditi-pandit** [comment]
@kewang1024 : Is there a dependency on updating Velox ? We usually update Velox in individual PRs.

**Comment by xiaoxmeng** [comment]
> @kewang1024 : Is there a dependency on updating Velox ? We usually update Velox in individual PRs.

@kewang1024 we probably don't need this. Can revert the velox upgrade before land. Thanks!

**Review by xiaoxmeng — APPROVED** [review]
@kewang1024 thanks for the refactor!

**Comment by kewang1024** [comment]
> @kewang1024 : Is there a dependency on updating Velox ? We usually update Velox in individual PRs.

We don't need that, I must have pushed by mistake, let me revert the velox update

**Review by xiaoxmeng — DISMISSED** [review]

**Review by xiaoxmeng — APPROVED** [review]

**Pull request merged**
