### PR TITLE
Fix NaN/Infinity value for double/float partition columns

### PR DESCRIPTION
**Pull request by gupteaj**
Cherry-pick of https://github.com/trinodb/trino/pull/15727 (https://github.com/trinodb/trino/pull/15727)

Co-authored-by: ebyhr <ebyhry@gmail.com>

Cherry-pick : NaN value for double/float partition columns
Presto fix : Infinity value for double/float partition columns

issue - https://github.com/prestodb/presto/issues/20366
Test plan - (Please fill in how you tested your changes)
- Added tests for NaN and Infinity cases 

create table test.part_double (c1 varchar, c2 double) with (partitioning =array['c2']);
insert into test.part_double values ('fix', real 'NaN');
insert into test.part_double values ('fix', double 'NaN');
presto:test> select * from part_double where c1 = 'fix';
 c1  | c2  
-----+-----
 fix | NaN 
 fix | NaN 
(2 rows)

Please make sure your submission complies with our [Development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [Formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), and [Commit Message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests) guidelines. Don't forget to follow our [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution) for any code copied from other projects.

Fill in the release notes towards the bottom of the PR description.
See [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) for details.

```
== RELEASE NOTES ==

Iceberg Changes 

* Fix incorrect results when reading or writing `NaN`, 'Infinity', '-Infinity' with `real` or `double` types on partitioned columns.

```

### CODE REVIEW

**Comment by gupteaj** [comment]
@tdcmeehan , can you please review this change ?

**Comment by tdcmeehan** [comment]
Does the same problem happen with `Infinity`?

**Comment by gupteaj** [comment]
> Does the same problem happen with `Infinity`?
@tdcmeehan , yes. should I create a new issue or fix in same pr ? Since this pr is cherry-pick from trino. 

```
SELECT part FROM test_partitioned_by_double
not equal
Actual rows (up to 100 of 1 extra rows shown, 1 rows in total):
    [0.0]
Expected rows (up to 100 of 1 missing rows shown, 1 rows in total):
    [Infinity]
```

**Comment by tdcmeehan** [comment]
Let's go ahead and fix this too while we're at it. 😄

**Comment by tdcmeehan** [comment]
You can put the `Infinity` fix as a separate commit to preserve attribution for the `NaN` fix.

**Comment by tdcmeehan** [comment]
LGTM % fix the checkstyle errors

**Pull request merged**
