### PR TITLE
[native] Update clang check CI image

### PR DESCRIPTION
**Pull request by majetideepak**
## Description

Fix for `clang-format:75:1: error: unknown key 'InsertNewlineAtEOF'
InsertNewlineAtEOF: true`
Resolves https://github.com/prestodb/presto/issues/23221

Exclude Velox from the header and format check in CI. 
The Velox project does these checks.

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by majetideepak** [comment]
@wanglinsong, Presto CI uses an old CI image for the presto-native-execution format check. I fixed it here by using the Velox CI Image for check. Should we copy this to the Presto project?

**Comment by wanglinsong** [comment]
> @wanglinsong, Presto CI uses an old CI image for the presto-native-execution format check. I fixed it here by using the latest Velox CI Image for check. Should we copy this to the Presto project?

Yes, please. We then can rebase the branch `native-worker-image` to the latest master.

**Comment by majetideepak** [comment]
@wanglinsong This is purely related to CI. The image `ghcr.io/facebookincubator/velox-dev:check` for the format and header check is in the Velox project.
I was wondering if we should copy this image to the Presto image repo for Prestissimo CI.

**Comment by wanglinsong** [comment]
> @wanglinsong This is purely related to CI. The image `ghcr.io/facebookincubator/velox-dev:check` for the format and header check is in the Velox project. I was wondering if we should copy this image to the Presto image repo for Prestissimo CI.

Do you want to push it into `https://gallery.ecr.aws/oss-presto` or `https://hub.docker.com/u/prestodb`?
Both are publicly accessible.

**Comment by majetideepak** [comment]
@tdcmeehan can you help review/merge this PR? Thanks!

**Review by tdcmeehan — APPROVED** [review]

**Review by wanglinsong — APPROVED** [review]
LGTM

**Pull request merged**
