### PR TITLE
Add MAX_STEP Window function

### PR DESCRIPTION
**Pull request by tinylambda**
Use case:

In case we want to calculate the transfer rate based on the time series data, it means that all the data must be ordered by the timestamp column;

say that , we want to check every user if he or she has the following pattern or its sub-patterns（ordered by timestamp）:

pattern defination: 
page_view  => attempt_to_register => register_success

sub-patterns: 
page_view
page_view  => attempt_to_register

We found that it's a common requirement, so we write a window function to fulfill this requirement.

we successfully use this MAX_STEP window function in the Presto-0.147 environment, but **not tested on other versions of Presto**, It can be used as following:

SELECT ap, COUNT(1) AS mp
FROM
(SELECT userid, MAX(action_pattern) AS ap
FROM
(SELECT userid, MAX_STEP(xwhat, 'step1=>step3') OVER (PARTITION BY userid ORDER By xwhen ASC) AS action_pattern
FROM tmp.event2
WHERE xwhat IN ('step1','step3') AND ds>='2016-06-05' AND ds<='2016-06-13') T1
GROUP BY userid) T2
GROUP BY ap;

By executing this SQL, we can get (MAX_STEP, USER_AMOUNT) pairs, and then, we can calculate the transfer rate by using the results.

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-9** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by tinylambda** [comment]
any suggestions on this new window function ?

**Comment by electrum** [comment]
Thanks for submitting this pull request. This function implements pattern matching over a window, albeit a very limited form. I think we could expand this into a more generic pattern matching facility. Related, I filed #5850 about Oracle's `MATCH_RECOGNIZE`.

**Comment by electrum** [comment]
We can define a pattern syntax that matches input items or "tokens". To keep the pattern syntax simple, a token should use a limited set of characters. Perhaps fully alphanumeric, or restrict to starting with a letter.

A pattern is one or more tokens, separated by spaces. Each token is matched exactly once, unless followed by a modifier:

`?` occurs zero or one times
`*` occurs zero or more times
`+` occurs one or more times

However, this actually doesn't work for the original use case, which doesn't care about non-matching things in between matches. We'd need a `.` operator that could match anything. It would also have to be non-greedy to allow a pattern like `A .* B` to work as expected. But then how does the returned count work? Only match explicit tokens? What about a pattern like `A B+ C` matched against `A B B B C D E`? Does it return `3` or `5`?

Maybe there's not a good way to generalize this without making the originally proposed use case too complicated.

**Comment by electrum** [comment]
Keeping with the original proposed function, it might be best to use an array rather than a string, which avoids parsing and lets you use anything for the pattern items:
```
max_step(value, array['step1', 'step3'])

**Comment by tinylambda** [comment]
hi electrum, thanks for the reply, and this is just a very simple function for detecting some user activity pattern on time series data.

though this function is not generic, it is a common requirement in the user activity analysis.

Question: What about a pattern like A B+ C matched against A B B B C D E? Does it return 3 or 5?
Answer: It should return 3, because the result is based on pattern definition's index ([A, B+, C]), not on the time series data (A B B B C D E).

PS: The name of the function seems like an aggregation function, so it's better to change the name of this function to STEP_DETECT, I think it's more like a window function's name, isn't it ?

As you suggested, it's much better to use ARRAY for the pattern definition, and I am trying to change the pattern definition to the ARRAY form, but I don't find any example that using ARRAY type in the window function implementation. Can you give some help?  Thanks very much.

**Comment by electrum** [comment]
Sorry for the late response. It looks like arrays aren't supported for window functions, but it should be easy to add:

* Add a `getObject()` method to `PagesIndex` that works like `getSlice()` but instead calls `Type.getObject()`.
* Add a corresponding method in `WindowIndex` and `PagesWindowIndex`.

At this point, we can use that to access the array in the window function:

```java
// get array from window function argument
Block array = (Block) windowIndex.getObject(patternDefChannel, currentPosition);

// create type for array(varchar)
Type arrayType = new ArrayType(createUnboundedVarcharType());

// iterate over array
for (int i = 0; i < array.getPositionCount(); i++) {
    if (array.isNull(i)) {
        output.appendNull();
        return;
    }
    Slice value = arrayType.getSlice(array, i);
    // use value
}

**Pull request closed without merging**
