### PR TITLE
Add support for MaxResults on Glue Hive Metastore

### PR DESCRIPTION
**Pull request by v-jizhang**
Cherry pick of https://github.com/trinodb/trino/pull/3024 and
https://github.com/trinodb/trino/pull/4938

Co-authored-by: Istvan <istvan@lambdainsight.com>
Co-authored-by: Ashhar Hasan <hashhar_dev@outlook.com>

```
== RELEASE NOTES ==

Hive Changes
* Add support for MaxResults on Glue Hive Metastore
```

### CODE REVIEW

**Review by aweisberg — APPROVED** [review]
Hard coded values gives me slight pause, but it's in production in Trino and no one is complaining so I will +1 it.

This is metadata so I assume a constant metadata fetch size is acceptable although if it includes statistics it seems like it might be a value people want to change?

**Comment by aweisberg** [comment]
@pettyjamesm do you have an opinion on this being hard coded? Would you mind merging if you think it is acceptable.

**Comment by pettyjamesm** [comment]
I saw this change in Trino after it had merged. I tried to reproduce the described behavior but what I saw seemed to indicate that setting this value actually has no effect and that there's some other implementation detail on the Glue end that actually determines how many partitions will be included in any given response. That said, hard coding a value should be harmless enough: I can't think of a  use case that would want any less than the maximum partitions per response and the maximum allowed values for APIs like this tend not to change all that often.

**Review by pettyjamesm — APPROVED** [review]

**Comment by aweisberg** [comment]
@pettyjamesm feel free to merge if you approve :-)

**Comment by pettyjamesm** [comment]
> @pettyjamesm feel free to merge if you approve :-)

The Facebook Integration step not being completed means that this PR hasn't met the "all checks must pass" criteria to merge. Is that something you can trigger on your side or will this PR need to be force-pushed to re-run?

**Comment by aweisberg** [comment]
Updated to see if that will trigger an integration build. I think there is almost no chance it would do that, but not worth risking.

**Comment by pettyjamesm** [comment]
Merged, thanks!

**Pull request merged**
