### PR TITLE
Use single line logging format for product tests

### LINKED ISSUE #5916: Use single line logging format for product tests
The output seems to use the default JUL two-line format which is hard to read:
```
Aug 20, 2016 12:35:39 AM com.teradata.tempto.internal.listeners.ProgressLoggingListener logTestEnd
INFO: SUCCESS     /    took 0 minutes and 5 seconds
```

One way to fix this is to set the system property `java.util.logging.SimpleFormatter.format`, which is what we do for unit tests in the Surefire configuration:
```
%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS %4$s %5$s%6$s%n
```

It could also be helpful to shorten the logger name to just the class name `ProgressLoggingListener`, though that isn't possible with the `SimpleFormatter`. One way is to change `ProgressLoggingListener` to not include the full package name in the logger name (i.e. just do `Logger.get("ProgressLoggingListener")` or perhaps something more semantic like `TestProgress`.

### PR DESCRIPTION
**Pull request by ArturGajowy**
Fixes #5916.

### CODE REVIEW

**Comment by ArturGajowy** [comment]
Sample test output:

```
[TestNG] Running:
  tempto-tests

2016-08-22 23:04:15 INFO: Starting tests running
2016-08-22 23:04:17 INFO: Reflections took 1848 ms to scan 1 urls, producing 3066 keys and 15717 values
2016-08-22 23:04:25 INFO:
2016-08-22 23:04:25 INFO: [1 of 21] com.facebook.presto.tests.AlterTableTests.addColumn (Groups: smoke, alter_table)
2016-08-22 23:04:32 INFO: SUCCESS     /    took 0 minutes and 6 seconds
2016-08-22 23:04:32 INFO:
2016-08-22 23:04:32 INFO: [2 of 21] com.facebook.presto.tests.AlterTableTests.renameColumn (Groups: smoke, alter_table)
2016-08-22 23:04:35 INFO: SUCCESS     /    took 0 minutes and 3 seconds
2016-08-22 23:04:35 INFO:
2016-08-22 23:04:35 INFO: [3 of 21] com.facebook.presto.tests.AlterTableTests.renameTable (Groups: smoke, alter_table)
2016-08-22 23:04:38 INFO: SUCCESS     /    took 0 minutes and 3 seconds
2016-08-22 23:04:38 INFO:
2016-08-22 23:04:38 INFO: [4 of 21] com.facebook.presto.tests.cli.PrestoCliTests.shouldDisplayVersion (Groups: cli)
2016-08-22 23:04:39 INFO: SUCCESS
//...
2016-08-22 23:04:56 INFO:
2016-08-22 23:04:56 INFO: [19 of 21] com.facebook.presto.tests.SimpleQueryTest.selectCountFromNation (Groups: smoke, simple)
2016-08-22 23:04:56 INFO: SUCCESS
2016-08-22 23:04:56 INFO:
2016-08-22 23:04:56 INFO: [20 of 21] com.facebook.presto.tests.CreateDropViewTests.createOrReplaceSimpleView (Groups: create_drop_view, smoke)
2016-08-22 23:04:58 INFO: SUCCESS     /    took 0 minutes and 1 seconds
2016-08-22 23:04:58 INFO:
2016-08-22 23:04:58 INFO: [21 of 21] com.facebook.presto.tests.CreateDropViewTests.dropViewTest (Groups: create_drop_view, smoke)
2016-08-22 23:05:00 INFO: SUCCESS     /    took 0 minutes and 1 seconds
2016-08-22 23:05:00 INFO:
2016-08-22 23:05:00 INFO: Completed 21 tests
2016-08-22 23:05:00 INFO: 21 SUCCEEDED      /      0 FAILED      /      0 SKIPPED
```

**Comment by ArturGajowy** [comment]
@electrum Please have a look :)

I dropped the class name from log output as the messages say everything themselves.
I kept the ':' after log level so that people searching for 'INFO: FAILURE' don't have to change habits.

**Comment by maciejgrzybek** [comment]
@ArturGajowy: isn't it suppose be one line per test instead of 3 lines?
Currently (as of your sample output) first line contains name of test, second line contains result and third is simple separator. It's quite verbose, don't you think?

**Comment by ArturGajowy** [comment]
@maciejgrzybek my thought exactly and I'm planning to change it... in tempto. Meanwhile, this is a clear improvement (I bet most of us didn't really notice the '3 messages per test' problem so far).

**Comment by ArturGajowy** [comment]
Additionally:
> isn't it suppose be one line per test instead of 3 lines?

The issue and commit title refer to logging format and require that it's one line per log message. So, technically, it isn't ;)

**Comment by electrum** [comment]
Merged, thanks!

**Comment by electrum** [comment]
The three line format is a bit verbose, but WAY more readable than before. Thanks for fixing!

After removing the download progress and bogus startup exceptions, the product tests don't produce that much output, so three lines might be fine. Though if you can come up with a good one-line format, even better.

**Pull request closed without merging**
