### PR TITLE
Ensure Parameters are in proper order for queries having WITH clause

### LINKED ISSUE #17012: Ensure Parameters are in proper order for queries having WITH clause
Hello Everyone,

I am having a bug with Presto and Prepare statement.

I run the following prepare statement:
```
PREPARE statement1 FROM 
with t1 as (select * 
from database.fact_order
join database.dim_poc
on database.dim_poc.poc_id = database.fact_order.poc_id
where "database"."dim_poc"."poc_category" IN (?)
and database.fact_order.poc_id = ?)
select * from t1
where created_date_brt = ?
limit 10
```

A normal behavior is to have something like that on Execution phase:
```
EXECUTE statement1 USING 'BAR', 1234, DATE '2021-11-16'
```

But PrestoDb Expected the wrong order:
```
EXECUTE statement1 USING DATE '2021-11-16', 'BAR', 1234
```

This bug is related to the same bug on Trino 
https://github.com/trinodb/trino/issues/1191

Trino has a PR to solve the problem:
https://github.com/trinodb/trino/pull/1529

thank you

### PR DESCRIPTION
**Pull request by v-jizhang**
Cherry-pick of https://github.com/trinodb/trino/pull/1529

Fixes #17012

Co-authored-by: praveenkrishna <praveenkrishna@tutanota.com>

Test plan - Added a test.

```
== RELEASE NOTES ==

General Changes
* Ensure Parameters are in proper order for queries having WITH clause

```

### CODE REVIEW

**Comment by rubenssoto** [comment]
Is there any chance of being merged in the next version? Very important fix for us.

Thank you!

**Comment by zhenxiao** [comment]
hi @v-jizhang could you please rebase this PR? I will take a look

**Comment by v-jizhang** [comment]
> hi @v-jizhang could you please rebase this PR? I will take a look
@zhenxiao 
Done. Thanks for reviewing.

**Review by zhenxiao — APPROVED** [review]
looks good

**Pull request merged**
