### PR TITLE
Use primitive array for blockPositionByHash in TypedSet

### PR DESCRIPTION
**Pull request by nezihyigitbasi**
This shaves off some memory overhead from `TypedSet` instances (shallow size of a single `IntArrayList` object is ~25 bytes).

### CODE REVIEW

**Comment by nezihyigitbasi** [comment]
This PR is related to #7342. 

As a side note, when running the test query in #7342 on my laptop I see that there is plenty of garbage due to `BlockBuilderStatus`/`PageBuilderStatus` instances (AFAIK not tracked by the memory manager) -- the retained size for `BlockBuilderStatus` is ~200MB. And since we are not really using these status instances for anything we can just use a single static final `BlockBuilderStatus` instance to get rid of this overhead in `KeyValuePairs`/`TypedSet` classes (again since this is not tracked by the memory manager this won't reduce the "tracked" peak memory usage of the test query, but it will reduce the garbage on heap).

image

**Comment by wenleix** [comment]
@nezihyigitbasi  Thank you ! Just curious why `IntArrayList` is so inefficient -- I glance at the code and it looks like it just has a redundant `size` besides the array? Is that because of the complicated extending and implementing?

**Comment by nezihyigitbasi** [comment]
@wenleix each `IntArrayList` has an additional object header of size 16 bytes, and the `size` field is aligned to a byte boundary (hence occupies 8 bytes instead of 4 bytes), so that's 16 + 8 = 24 bytes additional for each instance.

**Comment by nezihyigitbasi** [comment]
Superseded by #7421.

**Pull request closed without merging**
