### PR TITLE
Move presto-testng-services to top level

### PR DESCRIPTION
**Pull request by aweisberg**
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by ajaygeorge** [comment]
We need to change the module from `<module>testing/presto-testng-services</module>` to <module>presto-testng-services</module>` in the presto root pom.xml

**Review by ajaygeorge — APPROVED** [review]
LGTM

**Review by jainxrohit — APPROVED** [review]

**Comment by jainxrohit** [comment]
The test failures are related.

**Review by tdcmeehan — APPROVED** [review]

**Comment by ajaygeorge** [comment]
Thanks @tdcmeehan for reviewing this. Can you please merge this when you get a chance.

**Pull request merged**
