### PR TITLE
Limit size of response sent to client.

### LINKED ISSUE #11332: SELECT on a partitioning column can send a very large response to the client
An easy way to reproduce the issue is to create a partitioned table with a small number of partitions (~10) and a relatively large number of rows(~10million). 
For example if the table is partitioned on a string column `datepartition` with values of about 12 bytes each then  response for the following query was  in tens of MBs (accessing the query result endpoint directly through curl).
`select datepartition from my_partitioned_table;` 
For larger tables with 100million rows+ the response can be larger than a gigabyte. 

### Analysis
The constant `Query::DESIRED_RESULT_BYTES` is set at 1MB and expected to place an approximate limit on the size of the result when accessing the endpoint `/v1/statement/{queryId}/{token}` with the result size being restricted in this loop in `Query::getNextResult`
```
            long bytes = 0;
            long rows = 0;
            while (bytes < DESIRED_RESULT_BYTES) {
                SerializedPage serializedPage = exchangeClient.pollPage();
                if (serializedPage == null) {
                    break;
                }

                Page page = serde.deserialize(serializedPage);
                bytes += page.getSizeInBytes();
                rows += page.getPositionCount();
                pages.add(new RowIterable(session.toConnectorSession(), types, page));
            }

```
However  `page.getSizeInBytes()` is not  an accurate reflection of the size of  data that will be returned in the response because the pages in this case contain blocks of type `RunLengthEncodedBlock` and a few tens of bytes from `getSizeInBytes()` can represent over a thousand rows of data which consumes a few KBs as part of the json response to the API call. 

I noticed the issue is present for `DictionaryBlock` (and possibly other block types) as well however the ratio of size determined by the `getSizeInBytes` to the actual size in the json response is not as extreme as for `RunLengthEncodedBlocks`

I am looking into fixing the issue, will appreciate any suggestions.

### PR DESCRIPTION
**Pull request by sshardool**
Resolves #11332
Currently the size of the response sent to the client is evaluated using
page.getSize() which is not an accurate estimate of the data size that will
be returned by type.getObjectValue(), specially for blocks of type Dictionary
and RLE.
The commit fixes this by accounting for data size after serialization.

The original approach for fixing this and related discussion is at #11350

### CODE REVIEW

**Comment by sshardool** [comment]
Review request @findepi @dain 
Specially if there are any comments on avoiding the extra serialization introduced by this.

**Comment by sshardool** [comment]
@electrum Thanks for looking into this.
I documented  some of the same concerns along with possible solutions at: https://github.com/prestodb/presto/pull/11350#issuecomment-422224954

However I agree that the original approach of introducing `Block::getUnoptimizedSize` is cleaner, easier and would be useful beyond fixing this one issue.

@findepi @dain @electrum 
Please let me know if I should proceed with the original approach at #11350

**Comment by electrum** [comment]
I discussed this more with @dain and it seems other places would benefit from the new method:

* `HiveWriter`: this reports `inMemoryDataSizeInBytes` for each partition as part of the query completion event. I asked @arhimondr to confirm, but I suspect the intention was for it to be unoptimized size.
* `RcFileWriter` uses it to split pages to the target row group size. Since RCFile doesn't have dictionary, it seems this should be the unoptimized size, as that is a better estimate of the written size.
* `ArrayFlattenFunction` uses it to estimate the size of the output. From what I can tell, the output of the function will be uncompressed, thus the estimate should also use uncompressed.
* Raptor uses it to record the uncompressed (raw) data size to users, allowing comparison of compression ratios, among other things.

It's hard to say if this justifies adding new methods, although they are simple and add little maintenance cost. Certainly, we need to improve the Javadoc, as the existing *"the logical size of this block in memory"* is vague or misleading.

**Comment by electrum** [comment]
@sshardool Thanks for your work on this so far and sorry for all the back and forth.

If we decide not to add the method to `Block` and `Page`, I think we should change this PR to serialize to JSON itself in `Query`. Given the target response size of `1MB`, that should not be a problem. We should be able to change `QueryResults` to have an additional getter annotated with `@JsonRawValue` that returns the JSON as a `byte[]` (and change the corresponding non-`@JsonCreator` constructor to accept a `byte[]` as input rather than `Iterable`).

**Comment by dain** [comment]
@electrum, to be clear for @sshardool, do you want to go with the original proposed code in #11350?

**Comment by dain** [comment]
Superseded by #11628

**Pull request closed without merging**
