### PR TITLE
dashboard: upgrade webpack to v5

### PR DESCRIPTION
**Pull request by yhwang**
## Description
Node v16 is going to sunset on Sep 11, 2023. Although we only use it to compile the jsx, it's still good to switch to Node v18. Therefore, I also updated the
followings to newer versions:
- webpack and webpack-cli
- babel
- react

The extra benefit is:
The size of the new js files is reduced to almost 1/2.

While verifying the change, I also fixed some minor issues in StageDetail.jsx and timeline.html.

## Motivation and Context
When I attempted to compile the dashboard code, I hit some errors and failed to run `yarn install` because I was using
node v18. Apparently, the existing code base is using node v16 which will be sunset on Sep/11. So I go ahead and upgrade
the webpack and related npm packages to new versions which are compatible with node v18

## Impact
No UX change

## Test Plan
Since there is no test cases for UX, I manually verified each pages. 

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [x] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by yhwang** [comment]
hm, I didn't upgrade `flow-bin` package. After I updated it to a newer version locally, it detected 24 errors..., let me fix those errors.

**Comment by yhwang** [comment]
To fix the errors from the static code check tool: `Flow`, I temporally use `any` type for now. I can define more proper data types for the returning JSON when working on other UX related PRs in the future, otherwise, this PR will contains changes for multiple purposes.

**Review by tdcmeehan — APPROVED** [review]
LGTM.  CC: @rschlussel any objections?

**Comment by rschlussel** [comment]
@swapsmagic since you were looking at the coordinator UI recently -- any concerns about this?

**Pull request merged**
