### PR TITLE
[native] Advance velox.

### PR DESCRIPTION
**Pull request by amitkdutta**
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by aditi-pandit — DISMISSED** [review]

**Comment by amitkdutta** [comment]
@aditi-pandit @majetideepak 
This test is always failing with latest velox:
nativeworker.TestPrestoNativeIcebergTpcdsQueriesParquetUsingThrift.testTpcdsQ67


https://app.circleci.com/pipelines/github/prestodb/presto/17805/workflows/0e8600a6-8b18-4f60-8269-33f41f5aab77/jobs/70357/parallel-runs/4/steps/4-105

Shall we disable it?

**Comment by aditi-pandit** [comment]
@amitkdutta : That test is failing with the same error for which you did https://github.com/facebookincubator/velox/pull/10451 yesterday

`com.facebook.presto.verifier.framework.PrestoQueryException: java.sql.SQLException: Query failed (#20240711_160619_00752_kznww): sizeBits_ - 1 < spillInputStartPartitionBit (13 vs. 1) Operator: PartialAggregation[1802] 3`

Does this pull include your revert PR ? If not, we should try with a.newer Velox.

**Comment by majetideepak** [comment]
@amitkdutta CI is failing with `sizeBits_ - 1 < spillInputStartPartitionBit` which seemed to be fixed yesterday here https://github.com/facebookincubator/velox/pull/10451
Can you pull in the bits from yesterday?

**Comment by amitkdutta** [comment]
> @amitkdutta CI is failing with `sizeBits_ - 1 < spillInputStartPartitionBit` which is fixed yesterday here [facebookincubator/velox#10451](https://github.com/facebookincubator/velox/pull/10451) Can you pull in the bits from yesterday?

ah yea, I reverted that yesterday. also did a submodule update. Let me recheck.

**Review by aditi-pandit — APPROVED** [review]
Thanks @amitkdutta

**Pull request merged**
