### PR TITLE
Add hidden $partition column to Hive connector

### PR DESCRIPTION
**Pull request by ggilfb**
Resolves: #8337

### CODE REVIEW

**Comment by ggilfb** [comment]
@electrum Moved the refactoring to separate commit in the latest iteration.

**Comment by raghavsethi** [comment]
@ggilfb Could you rebase, and then I can review.

**Comment by raghavsethi** [comment]
@ggilfb what's the status on this?

**Comment by raghavsethi** [comment]
Closing, since this appears to be abandoned.

**Pull request closed without merging**
