### PR TITLE
Fix aggregation partitioning preferences for local exchanges

### PR DESCRIPTION
**Pull request by raghavsethi**
cc @erichwang.

Tests are going to be in another PR that will be merged shortly.

### CODE REVIEW

**Comment by electrum** [comment]
Put the release notes in the same commit

**Comment by haozhun** [comment]
@raghavsethi Is this caused by a "logical" merge conflict?

**Comment by raghavsethi** [comment]
@haozhun sorry I don't understand what you mean.
@electrum squashed the commits.

**Comment by haozhun** [comment]
Looks good

**Pull request closed without merging**
