### PR TITLE
Fix schema checks in file-based access control

### PR DESCRIPTION
**Pull request by findepi**
Update checks added in https://github.com/prestodb/presto/pull/11328

### CODE REVIEW

**Comment by rschlussel** [comment]
that means nobody will be able to create or drop a schema because it's not settable.  is that the desired behavior?

**Comment by findepi** [comment]
What would you propose instead?

**Comment by findepi** [comment]
@rschlussel @electrum do you want any changes here?

**Comment by dain** [comment]
Why not add more rules to control schema checks?

**Comment by findepi** [comment]
@dain That is a good idea. Might be a next step. My intention is to close the security gap we accidentally opened in 0.209.

**Pull request merged**
