### PR TITLE
Fix typo in TaskExecutor

### PR DESCRIPTION
**Pull request by hantangwangd**
## Description

Fix typo in TaskExecutor.

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by tdcmeehan — APPROVED** [review]

**Comment by skairali** [comment]
1 failing check. I have triggered a re run @tdcmeehan

**Review by skairali — APPROVED** [review]
This is just a comment update and a typo fix.  Good to merge

**Comment by skairali** [comment]
All checks passed and its typo fix.

**Comment by hantangwangd** [comment]
> All checks passed and its typo fix.

@skairali Thanks a lot.

**Pull request merged**
