### PR TITLE
Parse parenthesized query in CREATE TABLE AS

### LINKED ISSUE #7745: "CREATE TABLE ... AS ..." doesn't parse proper query expressions
```sql
CREATE TABLE u AS (
   WITH t(x) AS (VALUES 1) 
   SELECT x FROM t);
```

fails with a parsing error:

```
Query 20170405_035149_08220_kmjsc failed: line 1:31: mismatched input 'WITH' expecting {'(', 'SELECT', 'VALUES', 'TABLE'}
com.facebook.presto.sql.parser.ParsingException: line 1:31: mismatched input 'WITH' expecting {'(', 'SELECT', 'VALUES', 'TABLE'}
	at com.facebook.presto.sql.parser.SqlParser$1.syntaxError(SqlParser.java:45)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:540)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:301)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:124)
	at com.facebook.presto.sql.parser.SqlBaseParser.queryPrimary(SqlBaseParser.java:3450)
	at com.facebook.presto.sql.parser.SqlBaseParser.queryTerm(SqlBaseParser.java:3196)
	at com.facebook.presto.sql.parser.SqlBaseParser.queryNoWith(SqlBaseParser.java:3047)
	at com.facebook.presto.sql.parser.SqlBaseParser.queryPrimary(SqlBaseParser.java:3439)
	at com.facebook.presto.sql.parser.SqlBaseParser.queryTerm(SqlBaseParser.java:3196)
	at com.facebook.presto.sql.parser.SqlBaseParser.queryNoWith(SqlBaseParser.java:3047)
	at com.facebook.presto.sql.parser.SqlBaseParser.query(SqlBaseParser.java:2492)
	at com.facebook.presto.sql.parser.SqlBaseParser.statement(SqlBaseParser.java:1461)
	at com.facebook.presto.sql.parser.SqlBaseParser.singleStatement(SqlBaseParser.java:233)
	at com.facebook.presto.sql.parser.SqlParser.invokeParser(SqlParser.java:92)
	at com.facebook.presto.sql.parser.SqlParser.createStatement(SqlParser.java:65)
	at com.facebook.presto.execution.SqlQueryManager.createQuery(SqlQueryManager.java:338)
	at com.facebook.presto.server.StatementResource$Query.<init>(StatementResource.java:329)
	at com.facebook.presto.server.StatementResource.createQuery(StatementResource.java:173)
```

Per the spec, the `<table contents source>` should be a parenthesized query expression, which can start with a `WITH` clause. Presto currently parses it as a `<query>`, which can resolve to a `<query primary>` that doesn't allow such clause.

```
<table definition> ::=
  CREATE [ <table scope> ] TABLE <table name> <table contents source>
      [ WITH <system versioning clause> ]
      [ ON COMMIT <table commit action> ROWS ]

<table contents source> ::=
    <table element list>
  | <typed table clause>
  | <as subquery clause>

<as subquery clause> ::=
  [ <left paren> <column name list> <right paren> ] AS <table subquery>
      <with or without data>

<table subquery> ::=  <subquery>
<subquery> ::=  <left paren> <query expression> <right paren>

<query expression> ::=
  [ <with clause> ] <query expression body>
      [ <order by clause> ] [ <result offset clause> ] [ <fetch first clause> ]
```

### PR DESCRIPTION
**Pull request by ebyhr**
Fixed #7745

### CODE REVIEW

**Comment by electrum** [comment]
Thanks! We actually don't need test queries for this, since it's purely a parser issue. Can you instead add these as parser tests?

**Comment by ebyhr** [comment]
All right. Could you cancel my Travis CI build?

**Comment by findepi** [comment]
@ebyhr, Will (unparenthised)

```
CREATE TABLE u AS 
   WITH t(x) AS (VALUES 1) 
   SELECT x FROM t;
```

continue to work? (I think _yes_, but please make sure this is tested too)

**Comment by ebyhr** [comment]
@findepi Yes, the query continues to work. I'll make sure the test exists.

**Comment by ebyhr** [comment]
@electrum 
Should I add tests to [TestSqlParser.java](https://github.com/prestodb/presto/blob/master/presto-parser/src/test/java/com/facebook/presto/sql/parser/TestSqlParser.java)?
I've written tests in [TestStatementBuilder.java](https://github.com/prestodb/presto/blob/master/presto-parser/src/test/java/com/facebook/presto/sql/parser/TestStatementBuilder.java) at least.

**Comment by martint** [comment]
Yeah, they should go in testSqlParser. testStatementBuilder is just a sanity check to make sure parsing and printing roundtrips, but it doesn't verify anything.

**Comment by ebyhr** [comment]
I changed a part of test query, from `SELECT x FROM t` to `TABLE t` since it's simpler than former and it does't affect the result in this problem.

**Pull request merged**
