### PR TITLE
Preserve AST order when formatting properties

### PR DESCRIPTION
**Pull request by caithagoras**

### CODE REVIEW

**Comment by caithagoras** [comment]
I found that changing the property map to ImmutableSortedMap in RaptorMetadata and HiveMetadata is not helpful since they're used to re-create new property map later on. The place that construct the finalized my is in ShowQueriesRewrite.visitShowCreate()

**Comment by electrum** [comment]
This moves the sorting logic to `ShowQueriesRewrite`, not connectors. (it will still be sorted even if the connector returns them in a different order)

**Comment by caithagoras** [comment]
Commit message updated.

**Comment by electrum** [comment]
Let's make the commit message "Preserve AST order when formatting properties"

**Comment by electrum** [comment]
We should also rename `appendTableProperties` to `appendProperties` in `SqlFormatter` (as a separate commit or PR)

**Comment by electrum** [comment]
The current commit message says what the code does, but doesn't help the reader understand why (the motivation for the change). It's also a bit misleading, since the properties were already sorted when formatting.

**Comment by caithagoras** [comment]
Thanks. Acknowledged.

**Pull request merged**
