### PR TITLE
Update MSSQL Server JDBC driver to 12.6.0.jre8

### PR DESCRIPTION
**Pull request by Akanksha-kedia**
## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [x] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by Akanksha-kedia** [comment]
@tdcmeehan @skairali please review and merge.

**Comment by Akanksha-kedia** [comment]
Screenshot 2023-10-20 at 12 24 18 PM
 we are still 
Screenshot 2023-10-20 at 12 24 29 PM
using still old version when new versions are compatible and non-vunerable.

**Comment by tdcmeehan** [comment]
@Akanksha-kedia have you tested the SQL server driver with the updated dependency?

**Comment by steveburnett** [comment]
Based on the [Release Note Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines), please add a properly formatted release note entry describing this change, similar to our discussion in [PR 21668](https://github.com/prestodb/presto/pull/21668).

**Comment by agrawalreetika** [comment]
Hi @Akanksha-kedia 
Thank you for the PR. I don't see UT added for sql-server connector currently, I will add an issue regarding the same. So I have the same question as Tim, did you test sql-server connector after updating the dependency and could you please share the results?

**Comment by agrawalreetika** [comment]
I have added issue for adding UTs here - https://github.com/prestodb/presto/issues/21890
Also found out that product tests for sql-server were disabled as part of https://github.com/microsoft/mssql-docker/issues/76
and as per the comment here, the Issue no longer exists if we make use of microsoft/mssql-server-linux:2017-CU13 docker image instead.
It would be good if you want to enable Product tests for it and test out your changes as well.

**Comment by elharo** [comment]
stale, closing due to conflicts

**Pull request closed without merging**
