### PR TITLE
[native] Specify per-query memory limit

### PR DESCRIPTION
**Pull request by mbasmanova**
By default, per-query memory limit is 1/10th of the node memory limit. Since Presto-on-Spark runs only 1 query at a time, the default memory limit is inefficient. This change sets per-query memory limit to the same value as node memory limit.

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by xiaoxmeng — APPROVED** [review]
@mbasmanova LGTM. Thanks!

**Review by ajaygeorge — APPROVED** [review]
LGTM.
Do we have the test for native config similar to what we have in [java](https://github.com/prestodb/presto/blob/5eb6cc7ee1dcd7591959ef04a4cd4239b678f36f/presto-main/src/test/java/com/facebook/presto/server/TestInternalCommunicationConfig.java#L29).

**Comment by mbasmanova** [comment]
> Do we have the test for native config similar to what we have in [java](https://github.com/prestodb/presto/blob/5eb6cc7ee1dcd7591959ef04a4cd4239b678f36f/presto-main/src/test/java/com/facebook/presto/server/TestInternalCommunicationConfig.java#L29).

I'm not sure. @miaoever MJ, do you know?

**Comment by miaoever** [comment]
> > Do we have the test for native config similar to what we have in [java](https://github.com/prestodb/presto/blob/5eb6cc7ee1dcd7591959ef04a4cd4239b678f36f/presto-main/src/test/java/com/facebook/presto/server/TestInternalCommunicationConfig.java#L29).
> 
> I'm not sure. @miaoever MJ, do you know?

Yes we have:
https://github.com/prestodb/presto/blob/c50c95cca6c850a1dab70e3d99ef990620aeb6c0/presto-spark-base/src/test/java/com/facebook/presto/spark/execution/property/TestNativeExecutionSystemConfig.java#L4

**Review by miaoever — APPROVED** [review]

**Comment by ajaygeorge** [comment]
> > > Do we have the test for native config similar to what we have in [java](https://github.com/prestodb/presto/blob/5eb6cc7ee1dcd7591959ef04a4cd4239b678f36f/presto-main/src/test/java/com/facebook/presto/server/TestInternalCommunicationConfig.java#L29).
> > 
> > 
> > I'm not sure. @miaoever MJ, do you know?
> 
> Yes we have: https://github.com/prestodb/presto/blob/master/presto-spark-base/src/test/java/com/facebook/presto/spark/execution/property/TestNativeExecutionSystemConfig.java

@mbasmanova Can we update the test as well then.

**Comment by mbasmanova** [comment]
@ajaygeorge Yup. Updated.

**Pull request merged**
