### PR TITLE
Fix iam role session name for s3 access

### PR DESCRIPTION
**Pull request by ashishtadose**
Test plan - (Please fill in how you tested your changes)

Please make sure your submission complies with our [Development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [Formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), and [Commit Message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests) guidelines. Don't forget to follow our [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution) for any code copied from other projects.

Fill in the release notes towards the bottom of the PR description.
See [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) for details.

```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by ashishtadose** [comment]
Fixes #15621

**Comment by ashishtadose** [comment]
This fixes a bug introduced in S3 am role feature that restricts access to S3 using the IAM role due to restrictions on the session name.
I raise a separate PR for updating docs for S3 configs.

**Review by zhenxiao — APPROVED** [review]
LGTM, thank you, @ashishtadose 
could you please rerun the test, make sure all testcase pass?

**Comment by ashishtadose** [comment]
> LGTM, thank you, @ashishtadose
> could you please rerun the test, make sure all testcase pass?

thank you for the review @zhenxiao 
Test failures are not related to this fix and also I tried re-running the build & specific job from travis-ci but it's not triggering due to some error.  Please let me know if there's any laternative

**Pull request merged**
