### PR TITLE
Decimal v7

### PR DESCRIPTION
**Pull request by arhimondr**
Superseeds: #4750

### CODE REVIEW

**Comment by kokosing** [comment]
@arhimondr Can you please run travis build once more time. There were a bug in presto which caused product tests to fail. Now it is fixed, so travis should pass for your pull request.

**Comment by arhimondr** [comment]
@kokosing Thanks. Done.

**Comment by ilfrin** [comment]
@martint @dain any more comments on this one? It looks like things have finally converged here. Can we land this?

**Comment by ilfrin** [comment]
seeking permission to land ...

**Comment by martint** [comment]
I'm going to run this on our internal verification cluster. There are some merge conflicts (sorry :( ). Can you rebase on master?

**Comment by ilfrin** [comment]
Great, thanks. Ok we'll rebase this tomorrow.

czw., 31.03.2016, 20:20 użytkownik Martin Traverso <notifications@github.com>
napisał:

**Comment by martint** [comment]
Actually, hold on. I think they are easy to resolve. Let me give it a try and I'll let you know if it turns out to be more complicated than I thought.

**Comment by martint** [comment]
I was able to rebase it. I'm testing it now.

**Comment by ilfrin** [comment]
cool, thanks! holding my breath ;)

czw., 31.03.2016 o 23:30 użytkownik Martin Traverso <
notifications@github.com> napisał:

**Comment by martint** [comment]
AbstractTestHiveClient tests for CDH4 (and, possibly, others) are failing. The problem is that AbstractTestHiveClient.setupHive initializes the expected partitions to contain decimals, but that's not supported for all hive distributions.

Admittedly, this is a problem with how those tests are structured and composed, but fixing the structural problems would be a bigger undertaking.

My suggestion would be to remove those tests for now until we can figure out a better way to model this.

**Comment by martint** [comment]
The tests in from our internal verification suite passed, so once the failing tests in AbstractTestHiveClient are fixed we can merge it.

**Comment by martint** [comment]
BTW, here's a branch with the commits rebased on top of latest master and all merge conflicts resolved: https://github.com/martint/presto/tree/pr4810

**Comment by ilfrin** [comment]
Great, thank you. Will do.
By fixing the tests do you mean removing them for now as you suggested in
your previous comment?

pt., 1.04.2016, 08:06 użytkownik Martin Traverso <notifications@github.com>
napisał:

**Comment by martint** [comment]
> By fixing the tests do you mean removing them for now as you suggested in
> your previous comment?

Yes.

**Comment by ilfrin** [comment]
Ok. Will handle this today.

pt., 1.04.2016, 08:28 użytkownik Martin Traverso <notifications@github.com>
napisał:

**Comment by losipiuk** [comment]
@martint I removed the tests for presto-hive-cdh4 and presto-hive-hadoop1.
This is based on guess that both would fail - being older hadoop distributions.
It is hard for me to test if removing both is necessary as we do not have test environment running those distros.

**Comment by losipiuk** [comment]
rebased PR here https://github.com/prestodb/presto/pull/4920.
Closing this one.

**Pull request closed without merging**
