### PR TITLE
[native] Deprecate the arbitration timeout name

### PR DESCRIPTION
**Pull request by tanjialiang**
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by xiaoxmeng — APPROVED** [review]
@tanjialiang thanks!

**Review by aditi-pandit — APPROVED** [review]
Thanks.

**Review by steveburnett — APPROVED** [review]
LGTM! (docs)

Pull branch, local doc build, looks good. Thanks!

**Comment by majetideepak** [comment]
I am guessing that Prestissimo will throw a warning if the old config name is used.

**Review by feilong-liu — APPROVED** [review]

**Comment by tanjialiang** [comment]
> I am guessing that Prestissimo will throw a warning if the old config name is used.

Hi @majetideepak , actually Prestissimo will not throw a warning when non-existing config is used. This is something we have been discussing of adding.

**Pull request merged**
