### PR TITLE
Feature fast decimal v2

### PR DESCRIPTION
**Pull request by sopel39**

### CODE REVIEW

**Comment by sopel39** [comment]
Various benchmark results:

cast decimal to double:
```
Before:

Benchmark                                                          (expression)   Mode  Cnt  Score   Error   Units
BenchmarkDecimalOperators.decimalToDoubleCastBenchmark  cast(l_38_30 as double)  thrpt   30  0,044 ± 0,002  ops/ms
BenchmarkDecimalOperators.decimalToDoubleCastBenchmark   cast(l_38_2 as double)  thrpt   30  0,433 ± 0,018  ops/ms
BenchmarkDecimalOperators.decimalToDoubleCastBenchmark   cast(s_17_9 as double)  thrpt   30  2,027 ± 0,086  ops/ms

After:

Benchmark                                                          (expression)   Mode  Cnt  Score   Error   Units
BenchmarkDecimalOperators.decimalToDoubleCastBenchmark  cast(l_38_30 as double)  thrpt   30  0,050 ± 0,002  ops/ms
BenchmarkDecimalOperators.decimalToDoubleCastBenchmark   cast(l_38_2 as double)  thrpt   30  1,127 ± 0,039  ops/ms
BenchmarkDecimalOperators.decimalToDoubleCastBenchmark   cast(s_17_9 as double)  thrpt   30  1,962 ± 0,077  ops/ms
```

**Comment by sopel39** [comment]
Aggregations:
Benchmark results with old code (@wbiela pull request with avg/sum aggregations):

```
Benchmark                                                                                                             (project)          (type)  Mode  Cnt     Score    Error  Units
BenchmarkDecimalAggregation.benchmarkBuildHash                                                     orderstatus, avg(totalprice)   decimal(14,2)  avgt   30   274.957 ±  6.592  ms/op
BenchmarkDecimalAggregation.benchmarkBuildHash                                                     orderstatus, avg(totalprice)  decimal(30,10)  avgt   30   439.031 ±  7.239  ms/op
BenchmarkDecimalAggregation.benchmarkBuildHash                                                     orderstatus, min(totalprice)   decimal(14,2)  avgt   30   206.957 ±  5.151  ms/op
BenchmarkDecimalAggregation.benchmarkBuildHash                                                     orderstatus, min(totalprice)  decimal(30,10)  avgt   30   535.220 ± 28.227  ms/op
BenchmarkDecimalAggregation.benchmarkBuildHash  orderstatus, sum(totalprice), avg(totalprice), min(totalprice), max(totalprice)   decimal(14,2)  avgt   30   412.677 ±  9.621  ms/op
BenchmarkDecimalAggregation.benchmarkBuildHash  orderstatus, sum(totalprice), avg(totalprice), min(totalprice), max(totalprice)  decimal(30,10)  avgt   30  1165.726 ± 82.984  ms/op
```
After changes:

```
Benchmark                                                                                                             (project)  (type)  Mode  Cnt    Score    Error  Units
BenchmarkDecimalAggregation.benchmarkBuildHash                                                     orderstatus, avg(totalprice)          double  avgt   10  166.982 ±  1.467  ms/op
BenchmarkDecimalAggregation.benchmarkBuildHash                                                     orderstatus, min(totalprice)          double  avgt   10  149.677 ±  9.512  ms/op
BenchmarkDecimalAggregation.benchmarkBuildHash  orderstatus, sum(totalprice), avg(totalprice), min(totalprice), max(totalprice)          double  avgt   10  174.185 ± 5.591  ms/op
BenchmarkDecimalAggregation.benchmarkBuildHash                                                     orderstatus, avg(totalprice)   decimal(14,2)  avgt   10  172.849 ± 12.891  ms/op
BenchmarkDecimalAggregation.benchmarkBuildHash                                                     orderstatus, avg(totalprice)  decimal(30,10)  avgt   10  231.429 ±  3.415  ms/op
BenchmarkDecimalAggregation.benchmarkBuildHash                                                     orderstatus, min(totalprice)   decimal(14,2)  avgt   10  151.328 ±  7.758  ms/op
BenchmarkDecimalAggregation.benchmarkBuildHash                                                     orderstatus, min(totalprice)  decimal(30,10)  avgt   10  222.131 ±  7.071  ms/op
BenchmarkDecimalAggregation.benchmarkBuildHash  orderstatus, sum(totalprice), avg(totalprice), min(totalprice), max(totalprice)   decimal(14,2)  avgt   10  251.888 ± 19.230  ms/op
BenchmarkDecimalAggregation.benchmarkBuildHash  orderstatus, sum(totalprice), avg(totalprice), min(totalprice), max(totalprice)  decimal(30,10)  avgt   10  341.743 ±  4.464  ms/op
```

**Comment by sopel39** [comment]
cast decimal to int:
```
After:

Benchmark                                                         (expression)   Mode  Cnt  Score   Error   Units
BenchmarkDecimalOperators.decimalCastBenchmark  cast(l_38_30 as decimal(8, 0))  thrpt   40  0,179 ± 0,004  ops/ms
BenchmarkDecimalOperators.decimalCastBenchmark  cast(l_26_18 as decimal(8, 0))  thrpt   40  0,273 ± 0,005  ops/ms
BenchmarkDecimalOperators.decimalCastBenchmark  cast(l_20_12 as decimal(8, 0))  thrpt   40  0,679 ± 0,017  ops/ms
BenchmarkDecimalOperators.decimalCastBenchmark   cast(l_20_8 as decimal(8, 0))  thrpt   40  0,663 ± 0,027  ops/ms

Before:

# Run complete. Total time: 00:05:44

Benchmark                                                         (expression)   Mode  Cnt  Score   Error   Units
BenchmarkDecimalOperators.decimalCastBenchmark  cast(l_38_30 as decimal(8, 0))  thrpt   40  0,113 ± 0,003  ops/ms
BenchmarkDecimalOperators.decimalCastBenchmark  cast(l_26_18 as decimal(8, 0))  thrpt   40  0,109 ± 0,013  ops/ms
BenchmarkDecimalOperators.decimalCastBenchmark  cast(l_20_12 as decimal(8, 0))  thrpt   40  0,287 ± 0,010  ops/ms
BenchmarkDecimalOperators.decimalCastBenchmark   cast(l_20_8 as decimal(8, 0))  thrpt   40  0,313 ± 0,011  ops/ms
```

**Comment by sopel39** [comment]
Initial work into long decimals fast performance. FYI: @martint @cberner. It also includes patch from @fmeiser (thx!). Benchmarks before improvements:

```
# Run complete. Total time: 00:03:48

Benchmark                                                                                           (expression)   Mode  Cnt   Score   Error   Units
BenchmarkDecimalInequalityOperators.execute                                                              d1 < d2  thrpt   30  10,795 ± 0,579  ops/ms
BenchmarkDecimalInequalityOperators.execute  d1 < d2 AND d1 < d3 AND d1 < d4 AND d2 < d3 AND d2 < d4 AND d3 < d4  thrpt   30   4,046 ± 0,184  ops/ms
BenchmarkDecimalInequalityOperators.execute                                                              s1 < s2  thrpt   30   6,776 ± 0,429  ops/ms
BenchmarkDecimalInequalityOperators.execute  s1 < s2 AND s1 < s3 AND s1 < s4 AND s2 < s3 AND s2 < s4 AND s3 < s4  thrpt   30   1,670 ± 0,081  ops/ms
BenchmarkDecimalInequalityOperators.execute                                                              l1 < l2  thrpt   30   0,590 ± 0,033  ops/ms
BenchmarkDecimalInequalityOperators.execute  l1 < l2 AND l1 < l3 AND l1 < l4 AND l2 < l3 AND l2 < l4 AND l3 < l4  thrpt   30   0,092 ± 0,003  ops/ms
```

after:


```
# Run complete. Total time: 00:03:48

Benchmark                                                                                           (expression)   Mode  Cnt   Score   Error   Units
BenchmarkDecimalInequalityOperators.execute                                                              d1 < d2  thrpt   30  10,874 ± 0,469  ops/ms
BenchmarkDecimalInequalityOperators.execute  d1 < d2 AND d1 < d3 AND d1 < d4 AND d2 < d3 AND d2 < d4 AND d3 < d4  thrpt   30   4,351 ± 0,210  ops/ms
BenchmarkDecimalInequalityOperators.execute                                                              s1 < s2  thrpt   30  11,392 ± 0,431  ops/ms
BenchmarkDecimalInequalityOperators.execute  s1 < s2 AND s1 < s3 AND s1 < s4 AND s2 < s3 AND s2 < s4 AND s3 < s4  thrpt   30   4,462 ± 0,191  ops/ms
BenchmarkDecimalInequalityOperators.execute                                                              l1 < l2  thrpt   30   4,392 ± 0,343  ops/ms
BenchmarkDecimalInequalityOperators.execute  l1 < l2 AND l1 < l3 AND l1 < l4 AND l2 < l3 AND l2 < l4 AND l3 < l4  thrpt   30   0,821 ± 0,041  ops/ms
```

**Comment by sopel39** [comment]
Please ignore two first commits, they are part of https://github.com/prestodb/presto/pull/5378

**Comment by losipiuk** [comment]
Closing this one. 
Let's merge https://github.com/prestodb/presto/pull/5378 firts

**Pull request closed without merging**
