### PR TITLE
Increasing visibility of jdbc.QueryBuilder to allow subclasses to support custom predicate pushdown

### PR DESCRIPTION
**Pull request by AshwinJay**
I would like to reuse the `QueryBuilder` in my JDBC based connector. The current QueryBuilder only supports bigint, double and boolean. I would like to extend this class in my connector to support other types (example varchar).

I've refactored the QueryBuilder to allow sub-classing along with a unit test.

Thanks.

### CODE REVIEW

**Comment by yuananf** [comment]
Good feature!

**Comment by toyama0919** [comment]
@electrum ping

**Comment by toyama0919** [comment]
@electrum @yuananf Can you please take a look?

**Comment by youngwookim** [comment]
@AshwinJay @toyama0919 Nice work! Any progress on this? To support the various DBMS, users should be able to override the QueryBuilder.

**Comment by toyama0919** [comment]
>Nice work! Any progress on this? To support the various DBMS, users should be able to override the QueryBuilder.

Thanks!
waiting for reply..

**Comment by AshwinJay** [comment]
No idea. Been waiting for a response from the Presto team for months.

**Comment by electrum** [comment]
Thanks for contributing this and sorry for the incredibly long delay. We recently rewrote `QueryBuilder` to use JDBC `PreparedStatement` which alleviates security concerns from SQL injection. Support for pushdown of all types is being done in #4842.

**Comment by idoshichor** [comment]
Hi All,
In which Presto release was this issue fixed?

**Pull request closed without merging**
