### PR TITLE
Revert D48578640: [presto][diff_train] [native] Change json location for reuse with other third parties

### PR DESCRIPTION
**Pull request by bigfootjon**
Summary: Revert D48578640: [presto][diff_train] [native] Change json location for reuse…

Differential Revision: D48651132

### CODE REVIEW

**Review by amitkdutta — APPROVED** [review]

**Comment by majetideepak** [comment]
@amitkdutta, @bigfootjon why was this PR https://github.com/prestodb/presto/pull/20619 reverted?
This PR did not follow any of the PR guidelines as well. The title is incorrect. There is no description.
CC: @tdcmeehan

**Comment by amitkdutta** [comment]
@majetideepak This was reverted from a Meta internal system and it was already merged internally. So to keep the code sync work, we needed to merge it here. We are looking whats the issue and how to land this one. Apologies for the trouble.

**Comment by amitkdutta** [comment]
@majetideepak I have fixed the internal issue and merged https://github.com/prestodb/presto/pull/20749 cc: @czentgr

**Comment by majetideepak** [comment]
thanks, @amitkdutta!

**Pull request merged**
