### PR TITLE
Solve critical vulnerability of Presto UI from `@babel/traverse` npm package

### PR DESCRIPTION
**Pull request by yhwang**
Ref: #21319

## Description
Update @babel and related packages to newer versions to solve the critical vulnerability issue reported by `yarn audit`: https://github.com/advisories/GHSA-67hx-6x53-jw92

## Motivation and Context
The critical vulnerability issue reported by `yarn audit` may impact servers that run the babel to compile the Presto UI code or developers' machines. Although there is no `path.evaluate()` or `path.evaluateTruthy()` in the current code base, it's good to fix it.

## Impact
Most of the JS files are not changed, except `query.js`.

## Test Plan
Manually run the Presto UI and verify the query page.

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* Update Babel and related npm packages to solve critical vulnerability: https://github.com/advisories/GHSA-67hx-6x53-jw92
  The Babel packages are used to generate the JavaScript files for Presto UI. The update prevents the build servers
  or developers' machines from running arbitrary code while building the JavaScript files.
```

### CODE REVIEW

**Comment by yhwang** [comment]
Below, it's a screenshot of the query page, I don't see any issue of this page.
query-1

**Comment by yhwang** [comment]
Here is another screenshot which has a successful query:
query-2

**Review by tdcmeehan — APPROVED** [review]

**Review by skairali — APPROVED** [review]
This is a good change and required one from security perspective.

**Comment by steveburnett** [comment]
If this is a "critical vulnerability" as described in the title, consider adding a release note to this PR for the Security section of the next release notes.

**Comment by yhwang** [comment]
@steveburnett thanks for the feedback. update the description of this PR to include the release node.

**Pull request merged**
