### PR TITLE
Prefer String.toLowerCase(ENGLISH) over String.toLowerCase()

### PR DESCRIPTION
**Pull request by kokosing**
Prefer String.toLowerCase(ENGLISH) over String.toLowerCase()

### CODE REVIEW

**Comment by dain** [comment]
I believe @electrum had a preference for `toLowerCase(US)`

**Comment by electrum** [comment]
I need to research this but it sounds like ROOT makes sense. Does anyone have a good comparison between ROOT vs ENGLISH vs US? I couldn’t find one.

(I’ve always used ENGLISH not US, and I think that’s what we use everywhere)

**Comment by kokosing** [comment]
I updated this and added modernizer check.

**Comment by kokosing** [comment]
I would prefer to merge this as it is, then we could migrate to `Locale.ROOT` if needed.

**Pull request merged**
