### PR TITLE
[native] Clean temp hive tpch folder for E2E test runs

### PR DESCRIPTION
**Pull request by beroyfb**
Fix the following E2E test: 
TestHiveQueriesUsingJSON.testCreateTableAsSelect and TestHiveQueriesUsingThrift.testCreateTableAsSelect

Test plan - All checks

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by spershin — APPROVED** [review]

**Review by mbasmanova — COMMENTED** [review]
> Fix the following benchmarks:

Did you mean tests?

Please, add [native] to commit and PR titles and update commit message to provide more details.

**Review by mbasmanova — COMMENTED** [review]
@beroyfb Please, take a moment to review best practices for writing commit messages: https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/ and https://cbea.ms/git-commit/

It would be nice to update PR and commit titles to start with an active verb: Cleaning -> Clean up or Delete

**Comment by spershin** [comment]
> @beroyfb Please, take a moment to review best practices for writing commit messages: https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/ and https://cbea.ms/git-commit/
> 
> It would be nice to update PR and commit titles to start with an active verb: Cleaning -> Clean up or Delete

@mbasmanova I have updated these. Please, see if that is along the best practices.

**Comment by mbasmanova** [comment]
@spershin Thanks, but commit message is still the same.

The PR title is great % the first word: Cleaning -> Clean

This can be used for the commit title.

**Comment by spershin** [comment]
> @spershin Thanks, but commit message is still the same.
> 
> The PR title is great % the first word: Cleaning -> Clean
> 
> This can be used for the commit title.


Does it need to be resubmitted for the commit message to change? I remember there was some dullness in GH about that...

**Comment by mbasmanova** [comment]
@spershin Yes, commit message needs to be edited using git commit --amend (or similar). Then, PR needs to be updated.

**Review by ajaygeorge — APPROVED** [review]
LGTM

**Comment by arunthirupathi** [comment]
Are these directories not cleaned up in the original tests correctly ? If we launch dedicated containers we are fine, otherwise purging directories while other tests are running might cause random issues.

**Review by arunthirupathi — APPROVED** [review]
Approving to unblock.

**Comment by beroyfb** [comment]
Updated the commit message as well

**Comment by mbasmanova** [comment]
> Err, this change wasn't valid

@jsoref Josh, would you clarify?

**Comment by mbasmanova** [comment]
@jsoref Josh, are you saying the "rm" command needs to be part of "run: "? I wonder why there was not error.

@beroyfb Behnam, would you fix that?

**Comment by mbasmanova** [comment]
@jsoref Josh, do you know why this error didn't show up on the PR itself?

```
[Invalid workflow file: .github/workflows/test-native.yml#L95](https://github.com/prestodb/presto/actions/runs/3098126436/workflow)
You have an error in your yaml syntax on line 95
```

**Comment by jsoref** [comment]
It was reported here:
https://github.com/beroyfb/presto/actions
(And ideally the PR author should have noticed the failure before making the PR)

The `pull_request` tested the workflow in the destination branch, not the merged branch, and the target branch didn't have any errors, and thus had nothing to say.

**Comment by jsoref** [comment]
Generally speaking, you should assume that workflow changes won't themselves be tested in a PR.

When I want to test a workflow that's coming via a PR, I use a fork, pull the commit in and exercise the workflow.

**Comment by jsoref** [comment]
I haven't forgotten this, but I'm unlikely to get to it anytime soon either. (Apparently there are lots of variables in play, although I claim that my advice is probably still good -- i.e. it's better to assume that people aren't testing changes to workflows and to test them in a fork than to assume that they are being tested and be surprised when it turns out they aren't.)

**Comment by mbasmanova** [comment]
@jsoref Josh, appreciate your advice. If you do get some time, it would be great if you could help update the contributing guide.

**Pull request merged**
