### PR TITLE
Adding support for MAP_TOP_N_KEYS function to Presto

### PR DESCRIPTION
**Pull request by jainavi17**
Add an UDF for getting top N keys of a map, which returns an array of the top N keys of map. Optionally a lambda comparator can also be passed to perform a custom comparison of the values. Returns all the value if the value N is greater than or equal to size of the map. For N < 0, the function returns values in the reverse order. For N = 0, the function returns empty array.

map_top_n_keys(map(K, V), N) -> array(K)

For N > 0, returns the top N keys of a map. If N happens to larger than size of the map, it returns all the keys of the map in descending order
For N = 0, return empty array
For N < 0, returns the bottom N keys of a map.
map_top_n_keys(map(K, V), N, function(K, K, int)) -> array(K)
Return the top N keys of the map sorted using the lambda comparator.

Test plan - (Please fill in how you tested your changes)
Added unit tests.
Build successfully using the following terminal command
- `./mvnw clean install -Dtest=TestMapTopNKeysFunction -fn -pl presto-main`
- `./mvnw clean install -Dtest=TestMapTopNKeysComparatorFunction -fn -pl presto-main`

Fill in the release notes towards the bottom of the PR description.
See [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) for details.

```
== RELEASE NOTES ==

General Changes
* Add support for MAP_TOP_N_KEYS
* Returns an array of the top N keys of map. Optionally a lambda comparator can also be passed to perform a custom comparison of the keys. Returns all the keys if the value N is greater than or equal to size of the map. For N < 0, the function returns keys in the reverse order. For N = 0, the function returns empty array.

.. function:: map_top_n_keys(map(K, V), N) -> array(K)
   Returns the top N keys of ``map``. If N < 0, the function returns bottom N keys of ``map``. For N = 0, it returns empty ``array``.

.. function:: map_top_n_keys(map(K, V), N, function(K, K, int)) -> array(K)
   Returns the top N keys of ``map`` sorted using lambda comparator. If N < 0, the function returns bottom N keys of ``map`` sorted using lambda comparator. For N = 0, it returns empty ``array``.

`SELECT MAP_TOP_N_KEYS(MAP(ARRAY[4, 5, 6], ARRAY[1, 2, 3]), 2)); -- 6, 5`
`SELECT MAP_TOP_N_KEYS(MAP(ARRAY['a', 'b', 'c', 'd'], ARRAY[1, 2, 3, NULL, NULL]), -3)); -- 'a', 'b', 'c'`
`SELECT MAP_TOP_N_KEYS(MAP(ARRAY[4, 5, 6], ARRAY[1, 2, 3]), 4, (x, y) -> IF(x < y, 1, IF(x = y, 0, -1))); -- 4, 5, 6`
```

### CODE REVIEW

**Comment by kaikalur** [comment]
Look at the recent PR: #18581 that allows type parameters to sql functions. I think this function can be written more elegantly in as a SQL builtin (like ARRAY_SUM etc):

SLICE(REVERSE(ARRAYS_SORT(x)), 1, n) 

Given that we are going to have Velox soon, I think it makes sense to do some of these in SQL so they get ported automatically without having to reimplement.

**Comment by mbasmanova** [comment]
@jainavi17 Something is wrong with this PR. 50 commits. 8K lines of code. Conflicts. Would you rebase and update?

**Comment by kaikalur** [comment]
> CC: @amitkdutta A new function is being added to Presto.
> 
> CC: @spershin @xiaoxmeng

@mbasmanova I'm trying to convince contributors to use SQL udfs now wherever possible so they will be supported in velox for free so we can avoid the longtail situation.

**Comment by mbasmanova** [comment]
> > CC: @amitkdutta A new function is being added to Presto.
> > CC: @spershin @xiaoxmeng
> 
> @mbasmanova I'm trying to convince contributors to use SQL udfs now wherever possible so they will be supported in velox for free so we can avoid the longtail situation.

@kaikalur Sreeni, thank you for clarifying. How performance SQL udfs are? My impression these are pretty slow, no? But I agree, it is better to introduce new udfs as SQL udfs and allow these to run as is on Velox, while still allowing to provide an efficient native implementation in Velox.

**Comment by kaikalur** [comment]
> > > CC: @amitkdutta A new function is being added to Presto.
> > > CC: @spershin @xiaoxmeng
> > 
> > 
> > @mbasmanova I'm trying to convince contributors to use SQL udfs now wherever possible so they will be supported in velox for free so we can avoid the longtail situation.
> 
> @kaikalur Sreeni, thank you for clarifying. How performant SQL udfs are? My impression these are pretty slow, no? But I agree, it is better to introduce new udfs as SQL udfs and allow these to run as is on Velox, while still allowing to provide an efficient native implementation in Velox.

So the idea is these are long tail udfs that are newly added so we can port them as needed to Velox if there is huge demand. And no SQL udf should not be that slow especially when we enable inline_sql_functions by default.

**Comment by jainavi17** [comment]
> s wrong with this PR. 50 commits. 8K lines of code. Conflicts. Would you rebase and update?

I've created a new PR https://github.com/prestodb/presto/pull/18625

**Pull request closed without merging**
