### PR TITLE
Update to Airbase 61

### PR DESCRIPTION
**Pull request by electrum**
This includes the commits from #6995

### CODE REVIEW

**Comment by electrum** [comment]
This includes the commits from #6995

**Comment by kokosing** [comment]
What about the issue with cassandra (update of guava)?

As I see there are two solutions:
a. shade guava - https://github.com/prestodb/presto/pull/6995#issuecomment-273340497
b. load connector in tests in isolated classloader - https://github.com/prestodb/presto/pull/6995#issuecomment-273692383

I think we need to choose an approach and solve this issue as it lasts for so long and it causing that we are unable to upgrade airbase at all.

I vote for B.

**Comment by electrum** [comment]
We should shade Guava. Changing how testing works is a huge project and I'm not sure it's even possible without losing IDE support.

**Comment by kokosing** [comment]
Shading could be also a huge project and what is more, if do not change our approach we could hit similar issue in near feature once again with the other library.

**Comment by electrum** [comment]
Another problem is that the Cassandra plugin depends on Airlift which uses the latest Guava. So we'd need to keep it on an old version or remove Airlift.

Instead of shading, we could fork the project and publish a fork with the minor changes to update Guava. This is a temporary solution until they update (and hopefully learn their lesson so this isn't a problem for future Guava versions).

**Comment by kokosing** [comment]
> Instead of shading, we could fork the project and publish a fork with the minor changes to update Guava. This is a temporary solution until they update (and hopefully learn their lesson so this isn't a problem for future Guava versions).

Then... should we only use it for cassandra connector tests or generally for cassandra connector?

There are also some issues with hive:
```
java.lang.NoClassDefFoundError: com/google/common/io/InputSupplier
	at com.facebook.presto.hive.TestHiveFileFormats.testDwrf(TestHiveFileFormats.java:467)
Caused by: java.lang.ClassNotFoundException: com.google.common.io.InputSupplier
	at com.facebook.presto.hive.TestHiveFileFormats.testDwrf(TestHiveFileFormats.java:467)
```

But I understand hive is already shaded (forked) so we would need to handle guava there as well.

**Comment by electrum** [comment]
We'd need to fork any artifacts that aren't compatible.

I'm aware of the hive-dwrf problem and will release a patched version soon. It is a separate artifact and comes from here: https://github.com/facebookarchive/hive-dwrf

**Comment by electrum** [comment]
Fix for DWRF: https://github.com/facebookarchive/hive-dwrf/pull/24

**Comment by kokosing** [comment]
@electrum Thank you for taking care of this!

**Pull request closed without merging**
