### PR TITLE
Revert "Improve listing performance of Hudi tables" on release-0.272

### PR DESCRIPTION
**Pull request by mshang816**
This reverts commit ef1fd25c582631513ccdd097e0a654cda44ec3dc.

Test plan - (Please fill in how you tested your changes)

Please make sure your submission complies with our [Development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [Formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), and [Commit Message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests) guidelines. Don't forget to follow our [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution) for any code copied from other projects.

Fill in the release notes towards the bottom of the PR description.
See [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) for details.

```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by varungajjala — APPROVED** [review]

**Comment by ankushChatterjee** [comment]
why is this revert being made?

**Comment by codope** [comment]
@mshang816 @varungajjala This revert affects many Hudi users. May I know why this was done? Recommendations for shading and keeping hudi-presto-bundle thin were already taken care of in #17244 
cc @arunthirupathi

**Comment by arunthirupathi** [comment]
@codope  this is done just a hotfix for 0.272 release and not merged in master. It broke one of the connectors. so Hudi users are unaffected, unless they pick up this very specific build. I will follow up next week.

**Comment by codope** [comment]
Thanks for the update @arunthirupathi

**Comment by ankushChatterjee** [comment]
Hi @arunthirupathi what connector was the change breaking?

**Comment by rohanpednekar** [comment]
@arunthirupathi Could you please provide more guidance on this PR?

**Comment by arunthirupathi** [comment]
To unblock 0.272 release we did it. The problem is already addressed for 0.273 so this change will not land in master. Let me know if this is a problem.

**Comment by umehrot2** [comment]
@arunthirupathi can you please point us to the actual fix in 0.273 ? We want to use 0.272, but at the same time want this patch. If you can point to what the issue/fix was, that would be really helpful.

**Comment by arunthirupathi** [comment]
It was an internal connector and the connector was internally modified for the next release, does starting a release for the next version help ?

**Comment by umehrot2** [comment]
When you say internal connector, do you mean something internal to facebook ? If that is the case, then for us at Amazon EMR we can just not include this revert patch while building our 0.272 internally. If it does not affect any open source Presto functionality, we should be okay to not include this patch for us internally. We just want that confirmation.

**Comment by arunthirupathi** [comment]
The connector was internal to facebook(Meta). So reverting this patch for Amazon EMR makes sense.

**Comment by umehrot2** [comment]
Thanks @arunthirupathi for the confirmation !

**Comment by dwshmilyss** [comment]
why does not merge this commit to master

**Pull request merged**
