### PR TITLE
Revert "Revert "Add source location info to RowExpression""

### PR DESCRIPTION
**Pull request by kaikalur**
This reverts commit 547a06813204b937635865452685c1855e02d2ed.

Fixed the multiple @JsonCreator annotations that caused intermittent test failures.

Test plan - Tests added in the original PR being resurrected.

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by kaikalur** [comment]
Reviewers - just resurrecting this from the previous revert. Removed all the extra JsonCreator annotations and fixed the 100s of files to pass empty source location to the various RowExpression subclass constructors. It should be good now. Tests are passing. I was able to repro the issue using AbstractTestQueries and tpch constructor before this PR. But now that works fine. Please review this. Thanks!

**Comment by highker** [comment]
> Tests are passing. I was able to repro the issue using AbstractTestQueries and tpch connector before this PR.

I guess we already have unit tests to cover this in the updated PR?

**Comment by kaikalur** [comment]
> > Tests are passing. I was able to repro the issue using AbstractTestQueries and tpch connector before this PR.
> 
> I guess we already have unit tests to cover this in the updated PR?

Yes

**Review by highker — APPROVED** [review]
@rongrong wanna take another look as you were the original author? Or I could merge it by EOD

**Pull request merged**
