### PR TITLE
Cache Configurations and FileSystems

### PR DESCRIPTION
**Pull request by lliiun-z**
For tables with large number of small files, a huge amount of cpu times are
consumed by creating configuration and filesystem objects for their queries. We have observed this when we did experiments with clustering; this is also common for general tables with inappropriate partitioning or bucketing. For these tables, caching these objects for their queries will speed up their queries dramatically.

TESTS:
1. Ran Katchin tests, there was no test failures:
https://www.internalfb.com/intern/presto/verifier/results/?test_id=70910&statuses[0]=FAILED

Test plan - (Please fill in how you tested your changes)

Please make sure your submission complies with our [Development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [Formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), and [Commit Message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests) guidelines. Don't forget to follow our [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution) for any code copied from other projects.

Fill in the release notes towards the bottom of the PR description.
See [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) for details.

```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by pranjalssh** [comment]
Please fix the easycla error

**Review by highker — COMMENTED** [review]
For the commit message, let's cap each line within 72 characters and also remove anything that is FB specific.

**Comment by highker** [comment]
Can we also sign the CLA and force push after a full rebase?

**Comment by highker** [comment]
> @zybing also found this performance issue and had a fix (#17229) without caching. Let's do some experiment and if caching is necessary to fix it?

If we can improve the copy(), then that's good :D

**Comment by rongrong** [comment]
> > @zybing also found this performance issue and had a fix (#17229) without caching. Let's do some experiment and if caching is necessary to fix it?
> 
> If we can improve the copy(), then that's good :D

I'm not sure whether copy is even needed. Do we update HDFS configuration anywhere in the codebase at all? If not, why do we need to make a new copy every time?

**Pull request closed without merging**
