### PR TITLE
Allow s3 implementations to be configurable

### PR DESCRIPTION
**Pull request by z-york**
This pull request allows users to configure fs.(s3, s3a, s3n).impl in hive config. This is useful for users who want to compare performance across different implementations.

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by z-york** [comment]
Can someone take a look at this please? Thanks!

**Comment by z-york** [comment]
@electrum Can you take a look please?

**Comment by electrum** [comment]
This goes against our philosophy of only providing config options that users should reasonably be expected to change. Unlike Hadoop, Presto isn't a generic application platform. It needs to work well out of the box. We avoid having configs that use class names, since that is brittle and necessitates users messing around with JAR files, which is definitely not supported or encouraged.

The Hive connector only ships with one S3 file system, so there isn't any need to configure it. If we did want to allow configuration, we would do it like `HiveStorageFormat` which is a list of known types which are known to work well, rather than an arbitrary class name (which might not work or even exist).

For testing, benchmarks, etc., users can build Presto from source with whatever modifications are necessary. If it turns out that other S3 file systems have better performance, we should figure out why and incorporate that into `PrestoS3FileSystem`.

**Comment by dain** [comment]
@z-york we are willing to update Presto to support an alternate know better implementation of the S3 file system, but if this is just for testing, we suggest you just hack Presto and run a one off test.

**Comment by cce** [comment]
Hi @dain @electrum — curious if you think a S3 caching layer like https://github.com/qubole/rubix would be worth accepting a patch like this or some other mechanism for making the S3 FS implementation configurable?

**Pull request closed without merging**
