### PR TITLE
Remove redundant filter node

### PR DESCRIPTION
**Pull request by zhenxiao**
Fix first part of
https://github.com/facebook/presto/issues/3600
Do not pushdown predicate if it is an identical equalTo comparison

### CODE REVIEW

**Comment by martint** [comment]
The general fix for this is actually a lot more complicated. I expect that we'll need a way to canonicalize expressions so that they can be compared based on their semantics.

**Comment by zhenxiao** [comment]
And use their semantics to decide whether to push down? @martint could u elaborate more detail? My understanding could be wrong, am interested to learn

**Comment by erichwang** [comment]
Yup, there is definitely some need to canonicalize expressions here. @zhenxiao, canonicalization will help us normalize expressions to be more easily compared with each other for similarity and equality. For example, this may include removing redundant conjunctions from expressions. However, in this case, note that (a = a) would probably be canonicalized as (a IS NOT NULL) -- so we would still need to push that predicate down.

Since canonicalization is a lot more work, in the short term, I would support just having this explicit simplification in the SimplifyExpressions optimizer.

**Comment by zhenxiao** [comment]
thanks for your explanation @erichwang updated the PR with explicit simplification in SimplifyExpression
@martint @erichwang any comments are appreciated

**Comment by erichwang** [comment]
@zhenxiao, we need to replace the (a = a) type of expression with (a IS NOT NULL) to be correct. For example, this current code will produce incorrect results if the input contains any nulls.

The more general way to apply this would be to just transform identity equality to not null check in the ExpressionInterpreter when doing optimizations.

**Comment by miniway** [comment]
How is this issue going? I'm experiencing severe slowdown at a query.

Here is a simplified version of  my problem. In this example, (nationkey + 1) pushdown to the right table even though it should not. right table has same name field on it's criteria but it's different field. Also as a side effect of pushdown of redundant filter, ```("regionkey_12" + 2) + 1) = (("regionkey_12" + 2) + 1)```, it could cause a lot of CPU waste. In my case, each expression is huge complex and combined is much worse.

```
presto:sf1> explain (type distributed) select a.nationkey,a.nationkey2, a.name,b.comment from (select nationkey, nationkey + 1 as nationkey2, name from nation where nationkey > 1) a join (select regionkey + 2 as nationkey , comment from nation where nationkey > 0) b on a.nationkey = b.nationkey;

----------------------------------------------------------------------------------------------------------------------------------------------------------------
 Fragment 0 [SINGLE]
     Output layout: [nationkey, expr, name, comment_13]
     Output partitioning: SINGLE []
     - Output[nationkey, nationkey2, name, comment] => [nationkey:bigint, expr:bigint, name:varchar, comment_13:varchar]
             nationkey2 := expr
             comment := comment_13
         - RemoteSource[1] => [nationkey:bigint, expr:bigint, name:varchar, comment_13:varchar]

 Fragment 1 [HASH]
     Output layout: [nationkey, expr, name, comment_13]
     Output partitioning: SINGLE []
     - Project => [nationkey:bigint, expr:bigint, name:varchar, comment_13:varchar]
         - InnerJoin[("expr_46" = "expr_47") AND ("$hashvalue_48" = "combine_hash") AND ("combine_hash_49" = "$hashvalue_50") AND ("nationkey_51" = "expr_52")]
             - RemoteSource[2] => [expr:bigint, nationkey:bigint, $hashvalue:bigint, name:varchar, expr_46:bigint, $hashvalue_48:bigint, combine_hash_49:bigint,
             - RemoteSource[3] => [expr_42:bigint, expr_15:bigint, $hashvalue_45:bigint, comment_13:varchar, expr_47:bigint, combine_hash:bigint, $hashvalue_50:

 Fragment 2 [SOURCE]
     Output layout: [expr, nationkey, $hashvalue, name, expr, $hashvalue, $hashvalue, nationkey]
     Output partitioning: HASH [expr, nationkey]
     - Project => [expr:bigint, nationkey:bigint, $hashvalue:bigint, name:varchar]
             expr := ("nationkey" + 1)
             $hashvalue := "combine_hash"("combine_hash"(0, COALESCE("$operator$hash_code"(("nationkey" + 1)), 0)), COALESCE("$operator$hash_code"("nationkey"),
         - Filter[(("nationkey" > 1) AND (("nationkey" + 1) = ("nationkey" + 1)))] => [nationkey:bigint, name:varchar]
             - TableScan[tpch:tpch:nation:sf1.0, originalConstraint = ("nationkey" > 1)] => [nationkey:bigint, name:varchar]
                     nationkey := tpch:nationkey
                     name := tpch:name

 Fragment 3 [SOURCE]
     Output layout: [expr_42, expr_15, $hashvalue_45, comment_13, expr_42, $hashvalue_45, $hashvalue_45, expr_15]
     Output partitioning: HASH [expr_42, expr_15]
     - Project => [expr_42:bigint, expr_15:bigint, $hashvalue_45:bigint, comment_13:varchar]
             expr_42 := (("regionkey_12" + 2) + 1)
             expr_15 := ("regionkey_12" + 2)
             $hashvalue_45 := "combine_hash"("combine_hash"(0, COALESCE("$operator$hash_code"((("regionkey_12" + 2) + 1)), 0)), COALESCE("$operator$hash_code"((
         - Filter[(((("regionkey_12" + 2) + 1) = (("regionkey_12" + 2) + 1)) AND (("nationkey_10" > 0) AND (("regionkey_12" + 2) > 1)))] => [nationkey_10:bigint
             - TableScan[tpch:tpch:nation:sf1.0, originalConstraint = (("nationkey_10" > 0) AND (("regionkey_12" + 2) > 1))] => [nationkey_10:bigint, regionkey_
                     nationkey_10 := tpch:nationkey
                     regionkey_12 := tpch:regionkey
                     comment_13 := tpch:comment
```

**Comment by cberner** [comment]
@zhenxiao are you still working on this?

**Comment by zhenxiao** [comment]
oh, yes, did not look at this for some time. Let me take a rebase and resolve comments

**Comment by kokosing** [comment]
Is this still valid PR?

**Comment by raghavsethi** [comment]
Closing this due to lack of response. Please rebase and open another PR if this is still required.

**Pull request closed without merging**
