### PR TITLE
Move MapBlock related classes to a new package

### PR DESCRIPTION
**Pull request by yingsu00**
This is the preparation commit for the lazy MapBlock hashtable project.
It creates a new package com.facebook.presto.spi.block.Map and move all
map related classes to this package.

For simple read/write queries involve maps, we don't need to build the
hashtable. The idea is to build hashtable on the fly when the seekKey
methods in SingleMapBlock are called, and MapBlockBuilder need to
rebuild the missing hashtable when closeEntry() is called with a
passed in hashtable. However synchronizing the seekKey() and
closeEntry() methods is very complex and error prone. To reduce the
complexity of synchronization, we will make MapBlockBuilder build the
hashtable all the time and only synchronize when multiple threads are
trying to create the hashtable when calling seekKey(). In a seperate
project, we will avoid MapBlockBuilder to build the hashtables in the
PartitionOutputOperator. To make this way work, we need to make
SingleMapBlock to be able to see the hashtable inside of the MapBlock.
Instead of making it public, we will create a new Map package and make
the hashtable visible to this package.

### CODE REVIEW

**Comment by yingsu00** [comment]
@dain Sure. I'll add the logic change in a separate commit in this PR.

**Comment by findepi** [comment]
> The idea is to build hashtable on the fly when the seekKey methods in SingleMapBlock are called

This is clever. Note that, however, it may break memory allocations during execution -- MapBlock's retained size will increase when reading data from it, and operators will probably not know they need to recalculate memory usage.
For example, is it possible to have a Join with maps in the build side, where Join's filter involves calling `seekKey`?

**Comment by dain** [comment]
@findepi I think we know the size of the hash table ahead of time, so we could always add that regardless of if the actual state of the hashtable.  What do you think?  Also @haozhun, thoughts?

**Comment by findepi** [comment]
@dain could be. But if we're declaring memory as used (but not using it), what's the gain? No other query can use this memory anyway, right?

**Comment by dain** [comment]
@findepi my thought is "for safety", given the current design of the system that block sizes don't change after creation.

**Comment by wenleix** [comment]
@findepi : The current goal is to save CPU. If we later want to save memory, one thought is to introduce `LookupMap` vs. `DataMap` (bad name :P) :

- `DataMap` has no hash table, and `LookupMap` has hash table
- Lookup functions (such as `element_at` and `[]`) only supports `LookupMap`
- An implicit cast rule from `DataMap` to `LookupMap`
- An optimizer rule that pushes down `DataMap` to `LookupMap` to the reader. So a `LookupMap` will be constructed from the beginning if required.

This is just an idea. Not saying we will go with this direction :) . 

The idea is to make decisions at the planning time, so we don't need to worry about complicated concurrent hash table update issue at execution time :)

**Comment by findepi** [comment]
> The current goal is to save CPU. If we later want to save memory, ...

Make sense.

> The idea is to make decisions at the planning time, so we don't need to worry about complicated concurrent hash table update issue at execution time :)

This is indeed worrisome. You need to make sure you don't get much penalty when _using_ the map, i.e. just checking if it needs an update.

**Comment by findepi** [comment]
> To make this way work, we need to make
SingleMapBlock to be able to see the hashtable inside of the MapBlock.
Instead of making it public, we will create a new Map package and make
the hashtable visible to this package.

Maybe we consider making the hash table package-private without moving `SingleMapBlock`, `MapBlock` to a separate package?

**Comment by yingsu00** [comment]
Thanks @haozhun. I'm closing this PR and will send a new PR without moving the classes as per the discussin offline.

**Pull request closed without merging**
