### PR TITLE
Support for CSV format in hive

### LINKED ISSUE #10905: Support CSV storage format in Hive connector
I needed to query a CSV file stored in HDFS. The only option seemed to use the TEXTFILE format of Hive connector. I went like that:
`CREATE TABLE hive.default.person (nr INT, country VARCHAR, mbox_sha1sum VARCHAR, name VARCHAR, publishDate DATE, publisher INT) with (format = 'textfile', external_location = 'hdfs://host:54310/person.csv');`

The command looked like worked, but when I  `SELECT * FROM hive.default.person`, I get NULL values everywhere.

First, am I using the connector correctly i.e. to query CSV files? if yes, how to fix the NULL values?

### PR DESCRIPTION
**Pull request by ashishtadose**
PrestoSQL PR - https://github.com/prestosql/presto/pull/920

```
== RELEASE NOTES ==

Hive Changes
* Add support for CSV format in Hive connector
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```
resolve #10905

### CODE REVIEW

**Comment by aweisberg** [comment]
It looks like this is cherry-picking code from PrestoSQL. Don't forget to follow our [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).

**Comment by aweisberg** [comment]
This looks more connector than file format to me. @highker @bhhari can you find someone to review?

**Comment by ashishtadose** [comment]
Unlike other formats, CSV files don't contain special metadata sections such as column type, etc, and usually deferred to processing engines by schema-on-read
This implementation is based on [OpenCSV](http://opencsv.sourceforge.net/) which is used in Hive as well.

**Review by highker — APPROVED** [review]
LGTM

**Comment by highker** [comment]
Could you rebase and force push?

**Comment by aweisberg** [comment]
Came to late for this, but apparently the co-author tag doesn't get correctly parsed by GitHub unless there is a blank line between it and the commit description. See this branch I created to test the theory https://github.com/aweisberg/presto/commits/coauthor

**Comment by ashishtadose** [comment]
@aweisberg is this planned to roll out in any upcoming release?

**Pull request merged**
