### PR TITLE
Add presto-docs.sh script

### PR DESCRIPTION
**Pull request by mbasmanova**

### CODE REVIEW

**Comment by mbasmanova** [comment]
@nezihyigitbasi Nezih, thanks for the suggesting. I realized that this script need to run in a checkout of prestodb.github.io repository. Hence, it might make more sense to add it to that repository. What do you think?

**Comment by nezihyigitbasi** [comment]
Sure, that's why I asked you do document which directory to run it as it won't run under presto checkouts. Let's move it there.

**Comment by mbasmanova** [comment]
@nezihyigitbasi Nezih, I realized that I don't quite understand how the files from prestodb.github.io repository end up on http://prestodb.github.io/ website. More specifically, are ALL the files in the repo get exposed? If so, if we add presto-docs.sh script to that repo it may end up on the website. Perhaps, that's why it wasn't added to that repo in the first place. What do you think?

**Comment by mbasmanova** [comment]
CC: @caithagoras

**Comment by nezihyigitbasi** [comment]
Looks like we are using `.nojekyll` for our github pages and we just publish the static content that we push to that repo as our web page. That means whatever we push there will get published. I couldn't find a way to exclude files unfortunately (based on my understanding exclusion would be possible if we were using jekyll as we could specify a config yaml file for jekyll, but `.nojekyll` just disables jekyll processing). 

For now either we can continue keeping this as a gist file, which I am not a big fan of, or we can create a new repo under prestodb to maintain such handy scripts.

**Comment by wenleix** [comment]
@mbasmanova : What's the status of this PR -- should it be merged? Thanks!

**Pull request closed without merging**
