### PR TITLE
Fix infinite loop during planning caused by PickTableLayout

### PR DESCRIPTION
**Pull request by v-jizhang**
Replaces #16627

Co-authored-by: Brian Li <librian415@gmail.com>

Test plan - Added a test.

```
== RELEASE NOTES ==

General Changes
* Fix infinite loop during planning caused by PickTableLayout

```

### CODE REVIEW

**Comment by rohanpednekar** [comment]
@highker you did approve this PR at https://github.com/prestodb/presto/pull/16627 but it was missing few tests. 
Now @v-jizhang has added with rebase, could you please approve and merge?

**Review by NikhilCollooru — CHANGES_REQUESTED** [review]
For primitive types like `int`, please directly compare their values instead of using `Objects.equals` across this PR.

Direct value comparison for primitive types is much more efficient than `Object.equals` in Java

**Comment by NikhilCollooru** [comment]
Please squash the commits into one commit. The code changes look good.

**Comment by v-jizhang** [comment]
> @v-jizhang Please squash the commits into one commit. The code changes look good.

Squashed. Thank you!

**Review by rschlussel — APPROVED** [review]

**Pull request merged**
