### PR TITLE
Add MapR support

### PR DESCRIPTION
**Pull request by rlzhang**
Added a new connector for MapR.

### CODE REVIEW

**Comment by climberus** [comment]
@rlzhang I try to build the plugin for the hive-mapr4, but it looks, we got the native lib link error:

Caused by: java.lang.UnsatisfiedLinkError: com.mapr.security.JNISecurity.SetParsingDone()V

Do u have this issue for the mapr3?

**Comment by rlzhang** [comment]
@climberus ,
I didn't have the same issue as the same error, looks like you missed some of MapR native libraries.
You can check here and adding all necessary dependencies for MapR: https://github.com/facebook/presto/pull/1669/files

**Comment by cberner** [comment]
@joy-yao can you work with @electrum on this? We need to include MapR in our integration tests

**Comment by rlzhang** [comment]
I have tested on presto version 0.86, with a few code changes it can works well with MapR 3.1. @climberus, if you still have the same issue, you can try adding loadLibrary("MapRClient") in HadoopNative.java.

**Comment by cberner** [comment]
@rlzhang are you still working on this, and have you clarified the licensing issues?

**Comment by cberner** [comment]
Going to close this for now, but if you're still working on this and get the licensing issues sorted out please re-open!

**Comment by rsilvery** [comment]
Best to provide a way to specify JAR files at runtime. This would allow the usage of JAR files that aren't under the Apache License, such as for MapR.

**Comment by dain** [comment]
@rsilvery Last time we talked with MapR they agreed to provide all client libraries with Apache compatible licenses, but by the time we got the response, no one was interested any more.  If interest has built up again, we could look into shipping MapR libraries again.

**Comment by rsilvery** [comment]
Dain, please email me if you'd like to talk further: rsilver@maprtech.com. Please include the history so that I can get caught up.

**Pull request closed without merging**
