### PR TITLE
Improve URL function `url_extract_parameter` and `url_extract_query`

### PR DESCRIPTION
**Pull request by lxneng**
use `getRawQuery()` instead of `getQuery()` in `urlExtractParameter` and `urlExtractQuery`
method. to awoid decode query parameters.

for example:

```
presto:log> select url_extract_parameter('http://foo.com?source_url=http%3a%2f%2fbar.com%3fa%3dfoo%26b%3dbar',
'source_url');
_col0
----------------------
http://bar.com?a=foo
```
the expectation output is `http%3a%2f%2fbar.com%3fa%3dfoo%26b%3dbar`

and also in `url_extract_query` function

```
presto:log> select url_extract_query('http://foo.com?source_url=http%3a%2f%2fbar.com%3fa%3dfoo%26b%3dbar');
_col0
-------------------------------------
source_url=http://bar.com?a=foo&b=bar
```
and expectation output is `source_url=http%3a%2f%2fbar.com%3fa%3dfoo%26b%3dbar`

### CODE REVIEW

**Comment by akshatnair** [comment]
Add a test in TestUrlFunctions

**Comment by electrum** [comment]
We should add new functions instead. Changing behavior will break existing queries.

**Comment by xerial** [comment]
@lxneng Are you still working on the fix or preparing another function as @electrum suggested?

**Comment by lxneng** [comment]
@xerial Nope.

**Pull request closed without merging**
