### PR TITLE
Ignore the newly added test in presto_on_spark native execution to unblock e2e tests

### PR DESCRIPTION
**Pull request by mshang816**
Summary: As title

Reviewed By: mshang816

Differential Revision: D51001609

### CODE REVIEW

**Review by shuchipandit — APPROVED** [review]

**Review by mbasmanova — CHANGES_REQUESTED** [review]
@mshang816 Michael, please, provide more details about why you are disabling the test + a list to GitHub issue that has more context. Please, add [native pos] prefix in the commit message and PR title.

**Comment by mshang816** [comment]
> @mshang816 Michael, please, provide more details about why you are disabling the test + a list to GitHub issue that has more context. Please, add [native pos] prefix in the commit message and PR title.

@mbasmanova Actually I just exported the PR from an internal diff. @shuchipandit and I decided to ignore this one to unblock our internal e2e test faster. But actually I don't have too much knowledge on pos test, @shuchipandit can you provide some details here ?

**Comment by mbasmanova** [comment]
> I just exported the PR from an internal diff

@mshang816 We should not do that. Let's make sure all Presto PRs originate from GitHub.

**Comment by mshang816** [comment]
> > I just exported the PR from an internal diff
> 
> @mshang816 We should not do that. Let's make sure all Presto PRs originate from GitHub.

closing this PR

**Pull request closed without merging**
