### PR TITLE
Remove ahanaio/prestodb-sandbox reference

### PR DESCRIPTION
**Pull request by paoliniluis**
## Description
The container image no longer exists, so I removed the reference

## Motivation and Context
It won't guide the user to a dead link

## Impact
None

## Test Plan
Not needed

## Contributor checklist

- [X] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [X] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [X] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [X] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [X] Adequate tests were added if applicable.
- [X] CI passed.

## Release Notes
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by steveburnett — APPROVED** [review]
Good catch, thanks!

LGTM (docs)

Local build, everything looks good.

**Comment by paoliniluis** [comment]
thanks for the review @steveburnett, I just sent another one in parallel about the dockerfile in the same page as I'm testing locally and it didn't run out of the box

**Comment by tdcmeehan** [comment]
Thank you @paoliniluis!

**Comment by steveburnett** [comment]
> thanks for the review @steveburnett, I just sent another one in parallel about the dockerfile in the same page as I'm testing locally and it didn't run out of the box

Thanks! I've already tested, reviewed, and approved the other one - [PR 21455](https://github.com/prestodb/presto/pull/21455).

**Pull request merged**
