### PR TITLE
Extract pluggable KafkaTableDescriptionSupplier

### PR DESCRIPTION
**Pull request by yangy0000**
Cherry-pick of https://github.com/trinodb/trino/commit/0e379a36959dcd6676a4a1cdba2608f360a24d52

Co-Authored-By: Grzegorz Kokosiński <7569403+kokosing@users.noreply.github.com>

### CODE REVIEW

**Comment by dborkar** [comment]
@beinan when you get a chance , please have a look. thx.

**Comment by yangy0000** [comment]
> @beinan when you get a chance , please have a look. thx.
bump on the PR

**Review by beinan — APPROVED** [review]
lgtm, thank you for the contribution!   @zhenxiao @NikhilCollooru wanna have a second look?

**Review by zhenxiao — APPROVED** [review]
LGTM

**Pull request merged**
