### PR TITLE
Move AST to a separate module

### PR DESCRIPTION
**Pull request by highker**
Separate AST from parser as an individual module. Most dependent modules
only need AST rather than the parser.

### CODE REVIEW

**Comment by highker** [comment]
Yes! So I was exploring allowing connector to participate optimization. Whenever I include module `presto-parser` in some connectors, it always complain "antlr is not needed; please exclude". In most places of Presto codebase, only AST is needed rather than antlr. There are also existing connectors (e.g., `presto-hive`) that only need AST. It seems to be a clean separation to have a module (`presto-ast`) with only AST definition/structure and another module (`presto-parser`) to do the string-AST syntactic analysis. In the end, with or without connector participating optimization, the separation can be beneficial.

**Comment by rongrong** [comment]
I like the idea of separating AST into a separate module. Are we expecting to work on changes that would benefit from this refactoring in parallel? If not, maybe this can be part of a PR that would actually need this refactoring, which would also answer @raghavsethi's question in a way. We can also have a discussion on what this can enable and see whether it makes sense to get this in so other works can move forward.

**Comment by raghavsethi** [comment]
Agree with @rongrong: Let's do this when we need to, and make this an early commit in that PR.

**Comment by highker** [comment]
Yes, there will be benefit from having this change. As mentioned in my previous comment, we are working on connector participating optimization. We believe separating AST is the first step doing so, as @martint also mentioned refactoring IR. After a week's exploration, we found IR and optimizer refactoring is a huge pain at the moment, given logical plan, physical plan, and optimization are mixed in the same data structure (`PlanNode`). This separation is the only step we believe is clean and necessary. We will have a more clear picture once we finalize the design. By then, we can present to the team the whole picture.
There is no rush to merge this for sure.

**Comment by rongrong** [comment]
@raghavsethi There are evidence showing that we are introducing dependencies to presto-parser when we actually just need the tree. What do you think about this now?

**Comment by wenleix** [comment]
@highker : Is this superseded by the IR refactor work? Thanks!

**Pull request closed without merging**
