### PR TITLE
Add cast(ObjectId() as string) in mongodb connector

### LINKED ISSUE #14338: Cast MongoDB ObjectID as VARCHAR

### PR DESCRIPTION
**Pull request by Eywek**
fixes #14338

```
== RELEASE NOTES ==

MongoDB Changes
* add CAST(ObjectId() as STRING)
```

### CODE REVIEW

**Review by rschlussel — APPROVED** [review]

**Comment by rschlussel** [comment]
This is still a draft.  Are you planning to add more to it?

**Comment by rschlussel** [comment]
@Eywek If you are done, can you make this no longer a draft so I can merge it?

**Comment by Eywek** [comment]
Sorry, I haven't seen previous comments, it's ready to merge!

**Comment by rschlussel** [comment]
Thank you! can you rebase and push your branch again to restart the tests?

**Comment by Eywek** [comment]
Done!

**Comment by rschlussel** [comment]
sorry can you rebase one more time.  a fix for presto-docs is landed now.

**Comment by Eywek** [comment]
yep, it's done

**Pull request merged**
