### PR TITLE
Add missing JsonCreator annotation

### PR DESCRIPTION
**Pull request by miniway**

### CODE REVIEW

**Comment by haozhun** [comment]
Why did we not catch something so basic in tests? Can we introduce more tests and/or fix current tests? Additionally, it looks like `ExceptNode` is also broken. It's not even in `JsonSubTypes` of `PlanNode`.

**Comment by martint** [comment]
> Why did we not catch something so basic in tests? Can we introduce more tests and/or fix current tests? Additionally, it looks like ExceptNode is also broken. It's not even in JsonSubTypes of PlanNode

Unfortunately, there's no code that exercises json serialization of Intersect or Except. Those nodes are created by the planner and rewritten into other node types by the optimizer, so they never get serialized for transfer over the network.

**Comment by haozhun** [comment]
In this case, I see argument from both side about whether those classes should be JSON serializable at all (assuming it's possible to make it not JSON serializable). Therefore, this pull request seems ok. What do you think, @martint.

**Comment by martint** [comment]
@haozhun, they should be JSON-serializable. The fact that they are never transported over the network is an artifact of optimizations we make today, but that's the expectation for plan nodes. 

I was just explaining why none of the tests that we have today catch the problem. We're probably going to have to introduce explicit tests for json serializability.

**Comment by martint** [comment]
Merged, thanks!

**Pull request closed without merging**
