### PR TITLE
Refactor assertCreateTableAsSelect() and assertExplainAnalyze() code

### PR DESCRIPTION
**Pull request by pdabre12**
Refactored the assertCreateTableAsSelect() and assertExplainAnalyze() to reduce code duplication.

### CODE REVIEW

**Comment by pdabre12** [comment]
@majetideepak  Please review.

**Comment by majetideepak** [comment]
@pdabre12 Can you give a motivation for this refactor? Do we ever call `assertCreateTableAsSelect` with `allowDropTable` set to `false`?

**Comment by pdabre12** [comment]
@majetideepak Yes, it will be used in #20936.

**Comment by majetideepak** [comment]
> @majetideepak Yes, it will be used in #20936.

Why do we not want to delete the tables in that PR?

**Comment by pdabre12** [comment]
There is a small discussion about this in PR #20936. 
Basically in order to drop tables, I need to set a system property "hive"  which would mean modifying the file https://github.com/prestodb/presto/blob/dd5b168ff5bdf306de70be19cc37c9797ca00981/presto-native-execution/src/test/java/com/facebook/presto/nativeworker/NativeQueryRunnerUtils.java

**Comment by majetideepak** [comment]
> There is a small discussion about this in PR #20936.

I commented there. Let's add the system property to the NativeQueryRunner in a separate PR.
I don't think we should allow not dropping the tables.

**Comment by pdabre12** [comment]
@majetideepak 
Added the changes in #21641. 
Closing this PR as it's no longer needed.

**Pull request closed without merging**
