### PR TITLE
Handle fully filter pushdown for metadata query rewrite

### PR DESCRIPTION
**Pull request by yuanzhanhku**
Previously, the metadata query rewrite rule was applied after the filter
pushdown rule. If a filter on a non-partition column was fully pushed
down to the connector, the metadata query rewrite rule was not aware of
it and could incorrectly enable the rewrite.

This PR moves the metadata query rewrite rule before the filter
pushdown rule to avoid this issue.

Test plan
Added unit test.

```
== RELEASE NOTES ==

General Changes
* Fix a correctness bug which could be triggered for queries with aggregations on partitioning columns and filters on non-partitioning columns when both optimizing metadata queries and filter pushdown are enabled.
```

### CODE REVIEW

**Comment by highker** [comment]
The commit title is a bit weird "Disable metadata query rewrite for queries will fully filter pushdown". I think it's more about handling rather than disabling?

**Comment by yuanzhanhku** [comment]
> The commit title is a bit weird "Disable metadata query rewrite for queries will fully filter pushdown". I think it's more about handling rather than disabling?

Yes, updated the title. Thanks for the suggestion.

**Comment by highker** [comment]
Also, can we add release note?

**Review by highker — APPROVED** [review]

**Comment by highker** [comment]
For release note, we will need to be more user facing. So something like "Fix a correctness bug on ``max(partition_col)`` or `min(partition_col)`` when both optimizing metadata queries and filter pushdown are enabled".

**Comment by yuanzhanhku** [comment]
> For release note, we will need to be more user facing. So something like "Fix a correctness bug on `max(partition_col)` or `min(partition_col)` when both optimizing metadata queries and filter pushdown are enabled".

Sounds good. Updated. 
Just curious. So we also want to include these changes in the release note even if they are not enabled by default?

**Comment by highker** [comment]
> So we also want to include these changes in the release note even if they are not enabled by default?

So for release note, the rule of thumb is to check if there is any potential user impact. For this one, yes, because it is user-facing as someone could turn on the flag and get a wrong result. There are some changes that are not user facing so we don't need to add release note; for example the runtime stats framework.

**Pull request merged**
