### PR TITLE
[native] Support 'SqlFunctionHandle' in Presto Native.

### PR DESCRIPTION
**Pull request by spershin**
Test plan - New tests.

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by mbasmanova — COMMENTED** [review]
@spershin Curious what else is needed to make e2e test introduced in #19298 pass.

I assume we need to register some test functions (perhaps, based on some test-specific config or flag).

**Comment by spershin** [comment]
@mbasmanova 
I assume we need:
1. Register a function in coordinator or whatever layer serves as one (query parser + planner).
2. Implement that function in the cpp executable. How to do it is tricky - we don't want dodgy/dummy functions in the executable. Can be done with adding another executable and linking it with a test library that adds few functions. If fbcode we can use normal executable linked with new functions.
3. Add queries to E2E that use new functions.

**Comment by mbasmanova** [comment]
@spershin 

> Register a function in coordinator or whatever layer serves as one (query parser + planner).

Looks like #19298 has that.

> Implement that function in the cpp executable. How to do it is tricky - we don't want dodgy/dummy functions in the executable. 

How about adding a test-only configuration flag. When set, we register some existing Presto functions as "external" functions? 

> Add queries to E2E that use new functions.

Looks like #19298 has that as well.

**Comment by spershin** [comment]
Created a new PR instead of this.
https://github.com/prestodb/presto/pull/19325

**Pull request closed without merging**
