### PR TITLE
Add javadoc for Presto query submission protocol

### PR DESCRIPTION
**Pull request by ClarenceThreepwood**
#18347

== NO RELEASE NOTE ==

### CODE REVIEW

**Comment by yzhang1991** [comment]
@tdcmeehan ping on another javadoc PR.

**Comment by jainxrohit** [comment]
The classes for which we are adding javadoc and commit messages are not same. We should fix the commit message.

**Comment by highker** [comment]
Can we have PRs peer reviewed before sending to committers for final review?

**Comment by ClarenceThreepwood** [comment]
> The classes for which we are adding javadoc and commit messages are not same. We should fix the commit message.

The commit message says "Add javadoc for query submission protocol"
Isn't QueuedStatementResource the class where http submission requests and result processing are handled? A related/referenced class is QueryResults.

Would you rather have the explicit class names in the commit message?

**Review by highker — APPROVED** [review]
Could you rebase?

**Pull request merged**
