### PR TITLE
[Native] Change back to using environment variables for NativeQueryRu…

### PR DESCRIPTION
**Pull request by kewang1024**
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by kewang1024** [comment]
Followup for the PR: https://github.com/prestodb/presto/pull/21017

**Review by ZacBlanco — APPROVED** [review]

**Review by ZacBlanco — COMMENTED** [review]
Actually, looking at the old code, `System.getenv` usage was not consistent `System.getProperty`. I suspect depending on the code path different users may have broken. Changing this may break other usage?

e.g. `getenv`: https://github.com/prestodb/presto/pull/21017/files#diff-a88942948f0363c1bb42e8935e37cbdb044a515aab95aec55c11b9cbc1f0d993L56-L58

and `getProperty`

https://github.com/prestodb/presto/pull/21017/files#diff-a88942948f0363c1bb42e8935e37cbdb044a515aab95aec55c11b9cbc1f0d993L248-L250

**Comment by ZacBlanco** [comment]
A better solution might check environment variable first -> then system property -> then fall back to defaults

**Comment by kewang1024** [comment]
> https://github.com/prestodb/presto/pull/21017/files#diff-a88942948f0363c1bb42e8935e37cbdb044a515aab95aec55c11b9cbc1f0d993L56-L58

Thanks for catching that!

Since you have some context already, Can you help take care of this issue? https://github.com/prestodb/presto/issues/21162

**Review by aditi-pandit — COMMENTED** [review]
Thanks @kewang1024

**Pull request closed without merging**
