### PR TITLE
Add debug logging of statements to facilitate debugging. Similar capa…

### PR DESCRIPTION
**Pull request by jefimm**
Add debug logging of statements to facilitate debugging. Similar capabilities exists in most databases (logging of all queries)

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-3** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by petroav** [comment]
@jefimm thanks for the pull request! The first line of your commit message is too long (should be limited to 50 characters). Take a look at the convention described here http://chris.beams.io/posts/git-commit/.

**Comment by jefimm** [comment]
Could you please guide me how to fix that ?

**Comment by petroav** [comment]
@jefimm you probably want to `git commit --amend` locally, change your commit message, then `git push --force <your origin> <your branch>`.

**Comment by jefimm** [comment]
done

**Comment by jefimm** [comment]
Any chance that this will happen?

**Comment by martint** [comment]
Version 0.152 added support for event listener plugins that will get an event for every query that gets submitted and executed. We believe that's a better approach than adding hard-coded debug statements. 

See https://github.com/prestodb/presto/pull/4642 for a related discussion.

**Comment by electrum** [comment]
We can also add a standard plugin that writes events as text files and also support reading them with the Local File connector.

**Comment by cawallin** [comment]
@electrum @martint should this PR be closed, considering the functionality is available via event listeners?

**Comment by dain** [comment]
If something is still needed here, please reopen and explain the use case.

**Pull request closed without merging**
