### PR TITLE
Revise cli.rst for better comprehension

### PR DESCRIPTION
**Pull request by steveburnett**
Test plan - Revised presto-docs/cli.rst for improved readability by new users. 

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by tdcmeehan — APPROVED** [review]
LGTM

**Comment by tdcmeehan** [comment]
@steveburnett can you please rebase?  Should fix the test failure

**Comment by tdcmeehan** [comment]
Please squash commits as well!

**Comment by steveburnett** [comment]
Continue to have an error in the [linux-build-and-unit-test](https://app.circleci.com/pipelines/github/prestodb/presto/5104/workflows/12885083-1a6f-4327-a0e5-27985a18c3f8/jobs/13201), error 
"The following tests FAILED:
        5 - presto_server_test (Failed)"

If there's anything I should do to avoid this error, let me know.

**Comment by steveburnett** [comment]
Rebased this morning attempting to get a clean run and I am still having test failures.

**Comment by steveburnett** [comment]
Closing this as duplicate of merged #20346.

**Pull request closed without merging**
