### PR TITLE
Allow multiple or missing Hive bucket files

### PR DESCRIPTION
**Pull request by v-jizhang**
Cherry-pick of https://github.com/trinodb/trino/pull/822,
https://github.com/trinodb/trino/pull/848 and
https://github.com/trinodb/trino/pull/1375

Co-authored-by: David Phillips <david@acz.org>
Co-authored-by: Piotr Findeisen <piotr.findeisen@gmail.com>

```
== RELEASE NOTES ==

Hive Changes
* Allow multiple or missing Hive bucket files
```

### CODE REVIEW

**Review by aweisberg — CHANGES_REQUESTED** [review]
Can you break apart the three commits so that they map to the original ones? It helps preserve the history and makes them easier to review.

**Comment by c21** [comment]
Hi @v-jizhang - wondering do you have a plan to merge this PR soon? This might not be big impact internally in Facebook, and is important to allow open source Spark/Presto/Trino/Hive to write same bucket table, thanks.

**Comment by aweisberg** [comment]
@v-jizhang if you break apart the three commits then I can prioritize this review and we can get it done :-)

**Comment by v-jizhang** [comment]
> Hi @v-jizhang - wondering do you have a plan to work on this PR soon? This might not be big impact internally in Facebook, but is important to allow open source Spark/Presto/Trino/Hive to write same bucket table, thanks.

Thanks for reminding. Working on it now.

**Comment by v-jizhang** [comment]
Replaced by #16456.

**Comment by v-jizhang** [comment]
> @v-jizhang if you break apart the three commits then I can prioritize this review and we can get it done :-)

Done, please review #16456

**Pull request closed without merging**
