### PR TITLE
Remove empty staging directories after insert into hive table

### PR DESCRIPTION
**Pull request by kokosing**

### CODE REVIEW

**Comment by kokosing** [comment]
Supersedes #5338, I fixed codestyle errors so travis can run tests

**Comment by kokosing** [comment]
CC: @haozhun

**Comment by cberner** [comment]
Looks good

**Comment by ilfrin** [comment]
can we merge this in?

**Comment by martint** [comment]
We're waiting for the current release to go out and then we'll merge it

**Comment by haozhun** [comment]
Merged #5352

**Pull request closed without merging**
