### PR TITLE
Fix using qualified table name with views

### PR DESCRIPTION
**Pull request by jingw**
Without this patch, I can't qualify column references from views.

```
create table tbl (a bigint);
create view tbl_view as select * from tbl;
-- fails
select tbl_view.a from tbl_view;
-- works
select a from tbl_view;
```

With this patch, both work.

### CODE REVIEW

**Comment by jingw** [comment]
I'm told Dropbox has signed the FB CLA. Please let me know if I need to fill out anything.

**Comment by electrum** [comment]
Can you add a test for this?

**Comment by jingw** [comment]
I checked that the test fails without this patch: https://travis-ci.org/jingw/presto/builds/122331364

**Comment by electrum** [comment]
Can you also add a test in `TestAnalyzer`?

**Comment by electrum** [comment]
Product tests are heavy-weight integration tests, so they only run as part of the CI. We use normal unit tests for everything if possible since they are quick to run, easy to debug, run as part of the normal Maven build, etc.

**Comment by martint** [comment]
Merged, thanks!

**Pull request closed without merging**
