### PR TITLE
Add release notes for 0.273.3

### PR DESCRIPTION
**Pull request by prithvip**
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by rschlussel — COMMENTED** [review]
should we add a warning to 0.273.2 as well?

**Comment by prithvip** [comment]
> should we add a warning to 0.273.2 as well?

IIUC, the warning messages apply to 0.273 in general rather than to a specific 0.273.x, so both warnings are in release-0.273.rst

**Review by rschlussel — APPROVED** [review]

**Review by ajaygeorge — APPROVED** [review]
LGTM

**Review by kewang1024 — APPROVED** [review]

**Comment by prithvip** [comment]
@rschlussel can we merge this in?

**Pull request merged**
