### PR TITLE
Update testcontainers for apple silicon support

### PR DESCRIPTION
**Pull request by ZacBlanco**
Test plan

With the dependency update, as long as the CI passes we should not need additional tests.

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by ClarenceThreepwood — APPROVED** [review]
lgtm

**Review by yingsu00 — APPROVED** [review]
Commit title "Use updated dependency across all modules" -> "Use updated testcontainers dependency across all modules"

**Review by yingsu00 — CHANGES_REQUESTED** [review]
1. The first 4 commits all have test failures. Can you reorder and/or squash the commits to make sure all commits succeed? It's not allowed to have any commits that breaks the build or has test failures.
2. Commit title "Use updated dependency across all modules" -> "Use updated testcontainers dependency across all modules"

**Comment by ZacBlanco** [comment]
Thanks for the feedback @yingsu00  - Everything should be addressed now

**Review by yingsu00 — APPROVED** [review]

**Pull request merged**
