### PR TITLE
Introducing Hash Function 

### PR DESCRIPTION
**Pull request by shubham166**
Introduced a new function 'hash' that takes range and variable no. of arguments of any type and return the cumulative hash value within the given range.
For eg: 
<b>select hash(134, 45, 67, 89,199999999999)</b>  -> 68
<b>select hash(1747, 'superman', 'hello');</b> -> 157
<b>select hash(1747, 68.8, 68.7, 5757.4443);</b> -> 1218

### CODE REVIEW

**Comment by shubham166** [comment]
May I get some comments on this.

**Comment by snarayananqubole** [comment]
Any updates on this?

**Comment by cberner** [comment]
@martint and @electrum are discussing the return type of this function. The feeling is that we need a new binary type to represent the return value.

**Comment by dfrankow** [comment]
Any progress?

**Comment by kaschaeffer** [comment]
@electrum @martint what's the status of this? 

This has become a high priority for Deltoid project, as we need a way to downsample data as it's loaded into our system. We could use md5, but for our use case would make a lot more sense to use a more efficient hash function (since we do not require a cryptographic hash).

**Comment by Balandat** [comment]
An news on this? It seems like a lot of people do hacky things to get this to work.

**Comment by dain** [comment]
There are several hash functions, but I recommend https://prestodb.io/docs/current/functions/binary.html#xxhash64

You can turn the result into a BIGINT using https://prestodb.io/docs/current/functions/binary.html#from_big_endian_64

**Comment by Balandat** [comment]
That'll work, it's just that doing something like `ABS(from_big_endian_64(xxhash64(to_utf8(cast(some_column_name as varchar)))) % n_buckets) as bucket` seems really overkill if no crytographic hash is needed

**Comment by dain** [comment]
I casting everything to varchar is a bit expensive.  For numbers, I'd use to_big_endian_64.

**Comment by crorella** [comment]
The values returned by the Hive counterpart are different though

**Pull request closed without merging**
