### PR TITLE
Disable testPartitionStatisticsSampling for Glue metastore tests

### PR DESCRIPTION
**Pull request by kokosing**
Disable testPartitionStatisticsSampling for Glue metastore tests

### CODE REVIEW

**Comment by kokosing** [comment]
This was caught in internal testing.

**Comment by arhimondr** [comment]
@findepi Thanks

**Comment by findepi** [comment]
it wasn't me -- @kokosing

**Comment by arhimondr** [comment]
Sorry, still sleeping =) Thanks @kokosing

**Pull request merged**
