### PR TITLE
[native pos] Check null pointer before use in spark test

### PR DESCRIPTION
**Pull request by kewang1024**
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by amitkdutta** [comment]
@kewang1024 Please rebase on https://github.com/prestodb/presto/pull/20014

**Review by miaoever — APPROVED** [review]
Thanks for the fix, LGTM

**Review by amitkdutta — APPROVED** [review]
Thanks @kewang1024 for fixing it quickly.

**Review by pranjalssh — APPROVED** [review]

**Comment by pranjalssh** [comment]
Checks are failing, stamped in advance

**Comment by vermapratyush** [comment]
@kewang1024  Can you please rebase and add this test back (it is marked as ignore in master)
https://github.com/amitkdutta/presto/blob/e4a9df3a4ed886e63e8458d4c2c55e5ac1993c99/presto-native-execution/src/test/java/com/facebook/presto/spark/TestPrestoSparkNativeGeneralQueries.java#L70

**Pull request merged**
