### PR TITLE
Document JSON_EXISTS, JSON_VALUE and JSON_QUERY functions

### PR DESCRIPTION
**Pull request by v-jizhang**
This is documentation for the features introduced in #18021,
and should be merged after that PR.
Cherry-pick of https://github.com/trinodb/trino/pull/10655

Co-authored-by: kasiafi <30203062+kasiafi@users.noreply.github.com>

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by mbasmanova** [comment]
Any particular reason not to add this commit to https://github.com/prestodb/presto/pull/18021?

**Comment by v-jizhang** [comment]
> Any particular reason not to add this commit to #18021?

No, only because they are separate PRs originally.

**Comment by steveburnett** [comment]
This is so much of a change from and replacement of [the existing documentation](https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/functions/json.rst), and this change was proposed nearly two years ago, so that I am not comfortable reviewing it.

**Comment by steveburnett** [comment]
Closing due to lack of activity and age. If this is still relevant, please re-open this PR, rebase, and resolve any file conflicts.

**Pull request closed without merging**
