### PR TITLE
Dynamic filter planner

### PR DESCRIPTION
**Pull request by zhenxiao**
backport https://github.com/prestosql/presto/pull/91/commits/97fd53b98454ab261de012af8e51b29271c80550

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by mbasmanova** [comment]
What is "Dynamic filter"?

CC: @yingsu00

**Comment by zhenxiao** [comment]
follow the discussion: https://github.com/prestodb/presto/issues/7428

**Comment by yingsu00** [comment]
> backport https://github.com/prestosql/presto/pull/91/commits/97fd53b98454ab261de012af8e51b29271c80550
> 
> 
> 
> ```
> 
> == NO RELEASE NOTE ==
> 
> ```
> 
> 

@zhenxiao Amazon had backported PrestoSQLs dynamic filtering work to their internal repo and shared us with a patch. Is this PR the patch from Amazon?

**Comment by mbasmanova** [comment]
CC: @nezihyigitbasi

**Comment by zhenxiao** [comment]
oh, is it?
No, this is my backport dynamic filtering :)

**Comment by yingsu00** [comment]
> oh, is it?
> No, this is my backport dynamic filtering :)

I'll send you the patch and document offline. Will you read them and let us know your thoughts? Thank you!

**Comment by nezihyigitbasi** [comment]
@zhenxiao I will provide you more info shortly offline.

**Comment by zhenxiao** [comment]
let me close this PR. keep me posted when we are reviewing dynamic filtering patches

**Comment by kewang1024** [comment]
Hey, so why is this PR closed exactly?

**Comment by zhenxiao** [comment]
hi @yingsu00 are you working on dynamic filtering?
I thought this is duplicate work, so close it

**Pull request closed without merging**
