### PR TITLE
Enable Optimized Parquet Reader and Predicate Pushdown by default	

### PR DESCRIPTION
**Pull request by zhenxiao**
Fix https://github.com/prestodb/presto/issues/6299

### CODE REVIEW

**Comment by electrum** [comment]
Coming back to this PR, there are two questions:

1. Can we enable the optimized reader by default?
2. Is the optimized reader ready to replace the old one?

We can enable the new one by default, wait a few releases, then remove the old one.

**Comment by electrum** [comment]
Also, should Parquet predicate pushdown be enabled by default?

**Comment by zhenxiao** [comment]
Yes, I think the optimized Parquet Reader, and predicate pushdown could be turned on by default. We've using it in production for a long time.
I will update the patch.

**Comment by nezihyigitbasi** [comment]
@electrum +1 for both.

**Comment by zhenxiao** [comment]
rebased, first step, enable both by default @electrum @nezihyigitbasi

**Comment by electrum** [comment]
Thanks, looks good, checking why Travis failed.

Can you submit a new PR with the previous change that removes the old reader? We'll merge it in a few releases

**Comment by electrum** [comment]
Looks like legit test failures: https://s3.amazonaws.com/archive.travis-ci.org/jobs/208731273/log.txt

Example:
```
testInsert(com.facebook.presto.hive.TestHiveClient)  Time elapsed: 4.671 sec  <<< FAILURE!
java.lang.AssertionError: 
expected: collections to be equal (ignoring order).
Actual:
      [1, hello, 45, 345, 234, 123, -754.1985, 43.5, true, [apple, banana], {one=1, two=2}, [true, 1, true]]
      [2, null, null, null, null, null, null, null, null, [null], {null=null}, [null, null, null]]
      [3, bye, 46, 346, 345, 456, 754.2008, 98.1, false, [ape, bear], {four=4, three=3}, [false, 0, false]]
Expected:
      [1, hello, 45, 345, 234, 123, -754.1985, 43.5, true, [apple, banana], {one=1, two=2}, [true, 1, true]]
      [2, null, null, null, null, null, null, null, null, null, null, null]
      [3, bye, 46, 346, 345, 456, 754.2008, 98.1, false, [ape, bear], {four=4, three=3}, [false, 0, false]]
```

**Comment by electrum** [comment]
It's the structural types: array, map and row. We insert nulls, but they return non-null value that contains null: 
```
[null], {null=null}, [null, null, null]
```
So it seems the optimized reader has different (incorrect?) behavior.

**Comment by electrum** [comment]
And a different type of failure:
```
testTypesParquet(com.facebook.presto.hive.TestHiveClient)  Time elapsed: 0.636 sec  <<< FAILURE!
java.lang.IllegalArgumentException: position is not valid
```

**Comment by zhenxiao** [comment]
thank you, @electrum let me take a look and fix it

**Comment by electrum** [comment]
I suggest updating `TestHiveFileFormats` to cover these cases, since that runs as part of the normal Maven build and doesn't require an external Hive environment.

**Comment by electrum** [comment]
@zhenxiao I got the `AbstractTestHiveClient` tests to run against the testing metastore: https://github.com/prestodb/presto/pull/7539

If you rebase your changes on top of that PR, you can run `TestHiveClientTestingMetastore` in your IDE and reproduce the Travis failures.

**Comment by electrum** [comment]
I just merged that PR, so rebase on master should reproduce the failure. I'm going to restart the Travis job that runs the normal `presto-hive` tests, which should pick this up.

**Comment by nezihyigitbasi** [comment]
@zhenxiao @electrum I created a new PR to supersede this one to fix the test failure, so closing this one.

**Comment by nezihyigitbasi** [comment]
The fix seems to be more involved than I initially thought. The way we manage nestedness and offsets (especially when we have nulls) is not entirely correct. 

@zhenxiao I think it would be better if you take over #7601 as you are the initial author of the complex types support in the new reader. Currently, it passes most of the tests. It currently fails reading the array of struct (`array(row(s_string varchar, s_double double))`) in `presto_test_types_parquet` test in the integration tests in `presto-hive`.

**Comment by zhenxiao** [comment]
thank you @nezihyigitbasi 
sure. Let me do it, just assign it to me

**Comment by nezihyigitbasi** [comment]
@zhenxiao did you have a chance to look at this issue of null handling in the new reader?

**Comment by zhenxiao** [comment]
Not yet. Will do in 2 weeks

**Comment by zhenxiao** [comment]
@nezihyigitbasi @electrum 
Now could be a good time to enable new Parquet reader by default?

**Comment by electrum** [comment]
Sounds good to me, if you think so (we don’t use it). I can merge this after the release goes out.

**Comment by electrum** [comment]
Merged, thanks!

**Pull request closed without merging**
