### PR TITLE
Fix bugs in aria OrcInputStream

### PR DESCRIPTION
**Pull request by elonazoulay**
The uncompressedBufferOffset should be set to 0.
The uncompressedBuffer should be created with chunk.getBytes().

### CODE REVIEW

**Comment by elonazoulay** [comment]
There seem to be some other issues with the code: the methods used on the slice should not be interleaved with the buffer methods as a read() can reset the buffer.

There is no method to advance the stream without calling read(), etc. 
Will add one shortly.

**Comment by elonazoulay** [comment]
An issue with using this api (getBufferAndAdvance() or getBuffer() or getOffsetInBuffer()) and the slice api (read(), available(), remaining()):
If byte[] values are consumed in the client class and then read() is called, the available() method is either off by BYTES_CONSUMED or refers to the next byte[] array retrieved in the OrcInputStream.

This is confusing, requires extra logic wherever the code is reasoning about the offset or advancing the stream and is prone to error (ex. this is exactly the off by SIZE_OF_DOUBLE bug that was fixed in the DoubleStreamReader class).

**Comment by mbasmanova** [comment]
@elonazoulay Elon, I agree that interleaving getBuffer with original methods is problematic. How would you feel about removing getBuffer altogether and creating another version of OrcInputStream that doesn't use Slice? I imagine you'd extract an interface from  OrcInputStream, change current OrcInputStream into SliceBasedOrcInputStream and create another AriaOrcInputStream, then add a factory method that creates one of these instances based on a session property.

**Comment by elonazoulay** [comment]
> @elonazoulay Elon, I agree that interleaving getBuffer with original methods is problematic. How would you feel about removing getBuffer altogether and creating another version of OrcInputStream that doesn't use Slice? I imagine you'd extract an interface from OrcInputStream, change current OrcInputStream into SliceBasedOrcInputStream and create another AriaOrcInputStream, then add a factory method that creates one of these instances based on a session property.

That is a much better idea.

**Comment by oerling** [comment]
I fixed the uncompressed getBuffer case. The fix can be seen in test_struct_4.  This is a missing array header offset. The Slice address member must have the array header length subtracted before it works as an index into a byte[].

**Comment by elonazoulay** [comment]
Superceded by #12465

**Pull request closed without merging**
