### PR TITLE
Remove unused code

### PR DESCRIPTION
**Pull request by kaikalur**
We tried to get distinct+limit only queries to work via various different hacks until we finally figured out the right way in: 

https://github.com/prestodb/presto/pull/17640

So removing this deadcode that was introduced in two PRs:

https://github.com/prestodb/presto/pull/17199
https://github.com/prestodb/presto/pull/17536

Test plan - tests exist

```
== RELEASE NOTES ==

General Changes
* Removed two unused session params - `hash_based_distinct_limit_enabled` and `hash_based_distinct_limit_threshold` and the corresponding implementation in favor of the `quick_distinct_limit_enabled` feature.
```

### CODE REVIEW

**Comment by jainxrohit** [comment]
Add release note for removing the existing config?

**Comment by jainxrohit** [comment]
can we add some description in commit on what is being removed?

**Comment by kaikalur** [comment]
> can we add some description in commit on what is being removed?

done

**Comment by kaikalur** [comment]
> Add release note for removing the existing config?

Hmm ok maybe. I don't think anyone uses these - these are very specific enable/disable "feature" flags.

**Comment by jainxrohit** [comment]
> > Add release note for removing the existing config?
> 
> Hmm ok maybe. I don't think anyone uses these - these are very specific enable/disable "feature" flags.

Since we dont visibility in to external usage, it may be safe to assume that they might be?

**Comment by kaikalur** [comment]
> > > Add release note for removing the existing config?
> > 
> > 
> > Hmm ok maybe. I don't think anyone uses these - these are very specific enable/disable "feature" flags.
> 
> Since we dont visibility in to external usage, it may be safe to assume that they might be?

Done

**Review by rschlussel — APPROVED** [review]

**Pull request merged**
