### PR TITLE
Fix: Iceberg Parquet writer sometimes fails with "Failed to read footer of file: io.prestosql.plugin.iceberg.HdfsInputFile"

### LINKED ISSUE #16967: Iceberg Parquet writer sometimes fails with "Failed to read footer of file: io.prestosql.plugin.iceberg.HdfsInputFile"
We met the same problem as #16206 shows in our production environment, and I found the similar issue in trino: https://github.com/trinodb/trino/issues/5201 with a pr to solve that problem: https://github.com/trinodb/trino/pull/8504
I cherry-picked the fix to our production environment and it solved that problem quite well.

Maybe we can cherry-pick that fix.

### PR DESCRIPTION
**Pull request by liupan664021**
Cherry-pick of https://github.com/trinodb/trino/pull/8504

Co-authored-by: Pratham Desai <prathamd94@gmail.com>

The PR fixes #16967 #16206

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by beinan** [comment]
@ChunxuTang could you help take a look? looks like this one will fix the flaky iceberg tests, but I'm not sure if it's really an issue because the iceberg tests are working well mostly to me.

**Comment by liupan664021** [comment]
> @ChunxuTang could you help take a look? looks like this one will fix the flaky iceberg tests, but I'm not sure if it's really an issue because the iceberg tests are working well mostly to me.

Yep, this exception does not appear when running iceberg tests. We met this problem in our  production enviroment, and the PR from trino looks quite reasonable and solve the problem quite well. So I pick it :)

**Review by ChunxuTang — APPROVED** [review]
@liupan664021 Thanks for the work! LGTM.

**Review by beinan — APPROVED** [review]
Thank you for the contribution!

**Pull request merged**
