### PR TITLE
Fix logger crash for Kafka connector

### PR DESCRIPTION
**Pull request by liusuquan**
```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by highker** [comment]
Could you sign the CLA?

**Comment by liusuquan** [comment]
> Could you sign the CLA?

yes

**Comment by highker** [comment]
Could you rebase force push to trigger CLA build?

**Comment by liusuquan** [comment]
> Could you rebase force push to trigger CLA build?

hello highker, 
 i am sorry, I closed this patch for can not pass CLA check, and git push another now patch. with the url  https://github.com/prestodb/presto/pull/14721, Could you please help to review the code?

**Pull request closed without merging**
