### PR TITLE
Bump Nessie from 0.30.0 to 0.43.0

### PR DESCRIPTION
**Pull request by snazy**
Test plan - CI

```
== RELEASE NOTES ==

General Changes
* Bump Nessie from 0.30.0 to 0.43.0
```

Major Nessie improvements/changes:
* Support Iceberg 0.14.0
* Merge/transplant: detailed results & configurable merge behavior
* Improvements to Nessie API implementation & error handling
* Performance improvements
* Integration into "NesQuEIT" (Nessie query engine integration tests), CI job to verify compatibility w/ multiple query engines (currently Presto, Flink, Spark) w/ various versions

### CODE REVIEW

**Review by ChunxuTang — COMMENTED** [review]
@snazy Thanks for the upgrade!

Would you mind adding a bit more description of the improvement in Nessie 0.43.0 over 0.30.0 which may have an impact on the iceberg connector?

**Comment by snazy** [comment]
Sure, added to the PR description.

Links to GH release pages:
* https://github.com/projectnessie/nessie/releases/tag/nessie-0.40.0
* https://github.com/projectnessie/nessie/releases/tag/nessie-0.40.1
* https://github.com/projectnessie/nessie/releases/tag/nessie-0.40.2
* https://github.com/projectnessie/nessie/releases/tag/nessie-0.40.3
* https://github.com/projectnessie/nessie/releases/tag/nessie-0.41.0
* https://github.com/projectnessie/nessie/releases/tag/nessie-0.42.0
* https://github.com/projectnessie/nessie/releases/tag/nessie-0.43.0

**Review by ChunxuTang — APPROVED** [review]
LGTM. 
@snazy Thanks for the detailed description!

**Review by beinan — APPROVED** [review]
lgtm

**Pull request merged**
