### PR TITLE
ResourceGroup SelectionContext holds Session

### PR DESCRIPTION
**Pull request by miniway**
When we extend ResourceGroup other Session values like session properties might also useful to choose right ResourceGroup.

### CODE REVIEW

**Comment by cberner** [comment]
We intentionally didn't add `Session` to the `SelectionContext` to avoid exposing too much information to the resource groups manager. Are there specific pieces of it you need?
CC: @dain

**Comment by miniway** [comment]
I see. One use case is a query priority which is specified in the session properties. We've been using the property to choose a different set of query queue. And at a custom ResourceGroup, we'd like to utilize the session property to act differently.

**Comment by electrum** [comment]
We use the query "source" for priority in queue configs, but it could be useful to have a separate session property.

**Comment by cberner** [comment]
@miniway, ah I see. There's a `query_priority` in the `SystemSessionProperties`. How about just adding that to `SelectionContext` as an `OptionalInteger` would that work for you?

**Comment by miniway** [comment]
@cberner For now, it would be enough if we can access the `query_priority` session property.

**Comment by cberner** [comment]
Cool, could you update your PR to add query priority as another field in the `SelectionContext`?

**Comment by miniway** [comment]
I've exposed the `query_priority` session properties and hided `session` instance. But I've still let `SelectionContext` accept the `Session` for future extension. If you feel just adding `int query_priority` on the `SelectionConext` meets the intension better,  I'll submit a changed PR.

**Comment by cberner** [comment]
Lets just add `int queryPriority` to `SelectionContext`. I'd prefer not to put `Session` inside it, unless we're going to add a whole bunch more fields from `Session`

**Comment by miniway** [comment]
ok, I've changed `SelectionContext` into just accepting the query_priority

**Comment by cberner** [comment]
Merged. Thanks!

**Pull request closed without merging**
