### PR TITLE
Deflake TestNoisySumGaussian*Aggregation

### PR DESCRIPTION
**Pull request by tdcmeehan**
## Description
Use the same method as #22279

## Motivation and Context
Flaky test addressal

## Impact
Hopefully a more stable CI

## Test Plan
CI

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by tdcmeehan** [comment]
@jonhehir what do you think of this solution?

**Review by ajaygeorge — APPROVED** [review]
LGTM. Seems like a reasonable change to address the flakiness.

**Comment by tdcmeehan** [comment]
@jonhehir I will merge this, as this is causing many flaky test failures.  Please let me know if you have any feedback on this fix and I can address as a followup--thanks!

**Comment by jonhehir** [comment]
Thanks for the quick fix, @tdcmeehan ! Looks good to me! This is the same fix as described in #22325.

**Pull request merged**
