### PR TITLE
[native] Disable native github actions job

### PR DESCRIPTION
**Pull request by mshang816**
Disable native github actions jobs as we have better circleci job up and running now.

Test plan - (Please fill in how you tested your changes)
Make sure the native github actions jobs are NOT running

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by amitkdutta** [comment]
CC: @majetideepak @mbasmanova

**Review by amitkdutta — APPROVED** [review]
Looks good. Thanks so much @mshang816 for making the CI better and better.

**Review by majetideepak — APPROVED** [review]
@frankobe opened a PR as well last week
https://github.com/prestodb/presto/pull/19898

**Review by pranjalssh — APPROVED** [review]
Thanks!

**Pull request merged**
