### PR TITLE
adding F dist (#15798)

### PR DESCRIPTION
**Pull request by Masha-Iris**
Test plan - (Please fill in how you tested your changes)

Please make sure your submission complies with our [Development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [Formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), and [Commit Message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests) guidelines. Don't forget to follow our [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution) for any code copied from other projects.

Fill in the release notes towards the bottom of the PR description.
See [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) for details.

```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by leepface** [comment]
Looks like you have some unrelated "temp storage" changes in here. I think you need to rebase.

**Comment by leepface** [comment]
Code review:
- [ ] maven-checks errors are code formatting. Load in IntelliJ (no need for working build environment) and code format.

**Comment by talgalili** [comment]
@Masha-Iris  - please clean up this diff also :)

**Comment by talgalili** [comment]
@Masha-Iris  - could you please fix the "This branch has conflicts that must be resolved" issue?
(you'll need to re-base)

**Comment by talgalili** [comment]
Your diff seems to include irrelevant files changes. You'll need to remove them from the diff (or, in worst case scenario, start a new diff with only the changes you want)

**Comment by talgalili** [comment]
Hey @Masha-Iris  - I see that this diff has merge conflicts, could you please resolve them?

**Comment by talgalili** [comment]
@Masha-Iris  - I think this diff wasn't merged properly. I see you have 3 commits in it, and also that it includes adding other diffs as new content within your own diff. Please review.

**Comment by ajaygeorge** [comment]
@Masha-Iris  Can you please take a look at resolving the merge conflicts.
cc @jbapple

**Pull request closed without merging**
