### PR TITLE
[native] Fix the intermediate type of approx_percentile

### PR DESCRIPTION
**Pull request by Yuhta**
Summary:
Before this change, intermediate aggregation node for `approx_percentile` in worker only sees a type signature of `VARBINARY -> VARBINARY`, thus not be able to figure out the actual value type and cannot perform the merge properly when the value type is not `DOUBLE`.

This fix changes the intermediate result type to `ROW` so that we can get the value type from it and instantiate accumulator with proper type.

Fix https://github.com/facebookincubator/velox/issues/2430

Differential Revision: D39733152

### CODE REVIEW

**Comment by Yuhta** [comment]
@ChunxuTang Hi can you take a look?  The test will pass once we advance the Velox version

**Comment by Yuhta** [comment]
@mbasmanova Can you help stamp and merge this PR?

**Comment by mbasmanova** [comment]
@Yuhta Jimmy, there are test failures. Would you take a look?

**Comment by Yuhta** [comment]
> @Yuhta Jimmy, there are test failures. Would you take a look?

The test should pass if we sync up the Velox version (I ran it on devserver before I land the change internally).  Should I advance the version in this PR to make it pass?

**Comment by mbasmanova** [comment]
Yes, let's advance Velox version and add an e2e test that runs intermediate aggregation using approx_percentile. Also, please, update the commit message to following the guidelines at https://cbea.ms/git-commit/ and wrap it at 72 characters.

**Comment by mbasmanova** [comment]
@majetideepak Deepak, I thought you fixed these failures. Would you take a look?

```
Failures: 
Error:    TestHiveQueriesUsingThrift.testCatalogWithCacheEnabled:16->TestHiveQueries.testCatalogWithCacheEnabled:52->AbstractTestQueryFramework.assertQuery:144->AbstractTestQueryFramework.assertQuery:149 Execution of 'actual' query failed: SELECT * FROM tmp
Error:    TestHiveQueriesUsingThrift.testCreateTableAsSelect:16->TestHiveQueries.testCreateTableAsSelect:578 ? Runtime Unable to rename from file:/tmp/presto-hive/eed1f451-83d9-4c44-96e9-763adc3fe805 to file:/tmp/hive_data/tpch/tmp: target directory already exists
```

**Comment by majetideepak** [comment]
@mbasmanova these failures are different. https://github.com/prestodb/presto/issues/18437 is tracking this. I am going to take a look.

**Review by mbasmanova — APPROVED** [review]
@Yuhta Thank you, Jimmy. Accepting based on @majetideepak comment that suggests that test failures are unrelated and are being looked into separately.

**Pull request merged**
