### PR TITLE
Constraint annotation fixups

### PR DESCRIPTION
**Pull request by losipiuk**

### CODE REVIEW

**Comment by electrum** [comment]
We chose not to add this to the SPI yet because it's not clear this is the right interface (it's not even used anywhere yet!)

**Comment by losipiuk** [comment]
Oh. I did not know it was left in presto main intentionally. We use it
internally already. Anyway. I will change this pr to just add support for
repeated occurrences.

**Comment by losipiuk** [comment]
I updated the PR so it does not change the package/module of `Constraint` annotation.

**Comment by losipiuk** [comment]
What about merging that? This is trivial now. No point in keeping that hanging around.

**Comment by cberner** [comment]
Merged. Thanks!

**Pull request merged**
