### PR TITLE
Delete TaskExecutorSimulator.java

### PR DESCRIPTION
**Pull request by elharo**
## Description
Delete TaskExecutorSimulator.java

## Motivation and Context
No longer used

## Impact
None

## Test Plan
CI

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by elharo** [comment]
singlestore is failing again

**Comment by tdcmeehan** [comment]
I think there's other things in this directory that can also be deleted, should we remove them as well?

**Comment by elharo** [comment]
Yes, we should. It's a little easier and safer to take them out one at a time (unless you think the whole directory can go, in which case I can delete that in a single PR)

**Comment by elharo** [comment]
Can we go ahead and merge this one?

**Comment by tdcmeehan** [comment]
I believe the whole directory can be deleted--can you check that it can be deleted cleanly (i.e. there are no external references to the files in this directory)?  I'd rather delete all or nothing.

**Comment by elharo** [comment]
Easier to do it one piece at a time. Right now this is ready to remove. No idea when I'll have time to do the rest of it.

**Comment by elharo** [comment]
Doesn't look like the entire directory can be deleted. There's at least one test class in there; i.e. contains TestNG tests, not just test utilities and mocks.

**Comment by elharo** [comment]
superseded

**Pull request closed without merging**
