### PR TITLE
Expose approximate queue position

### PR DESCRIPTION
**Pull request by elonazoulay**
Will have to rebase once #10912 lands as this is a continuation of that branch.

### CODE REVIEW

**Comment by elonazoulay** [comment]
Need to have a deterministic ordering of resource groups so that the relative order of queued queries remains the same, ex. 
global.a has query q1 queued
global.b has query q2 queued 

Then the approximate order should always be q1, q2 for each call to getApproximateOrder.

Will push shortly.

**Comment by elonazoulay** [comment]
Pushed to github.

Would it be better to have this in the InternalResourceGroupManager so that it can be used by the webapp, client, etc.?

**Comment by elonazoulay** [comment]
Some issues with having the logic in the system table: 
 - If the scheduling policy is QUERY_PRIORITY then queries should be sorted by priority, otherwise the approximation can be very inaccurate which won't provide a good user experience
 - If queue reconstruction is done outside of the resource group then every time a scheduling policy is added the logic has to be replicated here

Issues with having the logic in the resource group:
 - The QuerySystemTable will have to merge results from queryInfo and resource groups, this could also result in very inaccurate approximations (i.e. if a new query is queued that has highest priority but is put at the end or vice versa)
 - Probably need to use a loading cache so the resource groups aren't locked by a flood of queries to the system table

Issues with adding to QueryInfo and client protocol:
 - Every time a query is dequeued the ordering has to be reconstructed
 - A query will either have to have it's QueryInfo approximate order constantly updated or pass around something which is aware of the overall order

Trying some things out, will update.

**Comment by raghavsethi** [comment]
Yes, you make a lot of good points. Let's talk offline about how we might make this work for all the scheduling policies.

**Pull request closed without merging**
