### PR TITLE
Move TableDescriptionSupplier to separate guice module

### PR DESCRIPTION
**Pull request by yangy0000**
Cherry-pick https://github.com/trinodb/trino/commit/696e10ba9e2cd292554b74f24e824719cf5a2449

Co-Authored-By: Elon Azoulay <elon.azoulay@gmail.com>

Test plan - (Please fill in how you tested your changes)

Please make sure your submission complies with our [Development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [Formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), and [Commit Message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests) guidelines. Don't forget to follow our [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution) for any code copied from other projects.

Fill in the release notes towards the bottom of the PR description.
See [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) for details.

```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by dborkar** [comment]
@beinan This is a kafka improvement, can you please review and merge.  🙏🏼

**Comment by beinan** [comment]
> @beinan This is a kafka improvement, can you please review and merge. 🙏🏼

sorry for my delay,  I will take a look by the end of this week

**Review by beinan — APPROVED** [review]
Excellent contribution!  Many thanks!

**Comment by beinan** [comment]
Hello @yangy0000 , the code change looks good to me, but I don't know why the Facebook Integration is still 'Pending',  could you do something like 'git push -f' (maybe also change something like the commit message) to your branch to trigger the build again?  thanks!

**Comment by yangy0000** [comment]
> Hello @yangy0000 , the code change looks good to me, but I don't know why the Facebook Integration is still 'Pending', could you do something like 'git push -f' (maybe also change something like the commit message) to your branch to trigger the build again? thanks!

sure, let me trigger the build again.

**Pull request merged**
