### PR TITLE
Update drift library to 1.28

### PR DESCRIPTION
**Pull request by viczhang861**
Test plan - (Please fill in how you tested your changes)

presto-facebook is using drift 1.28

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Review by wenleix — APPROVED** [review]
LGTM. @viczhang861 : Perhaps also explain what feature is beneficial in drift 1.28?

**Comment by viczhang861** [comment]
@wenleix  Version I.28 has new configuration `thrift.client.connection-pool.max-connections-per-destination`, but it is default value is the same as before (default: 1).  Not sure about changes 1.26 and 1.27

**Comment by wenleix** [comment]
@viczhang861 

> @wenleix Version I.28 has new configuration thrift.client.connection-pool.max-connections-per-destination, but it is default value is the same as before (default: 1). Not sure about changes in 1.26 and 1.27

Got it. So it's more about make sure drift version is consistent?

**Comment by wenleix** [comment]
@viczhang861 : please also fill in "test plan". e.g. "Travis"

**Comment by wenleix** [comment]
Merged #15153, thanks for the contribution!

**Comment by viczhang861** [comment]
> @viczhang861
> 
> > @wenleix Version I.28 has new configuration thrift.client.connection-pool.max-connections-per-destination, but it is default value is the same as before (default: 1). Not sure about changes in 1.26 and 1.27
> 
> Got it. So it's more about make sure drift version is consistent?

Correct.

**Pull request merged**
